Function: ExecuteStore
Datetime: 26/10/2017 3:02:46 PM
Error message: ORA-12545: Connect failed because target host or object does not exist
Stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 180
Other Text: DataAccess

Function: ExecuteStore
Datetime: 26/10/2017 3:03:25 PM
Error message: ORA-12545: Connect failed because target host or object does not exist
Stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 180
Other Text: DataAccess

Function: ExecuteStore
Datetime: 26/10/2017 3:06:04 PM
Error message: ORA-12545: Connect failed because target host or object does not exist
Stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 180
Other Text: DataAccess

Function: ExecuteStore
Datetime: 26/10/2017 3:07:22 PM
Error message: ORA-12545: Connect failed because target host or object does not exist
Stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 180
Other Text: DataAccess

Function: ExecuteStore
Datetime: 26/10/2017 3:11:55 PM
Error message: ORA-12545: Connect failed because target host or object does not exist
Stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 180
Other Text: DataAccess

Function: ExecuteStore
Datetime: 26/10/2017 4:24:54 PM
Error message: ORA-12545: Connect failed because target host or object does not exist
Stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 180
Other Text: DataAccess

Function: ExecuteStore
Datetime: 26/10/2017 4:32:53 PM
Error message: ORA-12545: Connect failed because target host or object does not exist
Stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 180
Other Text: DataAccess

Function: ExecuteStore
Datetime: 26/10/2017 4:35:21 PM
Error message: ORA-12545: Connect failed because target host or object does not exist
Stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 180
Other Text: DataAccess

Function: ExecuteStore
Datetime: 26/10/2017 8:46:42 PM
Error message: ORA-12170: TNS:Connect timeout occurred
Stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 180
Other Text: DataAccess

Function: ExecuteStore
Datetime: 26/10/2017 8:50:50 PM
Error message: ORA-12170: TNS:Connect timeout occurred
Stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 180
Other Text: DataAccess

Function: ExecuteStore
Datetime: 26/10/2017 8:53:43 PM
Error message: ORA-12170: TNS:Connect timeout occurred
Stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 180
Other Text: DataAccess

