Function: ExecuteStore
Datetime: 6/25/2017 4:25:37 PM
Error message: ORA-12170: TNS:Connect timeout occurred
Stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in C:\Users\thuydinh\Documents\Visual Studio 2010\Projects\Project1\Framework.Data\DataAccess\Query.vb:line 180
Other Text: DataAccess

Function: ExecuteStore
Datetime: 6/25/2017 4:26:00 PM
Error message: ORA-12170: TNS:Connect timeout occurred
Stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in C:\Users\thuydinh\Documents\Visual Studio 2010\Projects\Project1\Framework.Data\DataAccess\Query.vb:line 180
Other Text: DataAccess

