Public Class RC_REGISTER_CODEDTO
    Public Property ID As Decimal
    Public Property CODE As String
    Public Property YEAR As Decimal?
    Public Property ID_REQUIRED_VOTES As Decimal?
    Public Property REQUIRED_VOTES_NAME As String
    Public Property ORG_DESC_REQUEST As String
    Public Property ORG_ID_REQUEST As Decimal?
    Public Property ORG_REQUEST_NAME As String
    Public Property TITLE_ID As Decimal?
    Public Property TITLE_NAME As String
    Public Property NUMBER_PLAN As Decimal?
    Public Property NUMBER_NOW As Decimal?
    Public Property NUMBER_MUST As Decimal?
    Public Property RC_CREATE_DATE As Date?
    Public Property RC_CHECK As Decimal?
    Public Property RC_CHECK_NAME As String
    Public Property NUMBER_REQUIRED_DETAIL As Decimal?
    Public Property ID_REQUIRED_DETAIL As Decimal?
    Public Property TIME_REQUIRED As Date?
    Public Property TYPE_REQUIRED As Decimal?
    Public Property TYPE_REQUIRED_NAME As String
    Public Property ORG_DESC_PERFORM As String
    Public Property ORG_ID_PERFORM As Decimal?
    Public Property ORG_PERFROM_NAME As String
    Public Property FROM_AGE As Decimal?
    Public Property TO_AGE As Decimal?
    Public Property GENDER As Decimal?
    Public Property GENDER_NAME As String
    Public Property LEARNING_LEVEL As Decimal?
    Public Property LEARMING_LEVEL_NAME As String
    Public Property MAJOR As String
    Public Property EXPERIENCE As Decimal?
    Public Property SKILLS As String
    Public Property EXAM_1 As String
    Public Property EXAM_2 As String
    Public Property EXAM_3 As String
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
End Class