Public Class PASeniorityProcessDTO
    Public Property ID As Decimal?
    Public Property EMPLOYEE_ID As Decimal?
    Public Property EMPLOYEE_CODE As String
    Public Property EMPLOYEE_NAME As String
    Public Property ORG_ID As Decimal?
    Public Property ORG_NAME As String
    Public Property TITLE_ID As Decimal?
    Public Property TITLE_NAME As String
    Public Property STAFF_RANK_ID As Decimal?
    Public Property STAFF_RANK_NAME As String
    Public Property CONTRACT_ID As Decimal?
    Public Property IS_DISSOLVE As Boolean
    Public Property CONTRACT_TYPE_NAME As String
    Public Property D1 As Decimal?
    Public Property D2 As Decimal?
    Public Property D3 As Decimal?
    Public Property D4 As Decimal?
    Public Property D5 As Decimal?
    Public Property D6 As Decimal?
    Public Property D7 As Decimal?
    Public Property D8 As Decimal?
    Public Property D9 As Decimal?
    Public Property D10 As Decimal?
    Public Property D11 As Decimal?
    Public Property D12 As Decimal?
    Public Property D13 As Decimal?
    Public Property D14 As Decimal?
    Public Property D15 As Decimal?
    Public Property D16 As Decimal?
    Public Property D17 As Decimal?
    Public Property D18 As Decimal?
    Public Property D19 As Decimal?
    Public Property D20 As Decimal?
    Public Property D21 As Decimal?
    Public Property D22 As Decimal?
    Public Property D23 As Decimal?
    Public Property D24 As Decimal?
    Public Property D25 As Decimal?
    Public Property D26 As Decimal?
    Public Property D27 As Decimal?
    Public Property D28 As Decimal?
    Public Property D29 As Decimal?
    Public Property D30 As Decimal?
    Public Property D31 As Decimal?
    Public Property SALARY As Decimal?
    Public Property PERCENT_SALARY As Decimal?
    Public Property DISCIPLINE_COUNT As Decimal?
    Public Property DISCIPLINE_TYPE_NAME As String
    Public Property PERIOD_ID As Decimal?
End Class
