-- --------------------------------------------------
-- Entity Designer DDL Script for Oracle database
-- --------------------------------------------------
-- Date Created: 10/1/2019 10:21:01 AM
-- Generated from EDMX file: D:\TNG_SOURCE_NEW\AttendanceDAL\AttendanceContext.edmx
-- --------------------------------------------------

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

-- ALTER TABLE "AttendanceModelStoreContainer"."OT_OTHER_LIST" DROP CONSTRAINT "FK_OOLT_OOL" CASCADE;

-- ALTER TABLE "AttendanceModelStoreContainer"."OT_OTHER_LIST_TYPE" DROP CONSTRAINT "FK_OOLG_OOLT" CASCADE;

-- ALTER TABLE "AttendanceModelStoreContainer"."HU_EMPLOYEE_HEALTH" DROP CONSTRAINT "FK_FE_HEH" CASCADE;

-- ALTER TABLE "AttendanceModelStoreContainer"."HU_EMPLOYEE_EDUCATION" DROP CONSTRAINT "FK_HE_HEE" CASCADE;

-- ALTER TABLE "AttendanceModelStoreContainer"."HU_EMPLOYEE_FILES" DROP CONSTRAINT "FK_HE_HEF" CASCADE;

-- ALTER TABLE "AttendanceModelStoreContainer"."HU_EMPLOYEE_OTHER_INFO" DROP CONSTRAINT "FK_HE_HEO" CASCADE;

-- ALTER TABLE "AttendanceModelStoreContainer"."HU_EMPLOYEE_SALARY" DROP CONSTRAINT "FK_HE_HES" CASCADE;

-- ALTER TABLE "AttendanceModelStoreContainer"."HU_EMPLOYEE" DROP CONSTRAINT "FK_HUEMD_HUEM" CASCADE;

-- ALTER TABLE "AttendanceModelStoreContainer"."HU_ORGANIZATION" DROP CONSTRAINT "FK_HU_ORG_HU_ORG" CASCADE;

-- ALTER TABLE "AttendanceModelStoreContainer"."HU_ORG_TITLE" DROP CONSTRAINT "FK_HUTL_HUOT" CASCADE;

-- ALTER TABLE "AttendanceModelStoreContainer"."SE_USER_REPORT" DROP CONSTRAINT "FK_SE_USER_REPORT_SE_REPORT" CASCADE;

-- ALTER TABLE "AttendanceModelStoreContainer"."SE_USER_REPORT" DROP CONSTRAINT "FK_SE_USER_REPORT_SE_USER" CASCADE;

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

-- DROP TABLE "AttendanceModelStoreContainer"."OT_OTHER_LIST";

-- DROP TABLE "AttendanceModelStoreContainer"."OT_OTHER_LIST_GROUP";

-- DROP TABLE "AttendanceModelStoreContainer"."OT_OTHER_LIST_TYPE";

-- DROP TABLE "AttendanceModelStoreContainer"."SE_CHOSEN_ORG";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_GSIGN";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_SWIPE_DATA";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_ORG_PERIOD";

-- DROP TABLE "AttendanceModelStoreContainer"."HU_EMPLOYEE";

-- DROP TABLE "AttendanceModelStoreContainer"."HU_CONTRACT";

-- DROP TABLE "AttendanceModelStoreContainer"."HU_EMPLOYEE_EDUCATION";

-- DROP TABLE "AttendanceModelStoreContainer"."HU_EMPLOYEE_FILES";

-- DROP TABLE "AttendanceModelStoreContainer"."HU_EMPLOYEE_HEALTH";

-- DROP TABLE "AttendanceModelStoreContainer"."HU_EMPLOYEE_OTHER_INFO";

-- DROP TABLE "AttendanceModelStoreContainer"."HU_EMPLOYEE_SALARY";

-- DROP TABLE "AttendanceModelStoreContainer"."HU_EMPLOYEE_TRAIN";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_TIMESHEET_REGISTER";

-- DROP TABLE "AttendanceModelStoreContainer"."SE_APP_PROCESS";

-- DROP TABLE "AttendanceModelStoreContainer"."SE_APP_SETUP";

-- DROP TABLE "AttendanceModelStoreContainer"."SE_APP_SETUPEXT";

-- DROP TABLE "AttendanceModelStoreContainer"."SE_APP_TEMPLATE_DTL";

-- DROP TABLE "AttendanceModelStoreContainer"."SE_APP_TEMPLATE";

-- DROP TABLE "AttendanceModelStoreContainer"."HU_ORGANIZATION";

-- DROP TABLE "AttendanceModelStoreContainer"."HU_WORKING";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_PORTAL_APP";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_RGT";

-- DROP TABLE "AttendanceModelStoreContainer"."HU_ORG_TITLE";

-- DROP TABLE "AttendanceModelStoreContainer"."HU_TITLE";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_WORKSIGN";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_PORTAL_REG";

-- DROP TABLE "AttendanceModelStoreContainer"."HU_STAFF_RANK";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_TIME_TIMESHEET_RICE";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_TIME_TIMESHEET_OT";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_DMVS";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_HOLIDAY";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_HOLIDAY_GENERAL";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_HOLIDAY_OBJECT";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_LATE_COMBACKOUT";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_PERIOD";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_SETUP_SPECIAL";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_SIGNDEFAULT";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_TIME_MANUAL";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_TIME_RICE";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_TIME_TIMESHEET_DAILY";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_TIME_TIMESHEET_MACHINET";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_DATA_INOUT";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_FML";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_TERMINALS";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_ACTION_ORG_LOG";

-- DROP TABLE "AttendanceModelStoreContainer"."HU_EMPLOYEE_CV";

-- DROP TABLE "AttendanceModelStoreContainer"."SE_MAIL";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_SETUP_TIME_EMP";

-- DROP TABLE "AttendanceModelStoreContainer"."SE_EMPLOYEE_CHOSEN";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_LIST_PARAM_SYSTEM";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_REGISTER_OT";

-- DROP TABLE "AttendanceModelStoreContainer"."SE_USER";

-- DROP TABLE "AttendanceModelStoreContainer"."SE_REPORT";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_COMPENSATORY";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_ACTION_LOG";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_DECLARE_ENTITLEMENT";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_PROJECT";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_PROJECT_TITLE";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_PROJECT_EMP";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_PROJECT_WORK";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_PROJECT_ASSIGN";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_TIMESHEET_OT_DTL";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_TIME_TIMESHEET_MONTHLY";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_PORTAL_REG_LIST";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_TIMESHEET";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_SHIFTCYCLE_EMP_DETAIL";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_SETUP_ATT_EMP";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_OT_REGISTRATION";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_OFFSETTING_TIMEKEEPING";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_OFFSETTING_TIMEKEEPING_EMP";

-- DROP TABLE "AttendanceModelStoreContainer"."HUV_AT_PORTAL";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_SHIFTCYCLE";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_SHIFTCYCLE_EMP";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_SHIFTCYCLE_DETAIL";

-- DROP TABLE "AttendanceModelStoreContainer"."ATV_HOLIDAY_HOSE";

-- DROP TABLE "AttendanceModelStoreContainer"."HU_ANNUALLEAVE_PLANS";

-- DROP TABLE "AttendanceModelStoreContainer"."HU_CONTRACT_TYPE";

-- DROP TABLE "AttendanceModelStoreContainer"."PROCESS_APPROVED_STATUS";

-- DROP TABLE "AttendanceModelStoreContainer"."ATV_OFFSETTING";

-- DROP TABLE "AttendanceModelStoreContainer"."SE_USER_ORG_ACCESS";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_SHIFT";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_LEAVESHEET_DETAIL";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_LEAVESHEET";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_TIMESHEET_MACHINET_IMPORT";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_TYPE_PROCESS";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_TIME_MANUAL_RATE";

-- DROP TABLE "AttendanceModelStoreContainer"."AT_ENTITLEMENT";

-- DROP TABLE "AttendanceModelStoreContainer"."SE_USER_REPORT";

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'OT_OTHER_LIST'
CREATE TABLE "dbo"."OT_OTHER_LIST" (
   "ID" NUMBER(38,0) NOT NULL,
   "TYPE_ID" NUMBER(38,0) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "ATTRIBUTE1" NVARCHAR2(255) NULL,
   "ATTRIBUTE2" NVARCHAR2(255) NULL,
   "ATTRIBUTE3" NVARCHAR2(255) NULL,
   "ATTRIBUTE4" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "CODE" NVARCHAR2(15) NULL,
   "TYPE_CODE" NVARCHAR2(15) NULL
);

-- Creating table 'OT_OTHER_LIST_GROUP'
CREATE TABLE "dbo"."OT_OTHER_LIST_GROUP" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'OT_OTHER_LIST_TYPE'
CREATE TABLE "dbo"."OT_OTHER_LIST_TYPE" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(255) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "GROUP_ID" NUMBER(38,0) NULL,
   "IS_SYSTEM" NUMBER(5,0) NULL,
   "TABLE_RELATION" VARCHAR2(2000) NULL
);

-- Creating table 'SE_CHOSEN_ORG'
CREATE TABLE "dbo"."SE_CHOSEN_ORG" (
   "ORG_ID" NUMBER(38,0) NOT NULL,
   "USERNAME" NVARCHAR2(255) NOT NULL
);

-- Creating table 'AT_GSIGN'
CREATE TABLE "dbo"."AT_GSIGN" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(20) NOT NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "SOONEST_IN" NUMBER(38,0) NULL,
   "LATEST_OUT" NUMBER(38,0) NULL,
   "SOONEST_OUT" NUMBER(38,0) NULL,
   "LATEST_IN" NUMBER(38,0) NULL,
   "MIN_OT" NUMBER(38,0) NULL,
   "OT_BEFORE_SHIFT" NUMBER(38,0) NULL,
   "OT_AFTER_SHIFT" NUMBER(38,0) NULL,
   "TIME_OUT_SOON" NUMBER(38,0) NULL,
   "TIME_IN_LATE" NUMBER(38,0) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'AT_SWIPE_DATA'
CREATE TABLE "dbo"."AT_SWIPE_DATA" (
   "ID" NUMBER(38,0) NOT NULL,
   "ITIME_ID" NCLOB NULL,
   "VALTIME" DATE NULL,
   "TERMINAL_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "WORKINGDAY" DATE NULL,
   "MACHINE_TYPE" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL
);

-- Creating table 'AT_ORG_PERIOD'
CREATE TABLE "dbo"."AT_ORG_PERIOD" (
   "ID" NUMBER(38,0) NOT NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "STATUSCOLEX" NUMBER(38,0) NULL,
   "STATUSPAROX" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_EMPLOYEE'
CREATE TABLE "dbo"."HU_EMPLOYEE" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_CODE" NVARCHAR2(15) NULL,
   "FIRST_NAME_VN" NVARCHAR2(255) NULL,
   "LAST_NAME_VN" NVARCHAR2(255) NULL,
   "FULLNAME_VN" NVARCHAR2(255) NULL,
   "FIRST_NAME_EN" VARCHAR2(255) NULL,
   "LAST_NAME_EN" NVARCHAR2(255) NULL,
   "FULLNAME_EN" NVARCHAR2(255) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "WORK_STATUS" NUMBER(38,0) NULL,
   "CONTRACT_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "JOIN_DATE" DATE NULL,
   "DIRECT_MANAGER" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "LAST_WORKING_ID" NUMBER(38,0) NULL,
   "TER_EFFECT_DATE" DATE NULL,
   "TER_LAST_DATE" DATE NULL,
   "ITIME_ID" NCLOB NULL,
   "STAFF_RANK_ID" NUMBER(38,0) NULL,
   "JOIN_DATE_STATE" DATE NULL,
   "DIRECT_MANAGER_2" NUMBER(38,0) NULL,
   "DIRECT_MANAGER_3" NUMBER(38,0) NULL,
   "IS_KIEM_NHIEM" NUMBER(38,0) NULL
);

-- Creating table 'HU_CONTRACT'
CREATE TABLE "dbo"."HU_CONTRACT" (
   "ID" NUMBER(38,0) NOT NULL,
   "CONTRACT_NO" NVARCHAR2(255) NULL,
   "CONTRACT_TYPE_ID" NUMBER(38,0) NULL,
   "START_DATE" DATE NULL,
   "EXPIRE_DATE" DATE NULL,
   "SIGNER_TITLE" NVARCHAR2(255) NULL,
   "SIGNER_NAME" NVARCHAR2(255) NULL,
   "SIGN_DATE" DATE NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "STATUS_ID" NUMBER(38,0) NULL,
   "SIGN_ID" NUMBER(38,0) NULL,
   "WORKING_ID" NUMBER(38,0) NULL,
   "MORNING_START" DATE NULL,
   "MORNING_STOP" DATE NULL,
   "AFTERNOON_START" DATE NULL,
   "AFTERNOON_STOP" DATE NULL
);

-- Creating table 'HU_EMPLOYEE_EDUCATION'
CREATE TABLE "dbo"."HU_EMPLOYEE_EDUCATION" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "ACADEMY" NUMBER(38,0) NULL,
   "MAJOR" NUMBER(38,0) NULL,
   "NLEVEL" NUMBER(38,0) NULL,
   "COMPUTER_CER1" NVARCHAR2(255) NULL,
   "COMPUTER_CER2" NVARCHAR2(255) NULL,
   "COMPUTER_CER3" NVARCHAR2(255) NULL,
   "COMPUTER_LEVEL1" NUMBER(38,0) NULL,
   "COMPUTER_LEVEL2" NUMBER(38,0) NULL,
   "COMPUTER_LEVEL3" NUMBER(38,0) NULL,
   "COMPUTER_MARK1" NVARCHAR2(15) NULL,
   "COMPUTER_MARK2" NVARCHAR2(15) NULL,
   "COMPUTER_MARK3" NVARCHAR2(15) NULL,
   "LANGUAGE1" NUMBER(38,0) NULL,
   "LANGUAGE2" NUMBER(38,0) NULL,
   "LANGUAGE3" NUMBER(38,0) NULL,
   "LANGUAGE_LEVEL1" NUMBER(38,0) NULL,
   "LANGUAGE_LEVEL2" NUMBER(38,0) NULL,
   "LANGUAGE_LEVEL3" NUMBER(38,0) NULL,
   "LANGUAGE_MARK1" NVARCHAR2(15) NULL,
   "LANGUAGE_MARK2" NVARCHAR2(15) NULL,
   "LANGUAGE_MARK3" NVARCHAR2(15) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "GRADUATE_SCHOOL" NVARCHAR2(255) NULL
);

-- Creating table 'HU_EMPLOYEE_FILES'
CREATE TABLE "dbo"."HU_EMPLOYEE_FILES" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "FILE_TYPE" NUMBER(38,0) NULL,
   "FILE_NAME" NVARCHAR2(255) NULL,
   "FILE_SIZE" NUMBER(10,0) NULL,
   "NOTE" NVARCHAR2(255) NULL,
   "UPLOAD_BY" NVARCHAR2(255) NULL,
   "UPLOAD_DATE" DATE NULL
);

-- Creating table 'HU_EMPLOYEE_HEALTH'
CREATE TABLE "dbo"."HU_EMPLOYEE_HEALTH" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "CHIEU_CAO" BINARY_DOUBLE NULL,
   "CAN_NANG" BINARY_DOUBLE NULL,
   "NHOM_MAU" NVARCHAR2(15) NULL,
   "HUYET_AP" NVARCHAR2(15) NULL,
   "MAT_TRAI" NVARCHAR2(15) NULL,
   "MAT_PHAI" NVARCHAR2(15) NULL,
   "LOAI_SUC_KHOE" NUMBER(38,0) NULL,
   "TAI_MUI_HONG" NVARCHAR2(255) NULL,
   "RANG_HAM_MAT" NVARCHAR2(255) NULL,
   "TIM" NVARCHAR2(255) NULL,
   "PHOI_NGUC" NVARCHAR2(255) NULL,
   "VIEM_GAN_B" NVARCHAR2(255) NULL,
   "DA_HOA_LIEU" NVARCHAR2(255) NULL,
   "DU_SUC_KHOE" NVARCHAR2(255) NULL,
   "GHI_CHU_SUC_KHOE" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_EMPLOYEE_OTHER_INFO'
CREATE TABLE "dbo"."HU_EMPLOYEE_OTHER_INFO" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "NGAY_VAO_DOAN" DATE NULL,
   "NOI_VAO_DOAN" NVARCHAR2(255) NULL,
   "NOI_SINH_HOAT_DOAN" NVARCHAR2(255) NULL,
   "DOAN_PHI" NUMBER(5,0) NULL,
   "NGAY_VAO_DANG" DATE NULL,
   "NOI_VAO_DANG" NVARCHAR2(255) NULL,
   "NOI_SINH_HOAT_DANG" NVARCHAR2(255) NULL,
   "DANG_PHI" NUMBER(5,0) NULL,
   "SO_TAI_KHOAN" NVARCHAR2(255) NULL,
   "NGAN_HANG" NUMBER(38,0) NULL,
   "CHI_NHANH" NUMBER(38,0) NULL,
   "NGAY_HIEU_LUC" DATE NULL,
   "NGUOI_THU_HUONG" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_EMPLOYEE_SALARY'
CREATE TABLE "dbo"."HU_EMPLOYEE_SALARY" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "BASIC_SAL" NUMBER(38,0) NULL,
   "SOFT_SAL" NUMBER(38,0) NULL,
   "OTHER_SAL" NUMBER(38,0) NULL,
   "COEFFICIENT" NUMBER(38,0) NULL,
   "CONTRACTUAL_SAL" NUMBER(38,0) NULL,
   "SALARY_ENTERPRISE_ID" NUMBER(38,0) NULL,
   "ALLOWANCE_IDS" NVARCHAR2(255) NULL,
   "ALLOWANCE_SAL" NUMBER(38,0) NULL,
   "ALLOWANCE_TOTAL" NUMBER(38,0) NULL,
   "PERCENT_SALARY" NUMBER(5,0) NULL
);

-- Creating table 'HU_EMPLOYEE_TRAIN'
CREATE TABLE "dbo"."HU_EMPLOYEE_TRAIN" (
   "ID" NUMBER(38,0) NOT NULL,
   "FROM_DATE" DATE NULL,
   "TO_DATE" DATE NULL,
   "SCHOOL_NAME" NCLOB NULL,
   "TRAINING_FORM" NUMBER(38,0) NULL,
   "HIGHEST_LEVEL" NUMBER(5,0) NOT NULL,
   "LEARNING_LEVEL" NUMBER(38,0) NULL,
   "MAJOR" NUMBER(38,0) NULL,
   "GRADUATE_YEAR" NUMBER(38,0) NULL,
   "MARK" NUMBER(38,0) NULL,
   "TRAINING_CONTENT" NCLOB NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'AT_TIMESHEET_REGISTER'
CREATE TABLE "dbo"."AT_TIMESHEET_REGISTER" (
   "ID" NUMBER(38,0) NOT NULL,
   "HU_EMPLOYEEID" NUMBER(38,0) NULL,
   "WORKINGDAY" DATE NULL,
   "AT_SIGNID" NUMBER(38,0) NULL,
   "NVALUE" NUMBER(10,5) NULL,
   "SVALUE" NVARCHAR2(255) NULL,
   "DVALUE" DATE NULL,
   "ORGID" NUMBER(38,0) NULL,
   "POSID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ISAP" NVARCHAR2(1) NULL,
   "ISSYNC" NVARCHAR2(1) NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "NVALUE_ID" NUMBER(38,0) NULL
);

-- Creating table 'SE_APP_PROCESS'
CREATE TABLE "dbo"."SE_APP_PROCESS" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(150) NULL,
   "ACTFLG" VARCHAR2(1) NULL,
   "PROCESS_CODE" VARCHAR2(50) NULL,
   "NUMREQUEST" NUMBER(38,0) NULL,
   "EMAIL" NVARCHAR2(200) NULL
);

-- Creating table 'SE_APP_SETUP'
CREATE TABLE "dbo"."SE_APP_SETUP" (
   "ID" NUMBER(38,0) NOT NULL,
   "PROCESS_ID" NUMBER(38,0) NULL,
   "TEMPLATE_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "FROM_DATE" DATE NULL,
   "TO_DATE" DATE NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'SE_APP_SETUPEXT'
CREATE TABLE "dbo"."SE_APP_SETUPEXT" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "SUB_EMPLOYEE_ID" NUMBER(38,0) NULL,
   "PROCESS_ID" NUMBER(38,0) NULL,
   "FROM_DATE" DATE NULL,
   "TO_DATE" DATE NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'SE_APP_TEMPLATE_DTL'
CREATE TABLE "dbo"."SE_APP_TEMPLATE_DTL" (
   "ID" NUMBER(38,0) NOT NULL,
   "TEMPLATE_ID" NUMBER(38,0) NULL,
   "APP_LEVEL" NUMBER(38,0) NULL,
   "APP_TYPE" NUMBER(38,0) NULL,
   "APP_ID" NUMBER(38,0) NULL,
   "INFORM_DATE" NUMBER(38,0) NULL,
   "INFORM_EMAIL" VARCHAR2(150) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'SE_APP_TEMPLATE'
CREATE TABLE "dbo"."SE_APP_TEMPLATE" (
   "ID" NUMBER(38,0) NOT NULL,
   "TEMPLATE_NAME" NVARCHAR2(100) NULL,
   "TEMPLATE_TYPE" NUMBER(38,0) NULL,
   "TEMPLATE_ORDER" NUMBER(38,0) NULL,
   "ACTFLG" VARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_ORGANIZATION'
CREATE TABLE "dbo"."HU_ORGANIZATION" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(35) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "PARENT_ID" NUMBER(38,0) NULL,
   "DISSOLVE_DATE" DATE NULL,
   "FOUNDATION_DATE" DATE NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "HIERARCHICAL_PATH" VARCHAR2(1023) NULL,
   "DESCRIPTION_PATH" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ADDRESS" NVARCHAR2(1023) NULL,
   "FAX" NVARCHAR2(1023) NULL,
   "REPRESENTATIVE_ID" NUMBER(38,0) NULL
);

-- Creating table 'HU_WORKING'
CREATE TABLE "dbo"."HU_WORKING" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "STATUS_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "EFFECT_DATE" DATE NULL,
   "EXPIRE_DATE" DATE NULL,
   "DECISION_TYPE_ID" NUMBER(38,0) NULL,
   "DECISION_NO" NVARCHAR2(255) NULL,
   "SAL_GROUP_ID" NUMBER(38,0) NULL,
   "SAL_LEVEL_ID" NUMBER(38,0) NULL,
   "SAL_RANK_ID" NUMBER(38,0) NULL,
   "SAL_BASIC" NUMBER(38,0) NULL,
   "COST_SUPPORT" NUMBER(38,0) NULL,
   "SIGN_DATE" DATE NULL,
   "SIGN_ID" NUMBER(38,0) NULL,
   "SIGN_NAME" NVARCHAR2(255) NULL,
   "SIGN_TITLE" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "IS_PROCESS" NUMBER(5,0) NULL,
   "IS_MISSION" NUMBER(5,0) NULL,
   "IS_WAGE" NUMBER(5,0) NULL,
   "PERCENT_SALARY" NUMBER(38,0) NULL
);

-- Creating table 'AT_PORTAL_APP'
CREATE TABLE "dbo"."AT_PORTAL_APP" (
   "ID" NUMBER(38,0) NOT NULL,
   "level" NUMBER(38,0) NULL,
   "ID_EMPLOYEE" NUMBER(38,0) NULL,
   "APPROVE_DATE" DATE NULL,
   "APPROVE_STATUS" NUMBER(38,0) NULL,
   "ID_REGGROUP" NUMBER(38,0) NULL,
   "ID_REQUSERID" NUMBER(38,0) NULL
);

-- Creating table 'AT_RGT'
CREATE TABLE "dbo"."AT_RGT" (
   "ID" NUMBER(38,0) NOT NULL,
   "HU_EMPLOYEEID" NUMBER(38,0) NULL,
   "WORKINGDAY" DATE NULL,
   "AT_SIGNID" NUMBER(38,0) NULL,
   "NVALUE" NUMBER(38,0) NULL,
   "SVALUE" NVARCHAR2(255) NULL,
   "DVALUE" DATE NULL,
   "ORGID" NUMBER(38,0) NULL,
   "POSID" NUMBER(38,0) NULL,
   "ISSYNC" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ISAP" NVARCHAR2(1) NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "PLNID" NUMBER(38,0) NULL,
   "NVALUE_ID" NUMBER(38,0) NULL
);

-- Creating table 'HU_ORG_TITLE'
CREATE TABLE "dbo"."HU_ORG_TITLE" (
   "ID" NUMBER(38,0) NOT NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_TITLE'
CREATE TABLE "dbo"."HU_TITLE" (
   "ID" NUMBER(38,0) NOT NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CODE" NVARCHAR2(16) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(255) NULL,
   "TITLE_GROUP_ID" NUMBER(38,0) NULL,
   "HURT_TYPE_ID" NUMBER(38,0) NULL
);

-- Creating table 'AT_WORKSIGN'
CREATE TABLE "dbo"."AT_WORKSIGN" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "WORKINGDAY" DATE NOT NULL,
   "PERIOD_ID" NUMBER(38,0) NOT NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "SHIFT_ID" NUMBER(38,0) NULL
);

-- Creating table 'AT_PORTAL_REG'
CREATE TABLE "dbo"."AT_PORTAL_REG" (
   "ID" NUMBER(38,0) NOT NULL,
   "ID_EMPLOYEE" NUMBER(38,0) NULL,
   "FROM_DATE" DATE NULL,
   "TO_DATE" DATE NULL,
   "FROM_HOUR" DATE NULL,
   "TO_HOUR" DATE NULL,
   "DAYCOUNT" NUMBER(38,0) NULL,
   "HOURCOUNT" NUMBER(38,0) NULL,
   "REGDATE" DATE NULL,
   "NOTE" NCLOB NULL,
   "STATUS" NUMBER(38,0) NULL,
   "ID_SIGN" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "NVALUE" NUMBER(10,5) NULL,
   "SVALUE" NVARCHAR2(255) NULL,
   "DVALUE" DATE NULL,
   "NVALUE_ID" NUMBER(38,0) NULL,
   "ID_REGGROUP" NUMBER(38,0) NULL,
   "NOTE_AT" NCLOB NULL,
   "IS_NB" NUMBER(38,0) NULL,
   "WORKING_DAY" DATE NULL,
   "TYPE_LEAVE" NCLOB NULL,
   "DIRECT_ID" NUMBER(38,0) NULL,
   "APPROVE_DATE" DATE NULL,
   "AT_PORTAL_REG_LIST_ID" NUMBER(38,0) NULL,
   "DAYIN_KH" NUMBER(38,0) NULL,
   "DAYOUT_KH" NUMBER(38,0) NULL,
   "WORK_DAY" NUMBER(38,0) NULL,
   "REASON" NCLOB NULL
);

-- Creating table 'HU_STAFF_RANK'
CREATE TABLE "dbo"."HU_STAFF_RANK" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL
);

-- Creating table 'AT_TIME_TIMESHEET_RICE'
CREATE TABLE "dbo"."AT_TIME_TIMESHEET_RICE" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "STAFF_RANK_ID" NUMBER(38,0) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "FROM_DATE" DATE NULL,
   "END_DATE" DATE NULL,
   "D1" NUMBER(38,0) NULL,
   "D2" NUMBER(38,0) NULL,
   "D3" NUMBER(38,0) NULL,
   "D4" NUMBER(38,0) NULL,
   "D5" NUMBER(38,0) NULL,
   "D6" NUMBER(38,0) NULL,
   "D7" NUMBER(38,0) NULL,
   "D8" NUMBER(38,0) NULL,
   "D9" NUMBER(38,0) NULL,
   "D10" NUMBER(38,0) NULL,
   "D11" NUMBER(38,0) NULL,
   "D12" NUMBER(38,0) NULL,
   "D13" NUMBER(38,0) NULL,
   "D14" NUMBER(38,0) NULL,
   "D15" NUMBER(38,0) NULL,
   "D16" NUMBER(38,0) NULL,
   "D17" NUMBER(38,0) NULL,
   "D18" NUMBER(38,0) NULL,
   "D19" NUMBER(38,0) NULL,
   "D20" NUMBER(38,0) NULL,
   "D21" NUMBER(38,0) NULL,
   "D22" NUMBER(38,0) NULL,
   "D23" NUMBER(38,0) NULL,
   "D24" NUMBER(38,0) NULL,
   "D25" NUMBER(38,0) NULL,
   "D26" NUMBER(38,0) NULL,
   "D27" NUMBER(38,0) NULL,
   "D28" NUMBER(38,0) NULL,
   "D29" NUMBER(38,0) NULL,
   "D30" NUMBER(38,0) NULL,
   "D31" NUMBER(38,0) NULL,
   "NDAY_RICE" NUMBER(38,0) NULL,
   "TOTAL_RICE_PRICE" NUMBER(38,0) NULL,
   "TOTAL_RICE_DECLARE" NUMBER(38,0) NULL,
   "RICE_EDIT" NUMBER(38,0) NULL,
   "TOTAL_RICE" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'AT_TIME_TIMESHEET_OT'
CREATE TABLE "dbo"."AT_TIME_TIMESHEET_OT" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "STAFF_RANK_ID" NUMBER(38,0) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "D1" NUMBER(38,0) NULL,
   "D2" NUMBER(38,0) NULL,
   "D3" NUMBER(38,0) NULL,
   "D4" NUMBER(38,0) NULL,
   "D5" NUMBER(38,0) NULL,
   "D6" NUMBER(38,0) NULL,
   "D7" NUMBER(38,0) NULL,
   "D8" NUMBER(38,0) NULL,
   "D9" NUMBER(38,0) NULL,
   "D10" NUMBER(38,0) NULL,
   "D11" NUMBER(38,0) NULL,
   "D12" NUMBER(38,0) NULL,
   "D13" NUMBER(38,0) NULL,
   "D14" NUMBER(38,0) NULL,
   "D15" NUMBER(38,0) NULL,
   "D16" NUMBER(38,0) NULL,
   "D17" NUMBER(38,0) NULL,
   "D18" NUMBER(38,0) NULL,
   "D19" NUMBER(38,0) NULL,
   "D20" NUMBER(38,0) NULL,
   "D21" NUMBER(38,0) NULL,
   "D22" NUMBER(38,0) NULL,
   "D23" NUMBER(38,0) NULL,
   "D24" NUMBER(38,0) NULL,
   "D25" NUMBER(38,0) NULL,
   "D26" NUMBER(38,0) NULL,
   "D27" NUMBER(38,0) NULL,
   "D28" NUMBER(38,0) NULL,
   "D29" NUMBER(38,0) NULL,
   "D30" NUMBER(38,0) NULL,
   "D31" NUMBER(38,0) NULL,
   "TOTAL_FACTOR1" NUMBER(38,0) NULL,
   "TOTAL_FACTOR1_5" NUMBER(38,0) NULL,
   "TOTAL_FACTOR2" NUMBER(38,0) NULL,
   "TOTAL_FACTOR2_7" NUMBER(38,0) NULL,
   "TOTAL_FACTOR3" NUMBER(38,0) NULL,
   "TOTAL_FACTOR3_9" NUMBER(38,0) NULL,
   "TOTAL_FACTOR_CONVERT" NUMBER(38,0) NULL,
   "NUMBER_FACTOR_PAY" NUMBER(38,0) NULL,
   "NUMBER_FACTOR_CP" NUMBER(38,0) NULL,
   "CONGHIBU" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "FROM_DATE" DATE NULL,
   "END_DATE" DATE NULL,
   "BACKUP_MONTH_BEFORE" NUMBER(38,0) NULL,
   "TOTAL_FACTOR2_1" NUMBER(38,0) NULL
);

-- Creating table 'AT_DMVS'
CREATE TABLE "dbo"."AT_DMVS" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NOT NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "MUC1" NUMBER(38,0) NULL,
   "LOAIPHAT1" NUMBER(38,0) NULL,
   "GIATRI1" NUMBER(38,0) NULL,
   "MUC2" NUMBER(38,0) NULL,
   "LOAIPHAT2" NUMBER(38,0) NULL,
   "GIATRI2" NUMBER(38,0) NULL,
   "MUC3" NUMBER(38,0) NULL,
   "LOAIPHAT3" NUMBER(38,0) NULL,
   "GIATRI3" NUMBER(38,0) NULL,
   "MUC4" NUMBER(38,0) NULL,
   "LOAIPHAT4" NUMBER(38,0) NULL,
   "GIATRI4" NUMBER(38,0) NULL,
   "MUC5" NUMBER(38,0) NULL,
   "LOAIPHAT5" NUMBER(38,0) NULL,
   "GIATRI5" NUMBER(38,0) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'AT_HOLIDAY'
CREATE TABLE "dbo"."AT_HOLIDAY" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NOT NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "WORKINGDAY" DATE NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "YEAR" NUMBER(38,0) NULL,
   "OFFDAY" NUMBER(38,0) NULL,
   "IS_SA" NUMBER(38,0) NULL,
   "IS_SU" NUMBER(38,0) NULL
);

-- Creating table 'AT_HOLIDAY_GENERAL'
CREATE TABLE "dbo"."AT_HOLIDAY_GENERAL" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NOT NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "WORKINGDAY" DATE NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'AT_HOLIDAY_OBJECT'
CREATE TABLE "dbo"."AT_HOLIDAY_OBJECT" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMP_OBJECT" NUMBER(38,0) NULL,
   "TYPE_SHIT" NUMBER(38,0) NULL,
   "SALARIED_DATES" NUMBER(38,0) NULL,
   "SALARIED_DATES_CB" NUMBER(38,0) NULL,
   "EFFECT_DATE" DATE NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'AT_LATE_COMBACKOUT'
CREATE TABLE "dbo"."AT_LATE_COMBACKOUT" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "WORKINGDAY" DATE NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "TYPE_DSVM" NUMBER(38,0) NULL,
   "MINUTE" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "FROM_HOUR" DATE NULL,
   "TO_HOUR" DATE NULL
);

-- Creating table 'AT_PERIOD'
CREATE TABLE "dbo"."AT_PERIOD" (
   "YEAR" NUMBER(38,0) NULL,
   "MONTH" NUMBER(38,0) NULL,
   "PERIOD_NAME" NVARCHAR2(255) NULL,
   "START_DATE" DATE NULL,
   "END_DATE" DATE NULL,
   "PERIOD_STANDARD" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ID" NUMBER(38,0) NOT NULL,
   "STATUS" NUMBER(38,0) NULL
);

-- Creating table 'AT_SETUP_SPECIAL'
CREATE TABLE "dbo"."AT_SETUP_SPECIAL" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "POS_ID" NUMBER(38,0) NULL,
   "DATE_FROM" DATE NULL,
   "DATE_TO" DATE NULL,
   "NUMBER_SWIPECARD" NUMBER(38,0) NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "STAFF_RANK_ID" NUMBER(38,0) NULL
);

-- Creating table 'AT_SIGNDEFAULT'
CREATE TABLE "dbo"."AT_SIGNDEFAULT" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "EFFECT_DATE_FROM" DATE NULL,
   "EFFECT_DATE_TO" DATE NULL,
   "SINGDEFAULE" NUMBER(38,0) NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "SING_SAT" NUMBER(38,0) NULL,
   "SING_SUN" NUMBER(38,0) NULL
);

-- Creating table 'AT_TIME_MANUAL'
CREATE TABLE "dbo"."AT_TIME_MANUAL" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "MORNING_ID" NUMBER(38,0) NULL,
   "AFTERNOON_ID" NUMBER(38,0) NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "TYPE_PROSS_ID" NUMBER(38,0) NULL,
   "MORNING_RATE_ID" NUMBER(38,0) NULL,
   "AFTERNOON_RATE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "ORDERS" NUMBER(38,0) NULL
);

-- Creating table 'AT_TIME_RICE'
CREATE TABLE "dbo"."AT_TIME_RICE" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "STAFF_RANK_ID" NUMBER(38,0) NULL,
   "WORKINGDAY" DATE NULL,
   "PRICE" NUMBER(38,0) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "NOTE" VARCHAR2(1023) NULL
);

-- Creating table 'AT_TIME_TIMESHEET_DAILY'
CREATE TABLE "dbo"."AT_TIME_TIMESHEET_DAILY" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "WORKINGDAY" DATE NULL,
   "SHIFT_CODE" NVARCHAR2(50) NULL,
   "LEAVE_CODE" NVARCHAR2(20) NULL,
   "LATE" NUMBER(38,0) NULL,
   "COMEBACKOUT" NUMBER(38,0) NULL,
   "WORKDAY_OT" NUMBER(38,0) NULL,
   "WORKDAY_NIGHT" NUMBER(38,0) NULL,
   "TYPE_DAY" VARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "VALIN1" DATE NULL,
   "VALIN2" DATE NULL,
   "VALIN3" DATE NULL,
   "VALIN4" DATE NULL,
   "DECISION_ID" NUMBER(38,0) NULL,
   "PA_OBJECT_SALARY_ID" NUMBER(38,0) NULL,
   "SHIFT_ID" NUMBER(38,0) NULL,
   "MANUAL_ID" NUMBER(38,0) NULL,
   "LEAVE_ID" NUMBER(38,0) NULL
);

-- Creating table 'AT_TIME_TIMESHEET_MACHINET'
CREATE TABLE "dbo"."AT_TIME_TIMESHEET_MACHINET" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "WORKINGDAY" DATE NULL,
   "SHIFT_CODE" NVARCHAR2(50) NULL,
   "LEAVE_CODE" NVARCHAR2(50) NULL,
   "LATE" NUMBER(38,0) NULL,
   "COMEBACKOUT" NUMBER(38,0) NULL,
   "WORKDAY_OT" NUMBER(38,0) NULL,
   "WORKDAY_NIGHT" NUMBER(38,0) NULL,
   "TYPE_DAY" VARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "WORKINGHOUR" NUMBER(38,0) NULL,
   "VALIN1" DATE NULL,
   "VALIN2" DATE NULL,
   "VALIN3" DATE NULL,
   "VALIN4" DATE NULL,
   "SHIFT_ID" NUMBER(38,0) NULL,
   "MANUAL_ID" NUMBER(38,0) NULL,
   "LEAVE_ID" NUMBER(38,0) NULL,
   "OBJECT_ATTENDANCE" NUMBER(38,0) NULL,
   "MIN_IN_WORK" NUMBER(38,0) NULL,
   "MIN_OUT_WORK" NUMBER(38,0) NULL,
   "MIN_DEDUCT_WORK" NUMBER(38,0) NULL,
   "MIN_ON_LEAVE" NUMBER(38,0) NULL,
   "MIN_DEDUCT" NUMBER(38,0) NULL,
   "MIN_OUT_WORK_DEDUCT" NUMBER(38,0) NULL,
   "MIN_LATE" NUMBER(38,0) NULL,
   "MIN_EARLY" NUMBER(38,0) NULL,
   "MIN_LATE_EARLY" NUMBER(38,0) NULL,
   "WORKINGHOUR_SHIFT" NUMBER(38,0) NULL,
   "NUMBER_SWIPE" NUMBER(38,0) NULL,
   "IS_HOLIDAY" NUMBER(38,0) NULL,
   "IS_FULLDAY" NUMBER(38,0) NULL,
   "SHIFT_MANUAL_ID" NUMBER(38,0) NULL,
   "IS_NOON" NUMBER(38,0) NULL,
   "SHIFT_HOURS_START" DATE NULL,
   "SHIFT_HOURS_STOP" DATE NULL,
   "BREAKS_FORM" DATE NULL,
   "BREAKS_TO" DATE NULL,
   "MINUTE_DM" NUMBER(38,0) NULL,
   "MINUTE_VS" NUMBER(38,0) NULL,
   "REQUEST_ID" NUMBER(38,0) NULL,
   "STAFF_RANK_ID" NUMBER(38,0) NULL,
   "VALIN5" DATE NULL,
   "VALIN6" DATE NULL,
   "VALIN7" DATE NULL,
   "VALIN8" DATE NULL,
   "VALIN9" DATE NULL,
   "VALIN10" DATE NULL,
   "VALIN11" DATE NULL,
   "VALIN12" DATE NULL,
   "VALIN13" DATE NULL,
   "VALIN14" DATE NULL,
   "VALIN15" DATE NULL,
   "VALIN16" DATE NULL,
   "VALOUT1" DATE NULL,
   "VALOUT2" DATE NULL,
   "VALOUT3" DATE NULL,
   "VALOUT4" DATE NULL,
   "VALOUT5" DATE NULL,
   "VALOUT6" DATE NULL,
   "VALOUT7" DATE NULL,
   "VALOUT8" DATE NULL,
   "VALOUT9" DATE NULL,
   "VALOUT10" DATE NULL,
   "VALOUT11" DATE NULL,
   "VALOUT12" DATE NULL,
   "VALOUT13" DATE NULL,
   "VALOUT14" DATE NULL,
   "VALOUT15" DATE NULL,
   "VALOUT16" DATE NULL,
   "TIMEVALIN" DATE NULL,
   "TIMEVALOUT" DATE NULL,
   "WORK_HOUR" NUMBER(38,0) NULL,
   "TIMEVALIN_TEMP" DATE NULL,
   "OBJECT_ATTENDANCE_CODE" NCLOB NULL,
   "HOURS_STOP" DATE NULL,
   "HOURS_START" DATE NULL,
   "TIMEIN_REALITY" DATE NULL,
   "TIMEOUT_REALITY" DATE NULL,
   "START_MID_HOURS" DATE NULL,
   "WORKING_VALUE" NUMBER(38,0) NULL,
   "SHIFT_DAY" NUMBER(38,0) NULL,
   "SHIFT_TYPE_ID" NUMBER(38,0) NULL,
   "NOTE" NCLOB NULL,
   "SHIFT_TYPE_CODE" NCLOB NULL,
   "END_MID_HOURS" DATE NULL,
   "DAY_NUM" NUMBER(38,0) NULL,
   "STATUS_SHIFT" NUMBER(38,0) NULL,
   "STATUS_SHIFT_NAME" NCLOB NULL
);

-- Creating table 'AT_DATA_INOUT'
CREATE TABLE "dbo"."AT_DATA_INOUT" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ITIME_ID" NCLOB NULL,
   "WORKINGDAY" DATE NULL,
   "VALIN1" DATE NULL,
   "VALIN2" DATE NULL,
   "VALIN3" DATE NULL,
   "VALIN4" DATE NULL,
   "VALIN5" DATE NULL,
   "VALIN6" DATE NULL,
   "VALIN7" DATE NULL,
   "VALIN8" DATE NULL,
   "VALIN9" DATE NULL,
   "VALIN10" DATE NULL,
   "VALIN11" DATE NULL,
   "VALIN12" DATE NULL,
   "VALIN13" DATE NULL,
   "VALIN14" DATE NULL,
   "VALIN15" DATE NULL,
   "VALIN16" DATE NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "VALOUT1" DATE NULL,
   "VALOUT2" DATE NULL,
   "VALOUT3" DATE NULL,
   "VALOUT4" DATE NULL,
   "VALOUT5" DATE NULL,
   "VALOUT6" DATE NULL,
   "VALOUT7" DATE NULL,
   "VALOUT8" DATE NULL,
   "VALOUT9" DATE NULL,
   "VALOUT10" DATE NULL,
   "VALOUT11" DATE NULL,
   "VALOUT12" DATE NULL,
   "VALOUT13" DATE NULL,
   "VALOUT14" DATE NULL,
   "VALOUT15" DATE NULL,
   "VALOUT16" DATE NULL
);

-- Creating table 'AT_FML'
CREATE TABLE "dbo"."AT_FML" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(20) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "EFFECT_DATE" DATE NULL,
   "NOTE" NVARCHAR2(1000) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "IS_LEAVE" NUMBER(38,0) NULL,
   "IS_CALHOLIDAY" NUMBER(5,0) NULL,
   "HOURS" NUMBER(38,0) NULL,
   "IS_REG_SHIFT" NUMBER(10,0) NULL
);

-- Creating table 'AT_TERMINALS'
CREATE TABLE "dbo"."AT_TERMINALS" (
   "ID" NUMBER(38,0) NOT NULL,
   "TERMINAL_CODE" NVARCHAR2(50) NOT NULL,
   "TERMINAL_NAME" NVARCHAR2(255) NULL,
   "ADDRESS_PLACE" NVARCHAR2(255) NULL,
   "TERMINAL_IP" NVARCHAR2(50) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "TERMINAL_NUMBER" NUMBER(38,0) NULL,
   "PASS" NVARCHAR2(255) NULL,
   "PORT" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "LAST_TIME_UPDATE" DATE NULL,
   "LAST_TIME_STATUS" DATE NULL,
   "TERMINAL_STATUS" NVARCHAR2(50) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TERMINAL_ROW" NUMBER(38,0) NULL,
   "TERMINAL_TYPE" NUMBER(38,0) NULL,
   "TIME_RECORDER" NUMBER(38,0) NULL
);

-- Creating table 'AT_ACTION_ORG_LOG'
CREATE TABLE "dbo"."AT_ACTION_ORG_LOG" (
   "ID" NUMBER(38,0) NOT NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ACTION_LOG_ID" NUMBER(38,0) NULL
);

-- Creating table 'HU_EMPLOYEE_CV'
CREATE TABLE "dbo"."HU_EMPLOYEE_CV" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "GENDER" NUMBER(38,0) NULL,
   "IMAGE" NVARCHAR2(255) NULL,
   "BIRTH_DATE" DATE NULL,
   "BIRTH_PLACE" NVARCHAR2(255) NULL,
   "MARITAL_STATUS" NUMBER(38,0) NULL,
   "RELIGION" NUMBER(38,0) NULL,
   "NATIVE" NUMBER(38,0) NULL,
   "NATIONALITY" NUMBER(38,0) NULL,
   "PER_ADDRESS" NVARCHAR2(255) NULL,
   "PER_PROVINCE" NUMBER(38,0) NULL,
   "HOME_PHONE" NVARCHAR2(255) NULL,
   "MOBILE_PHONE" NVARCHAR2(255) NULL,
   "ID_NO" NVARCHAR2(15) NULL,
   "ID_DATE" DATE NULL,
   "PASS_NO" NVARCHAR2(255) NULL,
   "PASS_DATE" DATE NULL,
   "PASS_EXPIRE" DATE NULL,
   "PASS_PLACE" NVARCHAR2(255) NULL,
   "VISA" NVARCHAR2(255) NULL,
   "VISA_DATE" DATE NULL,
   "VISA_EXPIRE" DATE NULL,
   "VISA_PLACE" NVARCHAR2(255) NULL,
   "WORK_PERMIT" NVARCHAR2(255) NULL,
   "WORK_PERMIT_DATE" DATE NULL,
   "WORK_PERMIT_EXPIRE" DATE NULL,
   "WORK_EMAIL" NVARCHAR2(255) NULL,
   "NAV_ADDRESS" NVARCHAR2(255) NULL,
   "NAV_PROVINCE" NUMBER(38,0) NULL,
   "PIT_CODE" VARCHAR2(255) NULL,
   "PER_EMAIL" NVARCHAR2(255) NULL,
   "CONTACT_PER" NVARCHAR2(255) NULL,
   "CONTACT_PER_PHONE" NVARCHAR2(15) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ID_PLACE" NUMBER(38,0) NULL,
   "WORK_PERMIT_PLACE" NVARCHAR2(255) NULL,
   "BANK_ID" NUMBER(38,0) NULL,
   "BANK_BRANCH_ID" NUMBER(38,0) NULL,
   "BANK_NO" NVARCHAR2(255) NULL,
   "NGAY_VAO_DOAN" DATE NULL,
   "NOI_VAO_DOAN" NVARCHAR2(255) NULL,
   "CHUC_VU_DOAN" NVARCHAR2(255) NULL,
   "DOAN_PHI" NUMBER(5,0) NULL,
   "NGAY_VAO_DANG" DATE NULL,
   "NOI_VAO_DANG" NVARCHAR2(255) NULL,
   "CHUC_VU_DANG" NVARCHAR2(255) NULL,
   "DANG_PHI" NUMBER(5,0) NULL,
   "CAREER" NVARCHAR2(255) NULL,
   "PER_DISTRICT" NUMBER(38,0) NULL,
   "NAV_DISTRICT" NUMBER(38,0) NULL,
   "PER_WARD" NUMBER(38,0) NULL,
   "NAV_WARD" NUMBER(38,0) NULL
);

-- Creating table 'SE_MAIL'
CREATE TABLE "dbo"."SE_MAIL" (
   "ID" NUMBER(38,0) NOT NULL,
   "SUBJECT" NVARCHAR2(255) NULL,
   "MAIL_FROM" NVARCHAR2(255) NULL,
   "MAIL_TO" NVARCHAR2(1024) NULL,
   "MAIL_CC" NVARCHAR2(1024) NULL,
   "MAIL_BCC" NVARCHAR2(1024) NULL,
   "CONTENT" NCLOB NULL,
   "VIEW_NAME" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "ATTACHMENT" NCLOB NULL
);

-- Creating table 'AT_SETUP_TIME_EMP'
CREATE TABLE "dbo"."AT_SETUP_TIME_EMP" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "NUMBER_SWIPECARD" NUMBER(38,0) NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'SE_EMPLOYEE_CHOSEN'
CREATE TABLE "dbo"."SE_EMPLOYEE_CHOSEN" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "USING_USER" NVARCHAR2(20) NOT NULL,
   "WORKINGDAY" DATE NOT NULL
);

-- Creating table 'AT_LIST_PARAM_SYSTEM'
CREATE TABLE "dbo"."AT_LIST_PARAM_SYSTEM" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "EFFECT_DATE_FROM" DATE NULL,
   "EFFECT_DATE_TO_NB" DATE NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "TO_LEAVE_YEAR" DATE NULL,
   "RANK_PAY_OT" NUMBER(38,0) NULL,
   "HOUR_CAL_OT" NUMBER(38,0) NULL,
   "HOUR_MAX_OT" NUMBER(38,0) NULL,
   "FACTOR_OT" NUMBER(38,0) NULL,
   "CREATE_BY_SHOW" NVARCHAR2(255) NULL,
   "CREATE_DATE_SHOW" DATE NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "MAX_DAY_OT" NUMBER(38,0) NULL,
   "YEAR_P" NUMBER(38,0) NULL,
   "YEAR_TN" NUMBER(38,0) NULL,
   "DAY_TN" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "NO_EFFECT_ENT" NUMBER(38,0) NULL
);

-- Creating table 'AT_REGISTER_OT'
CREATE TABLE "dbo"."AT_REGISTER_OT" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "WORKINGDAY" DATE NULL,
   "FROM_HOUR" DATE NULL,
   "TO_HOUR" DATE NULL,
   "BREAK_HOUR" NUMBER(38,0) NULL,
   "NOTE" VARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "TYPE_OT" NUMBER(38,0) NULL,
   "HOUR" NUMBER(38,0) NULL,
   "HS_OT" NUMBER(38,0) NULL,
   "TYPE_INPUT" NUMBER(38,0) NULL,
   "IS_NB" NUMBER(38,0) NULL,
   "APPROVE_ID" NUMBER(38,0) NULL,
   "APPROVE_DATE" DATE NULL,
   "APPROVE_HOUR" NUMBER(38,0) NULL
);

-- Creating table 'SE_USER'
CREATE TABLE "dbo"."SE_USER" (
   "ID" NUMBER(38,0) NOT NULL,
   "USERNAME" NVARCHAR2(255) NOT NULL,
   "PASSWORD" NVARCHAR2(255) NULL,
   "FULLNAME" NVARCHAR2(255) NOT NULL,
   "EMAIL" NVARCHAR2(255) NULL,
   "TELEPHONE" NVARCHAR2(255) NULL,
   "LOCATION" NVARCHAR2(255) NULL,
   "IS_APP" NUMBER(5,0) NOT NULL,
   "IS_PORTAL" NUMBER(5,0) NOT NULL,
   "EMPLOYEE_CODE" VARCHAR2(15) NULL,
   "IS_AD" NUMBER(5,0) NULL,
   "EFFECT_DATE" DATE NULL,
   "EXPIRE_DATE" DATE NULL,
   "CREATED_DATE" DATE NOT NULL,
   "CREATED_BY" NVARCHAR2(255) NOT NULL,
   "CREATED_LOG" NVARCHAR2(255) NOT NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_BY" NVARCHAR2(255) NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NOT NULL,
   "ACTFLG" NVARCHAR2(1) NOT NULL,
   "IS_CHANGE_PASS" NUMBER(5,0) NULL,
   "CHANGE_PASS_DATE" DATE NULL,
   "REMINDER_COUNT" NUMBER(5,0) NULL,
   "MODULE_ADMIN" NVARCHAR2(255) NULL
);

-- Creating table 'SE_REPORT'
CREATE TABLE "dbo"."SE_REPORT" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NOT NULL,
   "CODE" NVARCHAR2(255) NOT NULL,
   "MODULE_ID" NUMBER(38,0) NOT NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_BY" NVARCHAR2(255) NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NOT NULL
);

-- Creating table 'AT_COMPENSATORY'
CREATE TABLE "dbo"."AT_COMPENSATORY" (
   "ID" NUMBER(38,0) NOT NULL,
   "YEAR" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "CAL_DATE" DATE NULL,
   "PREV_HAVE" NUMBER(38,0) NULL,
   "PREV_USED" NUMBER(38,0) NULL,
   "EXPIREDATE" DATE NULL,
   "CUR_HAVE" NUMBER(38,0) NULL,
   "CUR_USED" NUMBER(38,0) NULL,
   "CUR_HAVE1" NUMBER(38,0) NULL,
   "CUR_HAVE2" NUMBER(38,0) NULL,
   "CUR_HAVE3" NUMBER(38,0) NULL,
   "CUR_HAVE4" NUMBER(38,0) NULL,
   "CUR_HAVE5" NUMBER(38,0) NULL,
   "CUR_HAVE6" NUMBER(38,0) NULL,
   "CUR_HAVE7" NUMBER(38,0) NULL,
   "CUR_HAVE8" NUMBER(38,0) NULL,
   "CUR_HAVE9" NUMBER(38,0) NULL,
   "CUR_HAVE10" NUMBER(38,0) NULL,
   "CUR_HAVE11" NUMBER(38,0) NULL,
   "CUR_HAVE12" NUMBER(38,0) NULL,
   "CUR_USED1" NUMBER(38,0) NULL,
   "CUR_USED2" NUMBER(38,0) NULL,
   "CUR_USED3" NUMBER(38,0) NULL,
   "CUR_USED4" NUMBER(38,0) NULL,
   "CUR_USED5" NUMBER(38,0) NULL,
   "CUR_USED6" NUMBER(38,0) NULL,
   "CUR_USED7" NUMBER(38,0) NULL,
   "CUR_USED8" NUMBER(38,0) NULL,
   "CUR_USED9" NUMBER(38,0) NULL,
   "CUR_USED10" NUMBER(38,0) NULL,
   "CUR_USED11" NUMBER(38,0) NULL,
   "CUR_USED12" NUMBER(38,0) NULL,
   "AL_T1" NUMBER(38,0) NULL,
   "AL_T2" NUMBER(38,0) NULL,
   "AL_T3" NUMBER(38,0) NULL,
   "AL_T4" NUMBER(38,0) NULL,
   "AL_T5" NUMBER(38,0) NULL,
   "AL_T6" NUMBER(38,0) NULL,
   "AL_T7" NUMBER(38,0) NULL,
   "AL_T8" NUMBER(38,0) NULL,
   "AL_T9" NUMBER(38,0) NULL,
   "AL_T10" NUMBER(38,0) NULL,
   "AL_T11" NUMBER(38,0) NULL,
   "AL_T12" NUMBER(38,0) NULL,
   "PREV_USED1" NUMBER(38,0) NULL,
   "PREV_USED2" NUMBER(38,0) NULL,
   "PREV_USED3" NUMBER(38,0) NULL,
   "PREV_USED4" NUMBER(38,0) NULL,
   "PREV_USED5" NUMBER(38,0) NULL,
   "PREV_USED6" NUMBER(38,0) NULL,
   "PREV_USED7" NUMBER(38,0) NULL,
   "PREV_USED8" NUMBER(38,0) NULL,
   "PREV_USED9" NUMBER(38,0) NULL,
   "PREV_USED10" NUMBER(38,0) NULL,
   "PREV_USED11" NUMBER(38,0) NULL,
   "PREV_USED12" NUMBER(38,0) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "AL_ADD_T1" NUMBER(38,0) NULL,
   "AL_ADD_T2" NUMBER(38,0) NULL,
   "AL_ADD_T3" NUMBER(38,0) NULL,
   "AL_ADD_T4" NUMBER(38,0) NULL,
   "AL_ADD_T5" NUMBER(38,0) NULL,
   "AL_ADD_T6" NUMBER(38,0) NULL,
   "AL_ADD_T7" NUMBER(38,0) NULL,
   "AL_ADD_T8" NUMBER(38,0) NULL,
   "AL_ADD_T9" NUMBER(38,0) NULL,
   "AL_ADD_T10" NUMBER(38,0) NULL,
   "AL_ADD_T11" NUMBER(38,0) NULL,
   "AL_ADD_T12" NUMBER(38,0) NULL,
   "TOTAL_HAVE" NUMBER(38,0) NULL,
   "SUB_PREV_ENT" NUMBER(38,0) NULL
);

-- Creating table 'AT_ACTION_LOG'
CREATE TABLE "dbo"."AT_ACTION_LOG" (
   "ID" NUMBER(38,0) NOT NULL,
   "USERNAME" NVARCHAR2(255) NULL,
   "ACTION_NAME" NVARCHAR2(255) NULL,
   "ACTION_DATE" DATE NULL,
   "OBJECT_NAME" NVARCHAR2(255) NULL,
   "IP" NVARCHAR2(255) NULL,
   "COMPUTER_NAME" NVARCHAR2(255) NULL,
   "ACTION_TYPE" NVARCHAR2(255) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "NEW_VALUE" NVARCHAR2(1023) NULL,
   "OLD_VALUE" NVARCHAR2(1023) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL
);

-- Creating table 'AT_DECLARE_ENTITLEMENT'
CREATE TABLE "dbo"."AT_DECLARE_ENTITLEMENT" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ADJUST_MONTH_TN" NUMBER(38,0) NULL,
   "REMARK_NB" NVARCHAR2(1023) NULL,
   "ADJUST_ENTITLEMENT" NUMBER(38,0) NULL,
   "ADJUST_MONTH_ENTITLEMENT" NUMBER(38,0) NULL,
   "REMARK_ENTITLEMENT" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "START_MONTH_EXTEND" NUMBER(38,0) NULL,
   "START_MONTH_TN" NUMBER(38,0) NULL,
   "REMARK_TN" NVARCHAR2(1023) NULL,
   "START_MONTH_NB" NUMBER(38,0) NULL,
   "ADJUST_NB" NUMBER(38,0) NULL,
   "YEAR" NUMBER(38,0) NULL,
   "YEAR_NB" NUMBER(38,0) NULL,
   "YEAR_ENTITLEMENT" NUMBER(38,0) NULL,
   "MONTH_EXTENSION_NB" NUMBER(38,0) NULL,
   "COM_PAY" NUMBER(38,0) NULL,
   "ENT_PAY" NUMBER(38,0) NULL,
   "JOIN_DATE" DATE NULL,
   "MODIFY_TYPE_ID" NUMBER(38,0) NULL,
   "END_MONTH_TN" NUMBER(38,0) NULL,
   "EXPIRE_YEAR" NUMBER(38,0) NULL,
   "START_DATE" DATE NULL,
   "END_DATE" DATE NULL
);

-- Creating table 'AT_PROJECT'
CREATE TABLE "dbo"."AT_PROJECT" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(20) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "EFFECT_DATE" DATE NULL,
   "EXPIRE_DATE" DATE NULL,
   "MANAGER_ID" NUMBER(38,0) NULL,
   "STATUS_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'AT_PROJECT_TITLE'
CREATE TABLE "dbo"."AT_PROJECT_TITLE" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(20) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(1000) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'AT_PROJECT_EMP'
CREATE TABLE "dbo"."AT_PROJECT_EMP" (
   "ID" NUMBER(38,0) NOT NULL,
   "PROJECT_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "PROJECT_TITLE_ID" NUMBER(38,0) NULL,
   "EFFECT_DATE" DATE NULL,
   "EXPIRE_DATE" DATE NULL,
   "COST" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'AT_PROJECT_WORK'
CREATE TABLE "dbo"."AT_PROJECT_WORK" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(20) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(1000) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'AT_PROJECT_ASSIGN'
CREATE TABLE "dbo"."AT_PROJECT_ASSIGN" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "PROJECT_WORK_ID" NUMBER(38,0) NULL,
   "PROJECT_ID" NUMBER(38,0) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "WORKINGDAY" DATE NULL,
   "HOURS" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'AT_TIMESHEET_OT_DTL'
CREATE TABLE "dbo"."AT_TIMESHEET_OT_DTL" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "TOTAL_FACTOR1" NUMBER(38,0) NULL,
   "TOTAL_FACTOR1_5" NUMBER(38,0) NULL,
   "TOTAL_FACTOR2" NUMBER(38,0) NULL,
   "TOTAL_FACTOR2_7" NUMBER(38,0) NULL,
   "TOTAL_FACTOR3" NUMBER(38,0) NULL,
   "TOTAL_FACTOR3_9" NUMBER(38,0) NULL,
   "TOTAL_FACTOR_CONVERT" NUMBER(38,0) NULL,
   "NUMBER_FACTOR_PAY" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "D1" NUMBER(38,0) NULL,
   "D2" NUMBER(38,0) NULL,
   "D3" NUMBER(38,0) NULL,
   "D4" NUMBER(38,0) NULL,
   "D5" NUMBER(38,0) NULL,
   "D6" NUMBER(38,0) NULL,
   "D7" NUMBER(38,0) NULL,
   "D8" NUMBER(38,0) NULL,
   "D9" NUMBER(38,0) NULL,
   "D10" NUMBER(38,0) NULL,
   "D11" NUMBER(38,0) NULL,
   "D12" NUMBER(38,0) NULL,
   "D13" NUMBER(38,0) NULL,
   "D14" NUMBER(38,0) NULL,
   "D15" NUMBER(38,0) NULL,
   "D16" NUMBER(38,0) NULL,
   "D17" NUMBER(38,0) NULL,
   "D18" NUMBER(38,0) NULL,
   "D19" NUMBER(38,0) NULL,
   "D20" NUMBER(38,0) NULL,
   "D21" NUMBER(38,0) NULL,
   "D22" NUMBER(38,0) NULL,
   "D23" NUMBER(38,0) NULL,
   "D24" NUMBER(38,0) NULL,
   "D25" NUMBER(38,0) NULL,
   "D26" NUMBER(38,0) NULL,
   "D27" NUMBER(38,0) NULL,
   "D28" NUMBER(38,0) NULL,
   "D29" NUMBER(38,0) NULL,
   "D30" NUMBER(38,0) NULL,
   "D31" NUMBER(38,0) NULL,
   "FROM_DATE" DATE NULL,
   "END_DATE" DATE NULL,
   "WORKING_ID" NUMBER(38,0) NULL
);

-- Creating table 'AT_TIME_TIMESHEET_MONTHLY'
CREATE TABLE "dbo"."AT_TIME_TIMESHEET_MONTHLY" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "WORKING_E" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "DECISION_ID" NUMBER(38,0) NULL,
   "WORKING_X" NUMBER(38,0) NULL,
   "PA_OBJECT_SALARY_ID" NUMBER(38,0) NULL,
   "STAFF_RANK_ID" NUMBER(38,0) NULL,
   "FROM_DATE" DATE NULL,
   "END_DATE" DATE NULL,
   "WORKING_F" NUMBER(38,0) NULL,
   "WORKING_A" NUMBER(38,0) NULL,
   "WORKING_H" NUMBER(38,0) NULL,
   "WORKING_D" NUMBER(38,0) NULL,
   "WORKING_C" NUMBER(38,0) NULL,
   "WORKING_T" NUMBER(38,0) NULL,
   "WORKING_Q" NUMBER(38,0) NULL,
   "WORKING_N" NUMBER(38,0) NULL,
   "WORKING_P" NUMBER(38,0) NULL,
   "WORKING_L" NUMBER(38,0) NULL,
   "WORKING_R" NUMBER(38,0) NULL,
   "WORKING_S" NUMBER(38,0) NULL,
   "WORKING_B" NUMBER(38,0) NULL,
   "WORKING_K" NUMBER(38,0) NULL,
   "WORKING_J" NUMBER(38,0) NULL,
   "WORKING_TS" NUMBER(38,0) NULL,
   "WORKING_O" NUMBER(38,0) NULL,
   "WORKING_V" NUMBER(38,0) NULL,
   "TOTAL_WORKING" NUMBER(38,0) NULL,
   "WORKING_ADD" NUMBER(38,0) NULL,
   "DECISION_START" DATE NULL,
   "DECISION_END" DATE NULL,
   "WORKING_DA" NUMBER(38,0) NULL,
   "LATE" NUMBER(38,0) NULL,
   "COMEBACKOUT" NUMBER(38,0) NULL,
   "TOTAL_W_SALARY" NUMBER(38,0) NULL,
   "TOTAL_W_NOSALARY" NUMBER(38,0) NULL,
   "WORKING_MEAL" NUMBER(38,0) NULL,
   "OBJECT_ATTENDANCE" NUMBER(38,0) NULL,
   "MIN_IN_WORK" NUMBER(38,0) NULL,
   "MIN_OUT_WORK" NUMBER(38,0) NULL,
   "MIN_DEDUCT_WORK" NUMBER(38,0) NULL,
   "MIN_ON_LEAVE" NUMBER(38,0) NULL,
   "MIN_DEDUCT" NUMBER(38,0) NULL,
   "MIN_OUT_WORK_DEDUCT" NUMBER(38,0) NULL,
   "MIN_LATE" NUMBER(38,0) NULL,
   "MIN_EARLY" NUMBER(38,0) NULL,
   "MIN_LATE_EARLY" NUMBER(38,0) NULL,
   "WORKING_TN" NUMBER(38,0) NULL,
   "WORKING_KLD" NUMBER(38,0) NULL,
   "SALARY_ID_NEW" NUMBER(38,0) NULL,
   "SALARY_ID" NUMBER(38,0) NULL
);

-- Creating table 'AT_PORTAL_REG_LIST'
CREATE TABLE "dbo"."AT_PORTAL_REG_LIST" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "FROM_DATE" DATE NULL,
   "TO_DATE" DATE NULL,
   "TOTAL_LEAVE" NUMBER(38,0) NULL,
   "ID_SIGN" NUMBER(38,0) NULL,
   "STATUS" NUMBER(38,0) NULL,
   "NOTE" NCLOB NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "REASON" NCLOB NULL
);

-- Creating table 'AT_TIMESHEET'
CREATE TABLE "dbo"."AT_TIMESHEET" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "YEAR_ID" NUMBER(38,0) NULL,
   "MONTH_ID" NUMBER(38,0) NULL,
   "APPROVER_ID" NUMBER(38,0) NULL,
   "STATUS" NUMBER(38,0) NULL,
   "TOTAL_WOS" NUMBER(38,0) NULL,
   "TOTAL_COMPENSATION" NUMBER(38,1) NULL,
   "TOTAL_OT" NUMBER(38,1) NULL,
   "TOTAL_NIGHT_SHIFT_SUP" NUMBER(38,1) NULL,
   "TOTAL_OFFSHORE" NUMBER(38,1) NULL,
   "TOTAL_ANNUAL_LEAVE" NUMBER(38,1) NULL,
   "TOTAL_SICK_LEAVE" NUMBER(38,1) NULL,
   "TOTAL_MATERNITY_LEAVE" NUMBER(38,1) NULL,
   "TOTAL_MATERNITY_CHECKUP_LEAVE" NUMBER(38,1) NULL,
   "TOTAL_PETARNITY_LEAVE" NUMBER(38,1) NULL,
   "TOTAL_CHILD_SICK_LEAVE" NUMBER(38,1) NULL,
   "TOTAL_COMPASSIONATE_LEAVE" NUMBER(38,1) NULL,
   "TOTAL_UNPAID_LEAVE" NUMBER(38,1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "REASON" NVARCHAR2(255) NULL,
   "PAYROLL_YEAR" NUMBER(38,0) NULL,
   "PAYROLL_MONTH" NUMBER(38,0) NULL,
   "TOTAL_NIGHT" NUMBER(38,0) NULL,
   "TOTAL_150" NUMBER(38,1) NULL,
   "TOTAL_200" NUMBER(38,1) NULL,
   "TOTAL_210" NUMBER(38,1) NULL,
   "TOTAL_270" NUMBER(38,1) NULL,
   "TOTAL_300" NUMBER(38,1) NULL,
   "TOTAL_390" NUMBER(38,1) NULL
);

-- Creating table 'AT_SHIFTCYCLE_EMP_DETAIL'
CREATE TABLE "dbo"."AT_SHIFTCYCLE_EMP_DETAIL" (
   "ID" NUMBER(38,0) NOT NULL,
   "EFFECTIVEDATE" DATE NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "AT_SHIFTCYCLE_EMP_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "FML_ID" NUMBER(38,0) NULL
);

-- Creating table 'AT_SETUP_ATT_EMP'
CREATE TABLE "dbo"."AT_SETUP_ATT_EMP" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "MACHINE_ID" NUMBER(38,0) NULL,
   "CODE_ATT" NVARCHAR2(50) NULL,
   "APPROVE_DATE" DATE NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "NOTE" NVARCHAR2(255) NULL
);

-- Creating table 'AT_OT_REGISTRATION'
CREATE TABLE "dbo"."AT_OT_REGISTRATION" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "REGIST_DATE" DATE NULL,
   "SIGN_ID" NUMBER(38,0) NULL,
   "SIGN_CODE" NVARCHAR2(100) NULL,
   "OT_TYPE_ID" NUMBER(38,0) NULL,
   "TOTAL_OT" NUMBER(38,2) NULL,
   "OT_100" NUMBER(38,2) NULL,
   "OT_150" NUMBER(38,2) NULL,
   "OT_200" NUMBER(38,2) NULL,
   "OT_210" NUMBER(38,2) NULL,
   "OT_270" NUMBER(38,2) NULL,
   "OT_300" NUMBER(38,2) NULL,
   "OT_370" NUMBER(38,2) NULL,
   "NOTE" NVARCHAR2(500) NULL,
   "STATUS" NUMBER(38,0) NULL,
   "REASON" NVARCHAR2(500) NULL,
   "IS_DELETED" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "FROM_AM" NUMBER(38,0) NULL,
   "FROM_AM_MN" NUMBER(38,0) NULL,
   "TO_AM" NUMBER(38,0) NULL,
   "TO_AM_MN" NUMBER(38,0) NULL,
   "FROM_PM" NUMBER(38,0) NULL,
   "FROM_PM_MN" NUMBER(38,0) NULL,
   "TO_PM" NUMBER(38,0) NULL,
   "TO_PM_MN" NUMBER(38,0) NULL,
   "HR_REVIEW" NUMBER(38,0) NULL,
   "ID_REGGROUP" NUMBER(38,0) NULL
);

-- Creating table 'AT_OFFSETTING_TIMEKEEPING'
CREATE TABLE "dbo"."AT_OFFSETTING_TIMEKEEPING" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITILE_ID" NUMBER(38,0) NULL,
   "FROMDATE" DATE NULL,
   "TODATE" DATE NULL,
   "TYPE_BT" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1025) NULL,
   "MINUTES_BT" NUMBER(38,0) NULL
);

-- Creating table 'AT_OFFSETTING_TIMEKEEPING_EMP'
CREATE TABLE "dbo"."AT_OFFSETTING_TIMEKEEPING_EMP" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITILE_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "TYPE_BT" NUMBER(38,0) NULL,
   "GROUP_ID" NUMBER(38,0) NULL,
   "WORKING_DAY" DATE NULL
);

-- Creating table 'HUV_AT_PORTAL'
CREATE TABLE "dbo"."HUV_AT_PORTAL" (
   "ID" NUMBER(38,0) NOT NULL,
   "ID_REGGROUP" NUMBER(38,0) NULL,
   "FROM_DATE" DATE NULL,
   "TO_DATE" DATE NULL,
   "NVALUE" NUMBER(38,0) NULL
);

-- Creating table 'AT_SHIFTCYCLE'
CREATE TABLE "dbo"."AT_SHIFTCYCLE" (
   "ID" NUMBER(38,0) NOT NULL,
   "SHIFT_ID" NUMBER(38,0) NULL,
   "STARTDATE" DATE NULL,
   "ENDDATE" DATE NULL,
   "NOTE" NVARCHAR2(250) NULL,
   "IS_DELETED" NUMBER(38,0) NULL,
   "FML01_ID" NUMBER(38,0) NULL,
   "FML02_ID" NUMBER(38,0) NULL,
   "FML03_ID" NUMBER(38,0) NULL,
   "FML04_ID" NUMBER(38,0) NULL,
   "FML05_ID" NUMBER(38,0) NULL,
   "FML06_ID" NUMBER(38,0) NULL,
   "FML07_ID" NUMBER(38,0) NULL,
   "FML08_ID" NUMBER(38,0) NULL,
   "FML09_ID" NUMBER(38,0) NULL,
   "FML10_ID" NUMBER(38,0) NULL,
   "FML11_ID" NUMBER(38,0) NULL,
   "FML12_ID" NUMBER(38,0) NULL,
   "FML13_ID" NUMBER(38,0) NULL,
   "FML14_ID" NUMBER(38,0) NULL,
   "FML15_ID" NUMBER(38,0) NULL,
   "FML16_ID" NUMBER(38,0) NULL,
   "FML17_ID" NUMBER(38,0) NULL,
   "FML18_ID" NUMBER(38,0) NULL,
   "FML19_ID" NUMBER(38,0) NULL,
   "FML20_ID" NUMBER(38,0) NULL,
   "FML21_ID" NUMBER(38,0) NULL,
   "FML22_ID" NUMBER(38,0) NULL,
   "FML23_ID" NUMBER(38,0) NULL,
   "FML24_ID" NUMBER(38,0) NULL,
   "FML25_ID" NUMBER(38,0) NULL,
   "FML26_ID" NUMBER(38,0) NULL,
   "FML27_ID" NUMBER(38,0) NULL,
   "FML28_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "FML29_ID" NUMBER(38,0) NULL,
   "FML30_ID" NUMBER(38,0) NULL,
   "FML31_ID" NUMBER(38,0) NULL
);

-- Creating table 'AT_SHIFTCYCLE_EMP'
CREATE TABLE "dbo"."AT_SHIFTCYCLE_EMP" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "SHIFT_ID" NUMBER(38,0) NULL,
   "FROMDATE" DATE NULL,
   "TODATE" DATE NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'AT_SHIFTCYCLE_DETAIL'
CREATE TABLE "dbo"."AT_SHIFTCYCLE_DETAIL" (
   "ID" NUMBER(38,0) NOT NULL,
   "SHIFTCYCLE_ID" NUMBER(38,0) NULL,
   "SHIFTDATE" DATE NULL,
   "FML_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'ATV_HOLIDAY_HOSE'
CREATE TABLE "dbo"."ATV_HOLIDAY_HOSE" (
   "ID" NUMBER(38,0) NULL,
   "CODE" NVARCHAR2(50) NOT NULL,
   "FROMDATE" DATE NULL,
   "TODATE" DATE NULL,
   "IS_SA" NUMBER(38,0) NULL,
   "IS_SU" NUMBER(38,0) NULL
);

-- Creating table 'HU_ANNUALLEAVE_PLANS'
CREATE TABLE "dbo"."HU_ANNUALLEAVE_PLANS" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "START_DATE" DATE NULL,
   "END_DATE" DATE NULL,
   "YEAR" NUMBER(5,0) NULL,
   "DAY_NUMBER" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_CONTRACT_TYPE'
CREATE TABLE "dbo"."HU_CONTRACT_TYPE" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NULL,
   "CODE" NVARCHAR2(255) NULL,
   "PERIOD" NUMBER(10,0) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "BHXH" NUMBER(38,0) NULL,
   "BHYT" NUMBER(38,0) NULL,
   "BHTN" NUMBER(38,0) NULL,
   "ORD_NO" NUMBER(38,0) NULL,
   "TYPE_ID" NUMBER(38,0) NULL,
   "TYPE_CODE" VARCHAR2(255) NULL
);

-- Creating table 'PROCESS_APPROVED_STATUS'
CREATE TABLE "dbo"."PROCESS_APPROVED_STATUS" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_APPROVED" NUMBER(38,0) NULL,
   "APP_DATE" DATE NULL,
   "APP_LEVEL" NUMBER(38,0) NULL,
   "APP_NOTES" NVARCHAR2(1000) NULL,
   "CREATED_BY" NVARCHAR2(100) NULL,
   "CREATED_DATE" DATE NULL,
   "APP_STATUS" NUMBER(38,0) NULL,
   "PE_PERIOD_ID" NUMBER(38,0) NULL,
   "ID_REGGROUP" NUMBER(38,0) NULL,
   "TEMPLATE_ID" NUMBER(38,0) NULL,
   "PROCESS_TYPE" NVARCHAR2(100) NULL
);

-- Creating table 'ATV_OFFSETTING'
CREATE TABLE "dbo"."ATV_OFFSETTING" (
   "ID" NUMBER(38,0) NOT NULL,
   "GROUP_ID" NUMBER(38,0) NULL,
   "FROM_DATE" DATE NULL,
   "TO_DATE" DATE NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL
);

-- Creating table 'SE_USER_ORG_ACCESS'
CREATE TABLE "dbo"."SE_USER_ORG_ACCESS" (
   "ID" NUMBER(38,0) NOT NULL,
   "USER_ID" NUMBER(38,0) NOT NULL,
   "ORG_ID" NUMBER(38,0) NOT NULL
);

-- Creating table 'AT_SHIFT'
CREATE TABLE "dbo"."AT_SHIFT" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NOT NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "APPLY_LAW" NUMBER(38,0) NULL,
   "PENALIZEA" NUMBER(38,0) NULL,
   "HOURS_START" DATE NULL,
   "HOURS_STOP" DATE NULL,
   "HOURS_STAR_CHECKIN" DATE NULL,
   "HOURS_STAR_CHECKOUT" DATE NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "IS_PARTTIME" NUMBER(38,0) NULL,
   "MANUAL_ID" NUMBER(38,0) NULL,
   "SATURDAY" NUMBER(38,0) NULL,
   "SUNDAY" NUMBER(38,0) NULL,
   "IS_NOON" NUMBER(5,0) NULL,
   "MINHOURS" NUMBER(38,0) NULL,
   "LATE_MINUTES" NUMBER(38,0) NULL,
   "WORK_HOUR" NUMBER(38,0) NULL,
   "START_MID_HOURS" DATE NULL,
   "END_MID_HOURS" DATE NULL,
   "AT_SIGN_CODE" NVARCHAR2(255) NULL,
   "OT_START" DATE NULL,
   "OT_END" DATE NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "SHIFT_DAY" NUMBER(38,0) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "IS_HOURS_STOP" NUMBER(38,0) NULL,
   "IS_HOURS_CHECKOUT" NUMBER(38,0) NULL,
   "IS_MID_END" NUMBER(38,0) NULL
);

-- Creating table 'AT_LEAVESHEET_DETAIL'
CREATE TABLE "dbo"."AT_LEAVESHEET_DETAIL" (
   "ID" NUMBER(38,0) NOT NULL,
   "LEAVESHEET_ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "LEAVE_DAY" DATE NULL,
   "MANUAL_ID" NUMBER(38,0) NULL,
   "DAY_NUM" NUMBER(38,0) NULL,
   "STATUS_SHIFT" NUMBER(38,0) NULL,
   "SHIFT_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'AT_LEAVESHEET'
CREATE TABLE "dbo"."AT_LEAVESHEET" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "BALANCE_NOW" NUMBER(38,0) NULL,
   "LEAVE_FROM" DATE NULL,
   "LEAVE_TO" DATE NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "MANUAL_ID" NUMBER(38,0) NULL,
   "DAY_NUM" NUMBER(38,0) NULL,
   "EMP_APPROVES_NAME" NVARCHAR2(255) NULL,
   "IS_APP" NUMBER(38,0) NULL,
   "STATUS" NUMBER(38,0) NULL,
   "IMPORT" NUMBER(38,0) NULL,
   "REASON" NCLOB NULL
);

-- Creating table 'AT_TIMESHEET_MACHINET_IMPORT'
CREATE TABLE "dbo"."AT_TIMESHEET_MACHINET_IMPORT" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "NOTE" NVARCHAR2(2000) NULL,
   "TIMEIN_REALITY" DATE NULL,
   "TIMEOUT_REALITY" DATE NULL,
   "WORKING_DAY" DATE NULL
);

-- Creating table 'AT_TYPE_PROCESS'
CREATE TABLE "dbo"."AT_TYPE_PROCESS" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "NAME_EN" NVARCHAR2(255) NULL
);

-- Creating table 'AT_TIME_MANUAL_RATE'
CREATE TABLE "dbo"."AT_TIME_MANUAL_RATE" (
   "ID" NUMBER(38,0) NOT NULL,
   "ACTFLG" NVARCHAR2(255) NULL,
   "VALUE_RATE" NUMBER(38,0) NULL
);

-- Creating table 'AT_ENTITLEMENT'
CREATE TABLE "dbo"."AT_ENTITLEMENT" (
   "YEAR" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "WORKING_TIME_HAVE" NUMBER(38,0) NULL,
   "BALANCE_WORKING_TIME" NUMBER(38,0) NULL,
   "CAL_DATE" DATE NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ID" NUMBER(38,0) NOT NULL,
   "PREV_HAVE" NUMBER(38,0) NULL,
   "PREV_USED" NUMBER(38,0) NULL,
   "EXPIREDATE" DATE NULL,
   "CUR_HAVE" NUMBER(38,0) NULL,
   "CUR_USED" NUMBER(38,0) NULL,
   "FUND" NUMBER(38,0) NULL,
   "SPECIAL" NUMBER(38,0) NULL,
   "CUR_HAVE1" NUMBER(38,0) NULL,
   "CUR_HAVE2" NUMBER(38,0) NULL,
   "CUR_HAVE3" NUMBER(38,0) NULL,
   "CUR_HAVE4" NUMBER(38,0) NULL,
   "CUR_HAVE5" NUMBER(38,0) NULL,
   "CUR_HAVE6" NUMBER(38,0) NULL,
   "CUR_HAVE7" NUMBER(38,0) NULL,
   "CUR_HAVE8" NUMBER(38,0) NULL,
   "CUR_HAVE9" NUMBER(38,0) NULL,
   "CUR_HAVE10" NUMBER(38,0) NULL,
   "CUR_HAVE11" NUMBER(38,0) NULL,
   "CUR_HAVE12" NUMBER(38,0) NULL,
   "CUR_USED1" NUMBER(38,0) NULL,
   "CUR_USED2" NUMBER(38,0) NULL,
   "CUR_USED3" NUMBER(38,0) NULL,
   "CUR_USED4" NUMBER(38,0) NULL,
   "CUR_USED5" NUMBER(38,0) NULL,
   "CUR_USED6" NUMBER(38,0) NULL,
   "CUR_USED7" NUMBER(38,0) NULL,
   "CUR_USED8" NUMBER(38,0) NULL,
   "CUR_USED9" NUMBER(38,0) NULL,
   "CUR_USED10" NUMBER(38,0) NULL,
   "CUR_USED11" NUMBER(38,0) NULL,
   "CUR_USED12" NUMBER(38,0) NULL,
   "AL_TO_CASH" NUMBER(38,0) NULL,
   "REASON" NVARCHAR2(1023) NULL,
   "EXPIREDATE_NB" DATE NULL,
   "FIXADD" NUMBER(38,0) NULL,
   "PAY_PREV_ENT" NUMBER(38,0) NULL,
   "AL_T1" NUMBER(38,0) NULL,
   "AL_T2" NUMBER(38,0) NULL,
   "AL_T3" NUMBER(38,0) NULL,
   "AL_T4" NUMBER(38,0) NULL,
   "AL_T5" NUMBER(38,0) NULL,
   "AL_T6" NUMBER(38,0) NULL,
   "AL_T7" NUMBER(38,0) NULL,
   "AL_T8" NUMBER(38,0) NULL,
   "AL_T9" NUMBER(38,0) NULL,
   "AL_T10" NUMBER(38,0) NULL,
   "AL_T11" NUMBER(38,0) NULL,
   "AL_T12" NUMBER(38,0) NULL,
   "AL_ADD_T1" NUMBER(38,0) NULL,
   "AL_ADD_T2" NUMBER(38,0) NULL,
   "AL_ADD_T3" NUMBER(38,0) NULL,
   "AL_ADD_T4" NUMBER(38,0) NULL,
   "AL_ADD_T5" NUMBER(38,0) NULL,
   "AL_ADD_T6" NUMBER(38,0) NULL,
   "AL_ADD_T7" NUMBER(38,0) NULL,
   "AL_ADD_T8" NUMBER(38,0) NULL,
   "AL_ADD_T9" NUMBER(38,0) NULL,
   "AL_ADD_T10" NUMBER(38,0) NULL,
   "AL_ADD_T11" NUMBER(38,0) NULL,
   "AL_ADD_T12" NUMBER(38,0) NULL,
   "PREV_USED1" NUMBER(38,0) NULL,
   "PREV_USED2" NUMBER(38,0) NULL,
   "PREV_USED3" NUMBER(38,0) NULL,
   "PREV_USED4" NUMBER(38,0) NULL,
   "PREV_USED5" NUMBER(38,0) NULL,
   "PREV_USED6" NUMBER(38,0) NULL,
   "PREV_USED7" NUMBER(38,0) NULL,
   "PREV_USED8" NUMBER(38,0) NULL,
   "PREV_USED9" NUMBER(38,0) NULL,
   "PREV_USED10" NUMBER(38,0) NULL,
   "PREV_USED11" NUMBER(38,0) NULL,
   "PREV_USED12" NUMBER(38,0) NULL,
   "TOTAL_PAY_PREV_ENT" NUMBER(38,0) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "TOTAL_HAVE" NUMBER(38,0) NULL,
   "SUB_PREV_ENT" NUMBER(38,0) NULL,
   "BALANCE_WORKING_TIME_3B" NUMBER(38,0) NULL,
   "MONTH" NUMBER(38,0) NULL,
   "SENIORITYHAVE" NUMBER(38,0) NULL,
   "TOTAL_HAVE1" NUMBER(38,0) NULL,
   "PREVTOTAL_HAVE" NUMBER(38,0) NULL,
   "TIME_OUTSIDE_COMPANY" NUMBER(38,0) NULL,
   "TIME_SENIORITY" NUMBER(38,0) NULL,
   "MONTH_SENIORITY_CHANGE" NUMBER(38,0) NULL,
   "TIME_SENIORITY_AFTER_CHANGE" NUMBER(38,0) NULL,
   "SENIORITY" NUMBER(38,0) NULL,
   "SENIORITY_EDIT" NVARCHAR2(100) NULL,
   "TOTAL_HAVE2" NUMBER(38,0) NULL,
   "QP_YEAR" NUMBER(38,0) NULL,
   "TN_YEAR" NUMBER(38,0) NULL,
   "TN_DAY" NUMBER(38,0) NULL,
   "QP_MONTH" NUMBER(38,0) NULL,
   "TO_LEAVE_YEAR" NUMBER(38,0) NULL,
   "ADJUST_MONTH_TN" NUMBER(38,0) NULL
);

-- Creating table 'SE_USER_REPORT'
CREATE TABLE "dbo"."SE_USER_REPORT" (
   "SE_REPORT_ID" NUMBER(38,0) NOT NULL,
   "SE_USER_ID" NUMBER(38,0) NOT NULL
);


-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on "ID"in table 'OT_OTHER_LIST'
ALTER TABLE "dbo"."OT_OTHER_LIST"
ADD CONSTRAINT "PK_OT_OTHER_LIST"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST_GROUP'
ALTER TABLE "dbo"."OT_OTHER_LIST_GROUP"
ADD CONSTRAINT "PK_OT_OTHER_LIST_GROUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST_TYPE'
ALTER TABLE "dbo"."OT_OTHER_LIST_TYPE"
ADD CONSTRAINT "PK_OT_OTHER_LIST_TYPE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ORG_ID", "USERNAME"in table 'SE_CHOSEN_ORG'
ALTER TABLE "dbo"."SE_CHOSEN_ORG"
ADD CONSTRAINT "PK_SE_CHOSEN_ORG"
   PRIMARY KEY ("ORG_ID", "USERNAME" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_GSIGN'
ALTER TABLE "dbo"."AT_GSIGN"
ADD CONSTRAINT "PK_AT_GSIGN"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_SWIPE_DATA'
ALTER TABLE "dbo"."AT_SWIPE_DATA"
ADD CONSTRAINT "PK_AT_SWIPE_DATA"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_ORG_PERIOD'
ALTER TABLE "dbo"."AT_ORG_PERIOD"
ADD CONSTRAINT "PK_AT_ORG_PERIOD"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "PK_HU_EMPLOYEE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_CONTRACT'
ALTER TABLE "dbo"."HU_CONTRACT"
ADD CONSTRAINT "PK_HU_CONTRACT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_EDUCATION'
ALTER TABLE "dbo"."HU_EMPLOYEE_EDUCATION"
ADD CONSTRAINT "PK_HU_EMPLOYEE_EDUCATION"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE_FILES'
ALTER TABLE "dbo"."HU_EMPLOYEE_FILES"
ADD CONSTRAINT "PK_HU_EMPLOYEE_FILES"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_HEALTH'
ALTER TABLE "dbo"."HU_EMPLOYEE_HEALTH"
ADD CONSTRAINT "PK_HU_EMPLOYEE_HEALTH"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_OTHER_INFO'
ALTER TABLE "dbo"."HU_EMPLOYEE_OTHER_INFO"
ADD CONSTRAINT "PK_HU_EMPLOYEE_OTHER_INFO"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_SALARY'
ALTER TABLE "dbo"."HU_EMPLOYEE_SALARY"
ADD CONSTRAINT "PK_HU_EMPLOYEE_SALARY"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE_TRAIN'
ALTER TABLE "dbo"."HU_EMPLOYEE_TRAIN"
ADD CONSTRAINT "PK_HU_EMPLOYEE_TRAIN"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_TIMESHEET_REGISTER'
ALTER TABLE "dbo"."AT_TIMESHEET_REGISTER"
ADD CONSTRAINT "PK_AT_TIMESHEET_REGISTER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_APP_PROCESS'
ALTER TABLE "dbo"."SE_APP_PROCESS"
ADD CONSTRAINT "PK_SE_APP_PROCESS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_APP_SETUP'
ALTER TABLE "dbo"."SE_APP_SETUP"
ADD CONSTRAINT "PK_SE_APP_SETUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_APP_SETUPEXT'
ALTER TABLE "dbo"."SE_APP_SETUPEXT"
ADD CONSTRAINT "PK_SE_APP_SETUPEXT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_APP_TEMPLATE_DTL'
ALTER TABLE "dbo"."SE_APP_TEMPLATE_DTL"
ADD CONSTRAINT "PK_SE_APP_TEMPLATE_DTL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_APP_TEMPLATE'
ALTER TABLE "dbo"."SE_APP_TEMPLATE"
ADD CONSTRAINT "PK_SE_APP_TEMPLATE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ORGANIZATION'
ALTER TABLE "dbo"."HU_ORGANIZATION"
ADD CONSTRAINT "PK_HU_ORGANIZATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_WORKING'
ALTER TABLE "dbo"."HU_WORKING"
ADD CONSTRAINT "PK_HU_WORKING"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_PORTAL_APP'
ALTER TABLE "dbo"."AT_PORTAL_APP"
ADD CONSTRAINT "PK_AT_PORTAL_APP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_RGT'
ALTER TABLE "dbo"."AT_RGT"
ADD CONSTRAINT "PK_AT_RGT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ORG_TITLE'
ALTER TABLE "dbo"."HU_ORG_TITLE"
ADD CONSTRAINT "PK_HU_ORG_TITLE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_TITLE'
ALTER TABLE "dbo"."HU_TITLE"
ADD CONSTRAINT "PK_HU_TITLE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_WORKSIGN'
ALTER TABLE "dbo"."AT_WORKSIGN"
ADD CONSTRAINT "PK_AT_WORKSIGN"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_PORTAL_REG'
ALTER TABLE "dbo"."AT_PORTAL_REG"
ADD CONSTRAINT "PK_AT_PORTAL_REG"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_STAFF_RANK'
ALTER TABLE "dbo"."HU_STAFF_RANK"
ADD CONSTRAINT "PK_HU_STAFF_RANK"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_TIME_TIMESHEET_RICE'
ALTER TABLE "dbo"."AT_TIME_TIMESHEET_RICE"
ADD CONSTRAINT "PK_AT_TIME_TIMESHEET_RICE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_TIME_TIMESHEET_OT'
ALTER TABLE "dbo"."AT_TIME_TIMESHEET_OT"
ADD CONSTRAINT "PK_AT_TIME_TIMESHEET_OT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_DMVS'
ALTER TABLE "dbo"."AT_DMVS"
ADD CONSTRAINT "PK_AT_DMVS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_HOLIDAY'
ALTER TABLE "dbo"."AT_HOLIDAY"
ADD CONSTRAINT "PK_AT_HOLIDAY"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_HOLIDAY_GENERAL'
ALTER TABLE "dbo"."AT_HOLIDAY_GENERAL"
ADD CONSTRAINT "PK_AT_HOLIDAY_GENERAL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_HOLIDAY_OBJECT'
ALTER TABLE "dbo"."AT_HOLIDAY_OBJECT"
ADD CONSTRAINT "PK_AT_HOLIDAY_OBJECT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_LATE_COMBACKOUT'
ALTER TABLE "dbo"."AT_LATE_COMBACKOUT"
ADD CONSTRAINT "PK_AT_LATE_COMBACKOUT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_PERIOD'
ALTER TABLE "dbo"."AT_PERIOD"
ADD CONSTRAINT "PK_AT_PERIOD"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_SETUP_SPECIAL'
ALTER TABLE "dbo"."AT_SETUP_SPECIAL"
ADD CONSTRAINT "PK_AT_SETUP_SPECIAL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_SIGNDEFAULT'
ALTER TABLE "dbo"."AT_SIGNDEFAULT"
ADD CONSTRAINT "PK_AT_SIGNDEFAULT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_TIME_MANUAL'
ALTER TABLE "dbo"."AT_TIME_MANUAL"
ADD CONSTRAINT "PK_AT_TIME_MANUAL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_TIME_RICE'
ALTER TABLE "dbo"."AT_TIME_RICE"
ADD CONSTRAINT "PK_AT_TIME_RICE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_TIME_TIMESHEET_DAILY'
ALTER TABLE "dbo"."AT_TIME_TIMESHEET_DAILY"
ADD CONSTRAINT "PK_AT_TIME_TIMESHEET_DAILY"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_TIME_TIMESHEET_MACHINET'
ALTER TABLE "dbo"."AT_TIME_TIMESHEET_MACHINET"
ADD CONSTRAINT "PK_AT_TIME_TIMESHEET_MACHINET"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_DATA_INOUT'
ALTER TABLE "dbo"."AT_DATA_INOUT"
ADD CONSTRAINT "PK_AT_DATA_INOUT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_FML'
ALTER TABLE "dbo"."AT_FML"
ADD CONSTRAINT "PK_AT_FML"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_TERMINALS'
ALTER TABLE "dbo"."AT_TERMINALS"
ADD CONSTRAINT "PK_AT_TERMINALS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_ACTION_ORG_LOG'
ALTER TABLE "dbo"."AT_ACTION_ORG_LOG"
ADD CONSTRAINT "PK_AT_ACTION_ORG_LOG"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_CV'
ALTER TABLE "dbo"."HU_EMPLOYEE_CV"
ADD CONSTRAINT "PK_HU_EMPLOYEE_CV"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_MAIL'
ALTER TABLE "dbo"."SE_MAIL"
ADD CONSTRAINT "PK_SE_MAIL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_SETUP_TIME_EMP'
ALTER TABLE "dbo"."AT_SETUP_TIME_EMP"
ADD CONSTRAINT "PK_AT_SETUP_TIME_EMP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID", "USING_USER", "WORKINGDAY"in table 'SE_EMPLOYEE_CHOSEN'
ALTER TABLE "dbo"."SE_EMPLOYEE_CHOSEN"
ADD CONSTRAINT "PK_SE_EMPLOYEE_CHOSEN"
   PRIMARY KEY ("EMPLOYEE_ID", "USING_USER", "WORKINGDAY" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_LIST_PARAM_SYSTEM'
ALTER TABLE "dbo"."AT_LIST_PARAM_SYSTEM"
ADD CONSTRAINT "PK_AT_LIST_PARAM_SYSTEM"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_REGISTER_OT'
ALTER TABLE "dbo"."AT_REGISTER_OT"
ADD CONSTRAINT "PK_AT_REGISTER_OT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_USER'
ALTER TABLE "dbo"."SE_USER"
ADD CONSTRAINT "PK_SE_USER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_REPORT'
ALTER TABLE "dbo"."SE_REPORT"
ADD CONSTRAINT "PK_SE_REPORT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_COMPENSATORY'
ALTER TABLE "dbo"."AT_COMPENSATORY"
ADD CONSTRAINT "PK_AT_COMPENSATORY"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_ACTION_LOG'
ALTER TABLE "dbo"."AT_ACTION_LOG"
ADD CONSTRAINT "PK_AT_ACTION_LOG"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_DECLARE_ENTITLEMENT'
ALTER TABLE "dbo"."AT_DECLARE_ENTITLEMENT"
ADD CONSTRAINT "PK_AT_DECLARE_ENTITLEMENT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_PROJECT'
ALTER TABLE "dbo"."AT_PROJECT"
ADD CONSTRAINT "PK_AT_PROJECT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_PROJECT_TITLE'
ALTER TABLE "dbo"."AT_PROJECT_TITLE"
ADD CONSTRAINT "PK_AT_PROJECT_TITLE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_PROJECT_EMP'
ALTER TABLE "dbo"."AT_PROJECT_EMP"
ADD CONSTRAINT "PK_AT_PROJECT_EMP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_PROJECT_WORK'
ALTER TABLE "dbo"."AT_PROJECT_WORK"
ADD CONSTRAINT "PK_AT_PROJECT_WORK"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_PROJECT_ASSIGN'
ALTER TABLE "dbo"."AT_PROJECT_ASSIGN"
ADD CONSTRAINT "PK_AT_PROJECT_ASSIGN"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_TIMESHEET_OT_DTL'
ALTER TABLE "dbo"."AT_TIMESHEET_OT_DTL"
ADD CONSTRAINT "PK_AT_TIMESHEET_OT_DTL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_TIME_TIMESHEET_MONTHLY'
ALTER TABLE "dbo"."AT_TIME_TIMESHEET_MONTHLY"
ADD CONSTRAINT "PK_AT_TIME_TIMESHEET_MONTHLY"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_PORTAL_REG_LIST'
ALTER TABLE "dbo"."AT_PORTAL_REG_LIST"
ADD CONSTRAINT "PK_AT_PORTAL_REG_LIST"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_TIMESHEET'
ALTER TABLE "dbo"."AT_TIMESHEET"
ADD CONSTRAINT "PK_AT_TIMESHEET"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_SHIFTCYCLE_EMP_DETAIL'
ALTER TABLE "dbo"."AT_SHIFTCYCLE_EMP_DETAIL"
ADD CONSTRAINT "PK_AT_SHIFTCYCLE_EMP_DETAIL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_SETUP_ATT_EMP'
ALTER TABLE "dbo"."AT_SETUP_ATT_EMP"
ADD CONSTRAINT "PK_AT_SETUP_ATT_EMP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_OT_REGISTRATION'
ALTER TABLE "dbo"."AT_OT_REGISTRATION"
ADD CONSTRAINT "PK_AT_OT_REGISTRATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_OFFSETTING_TIMEKEEPING'
ALTER TABLE "dbo"."AT_OFFSETTING_TIMEKEEPING"
ADD CONSTRAINT "PK_AT_OFFSETTING_TIMEKEEPING"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_OFFSETTING_TIMEKEEPING_EMP'
ALTER TABLE "dbo"."AT_OFFSETTING_TIMEKEEPING_EMP"
ADD CONSTRAINT "PK_AT_OFFSETTING_TIMEKEEPING_EMP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HUV_AT_PORTAL'
ALTER TABLE "dbo"."HUV_AT_PORTAL"
ADD CONSTRAINT "PK_HUV_AT_PORTAL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_SHIFTCYCLE'
ALTER TABLE "dbo"."AT_SHIFTCYCLE"
ADD CONSTRAINT "PK_AT_SHIFTCYCLE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_SHIFTCYCLE_EMP'
ALTER TABLE "dbo"."AT_SHIFTCYCLE_EMP"
ADD CONSTRAINT "PK_AT_SHIFTCYCLE_EMP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_SHIFTCYCLE_DETAIL'
ALTER TABLE "dbo"."AT_SHIFTCYCLE_DETAIL"
ADD CONSTRAINT "PK_AT_SHIFTCYCLE_DETAIL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "CODE"in table 'ATV_HOLIDAY_HOSE'
ALTER TABLE "dbo"."ATV_HOLIDAY_HOSE"
ADD CONSTRAINT "PK_ATV_HOLIDAY_HOSE"
   PRIMARY KEY ("CODE" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ANNUALLEAVE_PLANS'
ALTER TABLE "dbo"."HU_ANNUALLEAVE_PLANS"
ADD CONSTRAINT "PK_HU_ANNUALLEAVE_PLANS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_CONTRACT_TYPE'
ALTER TABLE "dbo"."HU_CONTRACT_TYPE"
ADD CONSTRAINT "PK_HU_CONTRACT_TYPE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PROCESS_APPROVED_STATUS'
ALTER TABLE "dbo"."PROCESS_APPROVED_STATUS"
ADD CONSTRAINT "PK_PROCESS_APPROVED_STATUS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'ATV_OFFSETTING'
ALTER TABLE "dbo"."ATV_OFFSETTING"
ADD CONSTRAINT "PK_ATV_OFFSETTING"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_USER_ORG_ACCESS'
ALTER TABLE "dbo"."SE_USER_ORG_ACCESS"
ADD CONSTRAINT "PK_SE_USER_ORG_ACCESS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_SHIFT'
ALTER TABLE "dbo"."AT_SHIFT"
ADD CONSTRAINT "PK_AT_SHIFT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_LEAVESHEET_DETAIL'
ALTER TABLE "dbo"."AT_LEAVESHEET_DETAIL"
ADD CONSTRAINT "PK_AT_LEAVESHEET_DETAIL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_LEAVESHEET'
ALTER TABLE "dbo"."AT_LEAVESHEET"
ADD CONSTRAINT "PK_AT_LEAVESHEET"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_TIMESHEET_MACHINET_IMPORT'
ALTER TABLE "dbo"."AT_TIMESHEET_MACHINET_IMPORT"
ADD CONSTRAINT "PK_AT_TIMESHEET_MACHINET_IMPORT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_TYPE_PROCESS'
ALTER TABLE "dbo"."AT_TYPE_PROCESS"
ADD CONSTRAINT "PK_AT_TYPE_PROCESS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_TIME_MANUAL_RATE'
ALTER TABLE "dbo"."AT_TIME_MANUAL_RATE"
ADD CONSTRAINT "PK_AT_TIME_MANUAL_RATE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_ENTITLEMENT'
ALTER TABLE "dbo"."AT_ENTITLEMENT"
ADD CONSTRAINT "PK_AT_ENTITLEMENT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "SE_REPORT_ID", "SE_USER_ID"in table 'SE_USER_REPORT'
ALTER TABLE "dbo"."SE_USER_REPORT"
ADD CONSTRAINT "PK_SE_USER_REPORT"
   PRIMARY KEY ("SE_REPORT_ID", "SE_USER_ID" )
   ENABLE
   VALIDATE;


-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on "TYPE_ID" in table 'OT_OTHER_LIST'
ALTER TABLE "dbo"."OT_OTHER_LIST"
ADD CONSTRAINT "FK_OOLT_OOL"
   FOREIGN KEY ("TYPE_ID")
   REFERENCES "dbo"."OT_OTHER_LIST_TYPE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_OOLT_OOL'
CREATE INDEX "IX_FK_OOLT_OOL"
ON "dbo"."OT_OTHER_LIST"
   ("TYPE_ID");

-- Creating foreign key on "GROUP_ID" in table 'OT_OTHER_LIST_TYPE'
ALTER TABLE "dbo"."OT_OTHER_LIST_TYPE"
ADD CONSTRAINT "FK_OOLG_OOLT"
   FOREIGN KEY ("GROUP_ID")
   REFERENCES "dbo"."OT_OTHER_LIST_GROUP"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_OOLG_OOLT'
CREATE INDEX "IX_FK_OOLG_OOLT"
ON "dbo"."OT_OTHER_LIST_TYPE"
   ("GROUP_ID");

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_HEALTH'
ALTER TABLE "dbo"."HU_EMPLOYEE_HEALTH"
ADD CONSTRAINT "FK_FE_HEH"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_EDUCATION'
ALTER TABLE "dbo"."HU_EMPLOYEE_EDUCATION"
ADD CONSTRAINT "FK_HE_HEE"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_FILES'
ALTER TABLE "dbo"."HU_EMPLOYEE_FILES"
ADD CONSTRAINT "FK_HE_HEF"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HE_HEF'
CREATE INDEX "IX_FK_HE_HEF"
ON "dbo"."HU_EMPLOYEE_FILES"
   ("EMPLOYEE_ID");

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_OTHER_INFO'
ALTER TABLE "dbo"."HU_EMPLOYEE_OTHER_INFO"
ADD CONSTRAINT "FK_HE_HEO"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_SALARY'
ALTER TABLE "dbo"."HU_EMPLOYEE_SALARY"
ADD CONSTRAINT "FK_HE_HES"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "DIRECT_MANAGER" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HUEMD_HUEM"
   FOREIGN KEY ("DIRECT_MANAGER")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUEMD_HUEM'
CREATE INDEX "IX_FK_HUEMD_HUEM"
ON "dbo"."HU_EMPLOYEE"
   ("DIRECT_MANAGER");

-- Creating foreign key on "PARENT_ID" in table 'HU_ORGANIZATION'
ALTER TABLE "dbo"."HU_ORGANIZATION"
ADD CONSTRAINT "FK_HU_ORG_HU_ORG"
   FOREIGN KEY ("PARENT_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_ORG_HU_ORG'
CREATE INDEX "IX_FK_HU_ORG_HU_ORG"
ON "dbo"."HU_ORGANIZATION"
   ("PARENT_ID");

-- Creating foreign key on "TITLE_ID" in table 'HU_ORG_TITLE'
ALTER TABLE "dbo"."HU_ORG_TITLE"
ADD CONSTRAINT "FK_HUTL_HUOT"
   FOREIGN KEY ("TITLE_ID")
   REFERENCES "dbo"."HU_TITLE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUTL_HUOT'
CREATE INDEX "IX_FK_HUTL_HUOT"
ON "dbo"."HU_ORG_TITLE"
   ("TITLE_ID");

-- Creating foreign key on "SE_REPORT_ID" in table 'SE_USER_REPORT'
ALTER TABLE "dbo"."SE_USER_REPORT"
ADD CONSTRAINT "FK_SE_USER_REPORT_SE_REPORT"
   FOREIGN KEY ("SE_REPORT_ID")
   REFERENCES "dbo"."SE_REPORT"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SE_USER_REPORT_SE_REPORT'
CREATE INDEX "IX_FK_SE_USER_REPORT_SE_REPORT"
ON "dbo"."SE_USER_REPORT"
   ("SE_REPORT_ID");

-- Creating foreign key on "SE_USER_ID" in table 'SE_USER_REPORT'
ALTER TABLE "dbo"."SE_USER_REPORT"
ADD CONSTRAINT "FK_SE_USER_REPORT_SE_USER"
   FOREIGN KEY ("SE_USER_ID")
   REFERENCES "dbo"."SE_USER"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SE_USER_REPORT_SE_USER'
CREATE INDEX "IX_FK_SE_USER_REPORT_SE_USER"
ON "dbo"."SE_USER_REPORT"
   ("SE_USER_ID");

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------
