Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 06/11/2017 4:57:27 PM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INFOR_INS 
{
12,
OUT_DATE,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 06/11/2017 4:58:03 PM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INFOR_INS 
{
12,
OUT_DATE,
}

________________________________________________________________________________________________________

Function: Histaff.DataAccessLayer.DataAccess.QueryData.DataAccess => ExecuteStoreScalar
Datetime: 06/11/2017 5:02:09 PM
Error message: ORA-03135: connection lost contact
Process ID: 2256
Session ID: 30 Serial number: 58130
Stack trace:    at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, CommandType CommandType, String CommandText, OracleParameter[] CommandParameters) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Histaff.DataAccessLayer\OracleHelper.vb:line 647
   at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, String StoredProceduredName, Object[] ParameterValues) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Histaff.DataAccessLayer\OracleHelper.vb:line 667
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteStoreScalar(String storeName, List`1 parameters) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Histaff.DataAccessLayer\DataAccess.vb:line 144
Other Text: PKG_PROFILE.GET_INFOR_INS 
{
12,
OUT_DATE,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 06/11/2017 5:02:09 PM
Error message: ORA-03135: connection lost contact
Process ID: 2256
Session ID: 30 Serial number: 58130
Stack trace:    at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, CommandType CommandType, String CommandText, OracleParameter[] CommandParameters) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Histaff.DataAccessLayer\OracleHelper.vb:line 647
   at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, String StoredProceduredName, Object[] ParameterValues) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Histaff.DataAccessLayer\OracleHelper.vb:line 667
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteStoreScalar(String storeName, List`1 parameters) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Histaff.DataAccessLayer\DataAccess.vb:line 165
   at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteStoreScalar(String storeName, List`1 parameters) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 89
Other Text: PKG_PROFILE.GET_INFOR_INS 
{
12,
OUT_DATE,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 06/11/2017 5:05:01 PM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INFOR_INS 
{
6,
OUT_DATE,
}

________________________________________________________________________________________________________

