Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/11/2017 11:27:58 AM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INFOR_INS 
{
4,
OUT_DATE,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/11/2017 11:37:56 AM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INS_THAI_SAN 
{
4,
07/11/2017 12:00:00 AM,
OUT_NUMBER,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/11/2017 2:07:51 PM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INS_THAI_SAN 
{
4,
08/11/2017 12:00:00 AM,
OUT_NUMBER,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/11/2017 2:08:56 PM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INS_THAI_SAN 
{
4,
08/11/2017 12:00:00 AM,
OUT_NUMBER,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/11/2017 2:29:15 PM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INS_THAI_SAN 
{
4,
08/11/2017 12:00:00 AM,
OUT_NUMBER,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/11/2017 2:51:41 PM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INS_THAI_SAN 
{
4,
08/11/2017 12:00:00 AM,
OUT_NUMBER,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/11/2017 2:58:36 PM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INS_THAI_SAN 
{
4,
30/11/2017 12:00:00 AM,
OUT_NUMBER,
}

________________________________________________________________________________________________________

