Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 09/11/2017 9:22:17 AM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INS_THAI_SAN 
{
4,
30/11/2017 12:00:00 AM,
OUT_NUMBER,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 09/11/2017 11:14:43 AM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INS_THAI_SAN 
{
4,
30/11/2017 12:00:00 AM,
OUT_NUMBER,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 09/11/2017 11:41:31 AM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INS_THAI_SAN 
{
4,
30/11/2017 12:00:00 AM,
OUT_NUMBER,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 09/11/2017 11:42:10 AM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INS_THAI_SAN 
{
4,
30/11/2017 12:00:00 AM,
OUT_NUMBER,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 09/11/2017 11:42:19 AM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INS_THAI_SAN 
{
4,
30/11/2017 12:00:00 AM,
OUT_NUMBER,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 09/11/2017 11:42:24 AM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INS_THAI_SAN 
{
4,
23/11/2017 12:00:00 AM,
OUT_NUMBER,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 09/11/2017 3:04:47 PM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INS_THAI_SAN 
{
4,
30/11/2017 12:00:00 AM,
OUT_NUMBER,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 09/11/2017 3:11:43 PM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INS_THAI_SAN 
{
4,
30/11/2017 12:00:00 AM,
OUT_NUMBER,
}

________________________________________________________________________________________________________

