Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 08/11/2017 9:05:11 AM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INS_THAI_SAN 
{
4,
22/11/2017 12:00:00 AM,
OUT_NUMBER,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 08/11/2017 11:43:43 AM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INS_THAI_SAN 
{
4,
26/11/2017 12:00:00 AM,
OUT_NUMBER,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 08/11/2017 1:48:11 PM
Error message: No data found
Stack trace: 
Other Text: PKG_PROFILE.GET_INS_THAI_SAN 
{
4,
30/11/2017 12:00:00 AM,
OUT_NUMBER,
}

________________________________________________________________________________________________________

