-- --------------------------------------------------
-- Entity Designer DDL Script for Oracle database
-- --------------------------------------------------
-- Date Created: 3/5/2020 10:28:20 AM
-- Generated from EDMX file: D:\HiStaffWebApp\acv_19\TrainingDAL\TrainingContext.edmx
-- --------------------------------------------------

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

-- ALTER TABLE "TrainingModelStoreContainer"."HU_DISTRICT" DROP CONSTRAINT "FK_HU_PRO_HU_DIS" CASCADE;

-- ALTER TABLE "TrainingModelStoreContainer"."HU_PROVINCE" DROP CONSTRAINT "FK_HU_NAT_HU_PRO" CASCADE;

-- ALTER TABLE "TrainingModelStoreContainer"."HU_EMPLOYEE_CV" DROP CONSTRAINT "FK_HE_HEC" CASCADE;

-- ALTER TABLE "TrainingModelStoreContainer"."HU_EMPLOYEE" DROP CONSTRAINT "FK_HE_HT" CASCADE;

-- ALTER TABLE "TrainingModelStoreContainer"."HU_EMPLOYEE" DROP CONSTRAINT "FK_HU_ORG_HU_EMP" CASCADE;

-- ALTER TABLE "TrainingModelStoreContainer"."HU_EMPLOYEE" DROP CONSTRAINT "FK_HUEMD_HUEM" CASCADE;

-- ALTER TABLE "TrainingModelStoreContainer"."HU_ORG_TITLE" DROP CONSTRAINT "FK_HUOG_HUOT" CASCADE;

-- ALTER TABLE "TrainingModelStoreContainer"."HU_ORG_TITLE" DROP CONSTRAINT "FK_HUTL_HUOT" CASCADE;

-- ALTER TABLE "TrainingModelStoreContainer"."HU_ORGANIZATION" DROP CONSTRAINT "FK_HU_ORG_HU_ORG" CASCADE;

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

-- DROP TABLE "TrainingModelStoreContainer"."TR_COST_CENTER";

-- DROP TABLE "TrainingModelStoreContainer"."SE_CHOSEN_ORG";

-- DROP TABLE "TrainingModelStoreContainer"."TR_CENTER";

-- DROP TABLE "TrainingModelStoreContainer"."TR_CERTIFICATE";

-- DROP TABLE "TrainingModelStoreContainer"."TR_CLASS";

-- DROP TABLE "TrainingModelStoreContainer"."TR_COURSE";

-- DROP TABLE "TrainingModelStoreContainer"."TR_LECTURE";

-- DROP TABLE "TrainingModelStoreContainer"."TR_PLAN_JOBGRADE";

-- DROP TABLE "TrainingModelStoreContainer"."TR_PLAN_TITLE";

-- DROP TABLE "TrainingModelStoreContainer"."TR_PLAN_UNIT";

-- DROP TABLE "TrainingModelStoreContainer"."TR_PREPARE";

-- DROP TABLE "TrainingModelStoreContainer"."TR_PROGRAM";

-- DROP TABLE "TrainingModelStoreContainer"."TR_PROGRAM_CENTER";

-- DROP TABLE "TrainingModelStoreContainer"."TR_PROGRAM_JOBGRADE";

-- DROP TABLE "TrainingModelStoreContainer"."TR_PROGRAM_LECTURE";

-- DROP TABLE "TrainingModelStoreContainer"."TR_PROGRAM_TITLE";

-- DROP TABLE "TrainingModelStoreContainer"."TR_PROGRAM_UNIT";

-- DROP TABLE "TrainingModelStoreContainer"."TR_REQUEST";

-- DROP TABLE "TrainingModelStoreContainer"."TR_REQUEST_EMPLOYEE";

-- DROP TABLE "TrainingModelStoreContainer"."TR_CLASS_STUDENT";

-- DROP TABLE "TrainingModelStoreContainer"."OT_OTHER_LIST";

-- DROP TABLE "TrainingModelStoreContainer"."OT_OTHER_LIST_GROUP";

-- DROP TABLE "TrainingModelStoreContainer"."OT_OTHER_LIST_TYPE";

-- DROP TABLE "TrainingModelStoreContainer"."TR_PLAN_CENTER";

-- DROP TABLE "TrainingModelStoreContainer"."TR_PLAN";

-- DROP TABLE "TrainingModelStoreContainer"."HU_DISTRICT";

-- DROP TABLE "TrainingModelStoreContainer"."HU_NATION";

-- DROP TABLE "TrainingModelStoreContainer"."HU_PROVINCE";

-- DROP TABLE "TrainingModelStoreContainer"."HU_CONTRACT";

-- DROP TABLE "TrainingModelStoreContainer"."HU_CONTRACT_TYPE";

-- DROP TABLE "TrainingModelStoreContainer"."TR_CLASS_SCHEDULE";

-- DROP TABLE "TrainingModelStoreContainer"."TR_PROGRAM_COMMIT";

-- DROP TABLE "TrainingModelStoreContainer"."TR_PROGRAM_RESULT";

-- DROP TABLE "TrainingModelStoreContainer"."TR_PROGRAM_COST";

-- DROP TABLE "TrainingModelStoreContainer"."TR_ASSESSMENT_FORM";

-- DROP TABLE "TrainingModelStoreContainer"."TR_ASSESSMENT_RATE";

-- DROP TABLE "TrainingModelStoreContainer"."TR_CHOOSE_FORM";

-- DROP TABLE "TrainingModelStoreContainer"."TR_COMMIT_AFTER_TRAIN";

-- DROP TABLE "TrainingModelStoreContainer"."TR_REIMBURSEMENT";

-- DROP TABLE "TrainingModelStoreContainer"."TR_SETTING_ASS_FORM";

-- DROP TABLE "TrainingModelStoreContainer"."TR_SETTING_CRI_GRP";

-- DROP TABLE "TrainingModelStoreContainer"."TR_CRITERIA";

-- DROP TABLE "TrainingModelStoreContainer"."TR_CRITERIA_GROUP";

-- DROP TABLE "TrainingModelStoreContainer"."TR_ASSESSMENT_RESULT";

-- DROP TABLE "TrainingModelStoreContainer"."TR_ASSESSMENT_RESULT_DTL";

-- DROP TABLE "TrainingModelStoreContainer"."HU_EMPLOYEE";

-- DROP TABLE "TrainingModelStoreContainer"."HU_EMPLOYEE_CV";

-- DROP TABLE "TrainingModelStoreContainer"."HU_ORG_TITLE";

-- DROP TABLE "TrainingModelStoreContainer"."HU_ORGANIZATION";

-- DROP TABLE "TrainingModelStoreContainer"."HU_TITLE";

-- DROP TABLE "TrainingModelStoreContainer"."TR_PROGRAM_GROUP";

-- DROP TABLE "TrainingModelStoreContainer"."TR_REQUEST_CENTER";

-- DROP TABLE "TrainingModelStoreContainer"."TR_REQUEST_TEACHER";

-- DROP TABLE "TrainingModelStoreContainer"."TR_PLAN_COST_DETAIL";

-- DROP TABLE "TrainingModelStoreContainer"."TR_UNIT";

-- DROP TABLE "TrainingModelStoreContainer"."TR_PLAN_EMPLOYEE";

-- DROP TABLE "TrainingModelStoreContainer"."TR_TITLE_COURSE";

-- DROP TABLE "TrainingModelStoreContainer"."SE_REPORT";

-- DROP TABLE "TrainingModelStoreContainer"."SE_USER";

-- DROP TABLE "TrainingModelStoreContainer"."SE_USER_REPORT";

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'TR_COST_CENTER'
CREATE TABLE "dbo"."TR_COST_CENTER" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CODE" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NOT NULL,
   "CREATED_BY" NVARCHAR2(255) NOT NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_BY" NVARCHAR2(255) NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'SE_CHOSEN_ORG'
CREATE TABLE "dbo"."SE_CHOSEN_ORG" (
   "ORG_ID" NUMBER(38,0) NOT NULL,
   "USERNAME" NVARCHAR2(255) NOT NULL
);

-- Creating table 'TR_CENTER'
CREATE TABLE "dbo"."TR_CENTER" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "ADDRESS" NVARCHAR2(1023) NULL,
   "PHONE" NVARCHAR2(255) NULL,
   "FAX" NVARCHAR2(255) NULL,
   "WEB" NVARCHAR2(255) NULL,
   "CONTACT_PERSON" NVARCHAR2(1023) NULL,
   "CONTACT_PHONE" NVARCHAR2(255) NULL,
   "CONTACT_EMAIL" NVARCHAR2(255) NULL,
   "TAX_CODE" NVARCHAR2(255) NULL,
   "TRAIN_FIELD" NVARCHAR2(255) NULL,
   "DESCRIPTION" NVARCHAR2(1023) NULL,
   "REPRESENT" NVARCHAR2(255) NULL,
   "ACTFLG" NUMBER(5,0) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "REMARK" NCLOB NULL
);

-- Creating table 'TR_CERTIFICATE'
CREATE TABLE "dbo"."TR_CERTIFICATE" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "TR_CER_GROUP_ID" NUMBER(38,0) NULL,
   "ACTFLG" NUMBER(5,0) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "DURATION" NUMBER(38,0) NULL,
   "CATEGORY" NCLOB NULL,
   "TRANSPORTATION_TYPE" NCLOB NULL,
   "REMARK" NCLOB NULL
);

-- Creating table 'TR_CLASS'
CREATE TABLE "dbo"."TR_CLASS" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_PROGRAM_ID" NUMBER(38,0) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "START_DATE" DATE NULL,
   "END_DATE" DATE NULL,
   "ADDRESS" NVARCHAR2(1023) NULL,
   "DISTRICT_ID" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "PROVINCE_ID" NUMBER(38,0) NULL
);

-- Creating table 'TR_COURSE'
CREATE TABLE "dbo"."TR_COURSE" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "TR_CER_GROUP_ID" NUMBER(38,0) NULL,
   "TR_CERTIFICATE_ID" NUMBER(38,0) NULL,
   "ACTFLG" NUMBER(5,0) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "TR_TRAIN_FIELD" NUMBER(38,0) NULL,
   "TR_PROGRAM_GROUP" NUMBER(38,0) NULL,
   "DRIVER" NUMBER(38,0) NULL,
   "REMARK" NCLOB NULL,
   "TR_FREQUENCY" NUMBER(38,0) NULL
);

-- Creating table 'TR_LECTURE'
CREATE TABLE "dbo"."TR_LECTURE" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "TR_CENTER_ID" NUMBER(38,0) NULL,
   "IS_LOCAL" NUMBER(5,0) NULL,
   "PHONE" NVARCHAR2(255) NULL,
   "EMAIL" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "ACTFLG" NUMBER(5,0) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "LECTURE_ID" NUMBER(38,0) NULL
);

-- Creating table 'TR_PLAN_JOBGRADE'
CREATE TABLE "dbo"."TR_PLAN_JOBGRADE" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_PLAN_ID" NUMBER(38,0) NULL,
   "JOBGRADE_ID" NUMBER(38,0) NULL
);

-- Creating table 'TR_PLAN_TITLE'
CREATE TABLE "dbo"."TR_PLAN_TITLE" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_PLAN_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL
);

-- Creating table 'TR_PLAN_UNIT'
CREATE TABLE "dbo"."TR_PLAN_UNIT" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_PLAN_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL
);

-- Creating table 'TR_PREPARE'
CREATE TABLE "dbo"."TR_PREPARE" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_PROGRAM_ID" NUMBER(38,0) NULL,
   "TR_LIST_PREPARE_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL
);

-- Creating table 'TR_PROGRAM'
CREATE TABLE "dbo"."TR_PROGRAM" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "YEAR" NUMBER(38,0) NULL,
   "START_DATE" DATE NULL,
   "END_DATE" DATE NULL,
   "TR_COURSE_ID" NUMBER(38,0) NULL,
   "DURATION" NUMBER(38,0) NULL,
   "TR_DURATION_UNIT_ID" NUMBER(38,0) NULL,
   "DURATION_STUDY_ID" NUMBER(38,0) NULL,
   "DURATION_HC" NUMBER(38,0) NULL,
   "DURATION_OT" NUMBER(38,0) NULL,
   "TR_UNIT_ID" NUMBER(38,0) NULL,
   "IS_REIMBURSE" NUMBER(5,0) NULL,
   "TR_LANGUAGE_ID" NUMBER(38,0) NULL,
   "CONTENT" NVARCHAR2(1023) NULL,
   "TARGET_TRAIN" NVARCHAR2(1023) NULL,
   "VENUE" NVARCHAR2(1023) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "TITLES" NCLOB NULL,
   "DEPARTMENTS" NCLOB NULL,
   "CENTERS" NCLOB NULL,
   "IS_RETEST" NUMBER(5,0) NULL,
   "LECTURES" NCLOB NULL,
   "TR_REQUEST_ID" NUMBER(38,0) NULL,
   "TR_PLAN_ID" NUMBER(38,0) NULL,
   "COST_TOTAL_US" NUMBER(38,0) NULL,
   "COST_STUDENT_US" NUMBER(38,0) NULL,
   "STUDENT_NUMBER" NUMBER(38,0) NULL,
   "COST_STUDENT" NUMBER(38,0) NULL,
   "COST_TOTAL" NUMBER(38,0) NULL,
   "TRAIN_FORM_ID" NUMBER(38,0) NULL,
   "PROPERTIES_NEED_ID" NUMBER(38,0) NULL
);

-- Creating table 'TR_PROGRAM_CENTER'
CREATE TABLE "dbo"."TR_PROGRAM_CENTER" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_PROGRAM_ID" NUMBER(38,0) NULL,
   "TR_CENTER_ID" NUMBER(38,0) NULL
);

-- Creating table 'TR_PROGRAM_JOBGRADE'
CREATE TABLE "dbo"."TR_PROGRAM_JOBGRADE" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_PROGRAM_ID" NUMBER(38,0) NULL,
   "JOBGRADE_ID" NUMBER(38,0) NULL
);

-- Creating table 'TR_PROGRAM_LECTURE'
CREATE TABLE "dbo"."TR_PROGRAM_LECTURE" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_PROGRAM_ID" NUMBER(38,0) NULL,
   "TR_LECTURE_ID" NUMBER(38,0) NULL
);

-- Creating table 'TR_PROGRAM_TITLE'
CREATE TABLE "dbo"."TR_PROGRAM_TITLE" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_PROGRAM_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL
);

-- Creating table 'TR_PROGRAM_UNIT'
CREATE TABLE "dbo"."TR_PROGRAM_UNIT" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_PROGRAM_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL
);

-- Creating table 'TR_REQUEST'
CREATE TABLE "dbo"."TR_REQUEST" (
   "ID" NUMBER(38,0) NOT NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "REQUEST_DATE" DATE NULL,
   "YEAR" NUMBER(38,0) NULL,
   "TR_PLAN_ID" NUMBER(38,0) NULL,
   "CONTENT" NVARCHAR2(1023) NULL,
   "EXPECTED_DATE" DATE NULL,
   "START_DATE" DATE NULL,
   "EXPECTED_COST" NUMBER(38,0) NULL,
   "TR_CURRENCY_ID" NUMBER(38,0) NULL,
   "STATUS_ID" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "REQUEST_SENDER_ID" NUMBER(38,0) NULL,
   "IS_IRREGULARLY" NUMBER(5,0) NULL,
   "TR_COURSE_ID" NUMBER(38,0) NULL,
   "TRAIN_FORM_ID" NUMBER(38,0) NULL,
   "PROPERTIES_NEED_ID" NUMBER(38,0) NULL,
   "TR_UNIT_ID" NUMBER(38,0) NULL,
   "TARGET_TRAIN" NVARCHAR2(1023) NULL,
   "VENUE" NVARCHAR2(1023) NULL,
   "ATTACH_FILE" NVARCHAR2(200) NULL,
   "REJECT_REASON" NVARCHAR2(1023) NULL
);

-- Creating table 'TR_REQUEST_EMPLOYEE'
CREATE TABLE "dbo"."TR_REQUEST_EMPLOYEE" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_REQUEST_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL
);

-- Creating table 'TR_CLASS_STUDENT'
CREATE TABLE "dbo"."TR_CLASS_STUDENT" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_CLASS_ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL
);

-- Creating table 'OT_OTHER_LIST'
CREATE TABLE "dbo"."OT_OTHER_LIST" (
   "ID" NUMBER(38,0) NOT NULL,
   "TYPE_ID" NUMBER(38,0) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "ATTRIBUTE1" NVARCHAR2(255) NULL,
   "ATTRIBUTE2" NVARCHAR2(255) NULL,
   "ATTRIBUTE3" NVARCHAR2(255) NULL,
   "ATTRIBUTE4" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "CODE" NVARCHAR2(15) NULL,
   "TYPE_CODE" NVARCHAR2(15) NULL,
   "ORDERBYID" NUMBER(38,0) NULL
);

-- Creating table 'OT_OTHER_LIST_GROUP'
CREATE TABLE "dbo"."OT_OTHER_LIST_GROUP" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'OT_OTHER_LIST_TYPE'
CREATE TABLE "dbo"."OT_OTHER_LIST_TYPE" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(255) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "GROUP_ID" NUMBER(38,0) NULL,
   "IS_SYSTEM" NUMBER(5,0) NULL,
   "TABLE_RELATION" VARCHAR2(2000) NULL
);

-- Creating table 'TR_PLAN_CENTER'
CREATE TABLE "dbo"."TR_PLAN_CENTER" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_PLAN_ID" NUMBER(38,0) NULL,
   "CENTER_ID" NUMBER(38,0) NULL
);

-- Creating table 'TR_PLAN'
CREATE TABLE "dbo"."TR_PLAN" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TR_COURSE_ID" NUMBER(38,0) NULL,
   "PLAN_T1" NUMBER(5,0) NULL,
   "PLAN_T2" NUMBER(5,0) NULL,
   "PLAN_T3" NUMBER(5,0) NULL,
   "PLAN_T4" NUMBER(5,0) NULL,
   "PLAN_T5" NUMBER(5,0) NULL,
   "PLAN_T6" NUMBER(5,0) NULL,
   "PLAN_T7" NUMBER(5,0) NULL,
   "PLAN_T8" NUMBER(5,0) NULL,
   "PLAN_T9" NUMBER(5,0) NULL,
   "PLAN_T10" NUMBER(5,0) NULL,
   "PLAN_T11" NUMBER(5,0) NULL,
   "PLAN_T12" NUMBER(5,0) NULL,
   "DURATION" NUMBER(38,0) NULL,
   "TR_DURATION_UNIT_ID" NUMBER(38,0) NULL,
   "TEACHER_NUMBER" NUMBER(38,0) NULL,
   "STUDENT_NUMBER" NUMBER(38,0) NULL,
   "COST_TRAIN" NUMBER(38,0) NULL,
   "COST_INCURRED" NUMBER(38,0) NULL,
   "COST_TRAVEL" NUMBER(38,0) NULL,
   "COST_TOTAL" NUMBER(38,0) NULL,
   "COST_OF_STUDENT" NUMBER(38,0) NULL,
   "TR_CURRENCY_ID" NUMBER(38,0) NULL,
   "TARGET_TRAIN" NVARCHAR2(1023) NULL,
   "VENUE" NVARCHAR2(1023) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "COST_OTHER" NUMBER(38,0) NULL,
   "TITLES" NCLOB NULL,
   "DEPARTMENTS" NCLOB NULL,
   "CENTERS" NCLOB NULL,
   "MONTHS" NCLOB NULL,
   "YEAR" NUMBER(38,0) NULL,
   "TRAIN_FORM_ID" NUMBER(38,0) NULL,
   "PROPERTIES_NEED_ID" NUMBER(38,0) NULL,
   "UNIT_ID" NUMBER(38,0) NULL,
   "ATTACHFILE" NCLOB NULL,
   "COST_TOTAL_USD" NUMBER(38,0) NULL,
   "COST_OF_STUDENT_USD" NUMBER(38,0) NULL,
   "WORKS" NCLOB NULL
);

-- Creating table 'HU_DISTRICT'
CREATE TABLE "dbo"."HU_DISTRICT" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "PROVINCE_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "STATUS" NUMBER(5,0) NULL,
   "NOTE" NVARCHAR2(255) NULL,
   "CODE" NVARCHAR2(50) NULL
);

-- Creating table 'HU_NATION'
CREATE TABLE "dbo"."HU_NATION" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CODE" NVARCHAR2(15) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "STATUS" NUMBER(5,0) NULL,
   "NOTE" NVARCHAR2(255) NULL
);

-- Creating table 'HU_PROVINCE'
CREATE TABLE "dbo"."HU_PROVINCE" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CODE" NVARCHAR2(255) NULL,
   "NATION_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "STATUS" NUMBER(5,0) NULL,
   "NOTE" NVARCHAR2(255) NULL
);

-- Creating table 'HU_CONTRACT'
CREATE TABLE "dbo"."HU_CONTRACT" (
   "ID" NUMBER(38,0) NOT NULL,
   "CONTRACT_NO" NVARCHAR2(255) NULL,
   "CONTRACT_TYPE_ID" NUMBER(38,0) NOT NULL,
   "START_DATE" DATE NOT NULL,
   "EXPIRE_DATE" DATE NULL,
   "SIGNER_TITLE" NVARCHAR2(255) NULL,
   "SIGNER_NAME" NVARCHAR2(255) NULL,
   "SIGN_DATE" DATE NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "STATUS_ID" NUMBER(38,0) NULL,
   "SIGN_ID" NUMBER(38,0) NULL,
   "WORKING_ID" NUMBER(38,0) NULL,
   "PERCENT_SALARY" NUMBER(5,0) NULL,
   "CONTRACTTMP_ID" NUMBER(38,0) NULL,
   "SALARY" NUMBER(38,0) NULL,
   "LIQUI_DATE" DATE NULL,
   "AUTHORIZE_NO" NVARCHAR2(255) NULL,
   "SIGN_ORG_ID" NUMBER(38,0) NULL,
   "JOB" NVARCHAR2(500) NULL,
   "WORK_TIME" NVARCHAR2(255) NULL,
   "BREAK_TIME" NVARCHAR2(255) NULL
);

-- Creating table 'HU_CONTRACT_TYPE'
CREATE TABLE "dbo"."HU_CONTRACT_TYPE" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NOT NULL,
   "CODE" NVARCHAR2(255) NOT NULL,
   "PERIOD" NUMBER(10,0) NULL,
   "CREATED_DATE" DATE NOT NULL,
   "CREATED_BY" NVARCHAR2(255) NOT NULL,
   "CREATED_LOG" NVARCHAR2(255) NOT NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_BY" NVARCHAR2(255) NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NOT NULL,
   "STATUS" NUMBER(5,0) NULL,
   "TYPE" NUMBER(10,0) NULL,
   "REMARK" NCLOB NULL
);

-- Creating table 'TR_CLASS_SCHEDULE'
CREATE TABLE "dbo"."TR_CLASS_SCHEDULE" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_CLASS_ID" NUMBER(38,0) NULL,
   "START_TIME" DATE NULL,
   "END_TIME" DATE NULL,
   "IS_HC" NUMBER(5,0) NULL,
   "IS_HALF" NUMBER(5,0) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "CONTENT" NVARCHAR2(1023) NULL
);

-- Creating table 'TR_PROGRAM_COMMIT'
CREATE TABLE "dbo"."TR_PROGRAM_COMMIT" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_PROGRAM_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "COMMIT_NO" NVARCHAR2(255) NULL,
   "COMMIT_WORK" NUMBER(38,0) NULL,
   "COMMIT_DATE" DATE NULL,
   "APPROVER_ID" NUMBER(38,0) NULL,
   "COMMIT_REMARK" NVARCHAR2(1023) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL
);

-- Creating table 'TR_PROGRAM_RESULT'
CREATE TABLE "dbo"."TR_PROGRAM_RESULT" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_PROGRAM_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "DURATION" NUMBER(38,0) NULL,
   "IS_EXAMS" NUMBER(5,0) NULL,
   "IS_END" NUMBER(5,0) NULL,
   "IS_REACH" NUMBER(5,0) NULL,
   "IS_CERTIFICATE" NUMBER(5,0) NULL,
   "CERTIFICATE_DATE" DATE NULL,
   "CERTIFICATE_NO" NVARCHAR2(255) NULL,
   "TR_RANK_ID" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "TOIEC_BENCHMARK" NUMBER(38,0) NULL,
   "TOIEC_SCORE_IN" NUMBER(38,0) NULL,
   "TOIEC_SCORE_OUT" NUMBER(38,0) NULL,
   "INCREMENT_SCORE" NUMBER(38,0) NULL,
   "ABSENT_REASON" NUMBER(5,0) NULL,
   "ABSENT_UNREASON" NUMBER(5,0) NULL,
   "CER_RECEIVE_DATE" DATE NULL,
   "COMMIT_STARTDATE" DATE NULL,
   "COMMIT_ENDDATE" DATE NULL,
   "COMMIT_WORKMONTH" NUMBER(38,0) NULL,
   "IS_REFUND_FEE" NUMBER(5,0) NULL,
   "IS_RESERVES" NUMBER(5,0) NULL,
   "REMARK" NCLOB NULL,
   "FINAL_SCORE" NUMBER(38,0) NULL,
   "RETEST_SCORE" NUMBER(38,0) NULL,
   "RETEST_RANK_ID" NUMBER(38,0) NULL,
   "RETEST_REMARK" NCLOB NULL,
   "ATTACH_FILE" NCLOB NULL
);

-- Creating table 'TR_PROGRAM_COST'
CREATE TABLE "dbo"."TR_PROGRAM_COST" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_PROGRAM_ID" NUMBER(38,0) NULL,
   "COST_COMPANY" NUMBER(38,0) NULL,
   "STUDENT_NUMBER" NUMBER(38,0) NULL,
   "COST_OF_STUDENT" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "ORG_ID" NUMBER(38,0) NULL
);

-- Creating table 'TR_ASSESSMENT_FORM'
CREATE TABLE "dbo"."TR_ASSESSMENT_FORM" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL
);

-- Creating table 'TR_ASSESSMENT_RATE'
CREATE TABLE "dbo"."TR_ASSESSMENT_RATE" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "POINT_FROM" NUMBER(38,0) NULL,
   "POINT_TO" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "ACTFLG" NUMBER(5,0) NULL
);

-- Creating table 'TR_CHOOSE_FORM'
CREATE TABLE "dbo"."TR_CHOOSE_FORM" (
   "ID" NUMBER(38,0) NOT NULL,
   "YEAR" NUMBER(38,0) NULL,
   "TR_PROGRAM_ID" NUMBER(38,0) NULL,
   "TR_ASSESSMENT_FORM_ID" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL
);

-- Creating table 'TR_COMMIT_AFTER_TRAIN'
CREATE TABLE "dbo"."TR_COMMIT_AFTER_TRAIN" (
   "ID" NUMBER(38,0) NOT NULL,
   "COST_TRAIN_FROM" NUMBER(38,0) NULL,
   "TR_CURRENCY_ID" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "ACTFLG" NUMBER(5,0) NULL,
   "COMMIT_WORK" NUMBER(38,0) NULL,
   "COST_TRAIN_TO" NUMBER(38,0) NULL
);

-- Creating table 'TR_REIMBURSEMENT'
CREATE TABLE "dbo"."TR_REIMBURSEMENT" (
   "ID" NUMBER(38,0) NOT NULL,
   "YEAR" NUMBER(38,0) NULL,
   "TR_PROGRAM_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "START_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "COST_REIMBURSE" NUMBER(38,0) NULL,
   "IS_RESERVES" NUMBER(5,0) NULL
);

-- Creating table 'TR_SETTING_ASS_FORM'
CREATE TABLE "dbo"."TR_SETTING_ASS_FORM" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_ASSESSMENT_FORM_ID" NUMBER(38,0) NOT NULL,
   "TR_CRITERIA_GROUP_ID" NUMBER(38,0) NOT NULL,
   "CREATED_BY" NVARCHAR2(50) NOT NULL,
   "CREATED_DATE" DATE NOT NULL,
   "CREATED_LOG" NVARCHAR2(1023) NOT NULL,
   "MODIFIED_BY" NVARCHAR2(50) NOT NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NOT NULL
);

-- Creating table 'TR_SETTING_CRI_GRP'
CREATE TABLE "dbo"."TR_SETTING_CRI_GRP" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_CRITERIA_ID" NUMBER(38,0) NULL,
   "TR_CRITERIA_GROUP_ID" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL
);

-- Creating table 'TR_CRITERIA'
CREATE TABLE "dbo"."TR_CRITERIA" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "POINT_MAX" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "ACTFLG" NUMBER(5,0) NULL
);

-- Creating table 'TR_CRITERIA_GROUP'
CREATE TABLE "dbo"."TR_CRITERIA_GROUP" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "POINT_MAX" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "ACTFLG" NUMBER(5,0) NULL
);

-- Creating table 'TR_ASSESSMENT_RESULT'
CREATE TABLE "dbo"."TR_ASSESSMENT_RESULT" (
   "ID" NUMBER(38,0) NOT NULL,
   "YEAR" NUMBER(38,0) NULL,
   "TR_CHOOSE_FORM_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL
);

-- Creating table 'TR_ASSESSMENT_RESULT_DTL'
CREATE TABLE "dbo"."TR_ASSESSMENT_RESULT_DTL" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_ASSESSMENT_RESULT_ID" NUMBER(38,0) NULL,
   "TR_CHOOSE_FORM_ID" NUMBER(38,0) NULL,
   "TR_CRITERIA_GROUP_ID" NUMBER(38,0) NULL,
   "TR_CRITERIA_ID" NUMBER(38,0) NULL,
   "POINT_ASS" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL
);

-- Creating table 'HU_EMPLOYEE'
CREATE TABLE "dbo"."HU_EMPLOYEE" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_CODE" NVARCHAR2(15) NULL,
   "FIRST_NAME_VN" NVARCHAR2(255) NULL,
   "LAST_NAME_VN" NVARCHAR2(255) NULL,
   "FULLNAME_VN" NVARCHAR2(255) NULL,
   "FIRST_NAME_EN" VARCHAR2(255) NULL,
   "LAST_NAME_EN" NVARCHAR2(255) NULL,
   "FULLNAME_EN" NVARCHAR2(255) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "WORK_STATUS" NUMBER(38,0) NULL,
   "CONTRACT_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "JOIN_DATE" DATE NULL,
   "DIRECT_MANAGER" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "LAST_WORKING_ID" NUMBER(38,0) NULL,
   "TER_EFFECT_DATE" DATE NULL,
   "TER_LAST_DATE" DATE NULL,
   "ITIME_ID" NUMBER(38,0) NULL,
   "STAFF_RANK_ID" NUMBER(38,0) NULL
);

-- Creating table 'HU_EMPLOYEE_CV'
CREATE TABLE "dbo"."HU_EMPLOYEE_CV" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "GENDER" NUMBER(38,0) NULL,
   "IMAGE" NVARCHAR2(255) NULL,
   "BIRTH_DATE" DATE NULL,
   "BIRTH_PLACE" NVARCHAR2(255) NULL,
   "MARITAL_STATUS" NUMBER(38,0) NULL,
   "RELIGION" NUMBER(38,0) NULL,
   "NATIVE" NUMBER(38,0) NULL,
   "NATIONALITY" NUMBER(38,0) NULL,
   "PER_ADDRESS" NVARCHAR2(255) NULL,
   "PER_PROVINCE" NUMBER(38,0) NULL,
   "HOME_PHONE" NVARCHAR2(255) NULL,
   "MOBILE_PHONE" NVARCHAR2(255) NULL,
   "ID_NO" NVARCHAR2(15) NULL,
   "ID_DATE" DATE NULL,
   "PASS_NO" NVARCHAR2(255) NULL,
   "PASS_DATE" DATE NULL,
   "PASS_EXPIRE" DATE NULL,
   "PASS_PLACE" NVARCHAR2(255) NULL,
   "VISA" NVARCHAR2(255) NULL,
   "VISA_DATE" DATE NULL,
   "VISA_EXPIRE" DATE NULL,
   "VISA_PLACE" NVARCHAR2(255) NULL,
   "WORK_PERMIT" NVARCHAR2(255) NULL,
   "WORK_PERMIT_DATE" DATE NULL,
   "WORK_PERMIT_EXPIRE" DATE NULL,
   "WORK_EMAIL" NVARCHAR2(255) NULL,
   "NAV_ADDRESS" NVARCHAR2(255) NULL,
   "NAV_PROVINCE" NUMBER(38,0) NULL,
   "PIT_CODE" VARCHAR2(255) NULL,
   "PER_EMAIL" NVARCHAR2(255) NULL,
   "CONTACT_PER" NVARCHAR2(255) NULL,
   "CONTACT_PER_PHONE" NVARCHAR2(15) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ID_PLACE" NVARCHAR2(255) NULL,
   "WORK_PERMIT_PLACE" NVARCHAR2(255) NULL,
   "BANK_ID" NUMBER(38,0) NULL,
   "BANK_BRANCH_ID" NUMBER(38,0) NULL,
   "NGAY_VAO_DOAN" DATE NULL,
   "NOI_VAO_DOAN" NVARCHAR2(255) NULL,
   "CHUC_VU_DOAN" NVARCHAR2(255) NULL,
   "DOAN_PHI" NUMBER(5,0) NULL,
   "NGAY_VAO_DANG" DATE NULL,
   "NOI_VAO_DANG" NVARCHAR2(255) NULL,
   "CHUC_VU_DANG" NVARCHAR2(255) NULL,
   "DANG_PHI" NUMBER(5,0) NULL,
   "BANK_NO" NVARCHAR2(255) NULL,
   "DRIVER_LICENSE" NVARCHAR2(255) NULL,
   "DRIVER_LICENSE_DATE" DATE NULL,
   "DRIVER_LICENSE_EXPIRE" DATE NULL,
   "CAREER" NVARCHAR2(255) NULL
);

-- Creating table 'HU_ORG_TITLE'
CREATE TABLE "dbo"."HU_ORG_TITLE" (
   "ID" NUMBER(38,0) NOT NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_ORGANIZATION'
CREATE TABLE "dbo"."HU_ORGANIZATION" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(35) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "PARENT_ID" NUMBER(38,0) NULL,
   "LEVEL_ID" NUMBER(38,0) NULL,
   "DISSOLVE_DATE" DATE NULL,
   "FOUNDATION_DATE" DATE NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "HIERARCHICAL_PATH" VARCHAR2(1023) NULL,
   "DESCRIPTION_PATH" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ADDRESS" NVARCHAR2(1023) NULL,
   "FAX" NVARCHAR2(1023) NULL,
   "REPRESENTATIVE_ID" NUMBER(38,0) NULL
);

-- Creating table 'HU_TITLE'
CREATE TABLE "dbo"."HU_TITLE" (
   "ID" NUMBER(38,0) NOT NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CODE" NVARCHAR2(16) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(255) NULL,
   "TITLE_GROUP_ID" NUMBER(38,0) NULL,
   "WORK_INVOLVE_ID" NUMBER(38,0) NULL
);

-- Creating table 'TR_PROGRAM_GROUP'
CREATE TABLE "dbo"."TR_PROGRAM_GROUP" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NCLOB NULL,
   "NAME" NCLOB NULL,
   "TRAIN_FIELD_ID" NUMBER(38,0) NULL,
   "REMARK" NCLOB NULL,
   "CREATED_BY" NCLOB NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NCLOB NULL,
   "MODIFIED_BY" NCLOB NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NCLOB NULL,
   "ACTFLG" NUMBER(38,0) NULL
);

-- Creating table 'TR_REQUEST_CENTER'
CREATE TABLE "dbo"."TR_REQUEST_CENTER" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_REQUEST_ID" NUMBER(38,0) NULL,
   "CENTER_ID" NUMBER(38,0) NULL
);

-- Creating table 'TR_REQUEST_TEACHER'
CREATE TABLE "dbo"."TR_REQUEST_TEACHER" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_REQUEST_ID" NUMBER(38,0) NULL,
   "TEACHER_ID" NUMBER(38,0) NULL
);

-- Creating table 'TR_PLAN_COST_DETAIL'
CREATE TABLE "dbo"."TR_PLAN_COST_DETAIL" (
   "ID" NUMBER(38,0) NOT NULL,
   "PLAN_ID" NUMBER(38,0) NULL,
   "TYPE_ID" NUMBER(38,0) NULL,
   "MONEY" NUMBER(38,0) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MONEY_TYPE" NUMBER(38,0) NULL
);

-- Creating table 'TR_UNIT'
CREATE TABLE "dbo"."TR_UNIT" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NCLOB NULL,
   "NAME" NCLOB NULL,
   "ADDRESS" NVARCHAR2(50) NULL,
   "PHONE" DATE NULL,
   "FAX" NVARCHAR2(1023) NULL,
   "WEB" NVARCHAR2(50) NULL,
   "TAX_CODE" DATE NULL,
   "TRAIN_FIELD" NVARCHAR2(1023) NULL,
   "REPRESENT" NCLOB NULL,
   "CONTACT_PERSON" NCLOB NULL,
   "CONTACT_PHONE" NCLOB NULL,
   "CONTACT_EMAIL" NCLOB NULL,
   "REMARK" NCLOB NULL,
   "ACTFLG" NUMBER(38,0) NULL,
   "CREATED_BY" NCLOB NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NCLOB NULL,
   "MODIFIED_BY" NCLOB NULL,
   "MODIFIED_DATE" NCLOB NULL,
   "MODIFIED_LOG" NCLOB NULL
);

-- Creating table 'TR_PLAN_EMPLOYEE'
CREATE TABLE "dbo"."TR_PLAN_EMPLOYEE" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_PLAN_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL
);

-- Creating table 'TR_TITLE_COURSE'
CREATE TABLE "dbo"."TR_TITLE_COURSE" (
   "ID" NUMBER(38,0) NOT NULL,
   "TR_COURSE_ID" NUMBER(38,0) NOT NULL,
   "HU_TITLE_ID" NUMBER(38,0) NOT NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL
);

-- Creating table 'SE_REPORT'
CREATE TABLE "dbo"."SE_REPORT" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NULL,
   "MODULE_ID" NUMBER(38,0) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "CODE" NVARCHAR2(255) NULL
);

-- Creating table 'SE_USER'
CREATE TABLE "dbo"."SE_USER" (
   "ID" NUMBER(38,0) NOT NULL,
   "USERNAME" NVARCHAR2(255) NULL,
   "PASSWORD" NVARCHAR2(255) NULL,
   "FULLNAME" NVARCHAR2(255) NULL,
   "EMAIL" NVARCHAR2(255) NULL,
   "TELEPHONE" NVARCHAR2(255) NULL,
   "IS_APP" NUMBER(5,0) NULL,
   "IS_PORTAL" NUMBER(5,0) NULL,
   "EMPLOYEE_CODE" VARCHAR2(15) NULL,
   "IS_AD" NUMBER(5,0) NULL,
   "EFFECT_DATE" DATE NULL,
   "EXPIRE_DATE" DATE NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "LOCATION" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "IS_CHANGE_PASS" NUMBER(5,0) NULL,
   "CHANGE_PASS_DATE" DATE NULL,
   "REMINDER_COUNT" NUMBER(5,0) NULL,
   "MODULE_ADMIN" NVARCHAR2(255) NULL
);

-- Creating table 'SE_USER_REPORT'
CREATE TABLE "dbo"."SE_USER_REPORT" (
   "SE_REPORT_ID" NUMBER(38,0) NOT NULL,
   "SE_USER_ID" NUMBER(38,0) NOT NULL
);


-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on "ID"in table 'TR_COST_CENTER'
ALTER TABLE "dbo"."TR_COST_CENTER"
ADD CONSTRAINT "PK_TR_COST_CENTER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ORG_ID", "USERNAME"in table 'SE_CHOSEN_ORG'
ALTER TABLE "dbo"."SE_CHOSEN_ORG"
ADD CONSTRAINT "PK_SE_CHOSEN_ORG"
   PRIMARY KEY ("ORG_ID", "USERNAME" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_CENTER'
ALTER TABLE "dbo"."TR_CENTER"
ADD CONSTRAINT "PK_TR_CENTER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_CERTIFICATE'
ALTER TABLE "dbo"."TR_CERTIFICATE"
ADD CONSTRAINT "PK_TR_CERTIFICATE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_CLASS'
ALTER TABLE "dbo"."TR_CLASS"
ADD CONSTRAINT "PK_TR_CLASS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_COURSE'
ALTER TABLE "dbo"."TR_COURSE"
ADD CONSTRAINT "PK_TR_COURSE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_LECTURE'
ALTER TABLE "dbo"."TR_LECTURE"
ADD CONSTRAINT "PK_TR_LECTURE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_PLAN_JOBGRADE'
ALTER TABLE "dbo"."TR_PLAN_JOBGRADE"
ADD CONSTRAINT "PK_TR_PLAN_JOBGRADE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_PLAN_TITLE'
ALTER TABLE "dbo"."TR_PLAN_TITLE"
ADD CONSTRAINT "PK_TR_PLAN_TITLE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_PLAN_UNIT'
ALTER TABLE "dbo"."TR_PLAN_UNIT"
ADD CONSTRAINT "PK_TR_PLAN_UNIT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_PREPARE'
ALTER TABLE "dbo"."TR_PREPARE"
ADD CONSTRAINT "PK_TR_PREPARE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_PROGRAM'
ALTER TABLE "dbo"."TR_PROGRAM"
ADD CONSTRAINT "PK_TR_PROGRAM"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_PROGRAM_CENTER'
ALTER TABLE "dbo"."TR_PROGRAM_CENTER"
ADD CONSTRAINT "PK_TR_PROGRAM_CENTER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_PROGRAM_JOBGRADE'
ALTER TABLE "dbo"."TR_PROGRAM_JOBGRADE"
ADD CONSTRAINT "PK_TR_PROGRAM_JOBGRADE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_PROGRAM_LECTURE'
ALTER TABLE "dbo"."TR_PROGRAM_LECTURE"
ADD CONSTRAINT "PK_TR_PROGRAM_LECTURE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_PROGRAM_TITLE'
ALTER TABLE "dbo"."TR_PROGRAM_TITLE"
ADD CONSTRAINT "PK_TR_PROGRAM_TITLE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_PROGRAM_UNIT'
ALTER TABLE "dbo"."TR_PROGRAM_UNIT"
ADD CONSTRAINT "PK_TR_PROGRAM_UNIT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_REQUEST'
ALTER TABLE "dbo"."TR_REQUEST"
ADD CONSTRAINT "PK_TR_REQUEST"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_REQUEST_EMPLOYEE'
ALTER TABLE "dbo"."TR_REQUEST_EMPLOYEE"
ADD CONSTRAINT "PK_TR_REQUEST_EMPLOYEE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_CLASS_STUDENT'
ALTER TABLE "dbo"."TR_CLASS_STUDENT"
ADD CONSTRAINT "PK_TR_CLASS_STUDENT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST'
ALTER TABLE "dbo"."OT_OTHER_LIST"
ADD CONSTRAINT "PK_OT_OTHER_LIST"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST_GROUP'
ALTER TABLE "dbo"."OT_OTHER_LIST_GROUP"
ADD CONSTRAINT "PK_OT_OTHER_LIST_GROUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST_TYPE'
ALTER TABLE "dbo"."OT_OTHER_LIST_TYPE"
ADD CONSTRAINT "PK_OT_OTHER_LIST_TYPE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_PLAN_CENTER'
ALTER TABLE "dbo"."TR_PLAN_CENTER"
ADD CONSTRAINT "PK_TR_PLAN_CENTER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_PLAN'
ALTER TABLE "dbo"."TR_PLAN"
ADD CONSTRAINT "PK_TR_PLAN"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_DISTRICT'
ALTER TABLE "dbo"."HU_DISTRICT"
ADD CONSTRAINT "PK_HU_DISTRICT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_NATION'
ALTER TABLE "dbo"."HU_NATION"
ADD CONSTRAINT "PK_HU_NATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_PROVINCE'
ALTER TABLE "dbo"."HU_PROVINCE"
ADD CONSTRAINT "PK_HU_PROVINCE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_CONTRACT'
ALTER TABLE "dbo"."HU_CONTRACT"
ADD CONSTRAINT "PK_HU_CONTRACT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_CONTRACT_TYPE'
ALTER TABLE "dbo"."HU_CONTRACT_TYPE"
ADD CONSTRAINT "PK_HU_CONTRACT_TYPE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_CLASS_SCHEDULE'
ALTER TABLE "dbo"."TR_CLASS_SCHEDULE"
ADD CONSTRAINT "PK_TR_CLASS_SCHEDULE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_PROGRAM_COMMIT'
ALTER TABLE "dbo"."TR_PROGRAM_COMMIT"
ADD CONSTRAINT "PK_TR_PROGRAM_COMMIT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_PROGRAM_RESULT'
ALTER TABLE "dbo"."TR_PROGRAM_RESULT"
ADD CONSTRAINT "PK_TR_PROGRAM_RESULT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_PROGRAM_COST'
ALTER TABLE "dbo"."TR_PROGRAM_COST"
ADD CONSTRAINT "PK_TR_PROGRAM_COST"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_ASSESSMENT_FORM'
ALTER TABLE "dbo"."TR_ASSESSMENT_FORM"
ADD CONSTRAINT "PK_TR_ASSESSMENT_FORM"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_ASSESSMENT_RATE'
ALTER TABLE "dbo"."TR_ASSESSMENT_RATE"
ADD CONSTRAINT "PK_TR_ASSESSMENT_RATE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_CHOOSE_FORM'
ALTER TABLE "dbo"."TR_CHOOSE_FORM"
ADD CONSTRAINT "PK_TR_CHOOSE_FORM"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_COMMIT_AFTER_TRAIN'
ALTER TABLE "dbo"."TR_COMMIT_AFTER_TRAIN"
ADD CONSTRAINT "PK_TR_COMMIT_AFTER_TRAIN"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_REIMBURSEMENT'
ALTER TABLE "dbo"."TR_REIMBURSEMENT"
ADD CONSTRAINT "PK_TR_REIMBURSEMENT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_SETTING_ASS_FORM'
ALTER TABLE "dbo"."TR_SETTING_ASS_FORM"
ADD CONSTRAINT "PK_TR_SETTING_ASS_FORM"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_SETTING_CRI_GRP'
ALTER TABLE "dbo"."TR_SETTING_CRI_GRP"
ADD CONSTRAINT "PK_TR_SETTING_CRI_GRP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_CRITERIA'
ALTER TABLE "dbo"."TR_CRITERIA"
ADD CONSTRAINT "PK_TR_CRITERIA"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_CRITERIA_GROUP'
ALTER TABLE "dbo"."TR_CRITERIA_GROUP"
ADD CONSTRAINT "PK_TR_CRITERIA_GROUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_ASSESSMENT_RESULT'
ALTER TABLE "dbo"."TR_ASSESSMENT_RESULT"
ADD CONSTRAINT "PK_TR_ASSESSMENT_RESULT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_ASSESSMENT_RESULT_DTL'
ALTER TABLE "dbo"."TR_ASSESSMENT_RESULT_DTL"
ADD CONSTRAINT "PK_TR_ASSESSMENT_RESULT_DTL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "PK_HU_EMPLOYEE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_CV'
ALTER TABLE "dbo"."HU_EMPLOYEE_CV"
ADD CONSTRAINT "PK_HU_EMPLOYEE_CV"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ORG_TITLE'
ALTER TABLE "dbo"."HU_ORG_TITLE"
ADD CONSTRAINT "PK_HU_ORG_TITLE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ORGANIZATION'
ALTER TABLE "dbo"."HU_ORGANIZATION"
ADD CONSTRAINT "PK_HU_ORGANIZATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_TITLE'
ALTER TABLE "dbo"."HU_TITLE"
ADD CONSTRAINT "PK_HU_TITLE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_PROGRAM_GROUP'
ALTER TABLE "dbo"."TR_PROGRAM_GROUP"
ADD CONSTRAINT "PK_TR_PROGRAM_GROUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_REQUEST_CENTER'
ALTER TABLE "dbo"."TR_REQUEST_CENTER"
ADD CONSTRAINT "PK_TR_REQUEST_CENTER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_REQUEST_TEACHER'
ALTER TABLE "dbo"."TR_REQUEST_TEACHER"
ADD CONSTRAINT "PK_TR_REQUEST_TEACHER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_PLAN_COST_DETAIL'
ALTER TABLE "dbo"."TR_PLAN_COST_DETAIL"
ADD CONSTRAINT "PK_TR_PLAN_COST_DETAIL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_UNIT'
ALTER TABLE "dbo"."TR_UNIT"
ADD CONSTRAINT "PK_TR_UNIT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_PLAN_EMPLOYEE'
ALTER TABLE "dbo"."TR_PLAN_EMPLOYEE"
ADD CONSTRAINT "PK_TR_PLAN_EMPLOYEE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_TITLE_COURSE'
ALTER TABLE "dbo"."TR_TITLE_COURSE"
ADD CONSTRAINT "PK_TR_TITLE_COURSE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_REPORT'
ALTER TABLE "dbo"."SE_REPORT"
ADD CONSTRAINT "PK_SE_REPORT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_USER'
ALTER TABLE "dbo"."SE_USER"
ADD CONSTRAINT "PK_SE_USER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "SE_REPORT_ID", "SE_USER_ID"in table 'SE_USER_REPORT'
ALTER TABLE "dbo"."SE_USER_REPORT"
ADD CONSTRAINT "PK_SE_USER_REPORT"
   PRIMARY KEY ("SE_REPORT_ID", "SE_USER_ID" )
   ENABLE
   VALIDATE;


-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on "PROVINCE_ID" in table 'HU_DISTRICT'
ALTER TABLE "dbo"."HU_DISTRICT"
ADD CONSTRAINT "FK_HU_PRO_HU_DIS"
   FOREIGN KEY ("PROVINCE_ID")
   REFERENCES "dbo"."HU_PROVINCE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_PRO_HU_DIS'
CREATE INDEX "IX_FK_HU_PRO_HU_DIS"
ON "dbo"."HU_DISTRICT"
   ("PROVINCE_ID");

-- Creating foreign key on "NATION_ID" in table 'HU_PROVINCE'
ALTER TABLE "dbo"."HU_PROVINCE"
ADD CONSTRAINT "FK_HU_NAT_HU_PRO"
   FOREIGN KEY ("NATION_ID")
   REFERENCES "dbo"."HU_NATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_NAT_HU_PRO'
CREATE INDEX "IX_FK_HU_NAT_HU_PRO"
ON "dbo"."HU_PROVINCE"
   ("NATION_ID");

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_CV'
ALTER TABLE "dbo"."HU_EMPLOYEE_CV"
ADD CONSTRAINT "FK_HE_HEC"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "TITLE_ID" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HE_HT"
   FOREIGN KEY ("TITLE_ID")
   REFERENCES "dbo"."HU_TITLE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HE_HT'
CREATE INDEX "IX_FK_HE_HT"
ON "dbo"."HU_EMPLOYEE"
   ("TITLE_ID");

-- Creating foreign key on "ORG_ID" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HU_ORG_HU_EMP"
   FOREIGN KEY ("ORG_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_ORG_HU_EMP'
CREATE INDEX "IX_FK_HU_ORG_HU_EMP"
ON "dbo"."HU_EMPLOYEE"
   ("ORG_ID");

-- Creating foreign key on "DIRECT_MANAGER" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HUEMD_HUEM"
   FOREIGN KEY ("DIRECT_MANAGER")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUEMD_HUEM'
CREATE INDEX "IX_FK_HUEMD_HUEM"
ON "dbo"."HU_EMPLOYEE"
   ("DIRECT_MANAGER");

-- Creating foreign key on "ORG_ID" in table 'HU_ORG_TITLE'
ALTER TABLE "dbo"."HU_ORG_TITLE"
ADD CONSTRAINT "FK_HUOG_HUOT"
   FOREIGN KEY ("ORG_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUOG_HUOT'
CREATE INDEX "IX_FK_HUOG_HUOT"
ON "dbo"."HU_ORG_TITLE"
   ("ORG_ID");

-- Creating foreign key on "TITLE_ID" in table 'HU_ORG_TITLE'
ALTER TABLE "dbo"."HU_ORG_TITLE"
ADD CONSTRAINT "FK_HUTL_HUOT"
   FOREIGN KEY ("TITLE_ID")
   REFERENCES "dbo"."HU_TITLE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUTL_HUOT'
CREATE INDEX "IX_FK_HUTL_HUOT"
ON "dbo"."HU_ORG_TITLE"
   ("TITLE_ID");

-- Creating foreign key on "PARENT_ID" in table 'HU_ORGANIZATION'
ALTER TABLE "dbo"."HU_ORGANIZATION"
ADD CONSTRAINT "FK_HU_ORG_HU_ORG"
   FOREIGN KEY ("PARENT_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_ORG_HU_ORG'
CREATE INDEX "IX_FK_HU_ORG_HU_ORG"
ON "dbo"."HU_ORGANIZATION"
   ("PARENT_ID");

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------
