Public Class INS_ACCIDENT_RISKDTO
    Public Property ID As Decimal?
    Public Property EMPLOYEE_ID As Decimal?
    Public Property EMPLOYEE_CODE As String
    Public Property EMPLOYEE_NAME As String
    Public Property ORG_NAME As String
    Public Property ORG_DESC As String
    Public Property TITLE_NAME As String
    Public Property ORG_NAME2 As String
    Public Property ORG_NAME3 As String
    Public Property ORG_NAME4 As String
    Public Property BIRTH_DATE As Date?
    Public Property GENDER_NAME As String
    Public Property ADDRESS As String
    Public Property CONTRACT_NO As String
    Public Property ROWNUM_NO As String
    Public Property CONTRACT_SIGN_DATE As Date?
    Public Property CONTRACT_START_DATE As Date?
    Public Property CONTRACT_EXPIRE_DATE As Date?
    Public Property PLHD_CONTRACT_NO As String
    Public Property PLHD_SIGN_DATE As Date?
    Public Property PLHD_START_DATE As Date?
    Public Property PLHD_EXPIRE_DATE As Date?
    Public Property INS_ORG_NAME As String
    Public Property REMARK As String
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
    Public Property JOB_NAME As String
    Public Property INS_ORG_ID As Decimal?
End Class
