Public Class INS_SPECIFIED_OBJECTS_DTO
    Public Property ID As Decimal?
    Public Property LOCATION_ID As Decimal?
    Public Property LOCATION_NAME As String
    Public Property EFFECTIVE_DATE As Date?
    Public Property SI As Decimal?
    Public Property HI As Decimal?
    Public Property UI As Decimal?
    Public Property SI_COM As Decimal?
    Public Property SI_EMP As Decimal?
    Public Property HI_COM As Decimal?
    Public Property HI_EMP As Decimal?
    Public Property UI_COM As Decimal?
    Public Property UI_EMP As Decimal?
    Public Property BHTNLD_BNN_COM As Decimal?
    Public Property BHTNLD_BNN_EMP As Decimal?
    Public Property SICK As Decimal?
    Public Property MATERNITY As Decimal?
    Public Property OFF_IN_HOUSE As Decimal?
    Public Property OFF_TOGETHER As Decimal?
    Public Property RETIRE_MALE As Decimal?
    Public Property RETIRE_FEMALE As Decimal?
    Public Property STATUS As Decimal?
    Public Property SALARY_MIN As Decimal?
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
    Public Property SI_DATE As Decimal?
    Public Property HI_DATE As Decimal?
End Class
