Public Class INS_REMIGE_MANAGER_DTO
    Public Property ID As Decimal?
    Public Property EMPLOYEE_ID As Decimal?
    Public Property EMPLOYEE_CODE As String
    Public Property EMPLOYEE_NAME As String
    Public Property TITLE_NAME As String
    Public Property ORG_NAME As String
    Public Property ORG_DESC As String
    Public Property BIRTH_DATE As Date?
    Public Property BIRTH_ADDRESS As String
    Public Property STAFF_RANK_ID As Decimal?
    Public Property STAFF_RANK_NAME As String
    Public Property INSURRANCE_NUM As String
    Public Property BOOK_NUM As String
    Public Property ENTITLED_ID As Decimal?
    Public Property ENTITLED_NAME As String
    Public Property START_DATE As Date?
    Public Property END_DATE As Date?
    Public Property CHANGE_MONTH As Date?
    Public Property is_ATHOME As Boolean?
    Public Property is_FOCUSED As Boolean?
    Public Property NUM_DATE As Decimal?
    Public Property DATE_OFF_BIRT As Date?
    Public Property BABY_NAME As String
    Public Property NUM_BABY As Decimal?
    Public Property ACCUMULATED_DATE As Decimal?
    Public Property ALLOWANCE_SAL As Decimal?
    Public Property ALLOWANCE_MONEY As Decimal?
    Public Property ALLOWANCE_MONEY_EDIT As Decimal?
    Public Property TIME_ALLOWANCE As String
    Public Property CONDITION_ALLOWANCE As String
    Public Property SDESC As String
    Public Property APPROVAL_INSURRANCE As Decimal?
    Public Property APPROVAL_DATE As Date?
    Public Property APPROVAL_NUM As Decimal?
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String

    Public Property IS_TERMINATE As Boolean?
    Public Property WORK_STATUS As Decimal?
    Public Property TER_LAST_DATE As Date?
    Public Property FROM_DATE_SEARCH As Date?
    Public Property TO_DATE_SEARCH As Date?
End Class
