-- --------------------------------------------------
-- Entity Designer DDL Script for Oracle database
-- --------------------------------------------------
-- Date Created: 05/14/2020 8:54:07 AM
-- Generated from EDMX file: D:\MyProject2020\ACV_NEW\acv_19\PerformanceDAL\PerformanceContext.edmx
-- --------------------------------------------------

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

-- ALTER TABLE "dbo"."HU_EMPLOYEE_CV" DROP CONSTRAINT "FK_HE_HEC" CASCADE;

-- ALTER TABLE "dbo"."HU_EMPLOYEE" DROP CONSTRAINT "FK_HE_HT" CASCADE;

-- ALTER TABLE "dbo"."HU_EMPLOYEE" DROP CONSTRAINT "FK_HU_ORG_HU_EMP" CASCADE;

-- ALTER TABLE "dbo"."HU_EMPLOYEE" DROP CONSTRAINT "FK_HUEMD_HUEM" CASCADE;

-- ALTER TABLE "dbo"."HU_ORG_TITLE" DROP CONSTRAINT "FK_HUOG_HUOT" CASCADE;

-- ALTER TABLE "dbo"."HU_ORG_TITLE" DROP CONSTRAINT "FK_HUTL_HUOT" CASCADE;

-- ALTER TABLE "dbo"."HU_ORGANIZATION" DROP CONSTRAINT "FK_HU_ORG_HU_ORG" CASCADE;

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

-- DROP TABLE "dbo"."PE_CRITERIA";

-- DROP TABLE "dbo"."PE_OBJECT_GROUP";

-- DROP TABLE "dbo"."PE_OBJECT_GROUP_PERIOD";

-- DROP TABLE "dbo"."HU_EMPLOYEE";

-- DROP TABLE "dbo"."HU_EMPLOYEE_CV";

-- DROP TABLE "dbo"."HU_ORG_TITLE";

-- DROP TABLE "dbo"."HU_ORGANIZATION";

-- DROP TABLE "dbo"."HU_TITLE";

-- DROP TABLE "dbo"."SE_CHOSEN_ORG";

-- DROP TABLE "dbo"."HU_STAFF_RANK";

-- DROP TABLE "dbo"."HUV_ORGANIZATION";

-- DROP TABLE "dbo"."PE_PERSONAL";

-- DROP TABLE "dbo"."PE_EMPLOYEE_ASSESSMENT_DTL";

-- DROP TABLE "dbo"."PE_ORGANIZATION";

-- DROP TABLE "dbo"."PE_CLASSIFICATION";

-- DROP TABLE "dbo"."OT_OTHER_LIST";

-- DROP TABLE "dbo"."PE_ASSESSMENT";

-- DROP TABLE "dbo"."PE_EMPLOYEE_ASSESSMENT";

-- DROP TABLE "dbo"."PE_CRITERIA_OBJECT_GROUP";

-- DROP TABLE "dbo"."PE_PERIOD";

-- DROP TABLE "dbo"."PE_KPI_EVALUATE";

-- DROP TABLE "dbo"."PA_SALARY_LEVEL";

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'PE_CRITERIA'
CREATE TABLE "dbo"."PE_CRITERIA" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "REMARK" NVARCHAR2(1023) NULL
);

-- Creating table 'PE_OBJECT_GROUP'
CREATE TABLE "dbo"."PE_OBJECT_GROUP" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL
);

-- Creating table 'PE_OBJECT_GROUP_PERIOD'
CREATE TABLE "dbo"."PE_OBJECT_GROUP_PERIOD" (
   "ID" NUMBER(38,0) NOT NULL,
   "OBJECT_GROUP_ID" NUMBER(38,0) NOT NULL,
   "PERIOD_ID" NUMBER(38,0) NOT NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL
);

-- Creating table 'HU_EMPLOYEE'
CREATE TABLE "dbo"."HU_EMPLOYEE" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_CODE" NVARCHAR2(15) NULL,
   "FIRST_NAME_VN" NVARCHAR2(255) NULL,
   "LAST_NAME_VN" NVARCHAR2(255) NULL,
   "FULLNAME_VN" NVARCHAR2(255) NULL,
   "FIRST_NAME_EN" VARCHAR2(255) NULL,
   "LAST_NAME_EN" NVARCHAR2(255) NULL,
   "FULLNAME_EN" NVARCHAR2(255) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "WORK_STATUS" NUMBER(38,0) NULL,
   "CONTRACT_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "JOIN_DATE" DATE NULL,
   "DIRECT_MANAGER" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "LAST_WORKING_ID" NUMBER(38,0) NULL,
   "TER_EFFECT_DATE" DATE NULL,
   "TER_LAST_DATE" DATE NULL,
   "ITIME_ID" NUMBER(38,0) NULL,
   "STAFF_RANK_ID" NUMBER(38,0) NULL,
   "PA_OBJECT_SALARY_ID" NUMBER(38,0) NULL,
   "EXPIREDATE_ENT" DATE NULL,
   "JOIN_DATE_STATE" DATE NULL,
   "LEVEL_MANAGER" NUMBER(38,0) NULL,
   "EMPLOYEE_3B_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_CODE_OLD" NVARCHAR2(15) NULL,
   "IS_3B" NUMBER(5,0) NULL
);

-- Creating table 'HU_EMPLOYEE_CV'
CREATE TABLE "dbo"."HU_EMPLOYEE_CV" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "GENDER" NUMBER(38,0) NULL,
   "IMAGE" NVARCHAR2(255) NULL,
   "BIRTH_DATE" DATE NULL,
   "BIRTH_PLACE" NVARCHAR2(255) NULL,
   "MARITAL_STATUS" NUMBER(38,0) NULL,
   "RELIGION" NUMBER(38,0) NULL,
   "NATIVE" NUMBER(38,0) NULL,
   "NATIONALITY" NUMBER(38,0) NULL,
   "PER_ADDRESS" NVARCHAR2(255) NULL,
   "PER_PROVINCE" NUMBER(38,0) NULL,
   "HOME_PHONE" NVARCHAR2(255) NULL,
   "MOBILE_PHONE" NVARCHAR2(255) NULL,
   "ID_NO" NVARCHAR2(15) NULL,
   "ID_DATE" DATE NULL,
   "PASS_NO" NVARCHAR2(255) NULL,
   "PASS_DATE" DATE NULL,
   "PASS_EXPIRE" DATE NULL,
   "PASS_PLACE" NVARCHAR2(255) NULL,
   "VISA" NVARCHAR2(255) NULL,
   "VISA_DATE" DATE NULL,
   "VISA_EXPIRE" DATE NULL,
   "VISA_PLACE" NVARCHAR2(255) NULL,
   "WORK_PERMIT" NVARCHAR2(255) NULL,
   "WORK_PERMIT_DATE" DATE NULL,
   "WORK_PERMIT_EXPIRE" DATE NULL,
   "WORK_EMAIL" NVARCHAR2(255) NULL,
   "NAV_ADDRESS" NVARCHAR2(255) NULL,
   "NAV_PROVINCE" NUMBER(38,0) NULL,
   "PIT_CODE" VARCHAR2(255) NULL,
   "PER_EMAIL" NVARCHAR2(255) NULL,
   "CONTACT_PER" NVARCHAR2(255) NULL,
   "CONTACT_PER_PHONE" NVARCHAR2(15) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ID_PLACE" NVARCHAR2(255) NULL,
   "WORK_PERMIT_PLACE" NVARCHAR2(255) NULL,
   "BANK_ID" NUMBER(38,0) NULL,
   "BANK_BRANCH_ID" NUMBER(38,0) NULL,
   "BANK_NO" NVARCHAR2(255) NULL,
   "NGAY_VAO_DOAN" DATE NULL,
   "NOI_VAO_DOAN" NVARCHAR2(255) NULL,
   "CHUC_VU_DOAN" NVARCHAR2(255) NULL,
   "DOAN_PHI" NUMBER(5,0) NULL,
   "NGAY_VAO_DANG" DATE NULL,
   "NOI_VAO_DANG" NVARCHAR2(255) NULL,
   "CHUC_VU_DANG" NVARCHAR2(255) NULL,
   "DANG_PHI" NUMBER(5,0) NULL,
   "CAREER" NVARCHAR2(255) NULL,
   "PER_DISTRICT" NUMBER(38,0) NULL,
   "NAV_DISTRICT" NUMBER(38,0) NULL,
   "PER_WARD" NUMBER(38,0) NULL,
   "NAV_WARD" NUMBER(38,0) NULL,
   "WORKPLACE_ID" NUMBER(38,0) NULL,
   "IS_PERMISSION" NUMBER(5,0) NULL,
   "INS_REGION_ID" NUMBER(38,0) NULL
);

-- Creating table 'HU_ORG_TITLE'
CREATE TABLE "dbo"."HU_ORG_TITLE" (
   "ID" NUMBER(38,0) NOT NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_ORGANIZATION'
CREATE TABLE "dbo"."HU_ORGANIZATION" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "PARENT_ID" NUMBER(38,0) NULL,
   "LEVEL_ID" NUMBER(38,0) NULL,
   "DISSOLVE_DATE" DATE NULL,
   "FOUNDATION_DATE" DATE NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "HIERARCHICAL_PATH" VARCHAR2(1023) NULL,
   "DESCRIPTION_PATH" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ADDRESS" NVARCHAR2(1023) NULL,
   "FAX" NVARCHAR2(255) NULL,
   "REPRESENTATIVE_ID" NUMBER(38,0) NULL,
   "MOBILE" NVARCHAR2(255) NULL,
   "PROVINCE_NAME" NVARCHAR2(50) NULL,
   "COST_CENTER_CODE" NVARCHAR2(50) NULL,
   "ORD_NO" NUMBER(38,0) NULL
);

-- Creating table 'HU_TITLE'
CREATE TABLE "dbo"."HU_TITLE" (
   "ID" NUMBER(38,0) NOT NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "TITLE_GROUP_ID" NUMBER(38,0) NULL
);

-- Creating table 'SE_CHOSEN_ORG'
CREATE TABLE "dbo"."SE_CHOSEN_ORG" (
   "ORG_ID" NUMBER(38,0) NOT NULL,
   "USERNAME" NVARCHAR2(255) NOT NULL
);

-- Creating table 'HU_STAFF_RANK'
CREATE TABLE "dbo"."HU_STAFF_RANK" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "LEVEL_STAFF" NUMBER(38,0) NULL
);

-- Creating table 'HUV_ORGANIZATION'
CREATE TABLE "dbo"."HUV_ORGANIZATION" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "ORG_NAME" NVARCHAR2(255) NULL,
   "PARENT_ID" NUMBER(38,0) NULL,
   "CODE" NVARCHAR2(50) NULL,
   "ADDRESS" NVARCHAR2(1023) NULL,
   "DESCRIPTION_PATH" NVARCHAR2(1023) NULL,
   "COST_CENTER_CODE" NVARCHAR2(50) NULL,
   "PROVINCE_NAME" NVARCHAR2(50) NULL,
   "ORG_NAME1" NVARCHAR2(1999) NULL,
   "ORG_NAME2" NVARCHAR2(1999) NULL,
   "ORG_NAME3" NVARCHAR2(1999) NULL,
   "ORG_NAME4" NVARCHAR2(1999) NULL,
   "ORG_NAME5" NVARCHAR2(1999) NULL,
   "ORG_NAME6" NVARCHAR2(1999) NULL,
   "ORG_NAME7" NVARCHAR2(1999) NULL,
   "ORG_NAME8" NVARCHAR2(1999) NULL,
   "ORG_NAME9" NVARCHAR2(1999) NULL,
   "ORG_ID1" NUMBER(38,0) NULL,
   "ORG_ID2" NUMBER(38,0) NULL,
   "ORG_ID3" NUMBER(38,0) NULL,
   "ORG_ID4" NUMBER(38,0) NULL,
   "ORG_ID5" NUMBER(38,0) NULL,
   "ORG_ID6" NUMBER(38,0) NULL,
   "ORG_ID7" NUMBER(38,0) NULL,
   "ORG_ID8" NUMBER(38,0) NULL,
   "ORG_ID9" NUMBER(38,0) NULL,
   "ORG_CODE1" NVARCHAR2(1999) NULL,
   "ORG_CODE2" NVARCHAR2(1999) NULL,
   "ORG_CODE3" NVARCHAR2(1999) NULL,
   "ORG_CODE4" NVARCHAR2(1999) NULL,
   "ORG_CODE5" NVARCHAR2(1999) NULL,
   "ORG_CODE6" NVARCHAR2(1999) NULL,
   "ORG_CODE7" NVARCHAR2(1999) NULL,
   "ORG_CODE8" NVARCHAR2(1999) NULL,
   "ORG_CODE9" NVARCHAR2(1999) NULL,
   "ORG_COST_CENTER1" NVARCHAR2(1999) NULL,
   "ORG_COST_CENTER2" NVARCHAR2(1999) NULL,
   "ORG_COST_CENTER3" NVARCHAR2(1999) NULL,
   "ORG_COST_CENTER4" NVARCHAR2(1999) NULL,
   "ORG_COST_CENTER5" NVARCHAR2(1999) NULL,
   "ORG_COST_CENTER6" NVARCHAR2(1999) NULL,
   "ORG_COST_CENTER7" NVARCHAR2(1999) NULL,
   "ORG_COST_CENTER8" NVARCHAR2(1999) NULL,
   "ORG_COST_CENTER9" NVARCHAR2(1999) NULL,
   "ORG_PATH" NVARCHAR2(2000) NULL,
   "ORD_NO" NUMBER(38,0) NULL,
   "DISSOLVE_DATE" DATE NULL,
   "ACTFLG" NVARCHAR2(1) NULL
);

-- Creating table 'PE_PERSONAL'
CREATE TABLE "dbo"."PE_PERSONAL" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "PERIOD_ID" NUMBER(38,0) NOT NULL,
   "CRITERIA_GROUP_ID" NUMBER(38,0) NOT NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "OBJECT_GROUP_ID" NUMBER(38,0) NULL,
   "MARK" NUMBER(38,0) NULL,
   "RATING" NVARCHAR2(255) NULL
);

-- Creating table 'PE_EMPLOYEE_ASSESSMENT_DTL'
CREATE TABLE "dbo"."PE_EMPLOYEE_ASSESSMENT_DTL" (
   "ID" NUMBER(38,0) NOT NULL,
   "PE_EMPLOYEE_ASSESSMENT_ID" NUMBER(38,0) NOT NULL,
   "CRITERIA_ID" NUMBER(38,0) NOT NULL,
   "POINT" NUMBER(38,0) NOT NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "GROUP_OBJ_ID" NUMBER(38,0) NULL,
   "CLASSIFICATION" NVARCHAR2(255) NULL
);

-- Creating table 'PE_ORGANIZATION'
CREATE TABLE "dbo"."PE_ORGANIZATION" (
   "ID" NUMBER(38,0) NOT NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "RESULT" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL
);

-- Creating table 'PE_CLASSIFICATION'
CREATE TABLE "dbo"."PE_CLASSIFICATION" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(10) NULL,
   "NAME" NVARCHAR2(100) NULL,
   "VALUE_FROM" NUMBER(5,0) NULL,
   "VALUE_TO" NUMBER(5,0) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'OT_OTHER_LIST'
CREATE TABLE "dbo"."OT_OTHER_LIST" (
   "ID" NUMBER(38,0) NOT NULL,
   "TYPE_ID" NUMBER(38,0) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "ATTRIBUTE1" NVARCHAR2(255) NULL,
   "ATTRIBUTE2" NVARCHAR2(255) NULL,
   "ATTRIBUTE3" NVARCHAR2(255) NULL,
   "ATTRIBUTE4" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "CODE" NVARCHAR2(50) NULL,
   "TYPE_CODE" NVARCHAR2(50) NULL,
   "ORDERBYID" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1023) NULL
);

-- Creating table 'PE_ASSESSMENT'
CREATE TABLE "dbo"."PE_ASSESSMENT" (
   "ID" NUMBER(38,0) NOT NULL,
   "PE_EMPLOYEE_ASSESSMENT_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "PE_PERIO_ID" NUMBER(38,0) NULL,
   "PE_OBJECT_ID" NUMBER(38,0) NULL,
   "PE_CRITERIA_ID" NUMBER(38,0) NULL,
   "RESULT" NVARCHAR2(1023) NULL,
   "STATUS_EMP_ID" NUMBER(38,0) NULL,
   "DIRECT_ID" NUMBER(38,0) NULL,
   "UPDATE_DATE" DATE NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "RESULT_DIRECT" NVARCHAR2(1023) NULL,
   "ASS_DATE" DATE NULL,
   "REMARK_DIRECT" NVARCHAR2(1023) NULL,
   "RESULT_CONVERT" NUMBER(38,0) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "STATUS_DIRECT" NUMBER(38,0) NULL,
   "RESULT_CONVERT_QL" NUMBER(38,0) NULL
);

-- Creating table 'PE_EMPLOYEE_ASSESSMENT'
CREATE TABLE "dbo"."PE_EMPLOYEE_ASSESSMENT" (
   "ID" NUMBER(38,0) NOT NULL,
   "OBJECT_GROUP_ID" NUMBER(38,0) NOT NULL,
   "PERIOD_ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "PE_STATUS" NUMBER(38,0) NULL
);

-- Creating table 'PE_CRITERIA_OBJECT_GROUP'
CREATE TABLE "dbo"."PE_CRITERIA_OBJECT_GROUP" (
   "ID" NUMBER(38,0) NOT NULL,
   "OBJECT_GROUP_ID" NUMBER(38,0) NOT NULL,
   "CRITERIA_ID" NUMBER(38,0) NOT NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "EXPENSE" NVARCHAR2(100) NULL,
   "AMONG" NUMBER(38,0) NULL,
   "FROM_DATE" DATE NULL,
   "TO_DATE" DATE NULL
);

-- Creating table 'PE_PERIOD'
CREATE TABLE "dbo"."PE_PERIOD" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "START_DATE" DATE NULL,
   "END_DATE" DATE NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "TYPE_ASS" NUMBER(38,0) NULL,
   "YEAR" NUMBER(38,0) NULL
);

-- Creating table 'PE_KPI_EVALUATE'
CREATE TABLE "dbo"."PE_KPI_EVALUATE" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "SALARYLEVEL_ID" NUMBER(38,0) NULL,
   "JOIN_DATE" DATE NULL,
   "END_DATE" DATE NULL,
   "FINANCE_TT" NUMBER(38,2) NULL,
   "FINANCE_TTX" NUMBER(38,2) NULL,
   "CUSTOMER_TT" NUMBER(38,2) NULL,
   "CUSTOMER_TTX" NUMBER(38,2) NULL,
   "PROCESS_TT" NUMBER(38,2) NULL,
   "PROCESS_TTX" NUMBER(38,2) NULL,
   "LEARN_TT" NUMBER(38,2) NULL,
   "LEARN_TTX" NUMBER(38,2) NULL,
   "SUM_TT" NVARCHAR2(50) NULL,
   "SUM_TTX" NUMBER(38,2) NULL,
   "SUM_RATE_KPI" NUMBER(38,2) NULL,
   "CLASSFICATION" NUMBER(38,0) NULL,
   "COMMENTS" NVARCHAR2(1023) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "KPI_ID" NUMBER(38,0) NULL
);

-- Creating table 'PA_SALARY_LEVEL'
CREATE TABLE "dbo"."PA_SALARY_LEVEL" (
   "ID" NUMBER(38,0) NOT NULL,
   "SAL_GROUP_ID" NUMBER(38,0) NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NOT NULL,
   "CREATED_BY" NVARCHAR2(255) NOT NULL,
   "CREATED_LOG" NVARCHAR2(255) NOT NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_BY" NVARCHAR2(255) NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NOT NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "ORDERS" NUMBER(38,0) NULL,
   "OTHER_USE" NVARCHAR2(100) NULL,
   "GRADE_GROUP" NUMBER(38,0) NOT NULL,
   "SAL_FR" NUMBER(38,0) NOT NULL,
   "SAL_TO" NUMBER(38,0) NOT NULL
);


-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on "ID"in table 'PE_CRITERIA'
ALTER TABLE "dbo"."PE_CRITERIA"
ADD CONSTRAINT "PK_PE_CRITERIA"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PE_OBJECT_GROUP'
ALTER TABLE "dbo"."PE_OBJECT_GROUP"
ADD CONSTRAINT "PK_PE_OBJECT_GROUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PE_OBJECT_GROUP_PERIOD'
ALTER TABLE "dbo"."PE_OBJECT_GROUP_PERIOD"
ADD CONSTRAINT "PK_PE_OBJECT_GROUP_PERIOD"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "PK_HU_EMPLOYEE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_CV'
ALTER TABLE "dbo"."HU_EMPLOYEE_CV"
ADD CONSTRAINT "PK_HU_EMPLOYEE_CV"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ORG_TITLE'
ALTER TABLE "dbo"."HU_ORG_TITLE"
ADD CONSTRAINT "PK_HU_ORG_TITLE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ORGANIZATION'
ALTER TABLE "dbo"."HU_ORGANIZATION"
ADD CONSTRAINT "PK_HU_ORGANIZATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_TITLE'
ALTER TABLE "dbo"."HU_TITLE"
ADD CONSTRAINT "PK_HU_TITLE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ORG_ID", "USERNAME"in table 'SE_CHOSEN_ORG'
ALTER TABLE "dbo"."SE_CHOSEN_ORG"
ADD CONSTRAINT "PK_SE_CHOSEN_ORG"
   PRIMARY KEY ("ORG_ID", "USERNAME" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_STAFF_RANK'
ALTER TABLE "dbo"."HU_STAFF_RANK"
ADD CONSTRAINT "PK_HU_STAFF_RANK"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HUV_ORGANIZATION'
ALTER TABLE "dbo"."HUV_ORGANIZATION"
ADD CONSTRAINT "PK_HUV_ORGANIZATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PE_PERSONAL'
ALTER TABLE "dbo"."PE_PERSONAL"
ADD CONSTRAINT "PK_PE_PERSONAL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PE_EMPLOYEE_ASSESSMENT_DTL'
ALTER TABLE "dbo"."PE_EMPLOYEE_ASSESSMENT_DTL"
ADD CONSTRAINT "PK_PE_EMPLOYEE_ASSESSMENT_DTL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PE_ORGANIZATION'
ALTER TABLE "dbo"."PE_ORGANIZATION"
ADD CONSTRAINT "PK_PE_ORGANIZATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PE_CLASSIFICATION'
ALTER TABLE "dbo"."PE_CLASSIFICATION"
ADD CONSTRAINT "PK_PE_CLASSIFICATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST'
ALTER TABLE "dbo"."OT_OTHER_LIST"
ADD CONSTRAINT "PK_OT_OTHER_LIST"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PE_ASSESSMENT'
ALTER TABLE "dbo"."PE_ASSESSMENT"
ADD CONSTRAINT "PK_PE_ASSESSMENT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PE_EMPLOYEE_ASSESSMENT'
ALTER TABLE "dbo"."PE_EMPLOYEE_ASSESSMENT"
ADD CONSTRAINT "PK_PE_EMPLOYEE_ASSESSMENT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PE_CRITERIA_OBJECT_GROUP'
ALTER TABLE "dbo"."PE_CRITERIA_OBJECT_GROUP"
ADD CONSTRAINT "PK_PE_CRITERIA_OBJECT_GROUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PE_PERIOD'
ALTER TABLE "dbo"."PE_PERIOD"
ADD CONSTRAINT "PK_PE_PERIOD"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PE_KPI_EVALUATE'
ALTER TABLE "dbo"."PE_KPI_EVALUATE"
ADD CONSTRAINT "PK_PE_KPI_EVALUATE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SALARY_LEVEL'
ALTER TABLE "dbo"."PA_SALARY_LEVEL"
ADD CONSTRAINT "PK_PA_SALARY_LEVEL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_CV'
ALTER TABLE "dbo"."HU_EMPLOYEE_CV"
ADD CONSTRAINT "FK_HE_HEC"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "TITLE_ID" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HE_HT"
   FOREIGN KEY ("TITLE_ID")
   REFERENCES "dbo"."HU_TITLE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HE_HT'
CREATE INDEX "IX_FK_HE_HT"
ON "dbo"."HU_EMPLOYEE"
   ("TITLE_ID");

-- Creating foreign key on "ORG_ID" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HU_ORG_HU_EMP"
   FOREIGN KEY ("ORG_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_ORG_HU_EMP'
CREATE INDEX "IX_FK_HU_ORG_HU_EMP"
ON "dbo"."HU_EMPLOYEE"
   ("ORG_ID");

-- Creating foreign key on "DIRECT_MANAGER" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HUEMD_HUEM"
   FOREIGN KEY ("DIRECT_MANAGER")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUEMD_HUEM'
CREATE INDEX "IX_FK_HUEMD_HUEM"
ON "dbo"."HU_EMPLOYEE"
   ("DIRECT_MANAGER");

-- Creating foreign key on "ORG_ID" in table 'HU_ORG_TITLE'
ALTER TABLE "dbo"."HU_ORG_TITLE"
ADD CONSTRAINT "FK_HUOG_HUOT"
   FOREIGN KEY ("ORG_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUOG_HUOT'
CREATE INDEX "IX_FK_HUOG_HUOT"
ON "dbo"."HU_ORG_TITLE"
   ("ORG_ID");

-- Creating foreign key on "TITLE_ID" in table 'HU_ORG_TITLE'
ALTER TABLE "dbo"."HU_ORG_TITLE"
ADD CONSTRAINT "FK_HUTL_HUOT"
   FOREIGN KEY ("TITLE_ID")
   REFERENCES "dbo"."HU_TITLE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUTL_HUOT'
CREATE INDEX "IX_FK_HUTL_HUOT"
ON "dbo"."HU_ORG_TITLE"
   ("TITLE_ID");

-- Creating foreign key on "PARENT_ID" in table 'HU_ORGANIZATION'
ALTER TABLE "dbo"."HU_ORGANIZATION"
ADD CONSTRAINT "FK_HU_ORG_HU_ORG"
   FOREIGN KEY ("PARENT_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_ORG_HU_ORG'
CREATE INDEX "IX_FK_HU_ORG_HU_ORG"
ON "dbo"."HU_ORGANIZATION"
   ("PARENT_ID");

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------
