'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Site

    '''<summary>
    '''HeadContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager

    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''RadInputManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadInputManager1 As Global.Telerik.Web.UI.RadInputManager

    '''<summary>
    '''imglogo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imglogo1 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''btnNotiTimer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNotiTimer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''udTimePn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udTimePn As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ltrNumberRocord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrNumberRocord As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''dcontractRemind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcontractRemind As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblWLEO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWLEO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltrWLEO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrWLEO As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''dbirthdayRemind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dbirthdayRemind As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTime_LEAVE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTime_LEAVE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltrTime_LEAVE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrTime_LEAVE As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''dnoPaperRemind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dnoPaperRemind As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTime_GiayTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTime_GiayTo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltrTime_GiayTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrTime_GiayTo As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''dvisaRemind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvisaRemind As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTime_Visa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTime_Visa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltrTime_Visa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrTime_Visa As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''dvisaRemind1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvisaRemind1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTime_ToTrinh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTime_ToTrinh As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltrTime_ToTrinh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrTime_ToTrinh As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''dworPermitRemind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dworPermitRemind As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTime_GiayPhepLaoDong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTime_GiayPhepLaoDong As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltrTime_GiayPhepLaoDong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrTime_GiayPhepLaoDong As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''dcertificateRemind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcertificateRemind As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTime_ChungChi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTime_ChungChi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltrTime_ChungChi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrTime_ChungChi As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''dterminateRemind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dterminateRemind As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTime_NghiViec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTime_NghiViec As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltrTime_NghiViec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrTime_NghiViec As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''dworkingRemind1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dworkingRemind1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTime_ToTrinhPheDuyet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTime_ToTrinhPheDuyet As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltrTime_ToTrinhPheDuyet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrTime_ToTrinhPheDuyet As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''dProbationRemind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dProbationRemind As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblProbation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProbation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltrProbation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrProbation As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''dApproveRemind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dApproveRemind As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApprove As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltrApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrApprove As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''LoginView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoginView1 As Global.System.Web.UI.WebControls.LoginView

    '''<summary>
    '''HeadLoginName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadLoginName As Global.System.Web.UI.WebControls.LoginName

    '''<summary>
    '''RadToolTip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTip1 As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''rbiEmployeeImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbiEmployeeImage As Global.Telerik.Web.UI.RadBinaryImage

    '''<summary>
    '''lblUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HeadLoginStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadLoginStatus As Global.System.Web.UI.WebControls.LoginStatus

    '''<summary>
    '''rbiEmployeeImageAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbiEmployeeImageAll As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rbiEmployeeImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbiEmployeeImage1 As Global.Telerik.Web.UI.RadBinaryImage

    '''<summary>
    '''lblUserName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserName2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rsSkin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rsSkin As Global.Telerik.Web.UI.RadSkinManager

    '''<summary>
    '''QuickLaunchToolbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuickLaunchToolbar As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''rwAbout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rwAbout As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''rwLicense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rwLicense As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock
End Class
