Datetime: 2:54:34 PM Thursday, October 26, 2017
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 2:54:34 PM Thursday, October 26, 2017
Path: account_login_aspx | PageLoad
Datetime: 2:54:41 PM Thursday, October 26, 2017
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 2:54:41 PM Thursday, October 26, 2017
Path: account_login_aspx | PageLoad
Datetime: 2:54:48 PM Thursday, October 26, 2017
Path: account_login_aspx | PageLoad
Datetime: 2:55:02 PM Thursday, October 26, 2017
Path: account_login_aspx | OnAuthenticate
Datetime: 2:55:10 PM Thursday, October 26, 2017
Path: account_login_aspx | PageLoad
Datetime: 2:58:26 PM Thursday, October 26, 2017
Path: account_login_aspx | OnAuthenticate
Datetime: 3:02:59 PM Thursday, October 26, 2017
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 3:02:59 PM Thursday, October 26, 2017
Time Process: 25
Path: account_login_aspx | PageLoad
Datetime: 3:03:10 PM Thursday, October 26, 2017
Path: account_login_aspx | PageLoad
Datetime: 3:03:20 PM Thursday, October 26, 2017
Time Process: 10
Path: account_login_aspx | OnAuthenticate
Datetime: 3:03:20 PM Thursday, October 26, 2017
Path: account_login_aspx | LoggedIn
Datetime: 3:03:21 CH 26 Tháng Mười 2017
Path: default_aspx | OnInit
Datetime: 3:03:21 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 3:03:21 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 3:03:22 CH 26 Tháng Mười 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 3:03:22 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 3:03:22 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 3:03:58 CH 26 Tháng Mười 2017
Path: site_master | GetDataNotify
Datetime: 3:03:58 CH 26 Tháng Mười 2017
Time Process: 34
Path: site_master | LoadConfig
Datetime: 3:03:58 CH 26 Tháng Mười 2017
Time Process: 36
Path: site_master | Page_Load
Datetime: 3:03:58 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 3:03:59 CH 26 Tháng Mười 2017
Time Process: 1
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 3:03:59 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 3:03:59 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 3:03:59 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:03:59 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 3:03:59 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:03:59 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:03:59 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:03:59 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 3:04:00 CH 26 Tháng Mười 2017
Path: site_master | BuildMainMenu
Datetime: 3:06:41 PM Thursday, October 26, 2017
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 3:06:41 PM Thursday, October 26, 2017
Time Process: 66
Path: account_login_aspx | PageLoad
Datetime: 3:06:47 PM Thursday, October 26, 2017
Path: account_login_aspx | PageLoad
Datetime: 3:07:20 PM Thursday, October 26, 2017
Time Process: 32
Path: account_login_aspx | OnAuthenticate
Datetime: 3:07:20 PM Thursday, October 26, 2017
Path: account_login_aspx | LoggedIn
Datetime: 3:07:20 CH 26 Tháng Mười 2017
Path: default_aspx | OnInit
Datetime: 3:07:21 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 3:07:21 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 3:07:21 CH 26 Tháng Mười 2017
Path: default_aspx | OnInit
Datetime: 3:07:21 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 3:07:21 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 3:07:29 CH 26 Tháng Mười 2017
Path: site_master | GetDataNotify
Datetime: 3:07:29 CH 26 Tháng Mười 2017
Time Process: 7
Path: site_master | LoadConfig
Datetime: 3:07:29 CH 26 Tháng Mười 2017
Time Process: 8
Path: site_master | Page_Load
Datetime: 3:07:29 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 3:07:29 CH 26 Tháng Mười 2017
Time Process: 1
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 3:07:29 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 3:07:29 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 3:07:30 CH 26 Tháng Mười 2017
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 3:11:53 CH 26 Tháng Mười 2017
Time Process: 2
Path: default_aspx | OnInit
Datetime: 3:11:53 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 3:11:53 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | InitControl
Datetime: 3:11:53 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 3:12:03 CH 26 Tháng Mười 2017
Path: site_master | GetDataNotify
Datetime: 3:12:03 CH 26 Tháng Mười 2017
Time Process: 10
Path: site_master | LoadConfig
Datetime: 3:12:03 CH 26 Tháng Mười 2017
Time Process: 10
Path: site_master | Page_Load
Datetime: 3:12:03 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_organize_business_ctrlhu_organization_ascx | ToolbarAuthorization
Datetime: 3:12:03 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_organize_business_ctrlhu_organization_ascx | CheckAuthorization
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:05 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Time Process: 1
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | FillDataByTree
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | treeOrgFunction_NodeClick
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Time Process: 1
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeNode
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Time Process: 2
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | Refresh
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_organize_business_ctrlhu_organization_ascx | ChangeToolbarState
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | UpdateControlState
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | FillDataByTree
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Time Process: 2
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | ViewLoad
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 3:12:06 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 3:12:07 CH 26 Tháng Mười 2017
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 4:24:54 PM Thursday, October 26, 2017
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 4:24:54 PM Thursday, October 26, 2017
Time Process: 2565
Path: account_login_aspx | PageLoad
Datetime: 4:29:13 PM Thursday, October 26, 2017
Time Process: 29
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 4:29:13 PM Thursday, October 26, 2017
Time Process: 29
Path: account_login_aspx | PageLoad
Datetime: 4:29:19 PM Thursday, October 26, 2017
Path: account_login_aspx | PageLoad
Datetime: 4:29:30 PM Thursday, October 26, 2017
Time Process: 11
Path: account_login_aspx | OnAuthenticate
Datetime: 4:29:30 PM Thursday, October 26, 2017
Path: account_login_aspx | LoggedIn
Datetime: 4:29:32 CH 26 Tháng Mười 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 4:29:32 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 4:29:32 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | InitControl
Datetime: 4:29:32 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 4:29:34 CH 26 Tháng Mười 2017
Path: site_master | GetDataNotify
Datetime: 4:29:34 CH 26 Tháng Mười 2017
Time Process: 1
Path: site_master | LoadConfig
Datetime: 4:29:34 CH 26 Tháng Mười 2017
Time Process: 1
Path: site_master | Page_Load
Datetime: 4:29:34 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_organize_business_ctrlhu_organization_ascx | ToolbarAuthorization
Datetime: 4:29:34 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_organize_business_ctrlhu_organization_ascx | CheckAuthorization
Datetime: 4:29:35 CH 26 Tháng Mười 2017
Time Process: 1
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | GetDataCombo
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:37 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Time Process: 1
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeChildNode
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | FillDataByTree
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | treeOrgFunction_NodeClick
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Time Process: 1
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | BuildTreeNode
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Time Process: 3
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | Refresh
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_organize_business_ctrlhu_organization_ascx | ChangeToolbarState
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | UpdateControlState
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | FillDataByTree
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Time Process: 3
Path: Profile/Module/Profile/Setting/modules_organize_business_ctrlhu_organization_ascx | ViewLoad
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:38 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:29:39 CH 26 Tháng Mười 2017
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 4:31:23 PM Thursday, October 26, 2017
Time Process: 15
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 4:31:23 PM Thursday, October 26, 2017
Time Process: 16
Path: account_login_aspx | PageLoad
Datetime: 4:31:39 PM Thursday, October 26, 2017
Path: account_login_aspx | PageLoad
Datetime: 4:31:42 PM Thursday, October 26, 2017
Time Process: 3
Path: account_login_aspx | OnAuthenticate
Datetime: 4:31:42 PM Thursday, October 26, 2017
Path: account_login_aspx | LoggedIn
Datetime: 4:31:42 CH 26 Tháng Mười 2017
Path: default_aspx | OnInit
Datetime: 4:31:42 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 4:31:42 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 4:31:43 CH 26 Tháng Mười 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 4:31:43 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 4:31:43 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 4:31:45 CH 26 Tháng Mười 2017
Path: site_master | GetDataNotify
Datetime: 4:31:45 CH 26 Tháng Mười 2017
Time Process: 1
Path: site_master | LoadConfig
Datetime: 4:31:45 CH 26 Tháng Mười 2017
Time Process: 2
Path: site_master | Page_Load
Datetime: 4:31:45 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 4:31:45 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 4:31:45 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 4:31:45 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:31:46 CH 26 Tháng Mười 2017
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 4:35:21 PM Thursday, October 26, 2017
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 4:35:21 PM Thursday, October 26, 2017
Time Process: 163
Path: account_login_aspx | PageLoad
Datetime: 4:38:11 PM Thursday, October 26, 2017
Time Process: 33
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 4:38:11 PM Thursday, October 26, 2017
Time Process: 33
Path: account_login_aspx | PageLoad
Datetime: 4:38:19 PM Thursday, October 26, 2017
Path: account_login_aspx | PageLoad
Datetime: 4:38:32 PM Thursday, October 26, 2017
Time Process: 12
Path: account_login_aspx | OnAuthenticate
Datetime: 4:38:32 PM Thursday, October 26, 2017
Path: account_login_aspx | LoggedIn
Datetime: 4:38:32 CH 26 Tháng Mười 2017
Path: default_aspx | OnInit
Datetime: 4:38:33 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 4:38:33 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 4:38:33 CH 26 Tháng Mười 2017
Path: default_aspx | OnInit
Datetime: 4:38:33 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 4:38:33 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 4:39:28 CH 26 Tháng Mười 2017
Time Process: 54
Path: site_master | GetDataNotify
Datetime: 4:39:28 CH 26 Tháng Mười 2017
Time Process: 54
Path: site_master | LoadConfig
Datetime: 4:39:28 CH 26 Tháng Mười 2017
Time Process: 55
Path: site_master | Page_Load
Datetime: 4:39:28 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 4:39:28 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 4:39:28 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 4:39:28 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:39:29 CH 26 Tháng Mười 2017
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 4:56:28 PM Thursday, October 26, 2017
Time Process: 69
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 4:56:28 PM Thursday, October 26, 2017
Time Process: 69
Path: account_login_aspx | PageLoad
Datetime: 4:56:57 PM Thursday, October 26, 2017
Path: account_login_aspx | PageLoad
Datetime: 4:57:01 PM Thursday, October 26, 2017
Time Process: 3
Path: account_login_aspx | OnAuthenticate
Datetime: 4:57:01 PM Thursday, October 26, 2017
Path: account_login_aspx | LoggedIn
Datetime: 4:57:01 CH 26 Tháng Mười 2017
Path: default_aspx | OnInit
Datetime: 4:57:01 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 4:57:01 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 4:57:02 CH 26 Tháng Mười 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 4:57:02 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 4:57:02 CH 26 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Time Process: 20
Path: site_master | GetDataNotify
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Time Process: 20
Path: site_master | LoadConfig
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Time Process: 21
Path: site_master | Page_Load
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:24 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:25 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:25 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:25 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:25 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:25 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:25 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:25 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:25 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:57:25 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:25 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:25 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:25 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:25 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:57:25 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:25 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:25 CH 26 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 4:57:25 CH 26 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 4:57:25 CH 26 Tháng Mười 2017
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 8:46:43 PM Thursday, October 26, 2017
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 8:46:43 PM Thursday, October 26, 2017
Time Process: 222
Path: account_login_aspx | PageLoad
Datetime: 8:49:30 PM Thursday, October 26, 2017
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 8:49:30 PM Thursday, October 26, 2017
Time Process: 161
Path: account_login_aspx | PageLoad
Datetime: 8:50:50 PM Thursday, October 26, 2017
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 8:50:50 PM Thursday, October 26, 2017
Time Process: 131
Path: account_login_aspx | PageLoad
Datetime: 8:53:57 PM Thursday, October 26, 2017
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 8:53:57 PM Thursday, October 26, 2017
Time Process: 123
Path: account_login_aspx | PageLoad
Datetime: 8:58:11 PM Thursday, October 26, 2017
Time Process: 38
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 8:58:11 PM Thursday, October 26, 2017
Time Process: 38
Path: account_login_aspx | PageLoad
