Datetime: 11:01:14 AM Friday, October 27, 2017
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 11:01:14 AM Friday, October 27, 2017
Time Process: 647
Path: account_login_aspx | PageLoad
Datetime: 11:01:30 AM Friday, October 27, 2017
Time Process: 13
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 11:01:30 AM Friday, October 27, 2017
Time Process: 13
Path: account_login_aspx | PageLoad
Datetime: 11:01:40 AM Friday, October 27, 2017
Path: account_login_aspx | PageLoad
Datetime: 11:01:45 AM Friday, October 27, 2017
Time Process: 5
Path: account_login_aspx | OnAuthenticate
Datetime: 11:01:45 AM Friday, October 27, 2017
Path: account_login_aspx | LoggedIn
Datetime: 11:01:46 SA 27 Tháng Mười 2017
Path: default_aspx | OnInit
Datetime: 11:01:46 SA 27 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 11:01:46 SA 27 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 11:01:47 SA 27 Tháng Mười 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 11:01:47 SA 27 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 11:01:47 SA 27 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 11:02:02 SA 27 Tháng Mười 2017
Time Process: 12
Path: site_master | GetDataNotify
Datetime: 11:02:02 SA 27 Tháng Mười 2017
Time Process: 12
Path: site_master | LoadConfig
Datetime: 11:02:02 SA 27 Tháng Mười 2017
Time Process: 14
Path: site_master | Page_Load
Datetime: 11:02:02 SA 27 Tháng Mười 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Time Process: 1
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:03 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:04 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:04 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:04 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:04 SA 27 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 11:02:04 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:04 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:04 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:04 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:04 SA 27 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 11:02:04 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:04 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:04 SA 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 11:02:04 SA 27 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 11:02:04 SA 27 Tháng Mười 2017
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 1:27:14 PM Friday, October 27, 2017
Time Process: 9
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 1:27:14 PM Friday, October 27, 2017
Time Process: 9
Path: account_login_aspx | PageLoad
Datetime: 1:28:19 PM Friday, October 27, 2017
Time Process: 24
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 1:28:19 PM Friday, October 27, 2017
Time Process: 24
Path: account_login_aspx | PageLoad
Datetime: 1:28:32 PM Friday, October 27, 2017
Path: account_login_aspx | PageLoad
Datetime: 1:28:38 PM Friday, October 27, 2017
Time Process: 6
Path: account_login_aspx | OnAuthenticate
Datetime: 1:28:38 PM Friday, October 27, 2017
Path: account_login_aspx | LoggedIn
Datetime: 1:28:38 CH 27 Tháng Mười 2017
Path: default_aspx | OnInit
Datetime: 1:28:38 CH 27 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 1:28:38 CH 27 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 1:28:39 CH 27 Tháng Mười 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 1:28:40 CH 27 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 1:28:40 CH 27 Tháng Mười 2017
Path: default_aspx | PageLoad
Datetime: 1:28:45 CH 27 Tháng Mười 2017
Time Process: 4
Path: site_master | GetDataNotify
Datetime: 1:28:45 CH 27 Tháng Mười 2017
Time Process: 4
Path: site_master | LoadConfig
Datetime: 1:28:45 CH 27 Tháng Mười 2017
Time Process: 5
Path: site_master | Page_Load
Datetime: 1:28:45 CH 27 Tháng Mười 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 1:28:45 CH 27 Tháng Mười 2017
Time Process: 1
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 1:28:45 CH 27 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 1:28:45 CH 27 Tháng Mười 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | getChildElement
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Path: site_master | BuildMenu
Datetime: 1:28:46 CH 27 Tháng Mười 2017
Time Process: 1
Path: site_master | BuildMainMenu
