Datetime: 8:31:37 AM Wednesday, November 1, 2017
Path: account_login_aspx | PageLoad
Datetime: 8:31:39 AM Wednesday, November 1, 2017
Time Process: 2
Path: account_login_aspx | OnAuthenticate
Datetime: 8:31:39 AM Wednesday, November 1, 2017
Path: account_login_aspx | LoggedIn
Datetime: 8:31:39 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 8:31:39 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 8:31:40 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 8:31:41 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 8:31:41 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 8:31:41 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 8:31:43 SA 01 Tháng Mười Một 2017
Path: site_master | GetDataNotify
Datetime: 8:31:43 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | LoadConfig
Datetime: 8:31:43 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | Page_Load
Datetime: 8:31:43 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 8:31:44 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 8:31:44 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 8:31:44 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 8:31:44 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:46 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:31:46 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 8:31:46 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 8:34:19 SA 01 Tháng Mười Một 2017
Time Process: 3
Path: default_aspx | OnInit
Datetime: 8:34:19 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 8:34:19 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | ViewInit
Datetime: 8:34:19 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 8:34:20 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | GetDataNotify
Datetime: 8:34:20 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | LoadConfig
Datetime: 8:34:20 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | Page_Load
Datetime: 8:34:20 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ToolbarAuthorization
Datetime: 8:34:20 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | CheckAuthorization
Datetime: 8:34:20 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | Refresh
Datetime: 8:34:20 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ChangeToolbarState
Datetime: 8:34:20 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | UpdateControlState
Datetime: 8:34:20 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | ViewLoad
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 8:34:21 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 8:34:32 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 8:34:32 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | ViewInit
Datetime: 8:34:32 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 8:34:32 SA 01 Tháng Mười Một 2017
Path: site_master | GetDataNotify
Datetime: 8:34:32 SA 01 Tháng Mười Một 2017
Path: site_master | LoadConfig
Datetime: 8:34:32 SA 01 Tháng Mười Một 2017
Path: site_master | Page_Load
Datetime: 8:34:32 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ToolbarAuthorization
Datetime: 8:34:32 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | CheckAuthorization
Datetime: 8:34:32 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | Refresh
Datetime: 8:34:32 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ChangeToolbarState
Datetime: 8:34:32 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | UpdateControlState
Datetime: 8:34:32 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | ViewLoad
Datetime: 8:34:33 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 8:34:33 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 8:34:33 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | cvalCONTRACT_ServerValidate
Datetime: 8:34:33 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | cvalBIRTHDAY_ServerValidate
Datetime: 8:34:33 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | valnmVISA_ServerValidate
Datetime: 8:34:33 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ChangeToolbarState
Datetime: 8:34:33 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | UpdateControlState
Datetime: 8:34:33 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | OnToolbar_Command
Datetime: 8:34:33 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | OnMainToolbar_Click
Datetime: 8:36:42 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 8:36:42 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | ViewInit
Datetime: 8:36:42 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 8:36:43 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | GetDataNotify
Datetime: 8:36:43 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | LoadConfig
Datetime: 8:36:43 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | Page_Load
Datetime: 8:36:43 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ToolbarAuthorization
Datetime: 8:36:43 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | CheckAuthorization
Datetime: 8:36:43 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | Refresh
Datetime: 8:36:43 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ChangeToolbarState
Datetime: 8:36:43 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | UpdateControlState
Datetime: 8:36:43 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | ViewLoad
Datetime: 8:36:43 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 8:36:43 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 8:36:44 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | cvalCONTRACT_ServerValidate
Datetime: 8:36:44 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | cvalBIRTHDAY_ServerValidate
Datetime: 8:36:44 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | valnmVISA_ServerValidate
Datetime: 8:39:03 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ChangeToolbarState
Datetime: 8:39:03 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | UpdateControlState
Datetime: 8:39:04 SA 01 Tháng Mười Một 2017
Time Process: 137
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | OnToolbar_Command
Datetime: 8:39:04 SA 01 Tháng Mười Một 2017
Time Process: 140
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | OnMainToolbar_Click
Datetime: 8:39:12 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 8:39:12 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | ViewInit
Datetime: 8:39:12 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 8:39:12 SA 01 Tháng Mười Một 2017
Path: site_master | GetDataNotify
Datetime: 8:39:12 SA 01 Tháng Mười Một 2017
Path: site_master | LoadConfig
Datetime: 8:39:12 SA 01 Tháng Mười Một 2017
Path: site_master | Page_Load
Datetime: 8:39:12 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ToolbarAuthorization
Datetime: 8:39:12 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | CheckAuthorization
Datetime: 8:39:13 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | Refresh
Datetime: 8:39:13 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ChangeToolbarState
Datetime: 8:39:13 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | UpdateControlState
Datetime: 8:39:13 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | ViewLoad
Datetime: 8:39:13 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 8:39:13 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 8:39:13 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | cvalCONTRACT_ServerValidate
Datetime: 8:39:13 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | cvalBIRTHDAY_ServerValidate
Datetime: 8:39:13 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | valnmVISA_ServerValidate
Datetime: 8:46:35 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ChangeToolbarState
Datetime: 8:46:35 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | UpdateControlState
Datetime: 8:46:35 SA 01 Tháng Mười Một 2017
Time Process: 431
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | OnToolbar_Command
Datetime: 8:46:35 SA 01 Tháng Mười Một 2017
Time Process: 442
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | OnMainToolbar_Click
Datetime: 9:05:47 AM Wednesday, November 1, 2017
Time Process: 3
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 9:05:47 AM Wednesday, November 1, 2017
Time Process: 3
Path: account_login_aspx | PageLoad
Datetime: 9:06:18 AM Wednesday, November 1, 2017
Path: account_login_aspx | PageLoad
Datetime: 9:06:18 AM Wednesday, November 1, 2017
Path: account_login_aspx | OnAuthenticate
Datetime: 9:06:18 AM Wednesday, November 1, 2017
Path: account_login_aspx | LoggedIn
Datetime: 9:06:18 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 9:06:18 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 9:06:18 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 9:06:19 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 9:06:19 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 9:06:19 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | GetDataNotify
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Time Process: 345
Path: site_master | LoadConfig
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Time Process: 345
Path: site_master | Page_Load
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:12:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:05 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:12:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:12:05 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:12:05 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 9:12:21 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 9:12:21 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 9:12:21 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | ViewInit
Datetime: 9:12:21 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 9:15:14 SA 01 Tháng Mười Một 2017
Time Process: 166
Path: site_master | GetDataNotify
Datetime: 9:15:14 SA 01 Tháng Mười Một 2017
Time Process: 173
Path: site_master | LoadConfig
Datetime: 9:15:14 SA 01 Tháng Mười Một 2017
Time Process: 173
Path: site_master | Page_Load
Datetime: 9:15:14 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ToolbarAuthorization
Datetime: 9:15:14 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | CheckAuthorization
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | Refresh
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ChangeToolbarState
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | UpdateControlState
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | ViewLoad
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:16 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:16 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:16 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:15:16 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:16 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:16 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:15:16 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:15:16 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 9:20:16 AM Wednesday, November 1, 2017
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 9:20:16 AM Wednesday, November 1, 2017
Path: account_login_aspx | PageLoad
Datetime: 9:46:02 AM Wednesday, November 1, 2017
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 9:46:02 AM Wednesday, November 1, 2017
Path: account_login_aspx | PageLoad
Datetime: 9:58:15 AM Wednesday, November 1, 2017
Time Process: 11
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 9:58:15 AM Wednesday, November 1, 2017
Time Process: 11
Path: account_login_aspx | PageLoad
Datetime: 9:58:38 AM Wednesday, November 1, 2017
Path: account_login_aspx | PageLoad
Datetime: 9:58:38 AM Wednesday, November 1, 2017
Time Process: 1
Path: account_login_aspx | OnAuthenticate
Datetime: 9:58:38 AM Wednesday, November 1, 2017
Path: account_login_aspx | LoggedIn
Datetime: 9:58:38 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 9:58:39 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 9:58:39 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 9:58:40 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 9:58:40 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 9:58:40 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 9:58:46 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | GetDataNotify
Datetime: 9:58:46 SA 01 Tháng Mười Một 2017
Time Process: 6
Path: site_master | LoadConfig
Datetime: 9:58:46 SA 01 Tháng Mười Một 2017
Time Process: 6
Path: site_master | Page_Load
Datetime: 9:58:46 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 9:58:46 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 9:58:46 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 9:58:46 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:58:47 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 9:58:58 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 9:58:58 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 9:58:58 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlhu_welfarelist_ascx | ChangeToolbarState
Datetime: 9:58:58 SA 01 Tháng Mười Một 2017
Path: Profile/Module/Profile/List/modules_profile_setting_ctrlhu_welfarelist_ascx | UpdateToolbarState
Datetime: 9:58:58 SA 01 Tháng Mười Một 2017
Path: Profile/Module/Profile/List/modules_profile_setting_ctrlhu_welfarelist_ascx | UpdateControlState
Datetime: 9:58:58 SA 01 Tháng Mười Một 2017
Path: Profile/Module/Profile/List/modules_profile_setting_ctrlhu_welfarelist_ascx | Refresh
Datetime: 9:58:58 SA 01 Tháng Mười Một 2017
Path: Profile/Module/Profile/List/modules_profile_setting_ctrlhu_welfarelist_ascx | InitControl
Datetime: 9:58:58 SA 01 Tháng Mười Một 2017
Path: Profile/Module/Profile/List/modules_profile_setting_ctrlhu_welfarelist_ascx | ViewInit
Datetime: 9:58:58 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 9:59:04 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | GetDataNotify
Datetime: 9:59:04 SA 01 Tháng Mười Một 2017
Time Process: 6
Path: site_master | LoadConfig
Datetime: 9:59:04 SA 01 Tháng Mười Một 2017
Time Process: 6
Path: site_master | Page_Load
Datetime: 9:59:04 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlhu_welfarelist_ascx | ToolbarAuthorization
Datetime: 9:59:04 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlhu_welfarelist_ascx | CheckAuthorization
Datetime: 9:59:04 SA 01 Tháng Mười Một 2017
Path: Profile/Module/Profile/List/modules_profile_setting_ctrlhu_welfarelist_ascx | GetDataCombo
Datetime: 9:59:04 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: Profile/Module/Profile/List/modules_profile_setting_ctrlhu_welfarelist_ascx | BindData
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: Profile/Module/Profile/List/modules_profile_setting_ctrlhu_welfarelist_ascx | CreateDataFilter
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: Profile/Module/Profile/List/modules_profile_setting_ctrlhu_welfarelist_ascx | RadGrid_NeedDataSource
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:06 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:59:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:06 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:59:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:06 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:59:06 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 9:59:17 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 9:59:17 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 9:59:17 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 9:59:17 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | GetDataNotify
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Time Process: 4
Path: site_master | LoadConfig
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Time Process: 4
Path: site_master | Page_Load
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:22 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:22 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:59:22 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:22 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:22 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:22 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:22 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:59:22 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:22 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:22 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 9:59:22 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 9:59:22 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 10:48:45 AM Wednesday, November 1, 2017
Time Process: 5
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 10:48:45 AM Wednesday, November 1, 2017
Time Process: 5
Path: account_login_aspx | PageLoad
Datetime: 10:48:53 AM Wednesday, November 1, 2017
Path: account_login_aspx | PageLoad
Datetime: 10:48:56 AM Wednesday, November 1, 2017
Time Process: 3
Path: account_login_aspx | OnAuthenticate
Datetime: 10:48:56 AM Wednesday, November 1, 2017
Path: account_login_aspx | LoggedIn
Datetime: 10:48:56 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 10:48:56 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:48:56 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:48:57 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 10:48:57 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:48:57 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | GetDataNotify
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Time Process: 7
Path: site_master | LoadConfig
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Time Process: 8
Path: site_master | Page_Load
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:06 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:49:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:06 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:49:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:06 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:49:06 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 10:49:12 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 10:49:12 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 10:49:12 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:49:12 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:49:43 SA 01 Tháng Mười Một 2017
Time Process: 28
Path: site_master | GetDataNotify
Datetime: 10:49:45 SA 01 Tháng Mười Một 2017
Time Process: 32
Path: site_master | LoadConfig
Datetime: 10:49:48 SA 01 Tháng Mười Một 2017
Time Process: 35
Path: site_master | Page_Load
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:51 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:49:52 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:52 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:52 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:49:52 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:49:52 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 10:51:10 AM Wednesday, November 1, 2017
Time Process: 4
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 10:51:10 AM Wednesday, November 1, 2017
Time Process: 4
Path: account_login_aspx | PageLoad
Datetime: 10:51:16 AM Wednesday, November 1, 2017
Path: account_login_aspx | PageLoad
Datetime: 10:51:16 AM Wednesday, November 1, 2017
Path: account_login_aspx | OnAuthenticate
Datetime: 10:51:16 AM Wednesday, November 1, 2017
Path: account_login_aspx | LoggedIn
Datetime: 10:51:16 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 10:51:16 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:51:17 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:51:18 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 10:51:18 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:51:18 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:51:23 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | GetDataNotify
Datetime: 10:51:24 SA 01 Tháng Mười Một 2017
Time Process: 4
Path: site_master | LoadConfig
Datetime: 10:51:24 SA 01 Tháng Mười Một 2017
Time Process: 5
Path: site_master | Page_Load
Datetime: 10:51:24 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 10:51:24 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 10:51:24 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 10:51:25 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 10:51:25 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:25 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:51:25 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:26 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:51:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:27 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:51:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:28 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:28 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 10:51:28 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:28 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:28 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:29 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:29 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 10:51:29 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:29 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:29 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:30 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:30 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:51:30 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:30 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:30 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:31 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:51:31 SA 01 Tháng Mười Một 2017
Time Process: 6
Path: site_master | BuildMainMenu
Datetime: 10:51:39 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 10:51:39 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:51:39 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | ViewInit
Datetime: 10:51:39 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:51:43 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | GetDataNotify
Datetime: 10:51:44 SA 01 Tháng Mười Một 2017
Time Process: 4
Path: site_master | LoadConfig
Datetime: 10:51:44 SA 01 Tháng Mười Một 2017
Time Process: 4
Path: site_master | Page_Load
Datetime: 10:51:44 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ToolbarAuthorization
Datetime: 10:51:44 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | CheckAuthorization
Datetime: 10:51:44 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | Refresh
Datetime: 10:51:45 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ChangeToolbarState
Datetime: 10:51:45 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | UpdateControlState
Datetime: 10:51:45 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | ViewLoad
Datetime: 10:51:45 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 10:51:45 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 10:51:46 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:46 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:51:46 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:46 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:46 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:47 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:51:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:48 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:48 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:51:48 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:48 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:48 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:49 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:49 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 10:51:49 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:49 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:49 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:50 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:50 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 10:51:50 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:50 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:50 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:51 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:51:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:51:52 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:51:52 SA 01 Tháng Mười Một 2017
Time Process: 6
Path: site_master | BuildMainMenu
Datetime: 10:53:22 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 10:53:22 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:53:22 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | ViewInit
Datetime: 10:53:22 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:53:24 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | GetDataNotify
Datetime: 10:53:24 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | LoadConfig
Datetime: 10:53:24 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | Page_Load
Datetime: 10:53:24 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ToolbarAuthorization
Datetime: 10:53:24 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | CheckAuthorization
Datetime: 10:53:25 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | Refresh
Datetime: 10:53:25 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | ViewLoad
Datetime: 10:53:25 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 10:53:25 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 10:53:25 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:26 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:53:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:27 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:53:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:27 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:53:28 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:28 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:28 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:28 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:28 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 10:53:28 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:29 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:29 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:29 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:29 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:53:29 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:30 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:30 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:30 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:30 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:53:30 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:30 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:31 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:53:31 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:53:31 SA 01 Tháng Mười Một 2017
Time Process: 6
Path: site_master | BuildMainMenu
Datetime: 10:58:04 AM Wednesday, November 1, 2017
Time Process: 8
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 10:58:04 AM Wednesday, November 1, 2017
Time Process: 8
Path: account_login_aspx | PageLoad
Datetime: 10:58:12 AM Wednesday, November 1, 2017
Path: account_login_aspx | PageLoad
Datetime: 10:58:12 AM Wednesday, November 1, 2017
Time Process: 1
Path: account_login_aspx | OnAuthenticate
Datetime: 10:58:13 AM Wednesday, November 1, 2017
Path: account_login_aspx | LoggedIn
Datetime: 10:58:13 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 10:58:13 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:58:14 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:58:15 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 10:58:15 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:58:15 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:58:21 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | GetDataNotify
Datetime: 10:58:21 SA 01 Tháng Mười Một 2017
Time Process: 5
Path: site_master | LoadConfig
Datetime: 10:58:22 SA 01 Tháng Mười Một 2017
Time Process: 6
Path: site_master | Page_Load
Datetime: 10:58:22 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 10:58:23 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 10:58:23 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 10:58:23 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 10:58:23 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:24 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:58:24 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:24 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:24 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:24 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:25 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:25 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:58:25 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:25 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:26 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:58:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:27 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 10:58:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:28 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:28 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:28 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 10:58:28 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:28 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:29 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:29 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:29 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:58:29 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:30 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:30 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:30 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:58:30 SA 01 Tháng Mười Một 2017
Time Process: 7
Path: site_master | BuildMainMenu
Datetime: 10:58:37 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 10:58:37 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:58:38 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlhu_welfarelist_ascx | ChangeToolbarState
Datetime: 10:58:38 SA 01 Tháng Mười Một 2017
Path: Profile/Module/Profile/List/modules_profile_setting_ctrlhu_welfarelist_ascx | UpdateToolbarState
Datetime: 10:58:38 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: Profile/Module/Profile/List/modules_profile_setting_ctrlhu_welfarelist_ascx | UpdateControlState
Datetime: 10:58:39 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: Profile/Module/Profile/List/modules_profile_setting_ctrlhu_welfarelist_ascx | Refresh
Datetime: 10:58:39 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: Profile/Module/Profile/List/modules_profile_setting_ctrlhu_welfarelist_ascx | InitControl
Datetime: 10:58:39 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: Profile/Module/Profile/List/modules_profile_setting_ctrlhu_welfarelist_ascx | ViewInit
Datetime: 10:58:39 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: default_aspx | PageLoad
Datetime: 10:58:43 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | GetDataNotify
Datetime: 10:58:44 SA 01 Tháng Mười Một 2017
Time Process: 4
Path: site_master | LoadConfig
Datetime: 10:58:44 SA 01 Tháng Mười Một 2017
Time Process: 4
Path: site_master | Page_Load
Datetime: 10:58:44 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlhu_welfarelist_ascx | ToolbarAuthorization
Datetime: 10:58:44 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlhu_welfarelist_ascx | CheckAuthorization
Datetime: 10:58:45 SA 01 Tháng Mười Một 2017
Path: Profile/Module/Profile/List/modules_profile_setting_ctrlhu_welfarelist_ascx | GetDataCombo
Datetime: 10:58:45 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: Profile/Module/Profile/List/modules_profile_setting_ctrlhu_welfarelist_ascx | BindData
Datetime: 10:58:46 SA 01 Tháng Mười Một 2017
Path: Profile/Module/Profile/List/modules_profile_setting_ctrlhu_welfarelist_ascx | CreateDataFilter
Datetime: 10:58:46 SA 01 Tháng Mười Một 2017
Path: Profile/Module/Profile/List/modules_profile_setting_ctrlhu_welfarelist_ascx | RadGrid_NeedDataSource
Datetime: 10:58:46 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:58:46 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:58:47 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 10:58:47 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 10:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:47 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:58:48 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:48 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:48 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:48 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:48 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:49 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:58:49 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:49 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:49 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:50 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:58:50 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:50 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:50 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:50 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:51 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 10:58:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:52 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:52 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 10:58:52 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:52 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:52 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:53 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:53 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:58:53 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:53 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:54 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:58:54 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:58:54 SA 01 Tháng Mười Một 2017
Time Process: 7
Path: site_master | BuildMainMenu
Datetime: 10:59:02 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 10:59:03 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 10:59:03 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:59:03 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:59:07 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | GetDataNotify
Datetime: 10:59:07 SA 01 Tháng Mười Một 2017
Time Process: 3
Path: site_master | LoadConfig
Datetime: 10:59:07 SA 01 Tháng Mười Một 2017
Time Process: 4
Path: site_master | Page_Load
Datetime: 10:59:07 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 10:59:07 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 10:59:08 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:08 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:59:08 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:08 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:09 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:09 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:09 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:09 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:59:09 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:10 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:10 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:10 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:59:10 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:11 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:11 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:11 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:11 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 10:59:12 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:12 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:12 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:12 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:12 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 10:59:13 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:13 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:13 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:13 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:13 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:59:14 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:14 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:14 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:59:14 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 10:59:15 SA 01 Tháng Mười Một 2017
Time Process: 7
Path: site_master | BuildMainMenu
Datetime: 11:00:52 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 11:00:53 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:00:53 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | ViewInit
Datetime: 11:00:53 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | PageLoad
Datetime: 11:00:55 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | GetDataNotify
Datetime: 11:00:55 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | LoadConfig
Datetime: 11:00:55 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | Page_Load
Datetime: 11:00:55 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ToolbarAuthorization
Datetime: 11:00:55 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | CheckAuthorization
Datetime: 11:00:56 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | Refresh
Datetime: 11:00:56 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ChangeToolbarState
Datetime: 11:00:56 SA 01 Tháng Mười Một 2017
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | UpdateControlState
Datetime: 11:00:56 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | ViewLoad
Datetime: 11:00:57 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 11:00:57 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 11:00:57 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:00:57 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 11:00:58 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:00:58 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:00:58 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:00:58 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:00:58 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:00:59 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:00:59 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:00:59 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:00:59 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:01:00 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:01:00 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:01:00 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:01:00 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:01:01 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:01:01 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 11:01:01 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:01:01 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:01:01 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:01:02 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:01:02 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 11:01:02 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:01:02 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:01:02 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:01:03 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:01:03 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:01:03 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:01:03 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:01:03 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:01:04 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:01:04 SA 01 Tháng Mười Một 2017
Time Process: 7
Path: site_master | BuildMainMenu
Datetime: 11:19:09 AM Wednesday, November 1, 2017
Time Process: 4
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 11:19:09 AM Wednesday, November 1, 2017
Time Process: 4
Path: account_login_aspx | PageLoad
Datetime: 11:19:18 AM Wednesday, November 1, 2017
Path: account_login_aspx | PageLoad
Datetime: 11:19:21 AM Wednesday, November 1, 2017
Time Process: 3
Path: account_login_aspx | OnAuthenticate
Datetime: 11:19:21 AM Wednesday, November 1, 2017
Path: account_login_aspx | LoggedIn
Datetime: 11:19:21 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 11:19:21 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:19:22 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:19:23 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 11:19:23 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:19:23 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:19:28 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | GetDataNotify
Datetime: 11:19:28 SA 01 Tháng Mười Một 2017
Time Process: 4
Path: site_master | LoadConfig
Datetime: 11:19:28 SA 01 Tháng Mười Một 2017
Time Process: 5
Path: site_master | Page_Load
Datetime: 11:19:28 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 11:19:29 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 11:19:29 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 11:19:29 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 11:19:30 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:30 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 11:19:30 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:30 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:31 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:31 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:31 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:31 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:19:31 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:32 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:32 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:32 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:19:32 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:33 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:33 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:33 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:33 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 11:19:33 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:34 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:34 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:34 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:34 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 11:19:35 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:35 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:35 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:35 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:35 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:19:36 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:36 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:36 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:36 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:19:37 SA 01 Tháng Mười Một 2017
Time Process: 7
Path: site_master | BuildMainMenu
Datetime: 11:19:43 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 11:19:43 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 11:19:43 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:19:44 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:19:46 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | GetDataNotify
Datetime: 11:19:46 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | LoadConfig
Datetime: 11:19:46 SA 01 Tháng Mười Một 2017
Time Process: 3
Path: site_master | Page_Load
Datetime: 11:19:47 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 11:19:47 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 11:19:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:47 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 11:19:48 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:48 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:48 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:48 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:48 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:49 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:19:49 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:49 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:49 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:50 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:19:50 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:50 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:50 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:50 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:51 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 11:19:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:51 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:52 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:52 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 11:19:52 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:52 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:52 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:53 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:53 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:19:53 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:53 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:54 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:19:54 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:19:54 SA 01 Tháng Mười Một 2017
Time Process: 7
Path: site_master | BuildMainMenu
Datetime: 11:24:41 AM Wednesday, November 1, 2017
Time Process: 4
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 11:24:41 AM Wednesday, November 1, 2017
Time Process: 4
Path: account_login_aspx | PageLoad
Datetime: 11:24:56 AM Wednesday, November 1, 2017
Path: account_login_aspx | PageLoad
Datetime: 11:24:57 AM Wednesday, November 1, 2017
Path: account_login_aspx | OnAuthenticate
Datetime: 11:24:57 AM Wednesday, November 1, 2017
Path: account_login_aspx | LoggedIn
Datetime: 11:24:57 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 11:24:58 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:24:58 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:24:59 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 11:24:59 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:25:00 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:25:04 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | GetDataNotify
Datetime: 11:25:04 SA 01 Tháng Mười Một 2017
Time Process: 4
Path: site_master | LoadConfig
Datetime: 11:25:05 SA 01 Tháng Mười Một 2017
Time Process: 5
Path: site_master | Page_Load
Datetime: 11:25:05 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 11:25:05 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 11:25:05 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 11:25:06 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 11:25:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:06 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 11:25:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:07 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:07 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:07 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:07 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:07 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:25:08 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:08 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:08 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:08 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:25:09 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:09 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:09 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:09 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:09 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 11:25:10 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:10 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:10 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:10 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:11 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 11:25:11 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:11 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:11 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:12 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:12 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:25:12 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:12 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:13 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:13 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:25:13 SA 01 Tháng Mười Một 2017
Time Process: 7
Path: site_master | BuildMainMenu
Datetime: 11:25:21 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 11:25:21 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 11:25:21 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:25:21 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:25:34 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | GetDataNotify
Datetime: 11:25:34 SA 01 Tháng Mười Một 2017
Time Process: 12
Path: site_master | LoadConfig
Datetime: 11:25:34 SA 01 Tháng Mười Một 2017
Time Process: 13
Path: site_master | Page_Load
Datetime: 11:25:34 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 11:25:35 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 11:25:35 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:35 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 11:25:36 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:36 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:36 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:36 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:37 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:37 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:25:37 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:37 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:38 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:38 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:25:38 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:38 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:39 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:39 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:39 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 11:25:39 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:39 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:40 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:40 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:40 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 11:25:40 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:40 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:41 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:41 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:41 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:25:41 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:42 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:42 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:25:42 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:25:42 SA 01 Tháng Mười Một 2017
Time Process: 7
Path: site_master | BuildMainMenu
Datetime: 11:28:18 AM Wednesday, November 1, 2017
Time Process: 4
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 11:28:18 AM Wednesday, November 1, 2017
Time Process: 5
Path: account_login_aspx | PageLoad
Datetime: 11:28:24 AM Wednesday, November 1, 2017
Path: account_login_aspx | PageLoad
Datetime: 11:28:26 AM Wednesday, November 1, 2017
Time Process: 3
Path: account_login_aspx | OnAuthenticate
Datetime: 11:28:27 AM Wednesday, November 1, 2017
Path: account_login_aspx | LoggedIn
Datetime: 11:28:27 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 11:28:27 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:28:28 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:28:28 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 11:28:29 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:28:29 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:28:37 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | GetDataNotify
Datetime: 11:28:37 SA 01 Tháng Mười Một 2017
Time Process: 7
Path: site_master | LoadConfig
Datetime: 11:28:37 SA 01 Tháng Mười Một 2017
Time Process: 8
Path: site_master | Page_Load
Datetime: 11:28:37 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 11:28:38 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 11:28:38 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 11:28:38 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 11:28:39 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:39 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 11:28:39 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:39 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:39 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:40 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:40 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:40 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:28:40 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:41 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:41 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:41 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:28:41 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:41 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:42 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:42 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:42 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 11:28:42 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:43 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:43 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:43 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:43 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 11:28:43 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:44 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:44 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:44 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:44 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:28:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:28:45 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:28:45 SA 01 Tháng Mười Một 2017
Time Process: 7
Path: site_master | BuildMainMenu
Datetime: 11:28:52 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 11:28:53 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 11:28:53 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:28:53 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:28:59 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | GetDataNotify
Datetime: 11:28:59 SA 01 Tháng Mười Một 2017
Time Process: 6
Path: site_master | LoadConfig
Datetime: 11:28:59 SA 01 Tháng Mười Một 2017
Time Process: 6
Path: site_master | Page_Load
Datetime: 11:29:00 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 11:29:00 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 11:29:00 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:00 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 11:29:01 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:01 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:01 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:01 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:01 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:02 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:29:02 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:02 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:02 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:02 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:29:03 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:03 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:03 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:03 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:04 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 11:29:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:05 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 11:29:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:06 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:29:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:29:07 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:29:07 SA 01 Tháng Mười Một 2017
Time Process: 7
Path: site_master | BuildMainMenu
Datetime: 11:31:11 AM Wednesday, November 1, 2017
Time Process: 4
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 11:31:11 AM Wednesday, November 1, 2017
Time Process: 4
Path: account_login_aspx | PageLoad
Datetime: 11:31:18 AM Wednesday, November 1, 2017
Path: account_login_aspx | PageLoad
Datetime: 11:31:21 AM Wednesday, November 1, 2017
Time Process: 2
Path: account_login_aspx | OnAuthenticate
Datetime: 11:31:21 AM Wednesday, November 1, 2017
Path: account_login_aspx | LoggedIn
Datetime: 11:31:21 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 11:31:22 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:31:22 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:31:23 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 11:31:23 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:31:24 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:31:25 SA 01 Tháng Mười Một 2017
Path: site_master | LoadConfig
Datetime: 11:31:25 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | Page_Load
Datetime: 11:31:25 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 11:31:25 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 11:31:26 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 11:31:26 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 11:31:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:26 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 11:31:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:28 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:31:28 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:28 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:28 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:28 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:31:29 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:29 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:29 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:29 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:30 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 11:31:30 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:30 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:30 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:30 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:31 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 11:31:31 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:31 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:31 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:32 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:32 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:31:32 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:32 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:32 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:33 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:31:33 SA 01 Tháng Mười Một 2017
Time Process: 7
Path: site_master | BuildMainMenu
Datetime: 11:31:38 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 11:31:38 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 11:31:39 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:31:39 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:31:39 SA 01 Tháng Mười Một 2017
Path: site_master | LoadConfig
Datetime: 11:31:39 SA 01 Tháng Mười Một 2017
Path: site_master | Page_Load
Datetime: 11:31:40 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 11:31:40 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 11:31:40 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:40 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 11:31:40 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:41 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:41 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:41 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:41 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:42 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:31:42 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:42 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:42 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:43 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:31:43 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:43 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:43 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:43 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:44 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 11:31:44 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:44 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:44 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:45 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 11:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:46 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:46 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:31:46 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:46 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:31:47 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:31:47 SA 01 Tháng Mười Một 2017
Time Process: 7
Path: site_master | BuildMainMenu
Datetime: 11:32:55 AM Wednesday, November 1, 2017
Time Process: 3
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 11:32:55 AM Wednesday, November 1, 2017
Time Process: 3
Path: account_login_aspx | PageLoad
Datetime: 11:33:22 AM Wednesday, November 1, 2017
Time Process: 4
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 11:33:22 AM Wednesday, November 1, 2017
Time Process: 4
Path: account_login_aspx | PageLoad
Datetime: 11:33:29 AM Wednesday, November 1, 2017
Path: account_login_aspx | PageLoad
Datetime: 11:33:32 AM Wednesday, November 1, 2017
Time Process: 2
Path: account_login_aspx | OnAuthenticate
Datetime: 11:33:32 AM Wednesday, November 1, 2017
Path: account_login_aspx | LoggedIn
Datetime: 11:33:32 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 11:33:33 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:33:33 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:33:34 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 11:33:34 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:33:35 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:33:42 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | GetDataNotify
Datetime: 11:33:42 SA 01 Tháng Mười Một 2017
Time Process: 7
Path: site_master | LoadConfig
Datetime: 11:33:43 SA 01 Tháng Mười Một 2017
Time Process: 8
Path: site_master | Page_Load
Datetime: 11:33:43 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 11:33:43 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 11:33:43 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 11:33:44 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 11:33:44 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:44 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 11:33:44 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:45 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:46 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:33:46 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:46 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:46 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:46 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:33:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:47 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:47 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 11:33:48 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:48 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:48 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:48 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:49 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 11:33:49 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:49 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:49 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:49 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:50 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:33:50 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:50 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:50 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:33:51 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:33:51 SA 01 Tháng Mười Một 2017
Time Process: 7
Path: site_master | BuildMainMenu
Datetime: 11:34:01 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 11:34:02 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 11:34:02 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:34:02 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:34:42 SA 01 Tháng Mười Một 2017
Time Process: 38
Path: site_master | GetDataNotify
Datetime: 11:34:45 SA 01 Tháng Mười Một 2017
Time Process: 42
Path: site_master | LoadConfig
Datetime: 11:34:49 SA 01 Tháng Mười Một 2017
Time Process: 47
Path: site_master | Page_Load
Datetime: 11:34:52 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 11:34:52 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 11:35:03 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:04 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 11:35:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:04 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:05 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:35:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:06 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:35:06 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:07 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:07 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:07 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:07 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 11:35:08 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:08 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:08 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:09 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:09 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 11:35:09 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:09 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:10 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:10 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:10 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:35:11 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:11 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:11 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:35:11 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:35:12 SA 01 Tháng Mười Một 2017
Time Process: 9
Path: site_master | BuildMainMenu
Datetime: 11:35:30 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 11:35:30 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 11:35:30 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:35:30 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:36:03 SA 01 Tháng Mười Một 2017
Time Process: 31
Path: site_master | GetDataNotify
Datetime: 11:36:04 SA 01 Tháng Mười Một 2017
Time Process: 34
Path: site_master | LoadConfig
Datetime: 11:36:06 SA 01 Tháng Mười Một 2017
Time Process: 35
Path: site_master | Page_Load
Datetime: 11:36:09 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 11:36:09 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 11:37:05 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:05 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 11:37:12 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:13 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:13 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:13 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:13 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:14 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:37:14 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:14 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:14 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:15 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:37:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:15 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:16 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:16 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 11:37:16 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:16 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:17 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:17 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:17 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 11:37:17 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:17 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:18 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:18 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:18 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:37:18 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:19 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:19 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:37:19 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:37:23 SA 01 Tháng Mười Một 2017
Time Process: 57
Path: site_master | BuildMainMenu
Datetime: 11:37:56 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 11:37:56 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 11:37:56 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:37:56 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:38:00 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | GetDataNotify
Datetime: 11:38:00 SA 01 Tháng Mười Một 2017
Time Process: 4
Path: site_master | LoadConfig
Datetime: 11:38:00 SA 01 Tháng Mười Một 2017
Time Process: 4
Path: site_master | Page_Load
Datetime: 11:38:00 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 11:38:01 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 11:38:08 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:08 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 11:38:16 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:17 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:17 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:17 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:17 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:17 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:38:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:22 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:22 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:22 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:38:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:27 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 11:38:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:27 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:28 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:28 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 11:38:32 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:32 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:32 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:33 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:33 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:38:36 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:36 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:36 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:38:36 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:38:47 SA 01 Tháng Mười Một 2017
Time Process: 44
Path: site_master | BuildMainMenu
Datetime: 11:39:42 SA 01 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 11:39:43 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 11:39:43 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:39:43 SA 01 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 11:40:19 SA 01 Tháng Mười Một 2017
Time Process: 34
Path: site_master | GetDataNotify
Datetime: 11:40:19 SA 01 Tháng Mười Một 2017
Time Process: 36
Path: site_master | LoadConfig
Datetime: 11:40:19 SA 01 Tháng Mười Một 2017
Time Process: 36
Path: site_master | Page_Load
Datetime: 11:40:20 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 11:40:20 SA 01 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 11:40:20 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:20 SA 01 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 11:40:20 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:21 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:21 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:40:22 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:22 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:22 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:22 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:40:22 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:23 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:23 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:23 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:23 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | getChildElement
Datetime: 11:40:23 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:24 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:24 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:24 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:24 SA 01 Tháng Mười Một 2017
Time Process: 2
Path: site_master | BuildMenu
Datetime: 11:40:24 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:25 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:25 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:25 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:25 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:40:25 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:26 SA 01 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 11:40:26 SA 01 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMenu
Datetime: 11:40:26 SA 01 Tháng Mười Một 2017
Time Process: 6
Path: site_master | BuildMainMenu
Datetime: 12:10:30 PM Wednesday, November 1, 2017
Time Process: 1
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 12:10:30 PM Wednesday, November 1, 2017
Time Process: 1
Path: account_login_aspx | PageLoad
Datetime: 1:32:41 PM Wednesday, November 1, 2017
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 1:32:41 PM Wednesday, November 1, 2017
Time Process: 292
Path: account_login_aspx | PageLoad
Datetime: 1:34:54 PM Wednesday, November 1, 2017
Time Process: 4
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 1:34:55 PM Wednesday, November 1, 2017
Time Process: 5
Path: account_login_aspx | PageLoad
