Datetime: 10:07:44 AM Wednesday, November 15, 2017
Path: account_login_aspx | PageLoad
Datetime: 10:07:47 AM Wednesday, November 15, 2017
Time Process: 3
Path: account_login_aspx | OnAuthenticate
Datetime: 10:07:47 AM Wednesday, November 15, 2017
Path: account_login_aspx | LoggedIn
Datetime: 10:07:47 SA 15 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 10:07:48 SA 15 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:07:48 SA 15 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:07:49 SA 15 Tháng Mười Một 2017
Time Process: 1
Path: default_aspx | OnInit
Datetime: 10:07:49 SA 15 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:07:49 SA 15 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:07:59 SA 15 Tháng Mười Một 2017
Path: site_master | GetDataNotify
Datetime: 10:07:59 SA 15 Tháng Mười Một 2017
Time Process: 9
Path: site_master | LoadConfig
Datetime: 10:07:59 SA 15 Tháng Mười Một 2017
Time Process: 10
Path: site_master | Page_Load
Datetime: 10:07:59 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:00 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:01 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:01 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:01 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:01 SA 15 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:08:01 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:01 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:01 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:01 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:01 SA 15 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:08:01 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:01 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:01 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:08:01 SA 15 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:08:01 SA 15 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 10:18:22 SA 15 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 10:18:22 SA 15 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:18:22 SA 15 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:18:22 SA 15 Tháng Mười Một 2017
Path: default_aspx | OnInit
Datetime: 10:18:22 SA 15 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:18:22 SA 15 Tháng Mười Một 2017
Path: default_aspx | PageLoad
Datetime: 10:18:23 SA 15 Tháng Mười Một 2017
Time Process: 1
Path: site_master | GetDataNotify
Datetime: 10:18:23 SA 15 Tháng Mười Một 2017
Time Process: 1
Path: site_master | LoadConfig
Datetime: 10:18:23 SA 15 Tháng Mười Một 2017
Time Process: 1
Path: site_master | Page_Load
Datetime: 10:18:23 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 10:18:23 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 10:18:23 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 10:18:23 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 10:18:23 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:23 SA 15 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:18:23 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:23 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:23 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:23 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:23 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:23 SA 15 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | getChildElement
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Path: site_master | BuildMenu
Datetime: 10:18:24 SA 15 Tháng Mười Một 2017
Time Process: 1
Path: site_master | BuildMainMenu
