Datetime: 8:57:01 AM Friday, April 6, 2018
Path: account_login_aspx | PageLoad
Datetime: 8:57:01 AM Friday, April 6, 2018
Time Process: 1
Path: account_login_aspx | OnAuthenticate
Datetime: 8:57:02 AM Friday, April 6, 2018
Path: account_login_aspx | LoggedIn
Datetime: 8:57:02 SA 06 Tháng Tư 2018
Path: default_aspx | OnInit
Datetime: 8:57:02 SA 06 Tháng Tư 2018
Path: default_aspx | PageLoad
Datetime: 8:57:03 SA 06 Tháng Tư 2018
Path: default_aspx | PageLoad
Datetime: 8:57:04 SA 06 Tháng Tư 2018
Time Process: 2
Path: default_aspx | OnInit
Datetime: 8:57:05 SA 06 Tháng Tư 2018
Path: default_aspx | PageLoad
Datetime: 8:57:05 SA 06 Tháng Tư 2018
Path: default_aspx | PageLoad
Datetime: 8:57:06 SA 06 Tháng Tư 2018
Time Process: 1
Path: site_master | GetDataNotify
Datetime: 8:57:07 SA 06 Tháng Tư 2018
Time Process: 1
Path: site_master | LoadConfig
Datetime: 8:57:07 SA 06 Tháng Tư 2018
Time Process: 2
Path: site_master | Page_Load
Datetime: 8:57:07 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | ToolbarAuthorization
Datetime: 8:57:07 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_ctrlinformation_ascx | CheckAuthorization
Datetime: 8:57:07 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 8:57:07 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 8:57:07 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:07 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:57:07 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:07 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:07 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:07 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:07 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:08 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:57:08 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:08 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:08 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:08 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:08 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:08 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:57:08 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:08 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:08 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:08 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:08 SA 06 Tháng Tư 2018
Time Process: 1
Path: site_master | BuildMenu
Datetime: 8:57:08 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:08 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:08 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:09 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:09 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:57:09 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:09 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:09 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:09 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:57:09 SA 06 Tháng Tư 2018
Time Process: 2
Path: site_master | BuildMainMenu
Datetime: 8:57:34 SA 06 Tháng Tư 2018
Time Process: 2
Path: default_aspx | OnInit
Datetime: 8:57:34 SA 06 Tháng Tư 2018
Path: default_aspx | PageLoad
Datetime: 8:57:34 SA 06 Tháng Tư 2018
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | ViewInit
Datetime: 8:57:34 SA 06 Tháng Tư 2018
Path: default_aspx | PageLoad
Datetime: 8:57:34 SA 06 Tháng Tư 2018
Path: site_master | GetDataNotify
Datetime: 8:57:34 SA 06 Tháng Tư 2018
Path: site_master | LoadConfig
Datetime: 8:57:34 SA 06 Tháng Tư 2018
Path: site_master | Page_Load
Datetime: 8:57:34 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ToolbarAuthorization
Datetime: 8:57:34 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | CheckAuthorization
Datetime: 8:57:34 SA 06 Tháng Tư 2018
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | Refresh
Datetime: 8:57:34 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_setting_ctrlremindconfig_ascx | ChangeToolbarState
Datetime: 8:57:34 SA 06 Tháng Tư 2018
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | UpdateControlState
Datetime: 8:57:34 SA 06 Tháng Tư 2018
Path: Profile/Modules/Profile/Setting/modules_profile_setting_ctrlremindconfig_ascx | ViewLoad
Datetime: 8:57:34 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 8:57:34 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:35 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:36 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:57:36 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:36 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:36 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:57:36 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:57:36 SA 06 Tháng Tư 2018
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 8:58:41 SA 06 Tháng Tư 2018
Time Process: 24
Path: default_aspx | OnInit
Datetime: 8:58:41 SA 06 Tháng Tư 2018
Path: default_aspx | PageLoad
Datetime: 8:58:41 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | InitControl
Datetime: 8:58:41 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | ViewInit
Datetime: 8:58:41 SA 06 Tháng Tư 2018
Path: default_aspx | PageLoad
Datetime: 8:58:41 SA 06 Tháng Tư 2018
Path: site_master | GetDataNotify
Datetime: 8:58:41 SA 06 Tháng Tư 2018
Path: site_master | LoadConfig
Datetime: 8:58:41 SA 06 Tháng Tư 2018
Path: site_master | Page_Load
Datetime: 8:58:41 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_employeemng_ascx | ToolbarAuthorization
Datetime: 8:58:41 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_employeemng_ascx | CheckAuthorization
Datetime: 8:58:42 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | GetDataCombo
Datetime: 8:58:42 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | Refresh
Datetime: 8:58:42 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | ViewLoad
Datetime: 8:58:42 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:58:42 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:58:42 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlorganization_ascx | ToolbarAuthorization
Datetime: 8:58:42 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlorganization_ascx | CheckAuthorization
Datetime: 8:58:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:58:47 SA 06 Tháng Tư 2018
Time Process: 2
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | CreateDataFilter
Datetime: 8:58:47 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:47 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:48 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:48 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:48 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:48 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:48 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:48 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:48 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:48 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:48 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:48 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:48 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:48 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:48 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:49 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:49 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:49 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:49 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:49 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:49 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:49 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:49 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:49 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:49 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:49 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:49 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:49 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:49 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:50 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:50 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:50 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:50 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:50 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:50 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:50 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:50 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:50 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:50 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:50 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:50 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:50 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:50 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:51 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:51 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:51 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:51 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:51 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:51 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:51 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:51 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:51 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:51 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:51 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:51 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:51 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:51 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:52 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:52 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:52 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:52 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:52 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:52 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:52 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:52 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:52 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:52 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:52 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:52 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:52 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:52 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:53 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:53 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:53 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:53 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:53 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:53 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:53 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:53 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:53 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:53 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:53 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:53 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:53 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:53 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:54 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:54 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:54 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:54 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:54 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:54 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:54 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:54 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:54 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:54 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:54 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:54 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:54 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:54 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:55 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:55 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:55 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:55 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:55 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:55 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | rgEmployeeList_ItemDataBound
Datetime: 8:58:55 SA 06 Tháng Tư 2018
Time Process: 10
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_employeemng_ascx | ctrlOrganization_SelectedNodeChanged
Datetime: 8:58:55 SA 06 Tháng Tư 2018
Time Process: 10
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrgPostback_SelectedNodeChanged
Datetime: 8:58:55 SA 06 Tháng Tư 2018
Time Process: 13
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | BuildTreeNode
Datetime: 8:58:55 SA 06 Tháng Tư 2018
Time Process: 13
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | BuildOrganization
Datetime: 8:58:55 SA 06 Tháng Tư 2018
Time Process: 13
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | ViewLoad
Datetime: 8:58:55 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 8:58:55 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 8:58:55 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:55 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:58:55 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:55 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:58:56 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:58:57 SA 06 Tháng Tư 2018
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 8:59:07 SA 06 Tháng Tư 2018
Path: default_aspx | OnInit
Datetime: 8:59:07 SA 06 Tháng Tư 2018
Path: default_aspx | PageLoad
Datetime: 8:59:07 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Listmodules_profile_list_ctrlhu_titleconcurrent_ascx | InitControl
Datetime: 8:59:07 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Listmodules_profile_list_ctrlhu_titleconcurrent_ascx | ViewInit
Datetime: 8:59:07 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtlprofile_ascx | InitControl
Datetime: 8:59:08 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtlprofile_ascx | ViewInit
Datetime: 8:59:08 SA 06 Tháng Tư 2018
Time Process: 1
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtl_ascx | ViewInit
Datetime: 8:59:08 SA 06 Tháng Tư 2018
Time Process: 1
Path: default_aspx | PageLoad
Datetime: 8:59:08 SA 06 Tháng Tư 2018
Path: site_master | GetDataNotify
Datetime: 8:59:08 SA 06 Tháng Tư 2018
Path: site_master | LoadConfig
Datetime: 8:59:08 SA 06 Tháng Tư 2018
Path: site_master | Page_Load
Datetime: 8:59:08 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_empdtl_ascx | ToolbarAuthorization
Datetime: 8:59:08 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_empdtl_ascx | CheckAuthorization
Datetime: 8:59:09 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtl_ascx | UpdateControlState
Datetime: 8:59:09 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_empdtlprofile_ascx | ChangeToolbarState
Datetime: 8:59:09 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtl_ascx | UpdateControlState
Datetime: 8:59:09 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtl_ascx | ctrlHU_EmpDtl_OnReceiveData
Datetime: 8:59:09 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtlprofile_ascx | UpdateControlState
Datetime: 8:59:09 SA 06 Tháng Tư 2018
Time Process: 1
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtl_ascx | ViewLoad
Datetime: 8:59:09 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlimageupload_ascx | ToolbarAuthorization
Datetime: 8:59:10 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlimageupload_ascx | CheckAuthorization
Datetime: 8:59:10 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_empdtlprofile_ascx | ToolbarAuthorization
Datetime: 8:59:10 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_empdtlprofile_ascx | CheckAuthorization
Datetime: 8:59:10 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtlprofile_ascx | BindData
Datetime: 8:59:10 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_empdtlprofile_ascx | ChangeToolbarState
Datetime: 8:59:10 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtl_ascx | UpdateControlState
Datetime: 8:59:10 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtl_ascx | ctrlHU_EmpDtl_OnReceiveData
Datetime: 8:59:10 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtlprofile_ascx | UpdateControlState
Datetime: 8:59:10 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtlprofile_ascx | FillDataInControls
Datetime: 8:59:12 SA 06 Tháng Tư 2018
Time Process: 2
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtlprofile_ascx | Refresh
Datetime: 8:59:12 SA 06 Tháng Tư 2018
Time Process: 2
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtlprofile_ascx | ViewLoad
Datetime: 8:59:12 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:59:12 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:59:12 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_list_ctrlhu_titleconcurrent_ascx | ToolbarAuthorization
Datetime: 8:59:12 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_list_ctrlhu_titleconcurrent_ascx | CheckAuthorization
Datetime: 8:59:12 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Listmodules_profile_list_ctrlhu_titleconcurrent_ascx | BindData
Datetime: 8:59:12 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Listmodules_profile_list_ctrlhu_titleconcurrent_ascx | Refresh
Datetime: 8:59:12 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_list_ctrlhu_titleconcurrent_ascx | ChangeToolbarState
Datetime: 8:59:12 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Listmodules_profile_list_ctrlhu_titleconcurrent_ascx | UpdateToolbarState
Datetime: 8:59:12 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Listmodules_profile_list_ctrlhu_titleconcurrent_ascx | UpdateControlState
Datetime: 8:59:12 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Listmodules_profile_list_ctrlhu_titleconcurrent_ascx | ViewLoad
Datetime: 8:59:12 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlfindorgpopup_ascx | ToolbarAuthorization
Datetime: 8:59:12 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlfindorgpopup_ascx | CheckAuthorization
Datetime: 8:59:12 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlorganization_ascx | ToolbarAuthorization
Datetime: 8:59:12 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlorganization_ascx | CheckAuthorization
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:13 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:14 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 8:59:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrgPostback_SelectedNodeChanged
Datetime: 8:59:16 SA 06 Tháng Tư 2018
Time Process: 4
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | BuildTreeNode
Datetime: 8:59:16 SA 06 Tháng Tư 2018
Time Process: 4
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | BuildOrganization
Datetime: 8:59:16 SA 06 Tháng Tư 2018
Time Process: 4
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | ViewLoad
Datetime: 8:59:17 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Listmodules_profile_list_ctrlhu_titleconcurrent_ascx | CreateDataFilter
Datetime: 8:59:17 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Listmodules_profile_list_ctrlhu_titleconcurrent_ascx | RadGrid_NeedDataSource
Datetime: 8:59:17 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:59:17 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:59:17 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:59:17 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:59:17 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 8:59:17 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 8:59:17 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:17 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:59:17 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:17 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:17 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:17 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:17 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:18 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:19 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 8:59:19 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 8:59:19 SA 06 Tháng Tư 2018
Time Process: 2
Path: site_master | BuildMainMenu
Datetime: 9:00:38 SA 06 Tháng Tư 2018
Path: default_aspx | OnInit
Datetime: 9:00:38 SA 06 Tháng Tư 2018
Path: default_aspx | PageLoad
Datetime: 9:00:38 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Listmodules_profile_list_ctrlhu_titleconcurrent_ascx | InitControl
Datetime: 9:00:38 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Listmodules_profile_list_ctrlhu_titleconcurrent_ascx | ViewInit
Datetime: 9:00:38 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtlprofile_ascx | InitControl
Datetime: 9:00:38 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtlprofile_ascx | ViewInit
Datetime: 9:00:38 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtl_ascx | ViewInit
Datetime: 9:00:39 SA 06 Tháng Tư 2018
Path: default_aspx | PageLoad
Datetime: 9:00:39 SA 06 Tháng Tư 2018
Path: site_master | GetDataNotify
Datetime: 9:00:39 SA 06 Tháng Tư 2018
Path: site_master | LoadConfig
Datetime: 9:00:39 SA 06 Tháng Tư 2018
Time Process: 1
Path: site_master | Page_Load
Datetime: 9:00:39 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_empdtl_ascx | ToolbarAuthorization
Datetime: 9:00:39 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_empdtl_ascx | CheckAuthorization
Datetime: 9:00:39 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtl_ascx | UpdateControlState
Datetime: 9:00:39 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_empdtlprofile_ascx | ChangeToolbarState
Datetime: 9:00:39 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtl_ascx | UpdateControlState
Datetime: 9:00:39 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtl_ascx | ctrlHU_EmpDtl_OnReceiveData
Datetime: 9:00:39 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtlprofile_ascx | UpdateControlState
Datetime: 9:00:39 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtl_ascx | ViewLoad
Datetime: 9:00:40 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlimageupload_ascx | ToolbarAuthorization
Datetime: 9:00:40 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlimageupload_ascx | CheckAuthorization
Datetime: 9:00:40 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_empdtlprofile_ascx | ToolbarAuthorization
Datetime: 9:00:40 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_empdtlprofile_ascx | CheckAuthorization
Datetime: 9:00:40 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtlprofile_ascx | BindData
Datetime: 9:00:40 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_empdtlprofile_ascx | ChangeToolbarState
Datetime: 9:00:40 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtl_ascx | UpdateControlState
Datetime: 9:00:40 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtl_ascx | ctrlHU_EmpDtl_OnReceiveData
Datetime: 9:00:40 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtlprofile_ascx | UpdateControlState
Datetime: 9:00:40 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtlprofile_ascx | FillDataInControls
Datetime: 9:00:40 SA 06 Tháng Tư 2018
Time Process: 1
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtlprofile_ascx | Refresh
Datetime: 9:00:40 SA 06 Tháng Tư 2018
Time Process: 1
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_empdtlprofile_ascx | ViewLoad
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_list_ctrlhu_titleconcurrent_ascx | ToolbarAuthorization
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_list_ctrlhu_titleconcurrent_ascx | CheckAuthorization
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Listmodules_profile_list_ctrlhu_titleconcurrent_ascx | BindData
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Listmodules_profile_list_ctrlhu_titleconcurrent_ascx | Refresh
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_list_ctrlhu_titleconcurrent_ascx | ChangeToolbarState
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Listmodules_profile_list_ctrlhu_titleconcurrent_ascx | UpdateToolbarState
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Listmodules_profile_list_ctrlhu_titleconcurrent_ascx | UpdateControlState
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Listmodules_profile_list_ctrlhu_titleconcurrent_ascx | ViewLoad
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlfindorgpopup_ascx | ToolbarAuthorization
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlfindorgpopup_ascx | CheckAuthorization
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlorganization_ascx | ToolbarAuthorization
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlorganization_ascx | CheckAuthorization
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:41 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:42 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:43 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:44 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:00:45 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrgPostback_SelectedNodeChanged
Datetime: 9:00:45 SA 06 Tháng Tư 2018
Time Process: 4
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | BuildTreeNode
Datetime: 9:00:45 SA 06 Tháng Tư 2018
Time Process: 4
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | BuildOrganization
Datetime: 9:00:45 SA 06 Tháng Tư 2018
Time Process: 4
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | ViewLoad
Datetime: 9:00:45 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Listmodules_profile_list_ctrlhu_titleconcurrent_ascx | CreateDataFilter
Datetime: 9:00:45 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Listmodules_profile_list_ctrlhu_titleconcurrent_ascx | RadGrid_NeedDataSource
Datetime: 9:00:45 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:00:46 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:00:46 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:00:46 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:00:46 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 9:00:46 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 9:00:46 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:46 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:00:46 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:46 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:46 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:46 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:46 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:46 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:00:47 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:47 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:47 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:47 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:47 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:47 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:00:47 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:47 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:47 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:47 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:47 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:00:47 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:47 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:47 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:47 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:47 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:00:47 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:47 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:48 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:00:48 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:00:48 SA 06 Tháng Tư 2018
Time Process: 2
Path: site_master | BuildMainMenu
Datetime: 9:10:14 SA 06 Tháng Tư 2018
Time Process: 1
Path: default_aspx | OnInit
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: default_aspx | PageLoad
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | InitControl
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | ViewInit
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: default_aspx | PageLoad
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: site_master | GetDataNotify
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: site_master | LoadConfig
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: site_master | Page_Load
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_contract_ascx | ToolbarAuthorization
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_contract_ascx | CheckAuthorization
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | GetDataCombo
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | BindData
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | Refresh
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | UpdateControlState
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | ViewLoad
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlorganization_ascx | ToolbarAuthorization
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlorganization_ascx | CheckAuthorization
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:15 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:16 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:17 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:18 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:19 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:19 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrg_NodeDataBound
Datetime: 9:10:19 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | CreateDataFilter
Datetime: 9:10:19 SA 06 Tháng Tư 2018
Time Process: 1
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | RadGrid_NeedDataSource
Datetime: 9:10:19 SA 06 Tháng Tư 2018
Time Process: 1
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | ctrlOrg_SelectedNodeChanged
Datetime: 9:10:19 SA 06 Tháng Tư 2018
Time Process: 1
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | trvOrgPostback_SelectedNodeChanged
Datetime: 9:10:19 SA 06 Tháng Tư 2018
Time Process: 4
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | BuildTreeNode
Datetime: 9:10:19 SA 06 Tháng Tư 2018
Time Process: 4
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | BuildOrganization
Datetime: 9:10:19 SA 06 Tháng Tư 2018
Time Process: 4
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | ViewLoad
Datetime: 9:10:19 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:10:19 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:10:19 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:20 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:10:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:21 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:10:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:10:21 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:10:21 SA 06 Tháng Tư 2018
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 9:11:19 SA 06 Tháng Tư 2018
Path: default_aspx | OnInit
Datetime: 9:11:19 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | InitControl
Datetime: 9:11:19 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | ViewInit
Datetime: 9:11:19 SA 06 Tháng Tư 2018
Path: default_aspx | PageLoad
Datetime: 9:11:19 SA 06 Tháng Tư 2018
Path: site_master | GetDataNotify
Datetime: 9:11:19 SA 06 Tháng Tư 2018
Path: site_master | LoadConfig
Datetime: 9:11:19 SA 06 Tháng Tư 2018
Path: site_master | Page_Load
Datetime: 9:11:19 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_contract_ascx | ToolbarAuthorization
Datetime: 9:11:19 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_contract_ascx | CheckAuthorization
Datetime: 9:11:19 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | Refresh
Datetime: 9:11:19 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | UpdateControlState
Datetime: 9:11:19 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | ViewLoad
Datetime: 9:11:19 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlorganization_ascx | ToolbarAuthorization
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlorganization_ascx | CheckAuthorization
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | ViewLoad
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | OnToolbar_Command
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_contract_ascx | OnMainToolbar_Click
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:20 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:21 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:11:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:21 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:11:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:21 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:11:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:21 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:11:21 SA 06 Tháng Tư 2018
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 9:11:30 SA 06 Tháng Tư 2018
Path: default_aspx | OnInit
Datetime: 9:11:30 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | InitControl
Datetime: 9:11:30 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | ViewInit
Datetime: 9:11:30 SA 06 Tháng Tư 2018
Path: default_aspx | PageLoad
Datetime: 9:11:31 SA 06 Tháng Tư 2018
Path: site_master | GetDataNotify
Datetime: 9:11:31 SA 06 Tháng Tư 2018
Path: site_master | LoadConfig
Datetime: 9:11:31 SA 06 Tháng Tư 2018
Path: site_master | Page_Load
Datetime: 9:11:31 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_contract_ascx | ToolbarAuthorization
Datetime: 9:11:31 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_contract_ascx | CheckAuthorization
Datetime: 9:11:31 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | Refresh
Datetime: 9:11:31 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | UpdateControlState
Datetime: 9:11:31 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | ViewLoad
Datetime: 9:11:31 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlorganization_ascx | ToolbarAuthorization
Datetime: 9:11:31 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlorganization_ascx | CheckAuthorization
Datetime: 9:11:31 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | ViewLoad
Datetime: 9:11:31 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:11:31 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:11:31 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 9:11:31 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 9:11:36 SA 06 Tháng Tư 2018
Time Process: 5
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | btnPrintSupport_Click
Datetime: 9:11:36 SA 06 Tháng Tư 2018
Time Process: 5
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | OnToolbar_Command
Datetime: 9:11:36 SA 06 Tháng Tư 2018
Time Process: 5
Path: Common\Modules\Common\modules_profile_business_ctrlhu_contract_ascx | OnMainToolbar_Click
Datetime: 9:11:36 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:36 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:11:36 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:36 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 9:11:37 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 9:11:38 SA 06 Tháng Tư 2018
Time Process: 1
Path: site_master | BuildMainMenu
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: default_aspx | OnInit
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | InitControl
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | ViewInit
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: default_aspx | PageLoad
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: site_master | GetDataNotify
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: site_master | LoadConfig
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: site_master | Page_Load
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_contract_ascx | ToolbarAuthorization
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_profile_business_ctrlhu_contract_ascx | CheckAuthorization
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | Refresh
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | UpdateControlState
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | ViewLoad
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlorganization_ascx | ToolbarAuthorization
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlorganization_ascx | CheckAuthorization
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: Profile/Module/Profile/Setting/modules_common_ctrlorganization_ascx | ViewLoad
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | ToolbarAuthorization
Datetime: 9:23:38 SA 06 Tháng Tư 2018
Path: Common\Modules\Common\modules_common_ctrlsessionwarning_ascx | CheckAuthorization
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Time Process: 3042
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | btnPrintSupport_Click
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Time Process: 3042
Path: Profile\Modules\Profile\Businessmodules_profile_business_ctrlhu_contract_ascx | OnToolbar_Command
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Time Process: 3042
Path: Common\Modules\Common\modules_profile_business_ctrlhu_contract_ascx | OnMainToolbar_Click
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | getChildElement
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | BuildMenu
Datetime: 10:14:21 SA 06 Tháng Tư 2018
Path: site_master | BuildMainMenu
Datetime: 10:14:23 AM Friday, April 6, 2018
Time Process: 3
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 10:14:23 AM Friday, April 6, 2018
Time Process: 3
Path: account_login_aspx | PageLoad
Datetime: 10:14:24 AM Friday, April 6, 2018
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 10:14:24 AM Friday, April 6, 2018
Path: account_login_aspx | PageLoad
Datetime: 10:19:11 AM Friday, April 6, 2018
Path: account_login_aspx | LoadLanguageCombobox
Datetime: 10:19:11 AM Friday, April 6, 2018
Path: account_login_aspx | PageLoad
