Function: SendMail
Datetime: 21/05/2019 9:34:09 AM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in E:\histaffhcm-1\CommonDAL\CommonRepository.vb:line 913
Other Text: iCommon

Function: SendMail
Datetime: 21/05/2019 9:34:09 AM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in E:\histaffhcm-1\CommonDAL\CommonRepository.vb:line 913
Other Text: iCommon

