Function: SendMail
Datetime: 28/05/2019 10:16:25 AM
Error message: This property cannot be set to a null value.
Stack trace:    at System.Data.EntityUtil.ThrowPropertyIsNotNullable(String propertyName)
   at System.Data.Objects.DataClasses.StructuralObject.SetValidValue(String value, Boolean isNullable)
   at CommonDAL.SE_MAIL.set_MAIL_TO(String Value) in E:\histaffhcm-5\CommonDAL\CommonContext1.Designer.vb:line 11733
   at lambda_method(Closure , Shaper )
   at System.Data.Common.Internal.Materialization.Shaper.HandleEntityAppendOnly[TEntity](Func`2 constructEntityDelegate, EntityKey entityKey, EntitySet entitySet)
   at lambda_method(Closure , Shaper )
   at System.Data.Common.Internal.Materialization.Coordinator`1.ReadNextElement(Shaper shaper)
   at System.Data.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in E:\histaffhcm-5\CommonDAL\CommonRepository.vb:line 890
Other Text: iCommon

Function: SendMail
Datetime: 28/05/2019 10:17:11 AM
Error message: This property cannot be set to a null value.
Stack trace:    at System.Data.EntityUtil.ThrowPropertyIsNotNullable(String propertyName)
   at System.Data.Objects.DataClasses.StructuralObject.SetValidValue(String value, Boolean isNullable)
   at CommonDAL.SE_MAIL.set_MAIL_TO(String Value) in E:\histaffhcm-5\CommonDAL\CommonContext1.Designer.vb:line 11733
   at lambda_method(Closure , Shaper )
   at System.Data.Common.Internal.Materialization.Shaper.HandleEntityAppendOnly[TEntity](Func`2 constructEntityDelegate, EntityKey entityKey, EntitySet entitySet)
   at lambda_method(Closure , Shaper )
   at System.Data.Common.Internal.Materialization.Coordinator`1.ReadNextElement(Shaper shaper)
   at System.Data.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in E:\histaffhcm-5\CommonDAL\CommonRepository.vb:line 890
Other Text: iCommon

Function: SendMail
Datetime: 28/05/2019 10:18:11 AM
Error message: This property cannot be set to a null value.
Stack trace:    at System.Data.EntityUtil.ThrowPropertyIsNotNullable(String propertyName)
   at System.Data.Objects.DataClasses.StructuralObject.SetValidValue(String value, Boolean isNullable)
   at CommonDAL.SE_MAIL.set_MAIL_TO(String Value) in E:\histaffhcm-5\CommonDAL\CommonContext1.Designer.vb:line 11733
   at lambda_method(Closure , Shaper )
   at System.Data.Common.Internal.Materialization.Shaper.HandleEntityAppendOnly[TEntity](Func`2 constructEntityDelegate, EntityKey entityKey, EntitySet entitySet)
   at lambda_method(Closure , Shaper )
   at System.Data.Common.Internal.Materialization.Coordinator`1.ReadNextElement(Shaper shaper)
   at System.Data.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in E:\histaffhcm-5\CommonDAL\CommonRepository.vb:line 890
Other Text: iCommon

Function: SendMail
Datetime: 28/05/2019 10:24:07 AM
Error message: This property cannot be set to a null value.
Stack trace:    at System.Data.EntityUtil.ThrowPropertyIsNotNullable(String propertyName)
   at System.Data.Objects.DataClasses.StructuralObject.SetValidValue(String value, Boolean isNullable)
   at CommonDAL.SE_MAIL.set_MAIL_TO(String Value) in E:\histaffhcm-5\CommonDAL\CommonContext1.Designer.vb:line 11733
   at lambda_method(Closure , Shaper )
   at System.Data.Common.Internal.Materialization.Shaper.HandleEntityAppendOnly[TEntity](Func`2 constructEntityDelegate, EntityKey entityKey, EntitySet entitySet)
   at lambda_method(Closure , Shaper )
   at System.Data.Common.Internal.Materialization.Coordinator`1.ReadNextElement(Shaper shaper)
   at System.Data.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in E:\histaffhcm-5\CommonDAL\CommonRepository.vb:line 890
Other Text: iCommon

Function: SendMail
Datetime: 28/05/2019 10:26:07 AM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in E:\histaffhcm-5\CommonDAL\CommonRepository.vb:line 913
Other Text: iCommon

Function: SendMail
Datetime: 28/05/2019 10:26:07 AM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in E:\histaffhcm-5\CommonDAL\CommonRepository.vb:line 913
Other Text: iCommon

