-- --------------------------------------------------
-- Entity Designer DDL Script for Oracle database
-- --------------------------------------------------
-- Date Created: 15/4/2020 11:54:32 AM
-- Generated from EDMX file: G:\Cty TVC\Source\acv_19\RecruitmentDAL\RecruitmentContext.edmx
-- --------------------------------------------------

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

-- ALTER TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE_HEALTH1" DROP CONSTRAINT "FK_FE_HEH" CASCADE;

-- ALTER TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE_CV" DROP CONSTRAINT "FK_HE_HEC" CASCADE;

-- ALTER TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE_EDUCATION1" DROP CONSTRAINT "FK_HE_HEE" CASCADE;

-- ALTER TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE_OTHER_INFO1" DROP CONSTRAINT "FK_HE_HEO" CASCADE;

-- ALTER TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE" DROP CONSTRAINT "FK_HE_HT" CASCADE;

-- ALTER TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE" DROP CONSTRAINT "FK_HU_ORG_HU_EMP" CASCADE;

-- ALTER TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE" DROP CONSTRAINT "FK_HUEMD_HUEM" CASCADE;

-- ALTER TABLE "RecruitmentModelStoreContainer"."HU_ORG_TITLE" DROP CONSTRAINT "FK_HUOG_HUOT" CASCADE;

-- ALTER TABLE "RecruitmentModelStoreContainer"."HU_ORG_TITLE" DROP CONSTRAINT "FK_HUTL_HUOT" CASCADE;

-- ALTER TABLE "RecruitmentModelStoreContainer"."HU_ORGANIZATION" DROP CONSTRAINT "FK_HU_ORG_HU_ORG" CASCADE;

-- ALTER TABLE "RecruitmentModelStoreContainer"."HU_BANK_BRANCH" DROP CONSTRAINT "FK_BANKBANK_BRANCH" CASCADE;

-- ALTER TABLE "RecruitmentModelStoreContainer"."HU_DISTRICT" DROP CONSTRAINT "FK_HU_PRO_HU_DIS" CASCADE;

-- ALTER TABLE "RecruitmentModelStoreContainer"."HU_PROVINCE" DROP CONSTRAINT "FK_HU_NAT_HU_PRO" CASCADE;

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_COST_CENTER";

-- DROP TABLE "RecruitmentModelStoreContainer"."SE_CHOSEN_ORG";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_FAMILY";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_TERMINATE";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_EXAMS";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_EXAMS_DTL";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_PLAN_REG_EMP";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_PROGRAM_CHARACTER";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_PROGRAM_EMP";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_PROGRAM_EXAMS";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_PROGRAM_SCOPE";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_PROGRAM_SOFT_SKILL";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_REQUEST";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_REQUEST_EMP";

-- DROP TABLE "RecruitmentModelStoreContainer"."OT_OTHER_LIST";

-- DROP TABLE "RecruitmentModelStoreContainer"."OT_OTHER_LIST_GROUP";

-- DROP TABLE "RecruitmentModelStoreContainer"."OT_OTHER_LIST_TYPE";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_PLAN_REG";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_CONTRACT_TYPE";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_CANDIDATE";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_CANDIDATE_EDUCATION";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_CANDIDATE_HISTORY";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_CANDIDATE_OTHER_INFO";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_CANDIDATE_CV";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_PROGRAM_SCHEDULE";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_PROGRAM_SCHEDULE_CAN";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_PROGRAM_SCHEDULE_USHER";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_CANDIDATE_FAMILY";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_CANDIDATE_TRAINSINGER";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_CANDIDATE_BEFOREWT";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_COST";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_COST_FORM";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE_BANK";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE_BEFOREWT";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE_EDUCATION";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE_HEALTH";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE_OTHER_INFO";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE_TRAIN";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE_TRAINSINGER";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE_CV";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE_EDUCATION1";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE_HEALTH1";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_EMPLOYEE_OTHER_INFO1";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_ORG_TITLE";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_ORGANIZATION";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_TITLE";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_BANK";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_BANK_BRANCH";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_DISTRICT";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_NATION";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_PROVINCE";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_STAGE";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_COSTALLOCATE";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_COST_COSTALLOCATE";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_MANNING_ORG";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_MANNING_TITLE";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_CANDIDATE_EXPECT";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_CANDIDATE_HEALTH";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_CANDIDATE_REFERENCE";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_PROGRAM";

-- DROP TABLE "RecruitmentModelStoreContainer"."SE_USER";

-- DROP TABLE "RecruitmentModelStoreContainer"."SE_REPORT";

-- DROP TABLE "RecruitmentModelStoreContainer"."SE_USER_REPORT";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_WARD";

-- DROP TABLE "RecruitmentModelStoreContainer"."HU_ORGANIZATION_V";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_CANDIDATE_TRAINNING";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_PLAN_YEAR";

-- DROP TABLE "RecruitmentModelStoreContainer"."RC_RECRUITMENT_INSTEAD";

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'RC_COST_CENTER'
CREATE TABLE "dbo"."RC_COST_CENTER" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NOT NULL,
   "ACTFLG" NVARCHAR2(1) NOT NULL,
   "CODE" NVARCHAR2(255) NOT NULL,
   "CREATED_DATE" DATE NOT NULL,
   "CREATED_BY" NVARCHAR2(255) NOT NULL,
   "CREATED_LOG" NVARCHAR2(255) NOT NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_BY" NVARCHAR2(255) NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NOT NULL
);

-- Creating table 'SE_CHOSEN_ORG'
CREATE TABLE "dbo"."SE_CHOSEN_ORG" (
   "ORG_ID" NUMBER(38,0) NOT NULL,
   "USERNAME" NVARCHAR2(255) NOT NULL
);

-- Creating table 'HU_FAMILY'
CREATE TABLE "dbo"."HU_FAMILY" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ID_NO" VARCHAR2(15) NULL,
   "FULLNAME" NVARCHAR2(255) NULL,
   "RELATION_ID" NUMBER(38,0) NULL,
   "JOB" NVARCHAR2(255) NULL,
   "COMPANY" NVARCHAR2(255) NULL,
   "IS_DIED" NUMBER(5,0) NULL,
   "IS_MLG" NUMBER(5,0) NULL,
   "ADDRESS" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "BIRTH_DAY" NUMBER(5,0) NULL,
   "BIRTH_MONTH" NUMBER(5,0) NULL,
   "BIRTH_YEAR" NUMBER(5,0) NULL,
   "DIED_DATE" DATE NULL,
   "REMARK" NVARCHAR2(255) NULL,
   "PIT_CODE" NVARCHAR2(255) NULL,
   "PIT_DATE" DATE NULL,
   "ID_DATE" DATE NULL,
   "ID_PLACE" NUMBER(38,0) NULL,
   "PER_ADDRESS" NVARCHAR2(255) NULL,
   "BIRTH_NO" NUMBER(38,0) NULL,
   "BIRTH_BOOK" NUMBER(38,0) NULL,
   "BIRTH_NAT" NUMBER(38,0) NULL,
   "BIRTH_PRO" NUMBER(38,0) NULL,
   "BIRTH_DIS" NUMBER(38,0) NULL,
   "BIRTH_NAT2" NUMBER(38,0) NULL
);

-- Creating table 'HU_TERMINATE'
CREATE TABLE "dbo"."HU_TERMINATE" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "DECISION_ID" NUMBER(38,0) NULL,
   "IS_TERSINGLE" NUMBER(5,0) NULL,
   "IS_NOHIRE" NUMBER(5,0) NULL,
   "SEND_DATE" DATE NULL,
   "TER_REASON_ID" NUMBER(38,0) NULL,
   "TER_REASON_DETAIL" NVARCHAR2(1023) NULL,
   "LAST_DATE" DATE NULL,
   "STATUS_ID" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "EMP_SENIORITY" NVARCHAR2(255) NULL,
   "LAST_WORKING_ID" NUMBER(38,0) NULL,
   "BHYT_REVOCATION" NUMBER(5,0) NULL,
   "BHYT_MONEY" NUMBER(38,0) NULL,
   "EMPCARD_REVOCATION" NUMBER(5,0) NULL,
   "DECISION_TYPE" NUMBER(38,0) NULL,
   "IS_REEMPLOY" NUMBER(5,0) NULL,
   "MONEY" NUMBER(5,0) NULL,
   "FILE_NAME" NVARCHAR2(255) NULL,
   "REMARK2" NVARCHAR2(1023) NULL,
   "IS_PROPERTIES_RETURN" NUMBER(5,0) NULL,
   "YEARFORALLOW" NUMBER(10,0) NULL,
   "SALARYMEDIUM" NUMBER(38,0) NULL,
   "MONEYALLOW" NUMBER(38,0) NULL
);

-- Creating table 'RC_EXAMS'
CREATE TABLE "dbo"."RC_EXAMS" (
   "ID" NUMBER(38,0) NOT NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL
);

-- Creating table 'RC_EXAMS_DTL'
CREATE TABLE "dbo"."RC_EXAMS_DTL" (
   "ID" NUMBER(38,0) NOT NULL,
   "RC_EXAMS_ID" NUMBER(38,0) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "POINT_LADDER" NUMBER(38,0) NULL,
   "POINT_PASS" NUMBER(38,0) NULL,
   "EXAMS_ORDER" NUMBER(38,0) NULL,
   "IS_PV" NUMBER(5,0) NULL,
   "COEFFICIENT" NUMBER(10,0) NULL,
   "NOTE" NCLOB NULL
);

-- Creating table 'RC_PLAN_REG_EMP'
CREATE TABLE "dbo"."RC_PLAN_REG_EMP" (
   "ID" NUMBER(38,0) NOT NULL,
   "RC_PLAN_REG_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL
);

-- Creating table 'RC_PROGRAM_CHARACTER'
CREATE TABLE "dbo"."RC_PROGRAM_CHARACTER" (
   "ID" NUMBER(38,0) NOT NULL,
   "RC_PROGRAM_ID" NUMBER(38,0) NULL,
   "CHARACTER_ID" NUMBER(38,0) NULL
);

-- Creating table 'RC_PROGRAM_EMP'
CREATE TABLE "dbo"."RC_PROGRAM_EMP" (
   "ID" NUMBER(38,0) NOT NULL,
   "RC_PROGRAM_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL
);

-- Creating table 'RC_PROGRAM_EXAMS'
CREATE TABLE "dbo"."RC_PROGRAM_EXAMS" (
   "ID" NUMBER(38,0) NOT NULL,
   "RC_PROGRAM_ID" NUMBER(38,0) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "POINT_LADDER" NUMBER(38,0) NULL,
   "POINT_PASS" NUMBER(38,0) NULL,
   "EXAMS_ORDER" NUMBER(38,0) NULL,
   "IS_PV" NUMBER(5,0) NULL,
   "COEFFICIENT" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(2000) NULL
);

-- Creating table 'RC_PROGRAM_SCOPE'
CREATE TABLE "dbo"."RC_PROGRAM_SCOPE" (
   "ID" NUMBER(38,0) NOT NULL,
   "RC_PROGRAM_ID" NUMBER(38,0) NULL,
   "RECRUIT_SCOPE_ID" NUMBER(38,0) NULL
);

-- Creating table 'RC_PROGRAM_SOFT_SKILL'
CREATE TABLE "dbo"."RC_PROGRAM_SOFT_SKILL" (
   "ID" NUMBER(38,0) NOT NULL,
   "RC_PROGRAM_ID" NUMBER(38,0) NULL,
   "SOFT_SKILL_ID" NUMBER(38,0) NULL
);

-- Creating table 'RC_REQUEST'
CREATE TABLE "dbo"."RC_REQUEST" (
   "ID" NUMBER(38,0) NOT NULL,
   "IS_IN_PLAN" NUMBER(5,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "JOBGRADE_ID" NUMBER(38,0) NULL,
   "CONTRACT_TYPE_ID" NUMBER(38,0) NULL,
   "RECRUIT_REASON_ID" NUMBER(38,0) NULL,
   "RECRUIT_REASON" NVARCHAR2(1023) NULL,
   "LEARNING_LEVEL_ID" NUMBER(38,0) NULL,
   "AGE_FROM" NUMBER(38,0) NULL,
   "AGE_TO" NUMBER(38,0) NULL,
   "SEND_DATE" DATE NULL,
   "EXPECTED_JOIN_DATE" DATE NULL,
   "EXPERIENCE_NUMBER" NUMBER(38,0) NULL,
   "MALE_NUMBER" NUMBER(38,0) NULL,
   "FEMALE_NUMBER" NUMBER(38,0) NULL,
   "DESCRIPTION" NVARCHAR2(1023) NULL,
   "REQUEST_EXPERIENCE" NVARCHAR2(1023) NULL,
   "REQUEST_OTHER" NVARCHAR2(1023) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "STATUS_ID" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "REMARK_REJECT" NVARCHAR2(1023) NULL,
   "LANGUAGE" NVARCHAR2(1023) NULL,
   "LANGUAGELEVEL" NVARCHAR2(1023) NULL,
   "LANGUAGESCORES" NUMBER(38,0) NULL,
   "SPECIALSKILLS" NVARCHAR2(1023) NULL,
   "QUALIFICATION" NVARCHAR2(1023) NULL,
   "MAINTASK" NVARCHAR2(1023) NULL,
   "DESCRIPTIONATTACHFILE" NVARCHAR2(1023) NULL,
   "COMPUTER_LEVEL" NVARCHAR2(1023) NULL,
   "RC_PLAN_ID" NUMBER(38,0) NULL,
   "RC_RECRUIT_PROPERTY" NUMBER(38,0) NULL,
   "IS_OVER_LIMIT" NUMBER(38,0) NULL,
   "IS_SUPPORT" NUMBER(38,0) NULL,
   "FOREIGN_ABILITY" NCLOB NULL,
   "COMPUTER_APP_LEVEL" NCLOB NULL,
   "GENDER_PRIORITY" NUMBER(38,0) NULL,
   "UPLOAD_FILE" NCLOB NULL,
   "RECRUIT_NUMBER" NUMBER(38,0) NULL,
   "FILE_NAME" NVARCHAR2(1023) NULL,
   "LOCATION_ID" NUMBER(38,0) NULL
);

-- Creating table 'RC_REQUEST_EMP'
CREATE TABLE "dbo"."RC_REQUEST_EMP" (
   "ID" NUMBER(38,0) NOT NULL,
   "RC_REQUEST_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL
);

-- Creating table 'OT_OTHER_LIST'
CREATE TABLE "dbo"."OT_OTHER_LIST" (
   "ID" NUMBER(38,0) NOT NULL,
   "TYPE_ID" NUMBER(38,0) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "ATTRIBUTE1" NVARCHAR2(255) NULL,
   "ATTRIBUTE2" NVARCHAR2(255) NULL,
   "ATTRIBUTE3" NVARCHAR2(255) NULL,
   "ATTRIBUTE4" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "CODE" NVARCHAR2(15) NULL,
   "TYPE_CODE" NVARCHAR2(15) NULL,
   "ORDERBYID" NUMBER(38,0) NULL
);

-- Creating table 'OT_OTHER_LIST_GROUP'
CREATE TABLE "dbo"."OT_OTHER_LIST_GROUP" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'OT_OTHER_LIST_TYPE'
CREATE TABLE "dbo"."OT_OTHER_LIST_TYPE" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(255) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "GROUP_ID" NUMBER(38,0) NULL,
   "IS_SYSTEM" NUMBER(5,0) NULL,
   "TABLE_RELATION" VARCHAR2(2000) NULL
);

-- Creating table 'RC_PLAN_REG'
CREATE TABLE "dbo"."RC_PLAN_REG" (
   "ID" NUMBER(38,0) NOT NULL,
   "SEND_DATE" DATE NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "JOBGRADE_ID" NUMBER(38,0) NULL,
   "RECRUIT_NUMBER" NUMBER(38,0) NULL,
   "EXPECTED_JOIN_DATE" DATE NULL,
   "RECRUIT_REASON_ID" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "STATUS_ID" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "REMARK_REJECT" NCLOB NULL,
   "EDUCATIONLEVEL" NCLOB NULL,
   "AGESFROM" NUMBER(38,0) NULL,
   "AGESTO" NUMBER(38,0) NULL,
   "LANGUAGE" NCLOB NULL,
   "LANGUAGELEVEL" NCLOB NULL,
   "LANGUAGESCORES" NUMBER(38,0) NULL,
   "SPECIALSKILLS" NCLOB NULL,
   "MAINTASK" NCLOB NULL,
   "QUALIFICATION" NCLOB NULL,
   "QUALIFICATIONREQUEST" NCLOB NULL,
   "COMPUTER_LEVEL" NCLOB NULL,
   "FILE_NAME" NVARCHAR2(255) NULL
);

-- Creating table 'HU_CONTRACT_TYPE'
CREATE TABLE "dbo"."HU_CONTRACT_TYPE" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NOT NULL,
   "CODE" NVARCHAR2(255) NOT NULL,
   "PERIOD" NUMBER(10,0) NULL,
   "STATUS" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "TYPE" NUMBER(10,0) NULL,
   "REMARK" NVARCHAR2(255) NULL
);

-- Creating table 'RC_CANDIDATE'
CREATE TABLE "dbo"."RC_CANDIDATE" (
   "ID" NUMBER(38,0) NOT NULL,
   "CANDIDATE_CODE" NVARCHAR2(15) NULL,
   "FIRST_NAME_VN" NVARCHAR2(255) NULL,
   "LAST_NAME_VN" NVARCHAR2(255) NULL,
   "FULLNAME_VN" NVARCHAR2(255) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "JOIN_DATE" DATE NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "EFFECT_DATE" DATE NULL,
   "TITLE_NAME" NVARCHAR2(255) NULL,
   "FILE_SIZE" NUMBER(38,0) NULL,
   "FILE_NAME" NVARCHAR2(255) NULL,
   "WORK" NVARCHAR2(255) NULL,
   "RC_PROGRAM_ID" NUMBER(38,0) NULL,
   "IS_PONTENTIAL" NUMBER(5,0) NULL,
   "IS_BLACKLIST" NUMBER(5,0) NULL,
   "IS_REHIRE" NUMBER(5,0) NULL,
   "STATUS_ID" NCLOB NULL,
   "EMPLOYEE_CODE" NVARCHAR2(255) NULL,
   "CARE_TITLE_NAME" NVARCHAR2(225) NULL,
   "RECRUIMENT_WEBSITE" NVARCHAR2(225) NULL,
   "STATUS_US" NCLOB NULL
);

-- Creating table 'RC_CANDIDATE_EDUCATION'
CREATE TABLE "dbo"."RC_CANDIDATE_EDUCATION" (
   "CANDIDATE_ID" NUMBER(38,0) NOT NULL,
   "ACADEMY" NVARCHAR2(15) NULL,
   "HE_DAO_TAO" NUMBER(38,0) NULL,
   "HIGHEST_EDU" NUMBER(38,0) NULL,
   "HIGHEST_LEVEL" NUMBER(38,0) NULL,
   "TRAIN_FORM" NUMBER(38,0) NULL,
   "GRADUATE_YEAR" NUMBER(38,0) NULL,
   "MARK_EDU" NVARCHAR2(15) NULL,
   "COMPUTER_LEVEL" NVARCHAR2(15) NULL,
   "LANGUAGE_LEVEL" NVARCHAR2(15) NULL,
   "POLOTOCA_THEORY" NUMBER(38,0) NULL,
   "STATE_MNG" NUMBER(38,0) NULL,
   "ADD_INFO" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "SCHOOL_NAME" NVARCHAR2(255) NULL,
   "LEARNING_LEVEL" NVARCHAR2(15) NULL,
   "FIELD" NVARCHAR2(15) NULL,
   "SCHOOL" NVARCHAR2(15) NULL,
   "MAJOR" NVARCHAR2(15) NULL,
   "DEGREE" NVARCHAR2(15) NULL,
   "GPA" NUMBER(38,10) NULL,
   "IT_CERTIFICATE" NVARCHAR2(255) NULL,
   "IT_LEVEL" NVARCHAR2(15) NULL,
   "IT_MARK" NVARCHAR2(50) NULL,
   "IT_CERTIFICATE1" NVARCHAR2(255) NULL,
   "IT_LEVEL1" NVARCHAR2(15) NULL,
   "IT_MARK1" NVARCHAR2(50) NULL,
   "IT_CERTIFICATE2" NVARCHAR2(255) NULL,
   "IT_LEVEL2" NVARCHAR2(15) NULL,
   "IT_MARK2" NVARCHAR2(50) NULL,
   "ENGLISH" NVARCHAR2(255) NULL,
   "ENGLISH_LEVEL" NVARCHAR2(15) NULL,
   "ENGLISH_MARK" NVARCHAR2(50) NULL,
   "ENGLISH1" NVARCHAR2(255) NULL,
   "ENGLISH_LEVEL1" NVARCHAR2(15) NULL,
   "ENGLISH_MARK1" NVARCHAR2(50) NULL,
   "ENGLISH2" NVARCHAR2(255) NULL,
   "ENGLISH_LEVEL2" NVARCHAR2(15) NULL,
   "ENGLISH_MARK2" NVARCHAR2(50) NULL,
   "DATE_START" DATE NULL,
   "DATE_END" DATE NULL,
   "ENGLISH_SKILL" NCLOB NULL,
   "CERTIFICATE_ID" NUMBER(38,0) NULL,
   "LANGUAGE_ID" NUMBER(38,0) NULL,
   "YEAR_GRADUATE" NUMBER(38,0) NULL
);

-- Creating table 'RC_CANDIDATE_HISTORY'
CREATE TABLE "dbo"."RC_CANDIDATE_HISTORY" (
   "CANDIDATE_ID" NUMBER(38,0) NOT NULL,
   "CREATED_DATE" DATE NOT NULL,
   "CREATED_BY" NVARCHAR2(255) NOT NULL,
   "CREATED_LOG" NVARCHAR2(255) NOT NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_BY" NVARCHAR2(255) NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NOT NULL,
   "IS_OLD_REGIME" NUMBER(5,0) NULL,
   "OLD_REGIME_START" DATE NULL,
   "OLD_REGIME_END" DATE NULL,
   "OLD_REGIME_PROVINCE" NUMBER(38,0) NULL,
   "IS_FOREIGN_RELATION" NUMBER(5,0) NULL,
   "FOREIGN_WORK" VARCHAR2(255) NULL,
   "FOREIGN_NAME" VARCHAR2(255) NULL,
   "FOREIGN_OFFICE" VARCHAR2(255) NULL,
   "FOREIGN_FAMILY" VARCHAR2(255) NULL,
   "ECONOMY" VARCHAR2(255) NULL,
   "OTHER_ISSUE" VARCHAR2(255) NULL
);

-- Creating table 'RC_CANDIDATE_OTHER_INFO'
CREATE TABLE "dbo"."RC_CANDIDATE_OTHER_INFO" (
   "CANDIDATE_ID" NUMBER(38,0) NOT NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "NGAYVAOCONGDOAN" DATE NULL,
   "NOIVAOCONGDOAN" NVARCHAR2(255) NULL,
   "CONGDOANPHI" NUMBER(38,0) NULL,
   "ACCOUNT_NAME" NVARCHAR2(255) NULL,
   "ACCOUNT_NUMBER" NUMBER(38,0) NULL,
   "BANK" NVARCHAR2(255) NULL,
   "BANK_BRANCH" NVARCHAR2(255) NULL,
   "IS_PAYMENT_VIA_BANK" NUMBER(5,0) NULL,
   "ACCOUNT_EFFECT_DATE" DATE NULL,
   "DANG_PHI" NUMBER(5,0) NULL,
   "CHUC_VU_DANG" NUMBER(38,0) NULL,
   "CHUC_VU_DOAN" NUMBER(38,0) NULL,
   "CAREER" NVARCHAR2(255) NULL,
   "IS_DOANVIEN" NUMBER(5,0) NULL,
   "IS_DANGVIEN" NUMBER(5,0) NULL,
   "DANG_KIEMNHIEM" NUMBER(38,0) NULL,
   "CAPUY_HIENTAI" NVARCHAR2(255) NULL,
   "CAPUY_KIEMNHIEM" NVARCHAR2(255) NULL,
   "IS_CONGDOANPHI" NUMBER(5,0) NULL,
   "CDP_NGAYVAO" DATE NULL,
   "CDP_NOIVAO" NVARCHAR2(255) NULL,
   "IS_CCB" NUMBER(5,0) NULL,
   "CCB_NGAYVAO" DATE NULL,
   "CCB_CHUCVU" NUMBER(38,0) NULL,
   "CCB_NOIVAO" NVARCHAR2(255) NULL,
   "CCB_NGAYNHAPNGU" DATE NULL,
   "CCB_NGAYXUATNGU" DATE NULL,
   "CCB_QUANHAM" NVARCHAR2(255) NULL,
   "TPGD" NVARCHAR2(255) NULL,
   "DANHHIEU" NVARCHAR2(255) NULL,
   "SOTRUONGCONGTAC" NVARCHAR2(255) NULL,
   "LYLUANCHINHTRI" NUMBER(38,0) NULL,
   "CONGTAC_LAUNHAT" NVARCHAR2(255) NULL,
   "QUANLYNHANUOC" NUMBER(38,0) NULL,
   "THUONGBINH" NUMBER(38,0) NULL,
   "GDCS" NUMBER(38,0) NULL,
   "NGAY_NHAN_CV_DOAN" DATE NULL,
   "NGAY_NHAN_CV_DANG" DATE NULL,
   "DOAN_PHI" NUMBER(38,0) NULL,
   "NGAY_VAO_DOAN" DATE NULL,
   "NOI_VAO_DOAN" NCLOB NULL,
   "NOI_VAO_DANG" NCLOB NULL,
   "NGAY_VAO_DANG" DATE NULL
);

-- Creating table 'RC_CANDIDATE_CV'
CREATE TABLE "dbo"."RC_CANDIDATE_CV" (
   "CANDIDATE_ID" NUMBER(38,0) NOT NULL,
   "BIRTH_DATE" DATE NULL,
   "GENDER" NVARCHAR2(15) NULL,
   "ID_NO" NCLOB NULL,
   "ID_DATE" DATE NULL,
   "ID_PLACE" NCLOB NULL,
   "NAV_ADDRESS" NVARCHAR2(255) NULL,
   "NAV_PROVINCE" NUMBER(38,0) NULL,
   "BIRTH_ADDRESS" NVARCHAR2(255) NULL,
   "BIRTH_PROVINCE" NUMBER(38,0) NULL,
   "NATIVE" NVARCHAR2(15) NULL,
   "RELIGION" NVARCHAR2(15) NULL,
   "PER_ADDRESS" NVARCHAR2(255) NULL,
   "PER_PROVINCE" NUMBER(38,0) NULL,
   "CONTACT_ADDRESS" NVARCHAR2(255) NULL,
   "CONTACT_PROVINCE" NUMBER(38,0) NULL,
   "MARITAL_STATUS" NVARCHAR2(15) NULL,
   "MOBILE_PHONE" NVARCHAR2(255) NULL,
   "WORK_EMAIL" NVARCHAR2(255) NULL,
   "PIT_CODE" VARCHAR2(255) NULL,
   "BHXH_NO" NVARCHAR2(255) NULL,
   "HOSPITAL_ADDRESS" VARCHAR2(255) NULL,
   "WORK_FORTE" VARCHAR2(255) NULL,
   "IMAGE" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "NATIONALITY_ID" NUMBER(38,0) NULL,
   "INSURANCE_DATE" DATE NULL,
   "PASSPORT_ID" NVARCHAR2(255) NULL,
   "PASSPORT_DATE" DATE NULL,
   "PASSPORT_PLACE" NVARCHAR2(255) NULL,
   "BIRTH_NATION" NUMBER(38,0) NULL,
   "PERTAXCODE" NVARCHAR2(100) NULL,
   "EDUCATION_MAJORS" NVARCHAR2(255) NULL,
   "EDUCATION_ID" NUMBER(38,0) NULL,
   "CONTACT_NATION" NUMBER(38,0) NULL,
   "PER_NATION" NUMBER(38,0) NULL,
   "NAV_NATION" NUMBER(38,0) NULL,
   "PER_DISTRICT" NUMBER(38,0) NULL,
   "CONTACT_DISTRICT" NUMBER(38,0) NULL,
   "ID_DATE_EXPIRATION" DATE NULL,
   "IS_RESIDENT" NUMBER(38,0) NULL,
   "CONTACT_ADDRESS_TEMP" NVARCHAR2(255) NULL,
   "CONTACT_NATION_TEMP" NUMBER(38,0) NULL,
   "CONTACT_PROVINCE_TEMP" NUMBER(38,0) NULL,
   "CONTACT_DISTRICT_TEMP" NUMBER(38,0) NULL,
   "CONTACT_MOBILE" NVARCHAR2(100) NULL,
   "CONTACT_PHONE" NVARCHAR2(100) NULL,
   "PER_EMAIL" NVARCHAR2(255) NULL,
   "PER_TAX_DATE" DATE NULL,
   "PER_TAX_PLACE" NVARCHAR2(255) NULL,
   "PASSPORT_DATE_EXPIRATION" DATE NULL,
   "VISA_NUMBER" NVARCHAR2(100) NULL,
   "VISA_DATE" DATE NULL,
   "VISA_DATE_EXPIRATION" DATE NULL,
   "VISA_PLACE" NVARCHAR2(255) NULL,
   "VNAIRLINES_NUMBER" NVARCHAR2(100) NULL,
   "VNAIRLINES_DATE" DATE NULL,
   "VNAIRLINES_DATE_EXPIRATION" DATE NULL,
   "VNAIRLINES_PLACE" NVARCHAR2(255) NULL,
   "LABOUR_NUMBER" NVARCHAR2(100) NULL,
   "LABOUR_DATE" DATE NULL,
   "LABOUR_DATE_EXPIRATION" DATE NULL,
   "LABOUR_PLACE" NVARCHAR2(255) NULL,
   "WORK_PERMIT" NVARCHAR2(100) NULL,
   "WORK_PERMIT_START" DATE NULL,
   "WORK_PERMIT_END" DATE NULL,
   "TEMP_RESIDENCE_CARD" NVARCHAR2(100) NULL,
   "TEMP_RESIDENCE_CARD_START" DATE NULL,
   "TEMP_RESIDENCE_CARD_END" DATE NULL,
   "CON_COUNTRY" NUMBER(38,0) NULL,
   "CON_PROVINCE" NUMBER(38,0) NULL,
   "CON_DISTRICT" NUMBER(38,0) NULL,
   "CON_WARD" NUMBER(38,0) NULL,
   "CON_ADDRESS" NVARCHAR2(255) NULL,
   "PER_WARD" NUMBER(38,0) NULL,
   "FINDER_NAME" NCLOB NULL,
   "FINDER_SDT" NCLOB NULL,
   "FINDER_ADDRESS" NCLOB NULL,
   "URGENT_PER_NAME" NCLOB NULL,
   "URGENT_PER_RELATION" NUMBER(38,0) NULL,
   "URGENT_PER_SDT" NCLOB NULL,
   "URGENT_ADDRESS" NCLOB NULL,
   "STRANGER" NCLOB NULL,
   "WEAKNESS" NCLOB NULL,
   "CONTACT_ADDRESS_NOW" NCLOB NULL,
   "CONTACT_PERSON" NCLOB NULL,
   "CONTACT_PERSON_ADDRESS" NCLOB NULL,
   "CONTACT_PERSON_PHONE" NCLOB NULL,
   "NAV_DOMICILE" NCLOB NULL
);

-- Creating table 'RC_PROGRAM_SCHEDULE'
CREATE TABLE "dbo"."RC_PROGRAM_SCHEDULE" (
   "ID" NUMBER(38,0) NOT NULL,
   "RC_PROGRAM_ID" NUMBER(38,0) NULL,
   "RC_PROGRAM_EXAMS_ID" NUMBER(38,0) NULL,
   "SCHEDULE_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "EXAMS_PLACE" NVARCHAR2(255) NULL,
   "NOTE" NVARCHAR2(255) NULL
);

-- Creating table 'RC_PROGRAM_SCHEDULE_CAN'
CREATE TABLE "dbo"."RC_PROGRAM_SCHEDULE_CAN" (
   "ID" NUMBER(38,0) NOT NULL,
   "RC_PROGRAM_SCHEDULE_ID" NUMBER(38,0) NULL,
   "CANDIDATE_ID" NUMBER(38,0) NULL,
   "START_HOUR" DATE NULL,
   "END_HOUR" DATE NULL,
   "POINT_RESULT" NUMBER(38,0) NULL,
   "COMMENT_INFO" NVARCHAR2(1023) NULL,
   "ASSESSMENT_INFO" NVARCHAR2(1023) NULL,
   "IS_PASS" NUMBER(5,0) NULL
);

-- Creating table 'RC_PROGRAM_SCHEDULE_USHER'
CREATE TABLE "dbo"."RC_PROGRAM_SCHEDULE_USHER" (
   "ID" NUMBER(38,0) NOT NULL,
   "RC_PROGRAM_SCHEDULE_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL
);

-- Creating table 'RC_CANDIDATE_FAMILY'
CREATE TABLE "dbo"."RC_CANDIDATE_FAMILY" (
   "ID" NUMBER(38,0) NOT NULL,
   "CANDIDATE_ID" NUMBER(38,0) NULL,
   "ID_NO" VARCHAR2(15) NULL,
   "FULLNAME" NVARCHAR2(255) NULL,
   "RELATION_ID" NUMBER(38,0) NULL,
   "JOB" NVARCHAR2(255) NULL,
   "COMPANY" NVARCHAR2(255) NULL,
   "IS_DIED" NUMBER(5,0) NULL,
   "IS_MLG" NUMBER(5,0) NULL,
   "ADDRESS" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "BIRTH_DAY" NUMBER(5,0) NULL,
   "BIRTH_MONTH" NUMBER(5,0) NULL,
   "BIRTH_YEAR" NUMBER(5,0) NULL,
   "DIED_DATE" DATE NULL,
   "REMARK" NVARCHAR2(255) NULL,
   "PIT_CODE" NVARCHAR2(255) NULL,
   "PIT_DATE" DATE NULL,
   "ID_DATE" DATE NULL,
   "ID_PLACE" NUMBER(38,0) NULL,
   "PER_ADDRESS" NVARCHAR2(255) NULL,
   "BIRTH_NO" NVARCHAR2(255) NULL,
   "BIRTH_BOOK" NVARCHAR2(255) NULL,
   "BIRTH_NAT" NUMBER(38,0) NULL,
   "BIRTH_PRO" NUMBER(38,0) NULL,
   "BIRTH_DIS" NUMBER(38,0) NULL,
   "BIRTH_NAT2" NUMBER(38,0) NULL,
   "PHONE_NUMBER" NCLOB NULL
);

-- Creating table 'RC_CANDIDATE_TRAINSINGER'
CREATE TABLE "dbo"."RC_CANDIDATE_TRAINSINGER" (
   "ID" NUMBER(38,0) NOT NULL,
   "CANDIDATE_ID" NUMBER(38,0) NULL,
   "SCHOOL_NAME" NVARCHAR2(255) NULL,
   "BRANCH_NAME" NVARCHAR2(255) NULL,
   "LEVEL" NVARCHAR2(255) NULL,
   "CONTENT" NCLOB NULL,
   "CERTIFICATE" NVARCHAR2(255) NULL,
   "TRAINNING" NVARCHAR2(255) NULL,
   "FROMDATE" DATE NULL,
   "TODATE" DATE NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "RANK" NVARCHAR2(255) NULL,
   "YEAR_GRADUATE" NUMBER(38,0) NULL,
   "COST" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1000) NULL
);

-- Creating table 'RC_CANDIDATE_BEFOREWT'
CREATE TABLE "dbo"."RC_CANDIDATE_BEFOREWT" (
   "ID" NUMBER(38,0) NOT NULL,
   "CANDIDATE_ID" NUMBER(38,0) NULL,
   "ORG_NAME" NVARCHAR2(255) NULL,
   "TITLE_NAME" NVARCHAR2(255) NULL,
   "FROMDATE" DATE NULL,
   "TODATE" DATE NULL,
   "WORK" NVARCHAR2(255) NULL,
   "SALARY" NUMBER(38,0) NULL,
   "REFERENCE" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ORG_PHONE" NCLOB NULL,
   "ORG_ADDRESS" NCLOB NULL,
   "DIRECT_MANAGER" NCLOB NULL,
   "REASON_LEAVE" NCLOB NULL
);

-- Creating table 'RC_COST'
CREATE TABLE "dbo"."RC_COST" (
   "ID" NUMBER(38,0) NOT NULL,
   "RC_PROGRAM_ID" NUMBER(38,0) NULL,
   "COST_EXPECTED" NUMBER(38,0) NULL,
   "COST_DESCRIPTION" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "COST_ACTUAL" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "RC_FORM_NAMES" NCLOB NULL,
   "RC_STAGE_ID" NUMBER(38,0) NULL,
   "SOURCEOFREC_ID" NUMBER(38,0) NULL,
   "COSTESTIMATE" NUMBER(38,0) NULL,
   "COSTREALITY" NUMBER(38,0) NULL
);

-- Creating table 'RC_COST_FORM'
CREATE TABLE "dbo"."RC_COST_FORM" (
   "ID" NUMBER(38,0) NOT NULL,
   "RC_COST_ID" NUMBER(38,0) NULL,
   "RC_FORM_ID" NUMBER(38,0) NULL
);

-- Creating table 'HU_EMPLOYEE_BANK'
CREATE TABLE "dbo"."HU_EMPLOYEE_BANK" (
   "ID" NUMBER(38,0) NOT NULL,
   "BANK_ID" NUMBER(38,0) NULL,
   "BRANCH_ID" NUMBER(38,0) NULL,
   "ACCOUNT" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(1000) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NOT NULL,
   "CREATED_BY" NVARCHAR2(255) NOT NULL,
   "CREATED_LOG" NVARCHAR2(255) NOT NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_BY" NVARCHAR2(255) NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NOT NULL,
   "PAYMENT" NUMBER(5,0) NULL,
   "FROMDATE" DATE NULL,
   "TODATE" DATE NULL
);

-- Creating table 'HU_EMPLOYEE_BEFOREWT'
CREATE TABLE "dbo"."HU_EMPLOYEE_BEFOREWT" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ORG_NAME" NVARCHAR2(255) NULL,
   "TITLE_NAME" NVARCHAR2(255) NULL,
   "FROMDATE" DATE NULL,
   "TODATE" DATE NULL,
   "WORK" NVARCHAR2(255) NULL,
   "SALARY" NUMBER(38,0) NULL,
   "REFERENCE" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ORG_PHONE" NVARCHAR2(100) NULL,
   "ORG_ADDRESS" NVARCHAR2(255) NULL,
   "DIRECT_MANAGER" NVARCHAR2(255) NULL,
   "REASON_LEAVE" NVARCHAR2(255) NULL
);

-- Creating table 'HU_EMPLOYEE_EDUCATION'
CREATE TABLE "dbo"."HU_EMPLOYEE_EDUCATION" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "ACADEMY" NVARCHAR2(15) NULL,
   "HE_DAO_TAO" NUMBER(38,0) NULL,
   "HIGHEST_EDU" NUMBER(38,0) NULL,
   "HIGHEST_LEVEL" NUMBER(38,0) NULL,
   "TRAIN_FORM" NUMBER(38,0) NULL,
   "GRADUATE_YEAR" NUMBER(38,0) NULL,
   "MARK_EDU" NVARCHAR2(15) NULL,
   "COMPUTER_LEVEL" NVARCHAR2(15) NULL,
   "LANGUAGE_LEVEL" NVARCHAR2(15) NULL,
   "POLOTOCA_THEORY" NUMBER(38,0) NULL,
   "STATE_MNG" NUMBER(38,0) NULL,
   "ADD_INFO" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "SCHOOL_NAME" NVARCHAR2(255) NULL,
   "LEARNING_LEVEL" NVARCHAR2(15) NULL,
   "FIELD" NVARCHAR2(15) NULL,
   "SCHOOL" NVARCHAR2(15) NULL,
   "MAJOR" NVARCHAR2(15) NULL,
   "DEGREE" NVARCHAR2(15) NULL,
   "GPA" NUMBER(38,10) NULL,
   "IT_CERTIFICATE" NVARCHAR2(255) NULL,
   "IT_LEVEL" NVARCHAR2(15) NULL,
   "IT_MARK" NVARCHAR2(50) NULL,
   "IT_CERTIFICATE1" NVARCHAR2(255) NULL,
   "IT_LEVEL1" NVARCHAR2(15) NULL,
   "IT_MARK1" NVARCHAR2(50) NULL,
   "IT_CERTIFICATE2" NVARCHAR2(255) NULL,
   "IT_LEVEL2" NVARCHAR2(15) NULL,
   "IT_MARK2" NVARCHAR2(50) NULL,
   "ENGLISH" NVARCHAR2(255) NULL,
   "ENGLISH_LEVEL" NVARCHAR2(15) NULL,
   "ENGLISH_MARK" NVARCHAR2(50) NULL,
   "ENGLISH1" NVARCHAR2(255) NULL,
   "ENGLISH_LEVEL1" NVARCHAR2(15) NULL,
   "ENGLISH_MARK1" NVARCHAR2(50) NULL,
   "ENGLISH2" NVARCHAR2(255) NULL,
   "ENGLISH_LEVEL2" NVARCHAR2(15) NULL,
   "ENGLISH_MARK2" NVARCHAR2(50) NULL
);

-- Creating table 'HU_EMPLOYEE_HEALTH'
CREATE TABLE "dbo"."HU_EMPLOYEE_HEALTH" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "TENCOSO" NVARCHAR2(255) NULL,
   "CHIEUCAO" NVARCHAR2(255) NULL,
   "CANNANG" NVARCHAR2(255) NULL,
   "RANGHAMMAT" NVARCHAR2(255) NULL,
   "NHOMMAU" NVARCHAR2(255) NULL,
   "TIM" NVARCHAR2(255) NULL,
   "HUYETAP" NVARCHAR2(255) NULL,
   "PHOIVANGUC" NVARCHAR2(255) NULL,
   "THILUCMATRAI" NVARCHAR2(255) NULL,
   "VIEMGANB" NVARCHAR2(255) NULL,
   "THILUCMATPHAI" NVARCHAR2(255) NULL,
   "DALIEU" NVARCHAR2(255) NULL,
   "LOAISUCKHEO" NVARCHAR2(255) NULL,
   "MOTATHEM" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "NGAYKHAM" DATE NULL,
   "TAIMUIHONG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_EMPLOYEE_OTHER_INFO'
CREATE TABLE "dbo"."HU_EMPLOYEE_OTHER_INFO" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "NGAYVAOCONGDOAN" DATE NULL,
   "NOIVAOCONGDOAN" NVARCHAR2(255) NULL,
   "CONGDOANPHI" NUMBER(38,0) NULL,
   "RECRUITMENT_CODE" NVARCHAR2(255) NULL,
   "RECRUITMENT_REASON" NVARCHAR2(255) NULL,
   "RECRUITMENT_PRESENTER" NVARCHAR2(255) NULL,
   "EMPLOYEE_REPLACE_ID" NUMBER(38,0) NULL,
   "RECRUITMENT_NOTE" NVARCHAR2(255) NULL,
   "ACCOUNT_NAME" NVARCHAR2(255) NULL,
   "ACCOUNT_NUMBER" NUMBER(38,0) NULL,
   "BANK" NVARCHAR2(255) NULL,
   "BANK_BRANCH" NVARCHAR2(255) NULL,
   "IS_PAYMENT_VIA_BANK" NUMBER(5,0) NULL,
   "ACCOUNT_EFFECT_DATE" DATE NULL
);

-- Creating table 'HU_EMPLOYEE_TRAIN'
CREATE TABLE "dbo"."HU_EMPLOYEE_TRAIN" (
   "ID" NUMBER(38,0) NOT NULL,
   "FROM_DATE" DATE NULL,
   "TO_DATE" DATE NULL,
   "TRAINING_FORM" NUMBER(38,0) NULL,
   "LEARNING_LEVEL" NUMBER(38,0) NULL,
   "MAJOR" NUMBER(38,0) NULL,
   "GRADUATE_YEAR" NUMBER(38,0) NULL,
   "MARK" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "SCHOOL_NAME" NVARCHAR2(255) NULL,
   "TRAINING_CONTENT" NVARCHAR2(255) NULL
);

-- Creating table 'HU_EMPLOYEE_TRAINSINGER'
CREATE TABLE "dbo"."HU_EMPLOYEE_TRAINSINGER" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "SCHOOL_NAME" NVARCHAR2(255) NULL,
   "BRANCH_NAME" NVARCHAR2(255) NULL,
   "LEVEL" NVARCHAR2(255) NULL,
   "CONTENT" NVARCHAR2(255) NULL,
   "CERTIFICATE" NVARCHAR2(255) NULL,
   "TRAINNING" NVARCHAR2(255) NULL,
   "FROMDATE" DATE NULL,
   "TODATE" DATE NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "RANK" NVARCHAR2(255) NULL,
   "YEAR_GRADUATE" NUMBER(38,0) NULL,
   "COST" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(255) NULL
);

-- Creating table 'HU_EMPLOYEE'
CREATE TABLE "dbo"."HU_EMPLOYEE" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_CODE" NVARCHAR2(15) NULL,
   "FIRST_NAME_VN" NVARCHAR2(255) NULL,
   "LAST_NAME_VN" NVARCHAR2(255) NULL,
   "FULLNAME_VN" NVARCHAR2(255) NULL,
   "FIRST_NAME_EN" VARCHAR2(255) NULL,
   "LAST_NAME_EN" NVARCHAR2(255) NULL,
   "FULLNAME_EN" NVARCHAR2(255) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "WORK_STATUS" NUMBER(38,0) NULL,
   "CONTRACT_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "JOIN_DATE" DATE NULL,
   "DIRECT_MANAGER" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "LAST_WORKING_ID" NUMBER(38,0) NULL,
   "TER_EFFECT_DATE" DATE NULL,
   "TER_LAST_DATE" DATE NULL,
   "ITIME_ID" NUMBER(38,0) NULL,
   "STAFF_RANK_ID" NUMBER(38,0) NULL
);

-- Creating table 'HU_EMPLOYEE_CV'
CREATE TABLE "dbo"."HU_EMPLOYEE_CV" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "GENDER" NUMBER(38,0) NULL,
   "IMAGE" NVARCHAR2(255) NULL,
   "BIRTH_DATE" DATE NULL,
   "BIRTH_PLACE" NVARCHAR2(255) NULL,
   "MARITAL_STATUS" NUMBER(38,0) NULL,
   "RELIGION" NUMBER(38,0) NULL,
   "NATIVE" NUMBER(38,0) NULL,
   "NATIONALITY" NUMBER(38,0) NULL,
   "PER_ADDRESS" NVARCHAR2(255) NULL,
   "PER_PROVINCE" NUMBER(38,0) NULL,
   "HOME_PHONE" NVARCHAR2(255) NULL,
   "MOBILE_PHONE" NVARCHAR2(255) NULL,
   "ID_NO" NVARCHAR2(15) NULL,
   "ID_DATE" DATE NULL,
   "PASS_NO" NVARCHAR2(255) NULL,
   "PASS_DATE" DATE NULL,
   "PASS_EXPIRE" DATE NULL,
   "PASS_PLACE" NVARCHAR2(255) NULL,
   "VISA" NVARCHAR2(255) NULL,
   "VISA_DATE" DATE NULL,
   "VISA_EXPIRE" DATE NULL,
   "VISA_PLACE" NVARCHAR2(255) NULL,
   "WORK_PERMIT" NVARCHAR2(255) NULL,
   "WORK_PERMIT_DATE" DATE NULL,
   "WORK_PERMIT_EXPIRE" DATE NULL,
   "WORK_EMAIL" NVARCHAR2(255) NULL,
   "NAV_ADDRESS" NVARCHAR2(255) NULL,
   "NAV_PROVINCE" NUMBER(38,0) NULL,
   "PIT_CODE" VARCHAR2(255) NULL,
   "PER_EMAIL" NVARCHAR2(255) NULL,
   "CONTACT_PER" NVARCHAR2(255) NULL,
   "CONTACT_PER_PHONE" NVARCHAR2(15) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ID_PLACE" NVARCHAR2(255) NULL,
   "WORK_PERMIT_PLACE" NVARCHAR2(255) NULL,
   "BANK_ID" NUMBER(38,0) NULL,
   "BANK_BRANCH_ID" NUMBER(38,0) NULL,
   "NGAY_VAO_DOAN" DATE NULL,
   "NOI_VAO_DOAN" NVARCHAR2(255) NULL,
   "CHUC_VU_DOAN" NVARCHAR2(255) NULL,
   "DOAN_PHI" NUMBER(5,0) NULL,
   "NGAY_VAO_DANG" DATE NULL,
   "NOI_VAO_DANG" NVARCHAR2(255) NULL,
   "CHUC_VU_DANG" NVARCHAR2(255) NULL,
   "DANG_PHI" NUMBER(5,0) NULL,
   "BANK_NO" NVARCHAR2(255) NULL,
   "DRIVER_LICENSE" NVARCHAR2(255) NULL,
   "DRIVER_LICENSE_DATE" DATE NULL,
   "DRIVER_LICENSE_EXPIRE" DATE NULL,
   "CAREER" NVARCHAR2(255) NULL
);

-- Creating table 'HU_EMPLOYEE_EDUCATION1'
CREATE TABLE "dbo"."HU_EMPLOYEE_EDUCATION1" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "ACADEMY" NUMBER(38,0) NULL,
   "MAJOR" NUMBER(38,0) NULL,
   "COMPUTER_CER1" NVARCHAR2(255) NULL,
   "COMPUTER_CER2" NVARCHAR2(255) NULL,
   "COMPUTER_CER3" NVARCHAR2(255) NULL,
   "COMPUTER_LEVEL1" NUMBER(38,0) NULL,
   "COMPUTER_LEVEL2" NUMBER(38,0) NULL,
   "COMPUTER_LEVEL3" NUMBER(38,0) NULL,
   "COMPUTER_MARK1" NVARCHAR2(15) NULL,
   "COMPUTER_MARK2" NVARCHAR2(15) NULL,
   "COMPUTER_MARK3" NVARCHAR2(15) NULL,
   "LANGUAGE1" NUMBER(38,0) NULL,
   "LANGUAGE2" NUMBER(38,0) NULL,
   "LANGUAGE3" NUMBER(38,0) NULL,
   "LANGUAGE_LEVEL1" NUMBER(38,0) NULL,
   "LANGUAGE_LEVEL2" NUMBER(38,0) NULL,
   "LANGUAGE_LEVEL3" NUMBER(38,0) NULL,
   "LANGUAGE_MARK1" NVARCHAR2(15) NULL,
   "LANGUAGE_MARK2" NVARCHAR2(15) NULL,
   "LANGUAGE_MARK3" NVARCHAR2(15) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "GRADUATE_SCHOOL" NVARCHAR2(255) NULL,
   "MARK_EDU" NUMBER(38,0) NULL,
   "TRAINING_FORM" NUMBER(38,0) NULL,
   "LEARNING_LEVEL" NUMBER(38,0) NULL
);

-- Creating table 'HU_EMPLOYEE_HEALTH1'
CREATE TABLE "dbo"."HU_EMPLOYEE_HEALTH1" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "CHIEU_CAO" BINARY_DOUBLE NULL,
   "CAN_NANG" BINARY_DOUBLE NULL,
   "NHOM_MAU" NVARCHAR2(15) NULL,
   "HUYET_AP" NVARCHAR2(15) NULL,
   "MAT_TRAI" NVARCHAR2(15) NULL,
   "MAT_PHAI" NVARCHAR2(15) NULL,
   "TAI_MUI_HONG" NVARCHAR2(255) NULL,
   "RANG_HAM_MAT" NVARCHAR2(255) NULL,
   "TIM" NVARCHAR2(255) NULL,
   "PHOI_NGUC" NVARCHAR2(255) NULL,
   "VIEM_GAN_B" NVARCHAR2(255) NULL,
   "DA_HOA_LIEU" NVARCHAR2(255) NULL,
   "GHI_CHU_SUC_KHOE" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "LOAI_SUC_KHOE" NUMBER(38,0) NULL,
   "DU_SUC_KHOE" NUMBER(5,0) NULL
);

-- Creating table 'HU_EMPLOYEE_OTHER_INFO1'
CREATE TABLE "dbo"."HU_EMPLOYEE_OTHER_INFO1" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "NGAY_VAO_DOAN" DATE NULL,
   "NOI_VAO_DOAN" NVARCHAR2(255) NULL,
   "NOI_SINH_HOAT_DOAN" NVARCHAR2(255) NULL,
   "DOAN_PHI" NUMBER(5,0) NULL,
   "NGAY_VAO_DANG" DATE NULL,
   "NOI_VAO_DANG" NVARCHAR2(255) NULL,
   "NOI_SINH_HOAT_DANG" NVARCHAR2(255) NULL,
   "DANG_PHI" NUMBER(5,0) NULL,
   "SO_TAI_KHOAN" NVARCHAR2(255) NULL,
   "NGAN_HANG" NUMBER(38,0) NULL,
   "CHI_NHANH" NUMBER(38,0) NULL,
   "NGAY_HIEU_LUC" DATE NULL,
   "NGUOI_THU_HUONG" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_ORG_TITLE'
CREATE TABLE "dbo"."HU_ORG_TITLE" (
   "ID" NUMBER(38,0) NOT NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_ORGANIZATION'
CREATE TABLE "dbo"."HU_ORGANIZATION" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(35) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "PARENT_ID" NUMBER(38,0) NULL,
   "LEVEL_ID" NUMBER(38,0) NULL,
   "DISSOLVE_DATE" DATE NULL,
   "FOUNDATION_DATE" DATE NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "HIERARCHICAL_PATH" VARCHAR2(1023) NULL,
   "DESCRIPTION_PATH" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ADDRESS" NVARCHAR2(1023) NULL,
   "FAX" NVARCHAR2(1023) NULL,
   "REPRESENTATIVE_ID" NUMBER(38,0) NULL
);

-- Creating table 'HU_TITLE'
CREATE TABLE "dbo"."HU_TITLE" (
   "ID" NUMBER(38,0) NOT NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CODE" NVARCHAR2(16) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(255) NULL,
   "TITLE_GROUP_ID" NUMBER(38,0) NULL
);

-- Creating table 'HU_BANK'
CREATE TABLE "dbo"."HU_BANK" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(15) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "SHORT_NAME" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_BANK_BRANCH'
CREATE TABLE "dbo"."HU_BANK_BRANCH" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(15) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "BANK_ID" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_DISTRICT'
CREATE TABLE "dbo"."HU_DISTRICT" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "PROVINCE_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_NATION'
CREATE TABLE "dbo"."HU_NATION" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CODE" NVARCHAR2(15) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_PROVINCE'
CREATE TABLE "dbo"."HU_PROVINCE" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CODE" NVARCHAR2(255) NULL,
   "NATION_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'RC_STAGE'
CREATE TABLE "dbo"."RC_STAGE" (
   "ID" NUMBER(10,0) NOT NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "YEAR" NUMBER(38,0) NULL,
   "ORGANIZATIONNAME" NVARCHAR2(255) NULL,
   "TITLE" NVARCHAR2(500) NULL,
   "STARTDATE" DATE NULL,
   "ENDDATE" DATE NULL,
   "SOURCEOFREC_ID" NUMBER(38,0) NULL,
   "COSTESTIMATE" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(500) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(500) NULL,
   "REMARK" NVARCHAR2(2000) NULL
);

-- Creating table 'RC_COSTALLOCATE'
CREATE TABLE "dbo"."RC_COSTALLOCATE" (
   "ID" NUMBER(10,0) NOT NULL,
   "RC_STAGE_ID" NUMBER(38,0) NULL,
   "COSTAMOUNT" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(500) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(500) NULL,
   "REMARK" NVARCHAR2(2000) NULL,
   "ORG_ID" NUMBER(38,0) NULL
);

-- Creating table 'RC_COST_COSTALLOCATE'
CREATE TABLE "dbo"."RC_COST_COSTALLOCATE" (
   "ID" NUMBER(10,0) NOT NULL,
   "RC_COST_ID" NUMBER(38,0) NULL,
   "COSTAMOUNT" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(500) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(500) NULL,
   "REMARK" NVARCHAR2(2000) NULL,
   "ORG_ID" NUMBER(38,0) NULL
);

-- Creating table 'RC_MANNING_ORG'
CREATE TABLE "dbo"."RC_MANNING_ORG" (
   "Id" NUMBER(38,0) NOT NULL,
   "ORG_ID" NUMBER(38,0) NOT NULL,
   "NAME" NCLOB NOT NULL,
   "EFFECT_DATE" DATE NOT NULL,
   "NOTE" NCLOB NOT NULL,
   "OLD_MANNING" NUMBER(38,0) NOT NULL,
   "CURRENT_MANNING" NUMBER(38,0) NOT NULL,
   "NEW_MANNING" NUMBER(38,0) NOT NULL,
   "MOBILIZE_COUNT_MANNING" NUMBER(38,0) NOT NULL,
   "STATUS" NUMBER(38,0) NOT NULL
);

-- Creating table 'RC_MANNING_TITLE'
CREATE TABLE "dbo"."RC_MANNING_TITLE" (
   "Id" NUMBER(10,0) NOT NULL,
   "OLD_MANNING" NUMBER(38,0) NOT NULL,
   "CURRENT_MANNING" NUMBER(38,0) NOT NULL,
   "NEW_MANNING" NUMBER(38,0) NOT NULL,
   "MOBILIZE_COUNT_MANNING" NUMBER(38,0) NOT NULL,
   "TITLE_ID" NUMBER(38,0) NOT NULL,
   "NOTE" NVARCHAR2(255) NOT NULL,
   "MANNING_ORG_ID" NUMBER(38,0) NOT NULL
);

-- Creating table 'RC_CANDIDATE_EXPECT'
CREATE TABLE "dbo"."RC_CANDIDATE_EXPECT" (
   "CANDIDATE_ID" NUMBER(38,0) NOT NULL,
   "TIME_START" NCLOB NULL,
   "PROBATIONARY_SALARY" NUMBER(38,0) NULL,
   "OFFICIAL_SALARY" NUMBER(38,0) NULL,
   "DATE_START" DATE NULL,
   "OTHER_REQUEST" NCLOB NULL,
   "WORK_LOCATION" NVARCHAR2(500) NULL
);

-- Creating table 'RC_CANDIDATE_HEALTH'
CREATE TABLE "dbo"."RC_CANDIDATE_HEALTH" (
   "CANDIDATE_ID" NUMBER(38,0) NOT NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NCLOB NULL,
   "CREATED_LOG" NCLOB NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NCLOB NULL,
   "CHIEU_CAO" NCLOB NULL,
   "CAN_NANG" NCLOB NULL,
   "NHOM_MAU" NCLOB NULL,
   "HUYET_AP" NCLOB NULL,
   "MAT_TRAI" NCLOB NULL,
   "MAT_PHAI" NCLOB NULL,
   "LOAI_SUC_KHOE" NCLOB NULL,
   "TAI_MUI_HONG" NCLOB NULL,
   "RANG_HAM_MAT" NCLOB NULL,
   "TIM" NCLOB NULL,
   "PHOI_NGUC" NCLOB NULL,
   "VIEM_GAN_B" NCLOB NULL,
   "DA_HOA_LIEU" NCLOB NULL,
   "GHI_CHU_SUC_KHOE" NCLOB NULL
);

-- Creating table 'RC_CANDIDATE_REFERENCE'
CREATE TABLE "dbo"."RC_CANDIDATE_REFERENCE" (
   "ID" NUMBER(38,0) NOT NULL,
   "FULLNAME" NCLOB NOT NULL,
   "TITLE_NAME" NCLOB NOT NULL,
   "WORK_UNIT" NCLOB NOT NULL,
   "ADDRESS_CONTACT" NCLOB NOT NULL,
   "PHONENUMBER" NCLOB NOT NULL,
   "CANDIDATE_ID" NUMBER(38,0) NULL
);

-- Creating table 'RC_PROGRAM'
CREATE TABLE "dbo"."RC_PROGRAM" (
   "ID" NUMBER(38,0) NOT NULL,
   "IS_IN_PLAN" NUMBER(5,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "PIC_ID" NUMBER(38,0) NULL,
   "SEND_DATE" DATE NULL,
   "RECRUIT_TYPE_ID" NUMBER(38,0) NULL,
   "RECRUIT_REASON_ID" NUMBER(38,0) NULL,
   "RECRUIT_REASON" NVARCHAR2(1023) NULL,
   "GROUP_WORK_ID" NVARCHAR2(255) NULL,
   "PRIORITY_LEVEL_ID" NVARCHAR2(255) NULL,
   "IS_PORTAL" NUMBER(5,0) NULL,
   "CODE" NVARCHAR2(50) NULL,
   "JOB_NAME" NVARCHAR2(255) NULL,
   "DESCRIPTION" NVARCHAR2(1023) NULL,
   "REQUEST_EXPERIENCE" NVARCHAR2(1023) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "RECRUIT_START" DATE NULL,
   "RECEIVE_END" DATE NULL,
   "LEARNING_LEVEL_ID" NVARCHAR2(255) NULL,
   "EXPERIENCE_NUMBER" NUMBER(38,0) NULL,
   "TRAINING_LEVEL_MAIN_ID" NVARCHAR2(255) NULL,
   "TRAINING_SCHOOL_MAIN_ID" NVARCHAR2(255) NULL,
   "MAJOR_MAIN_ID" NVARCHAR2(255) NULL,
   "GRADUATION_TYPE_MAIN_ID" NVARCHAR2(255) NULL,
   "TRAINING_LEVEL_SUB_ID" NVARCHAR2(255) NULL,
   "TRAINING_SCHOOL_SUB_ID" NVARCHAR2(255) NULL,
   "MAJOR_SUB_ID" NVARCHAR2(255) NULL,
   "GRADUATION_TYPE_SUB_ID" NVARCHAR2(255) NULL,
   "LANGUAGE1_ID" NVARCHAR2(255) NULL,
   "LANGUAGE1_LEVEL_ID" NVARCHAR2(255) NULL,
   "LANGUAGE1_POINT_ID" NVARCHAR2(255) NULL,
   "LANGUAGE2_ID" NVARCHAR2(255) NULL,
   "LANGUAGE2_LEVEL_ID" NVARCHAR2(255) NULL,
   "LANGUAGE2_POINT_ID" NVARCHAR2(255) NULL,
   "LANGUAGE3_ID" NVARCHAR2(255) NULL,
   "LANGUAGE3_LEVEL_ID" NVARCHAR2(255) NULL,
   "LANGUAGE3_POINT_ID" NVARCHAR2(255) NULL,
   "COMPUTER_LEVEL_ID" NVARCHAR2(255) NULL,
   "AGE_FROM" NUMBER(38,0) NULL,
   "AGE_TO" NUMBER(38,0) NULL,
   "GENDER_ID" NVARCHAR2(255) NULL,
   "CHIEUCAO" NVARCHAR2(255) NULL,
   "CANNANG" NUMBER(38,0) NULL,
   "CONTRACT_TYPE_ID" NUMBER(38,0) NULL,
   "APPEARANCE_ID" NVARCHAR2(255) NULL,
   "THILUCTRAI" NVARCHAR2(255) NULL,
   "THILUCPHAI" NVARCHAR2(255) NULL,
   "HEALTH_STATUS_ID" NVARCHAR2(255) NULL,
   "STATUS_ID" NVARCHAR2(255) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "REQUEST_NUMBER" NUMBER(38,0) NULL,
   "RC_REQUEST_ID" NUMBER(38,0) NULL,
   "WORK_TIME_ID" NUMBER(38,0) NULL,
   "REQUEST_SALARY_FROM" NUMBER(38,0) NULL,
   "STAGE_ID" NUMBER(38,0) NULL,
   "REQUEST_SALARY_TO" NUMBER(38,0) NULL,
   "FOLLOWERS_EMP_ID" NUMBER(38,0) NULL,
   "STAGERECRUITMENT_ID" NUMBER(38,0) NULL,
   "NEGOTIABLESALARY" NUMBER(38,0) NULL,
   "POSITIONRECRUITMENT" NVARCHAR2(1023) NULL,
   "REQUESTOTHER" VARCHAR2(1023) NULL,
   "SPECIALSKILLS" NUMBER(38,0) NULL
);

-- Creating table 'SE_USER'
CREATE TABLE "dbo"."SE_USER" (
   "ID" NUMBER(38,0) NOT NULL,
   "USERNAME" NVARCHAR2(255) NULL,
   "PASSWORD" NVARCHAR2(255) NULL,
   "FULLNAME" NVARCHAR2(255) NULL,
   "EMAIL" NVARCHAR2(255) NULL,
   "TELEPHONE" NVARCHAR2(255) NULL,
   "IS_APP" NUMBER(5,0) NULL,
   "IS_PORTAL" NUMBER(5,0) NULL,
   "EMPLOYEE_CODE" VARCHAR2(15) NULL,
   "IS_AD" NUMBER(5,0) NULL,
   "EFFECT_DATE" DATE NULL,
   "EXPIRE_DATE" DATE NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "LOCATION" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "IS_CHANGE_PASS" NUMBER(5,0) NULL,
   "CHANGE_PASS_DATE" DATE NULL,
   "REMINDER_COUNT" NUMBER(5,0) NULL,
   "MODULE_ADMIN" NVARCHAR2(255) NULL
);

-- Creating table 'SE_REPORT'
CREATE TABLE "dbo"."SE_REPORT" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NULL,
   "MODULE_ID" NUMBER(38,0) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "CODE" NVARCHAR2(255) NULL
);

-- Creating table 'SE_USER_REPORT'
CREATE TABLE "dbo"."SE_USER_REPORT" (
   "SE_REPORT_ID" NUMBER(38,0) NOT NULL,
   "SE_USER_ID" NUMBER(38,0) NOT NULL
);

-- Creating table 'HU_WARD'
CREATE TABLE "dbo"."HU_WARD" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CODE" NVARCHAR2(255) NULL,
   "DISTRICT_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "NOTE" NVARCHAR2(1023) NULL
);

-- Creating table 'HU_ORGANIZATION_V'
CREATE TABLE "dbo"."HU_ORGANIZATION_V" (
   "CODE_C1" VARCHAR2(4000) NULL,
   "NAME_C1" NVARCHAR2(1999) NULL,
   "CODE_C2" VARCHAR2(4000) NULL,
   "NAME_C2" NVARCHAR2(1999) NULL,
   "CODE_C3" VARCHAR2(4000) NULL,
   "NAME_C3" NVARCHAR2(1999) NULL,
   "CODE_C4" VARCHAR2(4000) NULL,
   "NAME_C4" NVARCHAR2(1999) NULL,
   "CODE_C5" VARCHAR2(4000) NULL,
   "NAME_C5" NVARCHAR2(1999) NULL,
   "CODE_C6" VARCHAR2(4000) NULL,
   "NAME_C6" NVARCHAR2(1999) NULL,
   "CODE_C7" VARCHAR2(4000) NULL,
   "NAME_C7" NVARCHAR2(1999) NULL,
   "CODE_C8" VARCHAR2(4000) NULL,
   "NAME_C8" NVARCHAR2(1999) NULL,
   "CODE_C9" VARCHAR2(4000) NULL,
   "NAME_C9" NVARCHAR2(1999) NULL,
   "LEVEL_ID" NUMBER(38,0) NULL,
   "DESCRIPTION" NVARCHAR2(2000) NULL,
   "ID" NUMBER(38,0) NOT NULL,
   "ID1" VARCHAR2(4000) NULL,
   "ID2" VARCHAR2(4000) NULL,
   "ID3" VARCHAR2(4000) NULL,
   "ID4" VARCHAR2(4000) NULL,
   "ID5" VARCHAR2(4000) NULL,
   "ID6" VARCHAR2(4000) NULL,
   "ID7" VARCHAR2(4000) NULL,
   "ID8" VARCHAR2(4000) NULL,
   "ID9" VARCHAR2(4000) NULL,
   "DESCRIPTION4" NVARCHAR2(2000) NULL,
   "NAME_VN" NVARCHAR2(255) NULL
);

-- Creating table 'RC_CANDIDATE_TRAINNING'
CREATE TABLE "dbo"."RC_CANDIDATE_TRAINNING" (
   "ID" NUMBER(38,0) NOT NULL,
   "YEAR_GRA" NUMBER(38,0) NULL,
   "NAME_SHOOLS" NVARCHAR2(255) NULL,
   "FORM_TRAIN_ID" NUMBER(38,0) NULL,
   "SPECIALIZED_TRAIN" NVARCHAR2(255) NULL,
   "RESULT_TRAIN" NVARCHAR2(255) NULL,
   "CERTIFICATE" NUMBER(38,0) NULL,
   "EFFECTIVE_DATE_FROM" DATE NULL,
   "EFFECTIVE_DATE_TO" DATE NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "CANDIDATE_ID" NUMBER(38,0) NULL,
   "FROM_DATE" DATE NULL,
   "TO_DATE" DATE NULL,
   "UPLOAD_FILE" NVARCHAR2(1025) NULL,
   "FILE_NAME" NVARCHAR2(500) NULL,
   "TYPE_TRAIN_ID" NUMBER(38,0) NULL,
   "RECEIVE_DEGREE_DATE" DATE NULL,
   "IS_RENEWED" NUMBER(38,0) NULL,
   "LEVEL_ID" NUMBER(38,0) NULL,
   "POINT_LEVEL" NVARCHAR2(500) NULL,
   "CONTENT_LEVEL" NVARCHAR2(500) NULL,
   "NOTE" NVARCHAR2(1000) NULL,
   "CERTIFICATE_CODE" NVARCHAR2(50) NULL,
   "TYPE_TRAIN_NAME" NVARCHAR2(50) NULL,
   "COST" NUMBER(38,0) NULL
);

-- Creating table 'RC_PLAN_YEAR'
CREATE TABLE "dbo"."RC_PLAN_YEAR" (
   "ID" NUMBER(38,0) NOT NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "YEAR" NUMBER(38,0) NULL,
   "QUANTITY_CURRENT" NUMBER(38,0) NULL,
   "QUANTITY_NEEDED" NUMBER(38,0) NULL,
   "QUANTITY_RECEIVED" NUMBER(38,0) NULL,
   "MONTH_1" NUMBER(38,0) NULL,
   "MONTH_2" NUMBER(38,0) NULL,
   "MONTH_3" NUMBER(38,0) NULL,
   "MONTH_4" NUMBER(38,0) NULL,
   "MONTH_5" NUMBER(38,0) NULL,
   "MONTH_6" NUMBER(38,0) NULL,
   "MONTH_7" NUMBER(38,0) NULL,
   "MONTH_8" NUMBER(38,0) NULL,
   "MONTH_9" NUMBER(38,0) NULL,
   "MONTH_10" NUMBER(38,0) NULL,
   "MONTH_11" NUMBER(38,0) NULL,
   "MONTH_12" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL
);

-- Creating table 'RC_RECRUITMENT_INSTEAD'
CREATE TABLE "dbo"."RC_RECRUITMENT_INSTEAD" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "REQUEST_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);


-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on "ID"in table 'RC_COST_CENTER'
ALTER TABLE "dbo"."RC_COST_CENTER"
ADD CONSTRAINT "PK_RC_COST_CENTER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ORG_ID", "USERNAME"in table 'SE_CHOSEN_ORG'
ALTER TABLE "dbo"."SE_CHOSEN_ORG"
ADD CONSTRAINT "PK_SE_CHOSEN_ORG"
   PRIMARY KEY ("ORG_ID", "USERNAME" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_FAMILY'
ALTER TABLE "dbo"."HU_FAMILY"
ADD CONSTRAINT "PK_HU_FAMILY"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_TERMINATE'
ALTER TABLE "dbo"."HU_TERMINATE"
ADD CONSTRAINT "PK_HU_TERMINATE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_EXAMS'
ALTER TABLE "dbo"."RC_EXAMS"
ADD CONSTRAINT "PK_RC_EXAMS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_EXAMS_DTL'
ALTER TABLE "dbo"."RC_EXAMS_DTL"
ADD CONSTRAINT "PK_RC_EXAMS_DTL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_PLAN_REG_EMP'
ALTER TABLE "dbo"."RC_PLAN_REG_EMP"
ADD CONSTRAINT "PK_RC_PLAN_REG_EMP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_PROGRAM_CHARACTER'
ALTER TABLE "dbo"."RC_PROGRAM_CHARACTER"
ADD CONSTRAINT "PK_RC_PROGRAM_CHARACTER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_PROGRAM_EMP'
ALTER TABLE "dbo"."RC_PROGRAM_EMP"
ADD CONSTRAINT "PK_RC_PROGRAM_EMP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_PROGRAM_EXAMS'
ALTER TABLE "dbo"."RC_PROGRAM_EXAMS"
ADD CONSTRAINT "PK_RC_PROGRAM_EXAMS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_PROGRAM_SCOPE'
ALTER TABLE "dbo"."RC_PROGRAM_SCOPE"
ADD CONSTRAINT "PK_RC_PROGRAM_SCOPE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_PROGRAM_SOFT_SKILL'
ALTER TABLE "dbo"."RC_PROGRAM_SOFT_SKILL"
ADD CONSTRAINT "PK_RC_PROGRAM_SOFT_SKILL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_REQUEST'
ALTER TABLE "dbo"."RC_REQUEST"
ADD CONSTRAINT "PK_RC_REQUEST"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_REQUEST_EMP'
ALTER TABLE "dbo"."RC_REQUEST_EMP"
ADD CONSTRAINT "PK_RC_REQUEST_EMP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST'
ALTER TABLE "dbo"."OT_OTHER_LIST"
ADD CONSTRAINT "PK_OT_OTHER_LIST"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST_GROUP'
ALTER TABLE "dbo"."OT_OTHER_LIST_GROUP"
ADD CONSTRAINT "PK_OT_OTHER_LIST_GROUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST_TYPE'
ALTER TABLE "dbo"."OT_OTHER_LIST_TYPE"
ADD CONSTRAINT "PK_OT_OTHER_LIST_TYPE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_PLAN_REG'
ALTER TABLE "dbo"."RC_PLAN_REG"
ADD CONSTRAINT "PK_RC_PLAN_REG"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_CONTRACT_TYPE'
ALTER TABLE "dbo"."HU_CONTRACT_TYPE"
ADD CONSTRAINT "PK_HU_CONTRACT_TYPE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_CANDIDATE'
ALTER TABLE "dbo"."RC_CANDIDATE"
ADD CONSTRAINT "PK_RC_CANDIDATE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "CANDIDATE_ID"in table 'RC_CANDIDATE_EDUCATION'
ALTER TABLE "dbo"."RC_CANDIDATE_EDUCATION"
ADD CONSTRAINT "PK_RC_CANDIDATE_EDUCATION"
   PRIMARY KEY ("CANDIDATE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "CANDIDATE_ID"in table 'RC_CANDIDATE_HISTORY'
ALTER TABLE "dbo"."RC_CANDIDATE_HISTORY"
ADD CONSTRAINT "PK_RC_CANDIDATE_HISTORY"
   PRIMARY KEY ("CANDIDATE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "CANDIDATE_ID"in table 'RC_CANDIDATE_OTHER_INFO'
ALTER TABLE "dbo"."RC_CANDIDATE_OTHER_INFO"
ADD CONSTRAINT "PK_RC_CANDIDATE_OTHER_INFO"
   PRIMARY KEY ("CANDIDATE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "CANDIDATE_ID"in table 'RC_CANDIDATE_CV'
ALTER TABLE "dbo"."RC_CANDIDATE_CV"
ADD CONSTRAINT "PK_RC_CANDIDATE_CV"
   PRIMARY KEY ("CANDIDATE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_PROGRAM_SCHEDULE'
ALTER TABLE "dbo"."RC_PROGRAM_SCHEDULE"
ADD CONSTRAINT "PK_RC_PROGRAM_SCHEDULE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_PROGRAM_SCHEDULE_CAN'
ALTER TABLE "dbo"."RC_PROGRAM_SCHEDULE_CAN"
ADD CONSTRAINT "PK_RC_PROGRAM_SCHEDULE_CAN"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_PROGRAM_SCHEDULE_USHER'
ALTER TABLE "dbo"."RC_PROGRAM_SCHEDULE_USHER"
ADD CONSTRAINT "PK_RC_PROGRAM_SCHEDULE_USHER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_CANDIDATE_FAMILY'
ALTER TABLE "dbo"."RC_CANDIDATE_FAMILY"
ADD CONSTRAINT "PK_RC_CANDIDATE_FAMILY"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_CANDIDATE_TRAINSINGER'
ALTER TABLE "dbo"."RC_CANDIDATE_TRAINSINGER"
ADD CONSTRAINT "PK_RC_CANDIDATE_TRAINSINGER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_CANDIDATE_BEFOREWT'
ALTER TABLE "dbo"."RC_CANDIDATE_BEFOREWT"
ADD CONSTRAINT "PK_RC_CANDIDATE_BEFOREWT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_COST'
ALTER TABLE "dbo"."RC_COST"
ADD CONSTRAINT "PK_RC_COST"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_COST_FORM'
ALTER TABLE "dbo"."RC_COST_FORM"
ADD CONSTRAINT "PK_RC_COST_FORM"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE_BANK'
ALTER TABLE "dbo"."HU_EMPLOYEE_BANK"
ADD CONSTRAINT "PK_HU_EMPLOYEE_BANK"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE_BEFOREWT'
ALTER TABLE "dbo"."HU_EMPLOYEE_BEFOREWT"
ADD CONSTRAINT "PK_HU_EMPLOYEE_BEFOREWT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_EDUCATION'
ALTER TABLE "dbo"."HU_EMPLOYEE_EDUCATION"
ADD CONSTRAINT "PK_HU_EMPLOYEE_EDUCATION"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE_HEALTH'
ALTER TABLE "dbo"."HU_EMPLOYEE_HEALTH"
ADD CONSTRAINT "PK_HU_EMPLOYEE_HEALTH"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_OTHER_INFO'
ALTER TABLE "dbo"."HU_EMPLOYEE_OTHER_INFO"
ADD CONSTRAINT "PK_HU_EMPLOYEE_OTHER_INFO"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE_TRAIN'
ALTER TABLE "dbo"."HU_EMPLOYEE_TRAIN"
ADD CONSTRAINT "PK_HU_EMPLOYEE_TRAIN"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE_TRAINSINGER'
ALTER TABLE "dbo"."HU_EMPLOYEE_TRAINSINGER"
ADD CONSTRAINT "PK_HU_EMPLOYEE_TRAINSINGER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "PK_HU_EMPLOYEE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_CV'
ALTER TABLE "dbo"."HU_EMPLOYEE_CV"
ADD CONSTRAINT "PK_HU_EMPLOYEE_CV"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_EDUCATION1'
ALTER TABLE "dbo"."HU_EMPLOYEE_EDUCATION1"
ADD CONSTRAINT "PK_HU_EMPLOYEE_EDUCATION1"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_HEALTH1'
ALTER TABLE "dbo"."HU_EMPLOYEE_HEALTH1"
ADD CONSTRAINT "PK_HU_EMPLOYEE_HEALTH1"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_OTHER_INFO1'
ALTER TABLE "dbo"."HU_EMPLOYEE_OTHER_INFO1"
ADD CONSTRAINT "PK_HU_EMPLOYEE_OTHER_INFO1"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ORG_TITLE'
ALTER TABLE "dbo"."HU_ORG_TITLE"
ADD CONSTRAINT "PK_HU_ORG_TITLE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ORGANIZATION'
ALTER TABLE "dbo"."HU_ORGANIZATION"
ADD CONSTRAINT "PK_HU_ORGANIZATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_TITLE'
ALTER TABLE "dbo"."HU_TITLE"
ADD CONSTRAINT "PK_HU_TITLE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_BANK'
ALTER TABLE "dbo"."HU_BANK"
ADD CONSTRAINT "PK_HU_BANK"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_BANK_BRANCH'
ALTER TABLE "dbo"."HU_BANK_BRANCH"
ADD CONSTRAINT "PK_HU_BANK_BRANCH"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_DISTRICT'
ALTER TABLE "dbo"."HU_DISTRICT"
ADD CONSTRAINT "PK_HU_DISTRICT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_NATION'
ALTER TABLE "dbo"."HU_NATION"
ADD CONSTRAINT "PK_HU_NATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_PROVINCE'
ALTER TABLE "dbo"."HU_PROVINCE"
ADD CONSTRAINT "PK_HU_PROVINCE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_STAGE'
ALTER TABLE "dbo"."RC_STAGE"
ADD CONSTRAINT "PK_RC_STAGE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_COSTALLOCATE'
ALTER TABLE "dbo"."RC_COSTALLOCATE"
ADD CONSTRAINT "PK_RC_COSTALLOCATE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_COST_COSTALLOCATE'
ALTER TABLE "dbo"."RC_COST_COSTALLOCATE"
ADD CONSTRAINT "PK_RC_COST_COSTALLOCATE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "Id"in table 'RC_MANNING_ORG'
ALTER TABLE "dbo"."RC_MANNING_ORG"
ADD CONSTRAINT "PK_RC_MANNING_ORG"
   PRIMARY KEY ("Id" )
   ENABLE
   VALIDATE;


-- Creating primary key on "Id"in table 'RC_MANNING_TITLE'
ALTER TABLE "dbo"."RC_MANNING_TITLE"
ADD CONSTRAINT "PK_RC_MANNING_TITLE"
   PRIMARY KEY ("Id" )
   ENABLE
   VALIDATE;


-- Creating primary key on "CANDIDATE_ID"in table 'RC_CANDIDATE_EXPECT'
ALTER TABLE "dbo"."RC_CANDIDATE_EXPECT"
ADD CONSTRAINT "PK_RC_CANDIDATE_EXPECT"
   PRIMARY KEY ("CANDIDATE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "CANDIDATE_ID"in table 'RC_CANDIDATE_HEALTH'
ALTER TABLE "dbo"."RC_CANDIDATE_HEALTH"
ADD CONSTRAINT "PK_RC_CANDIDATE_HEALTH"
   PRIMARY KEY ("CANDIDATE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_CANDIDATE_REFERENCE'
ALTER TABLE "dbo"."RC_CANDIDATE_REFERENCE"
ADD CONSTRAINT "PK_RC_CANDIDATE_REFERENCE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_PROGRAM'
ALTER TABLE "dbo"."RC_PROGRAM"
ADD CONSTRAINT "PK_RC_PROGRAM"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_USER'
ALTER TABLE "dbo"."SE_USER"
ADD CONSTRAINT "PK_SE_USER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_REPORT'
ALTER TABLE "dbo"."SE_REPORT"
ADD CONSTRAINT "PK_SE_REPORT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "SE_REPORT_ID", "SE_USER_ID"in table 'SE_USER_REPORT'
ALTER TABLE "dbo"."SE_USER_REPORT"
ADD CONSTRAINT "PK_SE_USER_REPORT"
   PRIMARY KEY ("SE_REPORT_ID", "SE_USER_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_WARD'
ALTER TABLE "dbo"."HU_WARD"
ADD CONSTRAINT "PK_HU_WARD"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ORGANIZATION_V'
ALTER TABLE "dbo"."HU_ORGANIZATION_V"
ADD CONSTRAINT "PK_HU_ORGANIZATION_V"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_CANDIDATE_TRAINNING'
ALTER TABLE "dbo"."RC_CANDIDATE_TRAINNING"
ADD CONSTRAINT "PK_RC_CANDIDATE_TRAINNING"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_PLAN_YEAR'
ALTER TABLE "dbo"."RC_PLAN_YEAR"
ADD CONSTRAINT "PK_RC_PLAN_YEAR"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'RC_RECRUITMENT_INSTEAD'
ALTER TABLE "dbo"."RC_RECRUITMENT_INSTEAD"
ADD CONSTRAINT "PK_RC_RECRUITMENT_INSTEAD"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_HEALTH1'
ALTER TABLE "dbo"."HU_EMPLOYEE_HEALTH1"
ADD CONSTRAINT "FK_FE_HEH"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_CV'
ALTER TABLE "dbo"."HU_EMPLOYEE_CV"
ADD CONSTRAINT "FK_HE_HEC"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_EDUCATION1'
ALTER TABLE "dbo"."HU_EMPLOYEE_EDUCATION1"
ADD CONSTRAINT "FK_HE_HEE"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_OTHER_INFO1'
ALTER TABLE "dbo"."HU_EMPLOYEE_OTHER_INFO1"
ADD CONSTRAINT "FK_HE_HEO"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "TITLE_ID" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HE_HT"
   FOREIGN KEY ("TITLE_ID")
   REFERENCES "dbo"."HU_TITLE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HE_HT'
CREATE INDEX "IX_FK_HE_HT"
ON "dbo"."HU_EMPLOYEE"
   ("TITLE_ID");

-- Creating foreign key on "ORG_ID" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HU_ORG_HU_EMP"
   FOREIGN KEY ("ORG_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_ORG_HU_EMP'
CREATE INDEX "IX_FK_HU_ORG_HU_EMP"
ON "dbo"."HU_EMPLOYEE"
   ("ORG_ID");

-- Creating foreign key on "DIRECT_MANAGER" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HUEMD_HUEM"
   FOREIGN KEY ("DIRECT_MANAGER")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUEMD_HUEM'
CREATE INDEX "IX_FK_HUEMD_HUEM"
ON "dbo"."HU_EMPLOYEE"
   ("DIRECT_MANAGER");

-- Creating foreign key on "ORG_ID" in table 'HU_ORG_TITLE'
ALTER TABLE "dbo"."HU_ORG_TITLE"
ADD CONSTRAINT "FK_HUOG_HUOT"
   FOREIGN KEY ("ORG_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUOG_HUOT'
CREATE INDEX "IX_FK_HUOG_HUOT"
ON "dbo"."HU_ORG_TITLE"
   ("ORG_ID");

-- Creating foreign key on "TITLE_ID" in table 'HU_ORG_TITLE'
ALTER TABLE "dbo"."HU_ORG_TITLE"
ADD CONSTRAINT "FK_HUTL_HUOT"
   FOREIGN KEY ("TITLE_ID")
   REFERENCES "dbo"."HU_TITLE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUTL_HUOT'
CREATE INDEX "IX_FK_HUTL_HUOT"
ON "dbo"."HU_ORG_TITLE"
   ("TITLE_ID");

-- Creating foreign key on "PARENT_ID" in table 'HU_ORGANIZATION'
ALTER TABLE "dbo"."HU_ORGANIZATION"
ADD CONSTRAINT "FK_HU_ORG_HU_ORG"
   FOREIGN KEY ("PARENT_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_ORG_HU_ORG'
CREATE INDEX "IX_FK_HU_ORG_HU_ORG"
ON "dbo"."HU_ORGANIZATION"
   ("PARENT_ID");

-- Creating foreign key on "BANK_ID" in table 'HU_BANK_BRANCH'
ALTER TABLE "dbo"."HU_BANK_BRANCH"
ADD CONSTRAINT "FK_BANKBANK_BRANCH"
   FOREIGN KEY ("BANK_ID")
   REFERENCES "dbo"."HU_BANK"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_BANKBANK_BRANCH'
CREATE INDEX "IX_FK_BANKBANK_BRANCH"
ON "dbo"."HU_BANK_BRANCH"
   ("BANK_ID");

-- Creating foreign key on "PROVINCE_ID" in table 'HU_DISTRICT'
ALTER TABLE "dbo"."HU_DISTRICT"
ADD CONSTRAINT "FK_HU_PRO_HU_DIS"
   FOREIGN KEY ("PROVINCE_ID")
   REFERENCES "dbo"."HU_PROVINCE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_PRO_HU_DIS'
CREATE INDEX "IX_FK_HU_PRO_HU_DIS"
ON "dbo"."HU_DISTRICT"
   ("PROVINCE_ID");

-- Creating foreign key on "NATION_ID" in table 'HU_PROVINCE'
ALTER TABLE "dbo"."HU_PROVINCE"
ADD CONSTRAINT "FK_HU_NAT_HU_PRO"
   FOREIGN KEY ("NATION_ID")
   REFERENCES "dbo"."HU_NATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_NAT_HU_PRO'
CREATE INDEX "IX_FK_HU_NAT_HU_PRO"
ON "dbo"."HU_PROVINCE"
   ("NATION_ID");

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------
