'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctrlHU_EmpDtlProfile

    '''<summary>
    '''phPopupOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phPopupOrg As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''phPopupDirect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phPopupDirect As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''phPopupLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phPopupLevel As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''ctrlMessageBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlMessageBox As Global.Common.ctrlMessageBox

    '''<summary>
    '''RadSplitter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitter1 As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''ToolbarPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolbarPane As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''tbarMainToolBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbarMainToolBar As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''RadPane1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane1 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblChucDanh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChucDanh As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQLTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQLTT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPhongBan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPhongBan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQLTMC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQLTMC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DetailPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DetailPane As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''rtabProfileInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtabProfileInfo As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''rtIdEmpInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtIdEmpInfo As Global.Telerik.Web.UI.RadTab

    '''<summary>
    '''rtIdEmpPaper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtIdEmpPaper As Global.Telerik.Web.UI.RadTab

    '''<summary>
    '''rtIdTitleConcurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtIdTitleConcurrent As Global.Telerik.Web.UI.RadTab

    '''<summary>
    '''RadMultiPage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPage1 As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''rpvEmpInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpvEmpInfo As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''valSum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valSum As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''hidID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidIsTer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidIsTer As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidContractID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidContractID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidWorkingID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidWorkingID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidPrevious As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidNext As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidOrgID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidOrgID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidDirectManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidDirectManager As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidLevelManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidLevelManager As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtEmpCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmpCODE As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtFirstNameVN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstNameVN As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''reqFirstNameVN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqFirstNameVN As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtLastNameVN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastNameVN As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''reqLastNameVN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqLastNameVN As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtTimeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTimeID As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cusTimeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cusTimeID As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''cboEmpStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboEmpStatus As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''chkSaveHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSaveHistory As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''RadPanelBar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPanelBar1 As Global.Telerik.Web.UI.RadPanelBar

    '''<summary>
    '''txtOrgName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrgName2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''btnFindOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFindOrg As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtOrgName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrgName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtBan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBan As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTo As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cboTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTitle As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cusTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cusTitle As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''txtTitleGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTitleGroup As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cboStaffRank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboStaffRank As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtDirectManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDirectManager As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''btnFindDirect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFindDirect As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''txtManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManager As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rdBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdBirthDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''cboGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGender As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cusGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cusGender As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''cboWorkplace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboWorkplace As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtID_NO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtID_NO As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RequiredFieldValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cusNO_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cusNO_ID As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''rdIDDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdIDDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''cboIDPlace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboIDPlace As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cboNationlity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboNationlity As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cboNative control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboNative As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cboBIRTH_PLACE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboBIRTH_PLACE As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cboReligion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboReligion As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cboInsRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboInsRegion As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cusInsRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cusInsRegion As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''rdJoinDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdJoinDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''rdter_effect_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdter_effect_date As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''cboWorkStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboWorkStatus As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtPerAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPerAddress As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RequiredFieldValidator5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator5 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cboPer_Province control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPer_Province As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cusPer_Province control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cusPer_Province As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''cboPer_District control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPer_District As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cusPer_District control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cusPer_District As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''cboPer_Ward control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPer_Ward As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtNavAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNavAddress As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cboNav_Province control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboNav_Province As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cboNav_District control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboNav_District As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cboNav_Ward control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboNav_Ward As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtContractNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContractNo As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtContractType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContractType As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rdContractEffectDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdContractEffectDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''rdContractExpireDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdContractExpireDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtWorkEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWorkEmail As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''regEMAIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regEMAIL As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtPerEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPerEmail As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RegularExpressionValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''cboFamilyStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboFamilyStatus As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtMobilePhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMobilePhone As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtHomePhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHomePhone As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkDoanPhi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDoanPhi As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''rdNgayVaoDoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdNgayVaoDoan As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtChucVuDoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChucVuDoan As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtNoiVaoDoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoiVaoDoan As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPassNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPassNo As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rdPassDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdPassDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''rdPassExpireDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdPassExpireDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''cvalPassDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvalPassDate As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''txtPassPlace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPassPlace As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtVisa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVisa As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rdVisaDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdVisaDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''rdVisaExpireDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdVisaExpireDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''compare_VisaDate_ExpireDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents compare_VisaDate_ExpireDate As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''txtVisaPlace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVisaPlace As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtWorkPermit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWorkPermit As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rdWorkPermitDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdWorkPermitDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''rdWorPermitExpireDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdWorPermitExpireDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''compare_WorkPermitDate_PermitExpireDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents compare_WorkPermitDate_PermitExpireDate As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''txtWorkPermitPlace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWorkPermitPlace As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtCareer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCareer As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtContactPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactPerson As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtContactPersonPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactPersonPhone As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cboMajor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboMajor As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtNamTN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNamTN As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''cboAcademy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAcademy As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cboLearningLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboLearningLevel As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cboLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboLanguage As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cboLangLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboLangLevel As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtLangMark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLangMark As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtBankNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBankNo As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cboBank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboBank As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cboBankBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboBankBranch As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtPitCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPitCode As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkIs_pay_bank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIs_pay_bank As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtChieuCao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChieuCao As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtTaiMuiHong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTaiMuiHong As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtCanNang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCanNang As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtRangHamMat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRangHamMat As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtNhomMau control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNhomMau As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtTim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTim As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtHuyetAp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHuyetAp As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPhoiNguc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhoiNguc As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtMatTrai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMatTrai As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtVienGanB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVienGanB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtMatPhai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMatPhai As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtDaHoaLieu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDaHoaLieu As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtLoaiSucKhoe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoaiSucKhoe As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtGhiChuSK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGhiChuSK As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rpvEmpPaper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpvEmpPaper As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''lstbPaper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstbPaper As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''lstbPaperFiled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstbPaperFiled As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''rpvEmpTitleConcurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpvEmpTitleConcurrent As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''ctrlHU_TitleConcurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlHU_TitleConcurrent As Global.Profile.ctrlHU_TitleConcurrent

    '''<summary>
    '''RadPane4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane4 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''rwPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rwPopup As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''ScriptBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptBlock As Global.Telerik.Web.UI.RadScriptBlock
End Class
