Function: ApproveOtRegistration
Datetime: 20/05/2019 9:35:52 AM
Error message: Nullable object must have a value.
Stack trace:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.op_Explicit(Nullable`1 value)
   at AttendanceDAL.AttendanceRepository.ApproveOtRegistration(List`1 obj, Decimal empId, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 6555
Other Text: iTime

Function: ApproveOtRegistration
Datetime: 20/05/2019 9:37:10 AM
Error message: Nullable object must have a value.
Stack trace:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.op_Explicit(Nullable`1 value)
   at AttendanceDAL.AttendanceRepository.ApproveOtRegistration(List`1 obj, Decimal empId, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 6555
Other Text: iTime

Function: ApproveOtRegistration
Datetime: 20/05/2019 9:37:18 AM
Error message: Nullable object must have a value.
Stack trace:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.op_Explicit(Nullable`1 value)
   at AttendanceDAL.AttendanceRepository.ApproveOtRegistration(List`1 obj, Decimal empId, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 6555
Other Text: iTime

Function: ApproveOtRegistration
Datetime: 20/05/2019 9:44:50 AM
Error message: Nullable object must have a value.
Stack trace:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.op_Explicit(Nullable`1 value)
   at AttendanceDAL.AttendanceRepository.ApproveOtRegistration(List`1 obj, Decimal empId, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 6556
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 11:01:10 AM
Error message: Unable to cast object of type 'WhereListIterator`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5947
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 11:15:22 AM
Error message: Unable to cast object of type 'WhereListIterator`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5947
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 11:42:11 AM
Error message: Unable to cast object of type 'WhereListIterator`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5947
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 11:51:04 AM
Error message: Unable to cast object of type 'WhereListIterator`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5947
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 11:55:33 AM
Error message: Specified cast is not valid.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5929
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 12:33:23 PM
Error message: Operator '<>' is not defined for type 'DBNull' and string "".
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Operators.ConditionalCompareObjectNotEqual(Object Left, Object Right, Boolean TextCompare)
   at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log)
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 12:41:00 PM
Error message: Specified cast is not valid.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5929
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 12:51:26 PM
Error message: Specified cast is not valid.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5929
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 12:54:22 PM
Error message: Specified cast is not valid.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5929
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 12:56:52 PM
Error message: Specified cast is not valid.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5929
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 12:59:50 PM
Error message: Specified cast is not valid.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5929
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 1:08:56 PM
Error message: Specified cast is not valid.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5929
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 1:18:49 PM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5935
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 1:19:35 PM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5935
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 1:25:22 PM
Error message: Unable to cast object of type 'WhereListIterator`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5947
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 1:30:31 PM
Error message: Unable to cast object of type 'WhereListIterator`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5947
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 1:34:30 PM
Error message: Unable to cast object of type 'WhereListIterator`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5948
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 1:39:36 PM
Error message: Unable to cast object of type 'System.Linq.OrderedEnumerable`2[AttendanceDAL.AT_OT_REGISTRATIONDTO,System.Nullable`1[System.DateTime]]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 6056
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 1:39:47 PM
Error message: Unable to cast object of type 'System.Linq.OrderedEnumerable`2[AttendanceDAL.AT_OT_REGISTRATIONDTO,System.Nullable`1[System.DateTime]]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 6056
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 1:40:05 PM
Error message: Unable to cast object of type 'System.Linq.OrderedEnumerable`2[AttendanceDAL.AT_OT_REGISTRATIONDTO,System.Nullable`1[System.DateTime]]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 6056
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 1:43:03 PM
Error message: Unable to cast object of type 'WhereListIterator`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5948
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 1:48:03 PM
Error message: Unable to cast object of type 'WhereListIterator`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5949
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 1:48:13 PM
Error message: Unable to cast object of type 'WhereListIterator`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5949
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 1:48:21 PM
Error message: Unable to cast object of type 'WhereListIterator`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5949
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 1:51:30 PM
Error message: Unable to cast object of type 'WhereListIterator`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5949
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 2:01:45 PM
Error message: Unable to cast object of type 'WhereListIterator`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5949
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 2:02:04 PM
Error message: Unable to cast object of type 'WhereListIterator`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5949
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 2:21:59 PM
Error message: Unable to cast object of type 'WhereListIterator`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5947
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 2:23:04 PM
Error message: Unable to cast object of type 'WhereListIterator`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5947
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 2:25:55 PM
Error message: Unable to cast object of type '<TakeIterator>d__25`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 6082
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 2:27:17 PM
Error message: Unable to cast object of type '<TakeIterator>d__25`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]' to type 'System.Collections.Generic.List`1[AttendanceDAL.AT_OT_REGISTRATIONDTO]'.
Stack trace:    at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 6082
Other Text: iTime

Function: ApproveOtRegistration
Datetime: 20/05/2019 2:30:47 PM
Error message: Nullable object must have a value.
Stack trace:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.op_Explicit(Nullable`1 value)
   at AttendanceDAL.AttendanceRepository.ApproveOtRegistration(List`1 obj, Decimal empId, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 6252
Other Text: iTime

Function: ApproveOtRegistration
Datetime: 20/05/2019 2:33:16 PM
Error message: Nullable object must have a value.
Stack trace:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.op_Explicit(Nullable`1 value)
   at AttendanceDAL.AttendanceRepository.ApproveOtRegistration(List`1 obj, Decimal empId, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 6252
Other Text: iTime

Function: GET_WORKSIGN
Datetime: 20/05/2019 2:40:10 PM
Error message: ORA-04063: package body "HISTAFFHCM.PKG_ATTENDANCE_BUSINESS" has errors
ORA-06508: PL/SQL: could not find program unit being called: "HISTAFFHCM.PKG_ATTENDANCE_BUSINESS"
ORA-06512: at line 1
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\histaffhcm-1\Framework.Data\DataAccess\Query.vb:line 306
   at AttendanceDAL.AttendanceRepository.GET_WORKSIGN(AT_WORKSIGNDTO param, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 4523
Other Text: iTime

Function: GET_WORKSIGN
Datetime: 20/05/2019 2:40:15 PM
Error message: ORA-04063: package body "HISTAFFHCM.PKG_ATTENDANCE_BUSINESS" has errors
ORA-06508: PL/SQL: could not find program unit being called: "HISTAFFHCM.PKG_ATTENDANCE_BUSINESS"
ORA-06512: at line 1
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\histaffhcm-1\Framework.Data\DataAccess\Query.vb:line 306
   at AttendanceDAL.AttendanceRepository.GET_WORKSIGN(AT_WORKSIGNDTO param, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 4523
Other Text: iTime

Function: InsertWorkSign
Datetime: 20/05/2019 2:50:52 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at AttendanceDAL.AttendanceRepository.InsertWorkSign(List`1 objWorkSigns, AT_WORKSIGNDTO objWork, DateTime p_fromdate, Nullable`1 p_endDate, UserLog log, Decimal& gID) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 4714
Other Text: iTime

Function: InsertWorkSign
Datetime: 20/05/2019 2:51:23 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at AttendanceDAL.AttendanceRepository.InsertWorkSign(List`1 objWorkSigns, AT_WORKSIGNDTO objWork, DateTime p_fromdate, Nullable`1 p_endDate, UserLog log, Decimal& gID) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 4714
Other Text: iTime

Function: InsertWorkSign
Datetime: 20/05/2019 2:54:04 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at AttendanceDAL.AttendanceRepository.InsertWorkSign(List`1 objWorkSigns, AT_WORKSIGNDTO objWork, DateTime p_fromdate, Nullable`1 p_endDate, UserLog log, Decimal& gID) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 4714
Other Text: iTime

Function: InsertWorkSign
Datetime: 20/05/2019 2:55:08 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at AttendanceDAL.AttendanceRepository.InsertWorkSign(List`1 objWorkSigns, AT_WORKSIGNDTO objWork, DateTime p_fromdate, Nullable`1 p_endDate, UserLog log, Decimal& gID) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 4714
Other Text: iTime

Function: InsertWorkSign
Datetime: 20/05/2019 2:58:53 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at AttendanceDAL.AttendanceRepository.InsertWorkSign(List`1 objWorkSigns, AT_WORKSIGNDTO objWork, DateTime p_fromdate, Nullable`1 p_endDate, UserLog log, Decimal& gID) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 4714
Other Text: iTime

Function: InsertWorkSign
Datetime: 20/05/2019 3:09:14 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at AttendanceDAL.AttendanceRepository.InsertWorkSign(List`1 objWorkSigns, AT_WORKSIGNDTO objWork, DateTime p_fromdate, Nullable`1 p_endDate, UserLog log, Decimal& gID) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 4714
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 4:36:11 PM
Error message: Value cannot be null.
Parameter name: String
Stack trace:    at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Decimal.Parse(String s)
   at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5907
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 4:37:16 PM
Error message: Value cannot be null.
Parameter name: String
Stack trace:    at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Decimal.Parse(String s)
   at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5907
Other Text: iTime

Function: GetOtRegistration
Datetime: 20/05/2019 4:43:38 PM
Error message: ORA-04063: package body "HISTAFFHCM.PKG_AT_PROCESS" has errors
ORA-06508: PL/SQL: could not find program unit being called: "HISTAFFHCM.PKG_AT_PROCESS"
ORA-06512: at line 1
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\histaffhcm-1\Framework.Data\DataAccess\Query.vb:line 306
   at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 5913
Other Text: iTime

