Function: GetOtRegistration
Datetime: 28/05/2019 10:07:57 AM
Error message: ORA-06550: line 1, column 7:
PLS-00306: wrong number or types of arguments in call to 'PRS_GETOT_BY_EMPLOYEE'
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\histaffhcm-5\Framework.Data\DataAccess\Query.vb:line 306
   at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-5\AttendanceDAL\AttendanceRepository.Business.vb:line 6007
Other Text: iTime

Function: GetOtRegistration
Datetime: 28/05/2019 10:11:53 AM
Error message: ORA-06550: line 1, column 7:
PLS-00306: wrong number or types of arguments in call to 'PRS_GETOT_BY_EMPLOYEE'
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\histaffhcm-5\Framework.Data\DataAccess\Query.vb:line 306
   at AttendanceDAL.AttendanceRepository.GetOtRegistration(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in E:\histaffhcm-5\AttendanceDAL\AttendanceRepository.Business.vb:line 6007
Other Text: iTime

