Function: GetCCT
Datetime: 22/05/2019 8:33:44 AM
Error message: ORA-06550: line 1, column 31:
PLS-00302: component 'GET_CCT' must be declared
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\histaffhcm-1\Framework.Data\DataAccess\Query.vb:line 306
   at AttendanceDAL.AttendanceRepository.GetCCT(AT_TIME_TIMESHEET_DAILYDTO param, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 605
Other Text: iTime

Function: GetCCT
Datetime: 22/05/2019 8:37:23 AM
Error message: ORA-06550: line 1, column 31:
PLS-00302: component 'GET_CCT' must be declared
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\histaffhcm-1\Framework.Data\DataAccess\Query.vb:line 306
   at AttendanceDAL.AttendanceRepository.GetCCT(AT_TIME_TIMESHEET_DAILYDTO param, UserLog log) in E:\histaffhcm-1\AttendanceDAL\AttendanceRepository.Business.vb:line 605
Other Text: iTime

