# Generated by Django 3.0.7 on 2020-07-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20200705_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_parent_id', models.IntegerField(null=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('status', models.NullBooleanField()),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.TextField()),
                ('ship_address', models.TextField()),
                ('ship_phone', models.TextField()),
                ('ordered_date', models.DateTimeField()),
                ('total_amount', models.TextField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('product_price', models.TextField()),
                ('order_quantity', models.IntegerField()),
                ('amount', models.TextField()),
            ],
            options={
                'db_table': 'OrderDetail',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_id', models.IntegerField()),
                ('name', models.TextField()),
                ('price', models.TextField()),
                ('quantity', models.IntegerField()),
                ('image', models.TextField()),
                ('detail', models.TextField()),
                ('status', models.NullBooleanField()),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('image_path', models.TextField()),
            ],
            options={
                'db_table': 'ProductImage',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('discount', models.TextField()),
            ],
            options={
                'db_table': 'Promotion',
            },
        ),
    ]
