Public Class HU_ORGANIZATION_NEW
    Public Property ID As Decimal?
    Public Property CODE As String
    Public Property NAME_EN As String
    Public Property NAME_VN As String
    Public Property PARENT_ID As Decimal?
    Public Property LEVEL_ID As Decimal?
    Public Property DISSOLVE_DATE As Date?
    Public Property FOUNDATION_DATE As Date?
    Public Property REMARK As String
    Public Property ACTFLG As String
    Public Property HIERARCHICAL_PATH As String
    Public Property DESCRIPTION_PATH As String
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
    Public Property ADDRESS As String
    Public Property FAX As String
    Public Property REPRESENTATIVE_ID As Decimal?
    Public Property MOBILE As String
    Public Property PROVINCE_NAME As String
    Public Property COST_CENTER_CODE As String
    Public Property ORD_NO As Decimal?
    Public Property NUMBER_BUSINESS As String
    Public Property DATE_BUSINESS As Date?
    Public Property PIT_NO As String
    Public Property U_INSURANCE As Decimal?
    Public Property ORG_LEVEL As Decimal?
    Public Property REGION_ID As Decimal?
    Public Property HU_ORG_TITLEID As Decimal?
    Public Property AUTOGENTIMESHEET As Decimal?
    Public Property UNIT_LEVEL As Decimal?
    Public Property UNIT_ID As Decimal?
    Public Property LOCATION_WORK As String
    Public Property NUMBER_DECISION As String
    Public Property TYPE_DECISION As String
    Public Property CHK_ORGCHART As Decimal?
    Public Property FILES As String
    Public Property EFFECT_DATE As Date?
    Public Property SHORT_NAME As String
    Public Property IS_SIGN_CONTRACT As Decimal?
    Public Property CONTRACT_CODE As String
    Public Property GROUP_PAID_ID As Decimal?
    Public Property UNIT_RANK_ID As Decimal?
    Public Property PROVINCE_ID As Decimal?
    Public Property DISTRICT_ID As Decimal?
    Public Property WEBSITE_LINK As String
    Public Property BANK_NO As String
    Public Property BANK_ID As Decimal?
    Public Property BANK_BRACH_ID As Decimal?
    Public Property ACCOUNTING_ID As Decimal?
    Public Property HR_ID As Decimal?
    Public Property PROVINCE_CONTRACT_ID As Decimal?
    Public Property DISTRICT_CONTRACT_ID As Decimal?
    Public Property AUTHOR_LETTER As String
    Public Property BUSS_REG_NAME As String
    Public Property MAN_UNI_NAME As String
End Class
