-- --------------------------------------------------
-- Entity Designer DDL Script for Oracle database
-- --------------------------------------------------
-- Date Created: 4/23/2020 11:49:51 AM
-- Generated from EDMX file: D:\SOURCE_GIT_NEW\SOURCR_ACV_NEW\InsuranceDAL\InsuranceContext.edmx
-- --------------------------------------------------

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

-- DROP TABLE "ACV_19_DEV"."HU_JOB_POSITION";

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'HU_EMPLOYEE'
CREATE TABLE "dbo"."HU_EMPLOYEE" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_CODE" NVARCHAR2(15) NULL,
   "FIRST_NAME_VN" NVARCHAR2(255) NULL,
   "LAST_NAME_VN" NVARCHAR2(255) NULL,
   "FULLNAME_VN" NVARCHAR2(255) NULL,
   "FIRST_NAME_EN" VARCHAR2(255) NULL,
   "LAST_NAME_EN" NVARCHAR2(255) NULL,
   "FULLNAME_EN" NVARCHAR2(255) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "WORK_STATUS" NUMBER(38,0) NULL,
   "CONTRACT_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "JOIN_DATE" DATE NULL,
   "DIRECT_MANAGER" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "LAST_WORKING_ID" NUMBER(38,0) NULL,
   "TER_EFFECT_DATE" DATE NULL,
   "TER_LAST_DATE" DATE NULL,
   "ITIME_ID" NUMBER(38,0) NULL,
   "STAFF_RANK_ID" NUMBER(38,0) NULL
);

-- Creating table 'HU_EMPLOYEE_EDUCATION'
CREATE TABLE "dbo"."HU_EMPLOYEE_EDUCATION" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "ACADEMY" NUMBER(38,0) NULL,
   "MAJOR" NUMBER(38,0) NULL,
   "COMPUTER_CER1" NVARCHAR2(255) NULL,
   "COMPUTER_CER2" NVARCHAR2(255) NULL,
   "COMPUTER_CER3" NVARCHAR2(255) NULL,
   "COMPUTER_LEVEL1" NUMBER(38,0) NULL,
   "COMPUTER_LEVEL2" NUMBER(38,0) NULL,
   "COMPUTER_LEVEL3" NUMBER(38,0) NULL,
   "COMPUTER_MARK1" NVARCHAR2(15) NULL,
   "COMPUTER_MARK2" NVARCHAR2(15) NULL,
   "COMPUTER_MARK3" NVARCHAR2(15) NULL,
   "LANGUAGE1" NUMBER(38,0) NULL,
   "LANGUAGE2" NUMBER(38,0) NULL,
   "LANGUAGE3" NUMBER(38,0) NULL,
   "LANGUAGE_LEVEL1" NUMBER(38,0) NULL,
   "LANGUAGE_LEVEL2" NUMBER(38,0) NULL,
   "LANGUAGE_LEVEL3" NUMBER(38,0) NULL,
   "LANGUAGE_MARK1" NVARCHAR2(15) NULL,
   "LANGUAGE_MARK2" NVARCHAR2(15) NULL,
   "LANGUAGE_MARK3" NVARCHAR2(15) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "GRADUATE_SCHOOL" NVARCHAR2(255) NULL,
   "MARK_EDU" NUMBER(38,0) NULL,
   "TRAINING_FORM" NUMBER(38,0) NULL,
   "LEARNING_LEVEL" NUMBER(38,0) NULL
);

-- Creating table 'HU_EMPLOYEE_FILES'
CREATE TABLE "dbo"."HU_EMPLOYEE_FILES" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "FILE_TYPE" NUMBER(38,0) NULL,
   "FILE_NAME" NVARCHAR2(255) NULL,
   "FILE_SIZE" NUMBER(10,0) NULL,
   "NOTE" NVARCHAR2(255) NULL,
   "UPLOAD_BY" NVARCHAR2(255) NULL,
   "UPLOAD_DATE" DATE NULL
);

-- Creating table 'HU_EMPLOYEE_HEALTH'
CREATE TABLE "dbo"."HU_EMPLOYEE_HEALTH" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "CHIEU_CAO" BINARY_DOUBLE NULL,
   "CAN_NANG" BINARY_DOUBLE NULL,
   "NHOM_MAU" NVARCHAR2(15) NULL,
   "HUYET_AP" NVARCHAR2(15) NULL,
   "MAT_TRAI" NVARCHAR2(15) NULL,
   "MAT_PHAI" NVARCHAR2(15) NULL,
   "TAI_MUI_HONG" NVARCHAR2(255) NULL,
   "RANG_HAM_MAT" NVARCHAR2(255) NULL,
   "TIM" NVARCHAR2(255) NULL,
   "PHOI_NGUC" NVARCHAR2(255) NULL,
   "VIEM_GAN_B" NVARCHAR2(255) NULL,
   "DA_HOA_LIEU" NVARCHAR2(255) NULL,
   "GHI_CHU_SUC_KHOE" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "LOAI_SUC_KHOE" NUMBER(38,0) NULL,
   "DU_SUC_KHOE" NUMBER(5,0) NULL
);

-- Creating table 'HU_EMPLOYEE_OTHER_INFO'
CREATE TABLE "dbo"."HU_EMPLOYEE_OTHER_INFO" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "NGAY_VAO_DOAN" DATE NULL,
   "NOI_VAO_DOAN" NVARCHAR2(255) NULL,
   "NOI_SINH_HOAT_DOAN" NVARCHAR2(255) NULL,
   "DOAN_PHI" NUMBER(5,0) NULL,
   "NGAY_VAO_DANG" DATE NULL,
   "NOI_VAO_DANG" NVARCHAR2(255) NULL,
   "NOI_SINH_HOAT_DANG" NVARCHAR2(255) NULL,
   "DANG_PHI" NUMBER(5,0) NULL,
   "SO_TAI_KHOAN" NVARCHAR2(255) NULL,
   "NGAN_HANG" NUMBER(38,0) NULL,
   "CHI_NHANH" NUMBER(38,0) NULL,
   "NGAY_HIEU_LUC" DATE NULL,
   "NGUOI_THU_HUONG" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_EMPLOYEE_SALARY'
CREATE TABLE "dbo"."HU_EMPLOYEE_SALARY" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "BASIC_SAL" NUMBER(38,0) NULL,
   "SOFT_SAL" NUMBER(38,0) NULL,
   "OTHER_SAL" NUMBER(38,0) NULL,
   "COEFFICIENT" NUMBER(38,0) NULL,
   "CONTRACTUAL_SAL" NUMBER(38,0) NULL,
   "SALARY_ENTERPRISE_ID" NUMBER(38,0) NULL,
   "ALLOWANCE_IDS" NVARCHAR2(255) NULL,
   "ALLOWANCE_SAL" NUMBER(38,0) NULL,
   "ALLOWANCE_TOTAL" NUMBER(38,0) NULL,
   "PERCENT_SALARY" NUMBER(5,0) NULL
);

-- Creating table 'HU_EMPLOYEE_TRAIN'
CREATE TABLE "dbo"."HU_EMPLOYEE_TRAIN" (
   "ID" NUMBER(38,0) NOT NULL,
   "FROM_DATE" DATE NULL,
   "TO_DATE" DATE NULL,
   "SCHOOL_NAME" NCLOB NULL,
   "TRAINING_FORM" NUMBER(38,0) NULL,
   "HIGHEST_LEVEL" NUMBER(5,0) NOT NULL,
   "LEARNING_LEVEL" NUMBER(38,0) NULL,
   "MAJOR" NUMBER(38,0) NULL,
   "GRADUATE_YEAR" NUMBER(38,0) NULL,
   "MARK" NUMBER(38,0) NULL,
   "TRAINING_CONTENT" NCLOB NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_ORG_TITLE'
CREATE TABLE "dbo"."HU_ORG_TITLE" (
   "ID" NUMBER(38,0) NOT NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_ORGANIZATION'
CREATE TABLE "dbo"."HU_ORGANIZATION" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(35) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "PARENT_ID" NUMBER(38,0) NULL,
   "DISSOLVE_DATE" DATE NULL,
   "FOUNDATION_DATE" DATE NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "HIERARCHICAL_PATH" VARCHAR2(1023) NULL,
   "DESCRIPTION_PATH" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ADDRESS" NVARCHAR2(1023) NULL,
   "FAX" NVARCHAR2(1023) NULL,
   "REPRESENTATIVE_ID" NUMBER(38,0) NULL
);

-- Creating table 'HU_TITLE'
CREATE TABLE "dbo"."HU_TITLE" (
   "ID" NUMBER(38,0) NOT NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CODE" NVARCHAR2(16) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(255) NULL,
   "TITLE_GROUP_ID" NUMBER(38,0) NULL
);

-- Creating table 'HU_WORKING'
CREATE TABLE "dbo"."HU_WORKING" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "STATUS_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "EFFECT_DATE" DATE NULL,
   "EXPIRE_DATE" DATE NULL,
   "DECISION_TYPE_ID" NUMBER(38,0) NULL,
   "DECISION_NO" NVARCHAR2(255) NULL,
   "SAL_GROUP_ID" NUMBER(38,0) NULL,
   "SAL_LEVEL_ID" NUMBER(38,0) NULL,
   "SAL_RANK_ID" NUMBER(38,0) NULL,
   "SAL_BASIC" NUMBER(38,0) NULL,
   "COST_SUPPORT" NUMBER(38,0) NULL,
   "SIGN_DATE" DATE NULL,
   "SIGN_ID" NUMBER(38,0) NULL,
   "SIGN_NAME" NVARCHAR2(255) NULL,
   "SIGN_TITLE" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "IS_PROCESS" NUMBER(5,0) NULL,
   "IS_MISSION" NUMBER(5,0) NULL,
   "IS_WAGE" NUMBER(5,0) NULL,
   "PERCENT_SALARY" NUMBER(38,0) NULL
);

-- Creating table 'OT_OTHER_LIST'
CREATE TABLE "dbo"."OT_OTHER_LIST" (
   "ID" NUMBER(38,0) NOT NULL,
   "TYPE_ID" NUMBER(38,0) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "ATTRIBUTE1" NVARCHAR2(255) NULL,
   "ATTRIBUTE2" NVARCHAR2(255) NULL,
   "ATTRIBUTE3" NVARCHAR2(255) NULL,
   "ATTRIBUTE4" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "CODE" NVARCHAR2(15) NULL,
   "TYPE_CODE" NVARCHAR2(15) NULL,
   "ORDERBYID" NUMBER(38,0) NULL
);

-- Creating table 'OT_OTHER_LIST_GROUP'
CREATE TABLE "dbo"."OT_OTHER_LIST_GROUP" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'OT_OTHER_LIST_TYPE'
CREATE TABLE "dbo"."OT_OTHER_LIST_TYPE" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(255) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "GROUP_ID" NUMBER(38,0) NULL,
   "IS_SYSTEM" NUMBER(5,0) NULL,
   "TABLE_RELATION" VARCHAR2(2000) NULL
);

-- Creating table 'HU_DISTRICT'
CREATE TABLE "dbo"."HU_DISTRICT" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "PROVINCE_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_NATION'
CREATE TABLE "dbo"."HU_NATION" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CODE" NVARCHAR2(15) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_PROVINCE'
CREATE TABLE "dbo"."HU_PROVINCE" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CODE" NVARCHAR2(255) NULL,
   "NATION_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'SE_CHOSEN_ORG'
CREATE TABLE "dbo"."SE_CHOSEN_ORG" (
   "ORG_ID" NUMBER(38,0) NOT NULL,
   "USERNAME" NVARCHAR2(255) NOT NULL
);

-- Creating table 'HU_CONTRACT'
CREATE TABLE "dbo"."HU_CONTRACT" (
   "ID" NUMBER(38,0) NOT NULL,
   "CONTRACT_NO" NVARCHAR2(255) NULL,
   "CONTRACT_TYPE_ID" NUMBER(38,0) NULL,
   "START_DATE" DATE NULL,
   "EXPIRE_DATE" DATE NULL,
   "SIGNER_TITLE" NVARCHAR2(255) NULL,
   "SIGN_DATE" DATE NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "STATUS_ID" NUMBER(38,0) NULL,
   "SIGNER_NAME" NVARCHAR2(255) NULL,
   "SIGN_ID" NUMBER(38,0) NULL,
   "IS_CHALLENGE" NUMBER(5,0) NULL,
   "CHALLENGE_START" DATE NULL,
   "CHALLENGE_END" DATE NULL,
   "CHALLENGE_MONTH" NUMBER(5,0) NULL,
   "WORKING_ID" NUMBER(38,0) NULL,
   "PERCENT_SALARY" NUMBER(5,0) NULL
);

-- Creating table 'HU_CONTRACT_TYPE'
CREATE TABLE "dbo"."HU_CONTRACT_TYPE" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NULL,
   "CODE" NVARCHAR2(255) NULL,
   "PERIOD" NUMBER(10,0) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "BHXH" NUMBER(38,0) NULL,
   "BHYT" NUMBER(38,0) NULL,
   "BHTN" NUMBER(38,0) NULL,
   "BHTNLD_BNN" NUMBER(38,0) NULL
);

-- Creating table 'HU_CONTRACT_MAX_V'
CREATE TABLE "dbo"."HU_CONTRACT_MAX_V" (
   "ID" NUMBER(38,0) NOT NULL,
   "CONTRACT_NO" NVARCHAR2(255) NULL,
   "CONTRACT_TYPE_ID" NUMBER(38,0) NULL,
   "START_DATE" DATE NULL,
   "EXPIRE_DATE" DATE NULL,
   "SIGNER_TITLE" NVARCHAR2(255) NULL,
   "SIGN_DATE" DATE NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "SIGNER_NAME" NVARCHAR2(255) NULL,
   "SIGN_ID" NUMBER(38,0) NULL,
   "WORKING_ID" NUMBER(38,0) NULL,
   "STATUS_ID" NUMBER(38,0) NULL
);

-- Creating table 'HU_STAFF_RANK'
CREATE TABLE "dbo"."HU_STAFF_RANK" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(1023) NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL
);

-- Creating table 'INS_ARISING'
CREATE TABLE "dbo"."INS_ARISING" (
   "ID" NUMBER(38,0) NOT NULL,
   "CHANGE_GROUP" NUMBER(38,0) NULL,
   "OLD_POSNAME" NVARCHAR2(250) NULL,
   "NEW_POSNAME" NVARCHAR2(250) NULL,
   "OLD_ORGID" NUMBER(38,0) NULL,
   "NEW_ORGID" NUMBER(38,0) NULL,
   "OLD_SALARY" NUMBER(38,0) NULL,
   "NEW_SALARY" NUMBER(38,0) NULL,
   "ISBHXH" NUMBER(38,0) NULL,
   "ISBHYT" NUMBER(38,0) NULL,
   "ISBHTN" NUMBER(38,0) NULL,
   "STATUS" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "DATE_CHANGE" DATE NULL,
   "EFFECTDATE" DATE NULL,
   "PKEY_REF" NUMBER(38,0) NULL,
   "CODE" NVARCHAR2(50) NULL,
   "REASONS" NVARCHAR2(250) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(250) NULL,
   "CREATED_LOG" NVARCHAR2(250) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(250) NULL,
   "MODIFIED_LOG" NVARCHAR2(250) NULL,
   "SAL_BASE" NUMBER(38,0) NULL,
   "WORKING_ID" NUMBER(38,0) NULL,
   "TYPE_CHANE" NUMBER(38,0) NULL
);

-- Creating table 'INS_CHANGE'
CREATE TABLE "dbo"."INS_CHANGE" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "ORG_ID_INS" NUMBER(38,0) NULL,
   "OLDSALARY" NUMBER(38,0) NULL,
   "NEWSALARY" NUMBER(38,0) NULL,
   "ISBHXH" NUMBER(38,0) NULL,
   "ISBHYT" NUMBER(38,0) NULL,
   "ISBHTN" NUMBER(38,0) NULL,
   "CHANGE_TYPE" NUMBER(38,0) NULL,
   "EFFECTDATE" DATE NULL,
   "CHANGE_MONTH" DATE NULL,
   "RETURN_DATEBHXH" DATE NULL,
   "RETURN_DATEBHYT" DATE NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "CLTFRMMONTH" DATE NULL,
   "CLTTOMONTH" DATE NULL,
   "CLTBHXH" NUMBER(38,0) NULL,
   "CLTBHYT" NUMBER(38,0) NULL,
   "CLTBHTN" NUMBER(38,0) NULL,
   "REPFRMMONTH" DATE NULL,
   "REPTOMONTH" DATE NULL,
   "REPBHXH" NUMBER(38,0) NULL,
   "REPBHYT" NUMBER(38,0) NULL,
   "REPBHTN" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'INS_COST_FOLLOW_LEVER'
CREATE TABLE "dbo"."INS_COST_FOLLOW_LEVER" (
   "ID" NUMBER(38,0) NOT NULL,
   "COST_CODE" NVARCHAR2(50) NULL,
   "COST_NAME" NVARCHAR2(255) NULL,
   "COST_MONEY" NUMBER(38,0) NULL,
   "EFFECTDATE_FROM" DATE NULL,
   "EFFECTDATE_TO" DATE NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'INS_ENTITLED_TYPE'
CREATE TABLE "dbo"."INS_ENTITLED_TYPE" (
   "ID" NUMBER(38,0) NOT NULL,
   "CHANGE_TYPE_ID" NUMBER(38,0) NULL,
   "GROUP_ARISING_TYPE_ID" NUMBER(38,0) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "DAY_OFF_SUMMARY" NUMBER(38,0) NULL,
   "ENJOY_LEVEL" NUMBER(38,0) NULL,
   "STATUS" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "REGIME_SALARY_TYPE" NUMBER(38,0) NULL,
   "REGIME_DAY_TYPE" NUMBER(38,0) NULL
);

-- Creating table 'INS_GROUP_REGIMES'
CREATE TABLE "dbo"."INS_GROUP_REGIMES" (
   "ID" NUMBER(38,0) NOT NULL,
   "REGIMES_NAME" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "NOTE" NVARCHAR2(1023) NULL
);

-- Creating table 'INS_GROUP_SUN_CARE'
CREATE TABLE "dbo"."INS_GROUP_SUN_CARE" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "TITLE_ID_OLD" NUMBER(38,0) NULL,
   "TITLE_ID_NEW" NUMBER(38,0) NULL,
   "STAFF_RANK_ID_OLD" NUMBER(38,0) NULL,
   "STAFF_RANK_ID_NEW" NUMBER(38,0) NULL,
   "COST_LEVER_ID_OLD" NUMBER(38,0) NULL,
   "COST_LEVER_ID_NEW" NUMBER(38,0) NULL,
   "EFFECTDATE_COST_NEW" DATE NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "COST_MONEY" NUMBER(38,0) NULL
);

-- Creating table 'INS_SUN_CARE'
CREATE TABLE "dbo"."INS_SUN_CARE" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "START_DATE" DATE NULL,
   "END_DATE" DATE NULL,
   "LEVEL_ID" NUMBER(38,0) NULL,
   "COST" NUMBER(38,0) NULL,
   "STATUS" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "THOIDIEMHUONG" DATE NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "COST_SAL" NUMBER(38,0) NULL
);

-- Creating table 'INS_WHEREHEALTH'
CREATE TABLE "dbo"."INS_WHEREHEALTH" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NOT NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "ADDRESS" NVARCHAR2(255) NULL,
   "ID_PROVINCE" NUMBER(38,0) NULL,
   "ID_DISTRICT" NUMBER(38,0) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_EMPLOYEE_CV'
CREATE TABLE "dbo"."HU_EMPLOYEE_CV" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "GENDER" NUMBER(38,0) NULL,
   "IMAGE" NVARCHAR2(255) NULL,
   "BIRTH_DATE" DATE NULL,
   "BIRTH_PLACE" NVARCHAR2(255) NULL,
   "MARITAL_STATUS" NUMBER(38,0) NULL,
   "RELIGION" NUMBER(38,0) NULL,
   "NATIVE" NUMBER(38,0) NULL,
   "NATIONALITY" NUMBER(38,0) NULL,
   "PER_ADDRESS" NVARCHAR2(255) NULL,
   "PER_PROVINCE" NUMBER(38,0) NULL,
   "HOME_PHONE" NVARCHAR2(255) NULL,
   "MOBILE_PHONE" NVARCHAR2(255) NULL,
   "ID_NO" NVARCHAR2(15) NULL,
   "ID_DATE" DATE NULL,
   "PASS_NO" NVARCHAR2(255) NULL,
   "PASS_DATE" DATE NULL,
   "PASS_EXPIRE" DATE NULL,
   "PASS_PLACE" NVARCHAR2(255) NULL,
   "VISA" NVARCHAR2(255) NULL,
   "VISA_DATE" DATE NULL,
   "VISA_EXPIRE" DATE NULL,
   "VISA_PLACE" NVARCHAR2(255) NULL,
   "WORK_PERMIT" NVARCHAR2(255) NULL,
   "WORK_PERMIT_DATE" DATE NULL,
   "WORK_PERMIT_EXPIRE" DATE NULL,
   "WORK_EMAIL" NVARCHAR2(255) NULL,
   "NAV_ADDRESS" NVARCHAR2(255) NULL,
   "NAV_PROVINCE" NUMBER(38,0) NULL,
   "PIT_CODE" VARCHAR2(255) NULL,
   "PER_EMAIL" NVARCHAR2(255) NULL,
   "CONTACT_PER" NVARCHAR2(255) NULL,
   "CONTACT_PER_PHONE" NVARCHAR2(15) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ID_PLACE" NVARCHAR2(255) NULL,
   "WORK_PERMIT_PLACE" NVARCHAR2(255) NULL,
   "BANK_ID" NUMBER(38,0) NULL,
   "BANK_BRANCH_ID" NUMBER(38,0) NULL,
   "BANK_NO" NVARCHAR2(255) NULL,
   "NGAY_VAO_DOAN" DATE NULL,
   "NOI_VAO_DOAN" NVARCHAR2(255) NULL,
   "CHUC_VU_DOAN" NVARCHAR2(255) NULL,
   "DOAN_PHI" NUMBER(5,0) NULL,
   "NGAY_VAO_DANG" DATE NULL,
   "NOI_VAO_DANG" NVARCHAR2(255) NULL,
   "CHUC_VU_DANG" NVARCHAR2(255) NULL,
   "DANG_PHI" NUMBER(5,0) NULL,
   "CAREER" NVARCHAR2(255) NULL,
   "PER_DISTRICT" NUMBER(38,0) NULL,
   "NAV_DISTRICT" NUMBER(38,0) NULL,
   "PER_WARD" NUMBER(38,0) NULL,
   "NAV_WARD" NUMBER(38,0) NULL
);

-- Creating table 'HU_WORKING_ALLOW'
CREATE TABLE "dbo"."HU_WORKING_ALLOW" (
   "ID" NUMBER(38,0) NOT NULL,
   "HU_WORKING_ID" NUMBER(38,0) NULL,
   "ALLOWANCE_LIST_ID" NUMBER(38,0) NULL,
   "AMOUNT" NUMBER(38,0) NULL,
   "IS_INSURRANCE" NUMBER(5,0) NULL,
   "EFFECT_DATE" DATE NULL,
   "EXPIRE_DATE" DATE NULL
);

-- Creating table 'HU_WORKING_MAX'
CREATE TABLE "dbo"."HU_WORKING_MAX" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "EFFECT_DATE" DATE NULL,
   "EXPIRE_DATE" DATE NULL,
   "STATUS_ID" NUMBER(38,0) NULL,
   "DECISION_TYPE_ID" NUMBER(38,0) NULL,
   "DECISION_NO" NVARCHAR2(255) NULL,
   "SAL_GROUP_ID" NUMBER(38,0) NULL,
   "SAL_LEVEL_ID" NUMBER(38,0) NULL,
   "SAL_RANK_ID" NUMBER(38,0) NULL,
   "SAL_BASIC" NUMBER(38,0) NULL,
   "COST_SUPPORT" NUMBER(38,0) NULL,
   "SIGN_DATE" DATE NULL,
   "SIGN_ID" NUMBER(38,0) NULL,
   "SIGN_NAME" NVARCHAR2(255) NULL,
   "SIGN_TITLE" NVARCHAR2(255) NULL,
   "IS_PROCESS" NUMBER(5,0) NULL,
   "IS_WAGE" NUMBER(5,0) NULL,
   "IS_MISSION" NUMBER(5,0) NULL,
   "PERCENT_SALARY" NUMBER(38,0) NULL,
   "IS_3B" NUMBER(5,0) NULL,
   "STAFF_RANK_ID" NUMBER(38,0) NULL,
   "DIRECT_MANAGER" NUMBER(38,0) NULL
);

-- Creating table 'INS_SPECIFIED_OBJECTS'
CREATE TABLE "dbo"."INS_SPECIFIED_OBJECTS" (
   "ID" NUMBER(38,0) NOT NULL,
   "LOCATION_ID" NUMBER(38,0) NULL,
   "EFFECTIVE_DATE" DATE NULL,
   "SI" NUMBER(38,0) NULL,
   "HI" NUMBER(38,0) NULL,
   "UI" NUMBER(38,0) NULL,
   "SI_COM" NUMBER(38,0) NULL,
   "SI_EMP" NUMBER(38,0) NULL,
   "HI_COM" NUMBER(38,0) NULL,
   "HI_EMP" NUMBER(38,0) NULL,
   "UI_COM" NUMBER(38,0) NULL,
   "UI_EMP" NUMBER(38,0) NULL,
   "SICK" NUMBER(38,0) NULL,
   "MATERNITY" NUMBER(38,0) NULL,
   "OFF_IN_HOUSE" NUMBER(38,0) NULL,
   "OFF_TOGETHER" NUMBER(38,0) NULL,
   "RETIRE_MALE" NUMBER(38,0) NULL,
   "RETIRE_FEMALE" NUMBER(38,0) NULL,
   "STATUS" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "SALARY_MIN" NUMBER(38,0) NULL,
   "SI_DATE" NUMBER(38,0) NULL,
   "HI_DATE" NUMBER(38,0) NULL,
   "BHTNLD_BNN_COM" NUMBER(38,0) NULL,
   "BHTNLD_BNN_EMP" NUMBER(38,0) NULL,
   "SI_NN" NUMBER(38,0) NULL,
   "SI_EMP_NN" NUMBER(38,0) NULL,
   "SI_COM_NN" NUMBER(38,0) NULL
);

-- Creating table 'HU_WORKING_ALLOW1'
CREATE TABLE "dbo"."HU_WORKING_ALLOW1" (
   "ID" NUMBER(38,0) NOT NULL,
   "HU_WORKING_ID" NUMBER(38,0) NULL,
   "ALLOWANCE_LIST_ID" NUMBER(38,0) NULL,
   "AMOUNT" NUMBER(38,0) NULL,
   "IS_INSURRANCE" NUMBER(5,0) NULL,
   "EFFECT_DATE" DATE NULL,
   "EXPIRE_DATE" DATE NULL
);

-- Creating table 'INS_INFOOLD'
CREATE TABLE "dbo"."INS_INFOOLD" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEEID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "SALARY" NUMBER(38,0) NULL,
   "SOFROM" DATE NULL,
   "SOTO" DATE NULL,
   "SOBOOKNO" NVARCHAR2(255) NULL,
   "SOPRVDBOOKDAY" DATE NULL,
   "SOWHRPRVBOOK" NVARCHAR2(255) NULL,
   "SOSTATUS_BHXH" NUMBER(38,0) NULL,
   "HEFROM" DATE NULL,
   "HETO" DATE NULL,
   "HECARDNO" NVARCHAR2(255) NULL,
   "HEPRVDCARDDAY" DATE NULL,
   "HEWHRPRVCARD" NVARCHAR2(255) NULL,
   "HESTATUS_BHYT" NUMBER(38,0) NULL,
   "HEWHRREGISKEY" NVARCHAR2(255) NULL,
   "HECARDEFFFROM" DATE NULL,
   "HECARDEFFTO" DATE NULL,
   "UEFROM" DATE NULL,
   "UETO" DATE NULL,
   "SO" NUMBER(38,0) NULL,
   "HE" NUMBER(38,0) NULL,
   "UE" NUMBER(38,0) NULL,
   "REGISTER" NUMBER(38,0) NULL,
   "CONTRACTNO" NVARCHAR2(255) NULL,
   "SENIORITY" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ORG_ID_INS" NVARCHAR2(255) NULL,
   "ISBHXH" NUMBER(38,0) NULL,
   "ISBHYT" NUMBER(38,0) NULL,
   "ISBHTN" NUMBER(38,0) NULL,
   "NOTE_BHXH" NVARCHAR2(1023) NULL,
   "SO_DATESENDCTY" DATE NULL,
   "DAYPAYMENTCOMPANY" DATE NULL
);

-- Creating table 'INS_INFORMATION'
CREATE TABLE "dbo"."INS_INFORMATION" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "INSCENTERKEY" NUMBER(38,0) NULL,
   "SALARY" NUMBER(38,0) NULL,
   "POSITIONNAME" NVARCHAR2(255) NULL,
   "ORGNAME" NVARCHAR2(255) NULL,
   "SOFROM" DATE NULL,
   "SOTO" DATE NULL,
   "SOBOOKNO" NVARCHAR2(255) NULL,
   "SOPRVDBOOKDAY" DATE NULL,
   "SOWHRPRVBOOK" NVARCHAR2(255) NULL,
   "SOPRVDBOOKSTATUS" NUMBER(38,0) NULL,
   "HEFROM" DATE NULL,
   "HETO" DATE NULL,
   "HECARDNO" NVARCHAR2(255) NULL,
   "HEPRVDCARDDAY" DATE NULL,
   "HEWHRPRVCARD" NVARCHAR2(255) NULL,
   "HEPRVDCARDSTATUS" NUMBER(38,0) NULL,
   "HEWHRREGISKEY" NVARCHAR2(255) NULL,
   "HECARDEFFFROM" DATE NULL,
   "HECARDEFFTO" DATE NULL,
   "UEFROM" DATE NULL,
   "UETO" DATE NULL,
   "SO" NUMBER(38,0) NULL,
   "HE" NUMBER(38,0) NULL,
   "UE" NUMBER(38,0) NULL,
   "REGISTER" NUMBER(38,0) NULL,
   "CONTRACTNO" NVARCHAR2(255) NULL,
   "SENIORITY" NUMBER(38,0) NULL,
   "ORD_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "DAYPAYMENTCOMPANY" DATE NULL,
   "NOTE_SO" NVARCHAR2(1023) NULL,
   "TOTAL_TIME_INS_BEFOR" NUMBER(38,0) NULL
);

-- Creating table 'INS_CHANGE_TYPE'
CREATE TABLE "dbo"."INS_CHANGE_TYPE" (
   "ID" NUMBER(38,0) NOT NULL,
   "ARISING_TYPE" NUMBER(38,0) NULL,
   "ARISING_NAME" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "DISPLAY_COMBO" NVARCHAR2(1) NULL,
   "SIGN_ARISING" NUMBER(38,0) NULL,
   "SIGN_ARISING_DETAIL" NUMBER(38,0) NULL
);

-- Creating table 'INS_REMIGE_MANAGER'
CREATE TABLE "dbo"."INS_REMIGE_MANAGER" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ENTITLED_ID" NUMBER(38,0) NULL,
   "START_DATE" DATE NULL,
   "END_DATE" DATE NULL,
   "NUM_DATE" NUMBER(38,0) NULL,
   "DATE_OFF_BIRT" DATE NULL,
   "BABY_NAME" NVARCHAR2(255) NULL,
   "NUM_BABY" NUMBER(38,0) NULL,
   "ACCUMULATED_DATE" NUMBER(38,0) NULL,
   "ALLOWANCE_SAL" NUMBER(38,0) NULL,
   "ALLOWANCE_MONEY" NUMBER(38,0) NULL,
   "ALLOWANCE_MONEY_EDIT" NUMBER(38,0) NULL,
   "TIME_ALLOWANCE" NVARCHAR2(255) NULL,
   "CONDITION_ALLOWANCE" NVARCHAR2(255) NULL,
   "SDESC" NVARCHAR2(1023) NULL,
   "APPROVAL_INSURRANCE" NUMBER(38,0) NULL,
   "APPROVAL_DATE" DATE NULL,
   "APPROVAL_NUM" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "IS_ATHOME" NUMBER(38,0) NULL,
   "CHANGE_MONTH" DATE NULL
);

-- Creating table 'INS_REGION'
CREATE TABLE "dbo"."INS_REGION" (
   "ID" NUMBER(38,0) NOT NULL,
   "NOTE" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "EFFECTIVE_DATE" DATE NULL,
   "AREA_ID" NUMBER(38,0) NULL,
   "CEILING_AMOUNT" NUMBER(38,0) NULL,
   "MIN_AMOUNT" NUMBER(38,0) NULL
);

-- Creating table 'SE_USER'
CREATE TABLE "dbo"."SE_USER" (
   "ID" NUMBER(38,0) NOT NULL,
   "USERNAME" NVARCHAR2(255) NOT NULL,
   "PASSWORD" NVARCHAR2(255) NULL,
   "FULLNAME" NVARCHAR2(255) NOT NULL,
   "EMAIL" NVARCHAR2(255) NULL,
   "TELEPHONE" NVARCHAR2(255) NULL,
   "LOCATION" NVARCHAR2(255) NULL,
   "IS_APP" NUMBER(5,0) NOT NULL,
   "IS_PORTAL" NUMBER(5,0) NOT NULL,
   "EMPLOYEE_CODE" VARCHAR2(15) NULL,
   "IS_AD" NUMBER(5,0) NULL,
   "EFFECT_DATE" DATE NULL,
   "EXPIRE_DATE" DATE NULL,
   "CREATED_DATE" DATE NOT NULL,
   "CREATED_BY" NVARCHAR2(255) NOT NULL,
   "CREATED_LOG" NVARCHAR2(255) NOT NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_BY" NVARCHAR2(255) NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NOT NULL,
   "ACTFLG" NVARCHAR2(1) NOT NULL,
   "IS_CHANGE_PASS" NUMBER(5,0) NULL,
   "CHANGE_PASS_DATE" DATE NULL,
   "REMINDER_COUNT" NUMBER(5,0) NULL,
   "MODULE_ADMIN" NVARCHAR2(255) NULL
);

-- Creating table 'SE_REPORT'
CREATE TABLE "dbo"."SE_REPORT" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NOT NULL,
   "CODE" NVARCHAR2(255) NOT NULL,
   "MODULE_ID" NUMBER(38,0) NOT NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_BY" NVARCHAR2(255) NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NOT NULL
);

-- Creating table 'INS_REGIMES'
CREATE TABLE "dbo"."INS_REGIMES" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "REGIME_ID" NUMBER(38,0) NULL,
   "PAY_FORM" NUMBER(38,0) NULL,
   "FROM_DATE" DATE NULL,
   "TO_DATE" DATE NULL,
   "DAY_CALCULATOR" NUMBER(38,0) NULL,
   "BORN_DATE" DATE NULL,
   "NAME_CHILDREN" NVARCHAR2(200) NULL,
   "CHILDREN_NO" NUMBER(38,0) NULL,
   "ACCUMULATE_DAY" NUMBER(38,0) NULL,
   "SUBSIDY_SALARY" NUMBER(38,0) NULL,
   "SUBSIDY_AMOUNT" NUMBER(38,0) NULL,
   "PAYROLL_DATE" DATE NULL,
   "CONDITION" NVARCHAR2(500) NULL,
   "INS_PAY_AMOUNT" NUMBER(38,0) NULL,
   "PAY_APPROVE_DATE" DATE NULL,
   "APPROV_DAY_NUM" NUMBER(38,0) NULL,
   "NOTE" NVARCHAR2(500) NULL,
   "CREATED_BY" NVARCHAR2(100) NULL,
   "CREATED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(100) NULL,
   "MODIFIED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(500) NULL,
   "MODIFIED_LOG" NVARCHAR2(500) NULL,
   "MONEY_ADVANCE" NUMBER(38,0) NULL,
   "DECLARE_DATE" DATE NULL,
   "SUBSIDY" NUMBER(38,0) NULL,
   "IS_DELETED" NUMBER(38,0) NULL,
   "OFF_IN_HOUSE" NUMBER(38,0) NULL,
   "OFF_TOGETHER" NUMBER(38,0) NULL,
   "SUBSIDY_MODIFY" NUMBER(38,0) NULL,
   "REGIMES_SAL" NUMBER(38,0) NULL,
   "SICK_TYPE" NUMBER(38,0) NULL
);

-- Creating table 'INS_ACCIDENT_RISK'
CREATE TABLE "dbo"."INS_ACCIDENT_RISK" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "CONTRACT_NO" NVARCHAR2(255) NULL,
   "ROWNUM_NO" NVARCHAR2(255) NULL,
   "CONTRACT_SIGN_DATE" DATE NULL,
   "CONTRACT_START_DATE" DATE NULL,
   "CONTRACT_EXPIRE_DATE" DATE NULL,
   "PLHD_CONTRACT_NO" NVARCHAR2(255) NULL,
   "PLHD_SIGN_DATE" DATE NULL,
   "PLHD_START_DATE" DATE NULL,
   "PLHD_EXPIRE_DATE" DATE NULL,
   "INS_ORG_ID" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1000) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "IS_DELETED" NUMBER(38,0) NULL
);

-- Creating table 'HU_JOB_POSITION'
CREATE TABLE "dbo"."HU_JOB_POSITION" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(255) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "JOB_NOTE" NVARCHAR2(2000) NULL,
   "COST_CODE" NVARCHAR2(255) NULL,
   "IS_LEADER" NUMBER(5,0) NULL,
   "DIRECT_MANAGER" NUMBER(38,0) NULL,
   "EFFECT_DATE" DATE NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "JOB_NAME" NVARCHAR2(1000) NULL
);

-- Creating table 'SE_USER_REPORT'
CREATE TABLE "dbo"."SE_USER_REPORT" (
   "SE_REPORT_ID" NUMBER(38,0) NOT NULL,
   "SE_USER_ID" NUMBER(38,0) NOT NULL
);


-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on "ID"in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "PK_HU_EMPLOYEE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_EDUCATION'
ALTER TABLE "dbo"."HU_EMPLOYEE_EDUCATION"
ADD CONSTRAINT "PK_HU_EMPLOYEE_EDUCATION"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE_FILES'
ALTER TABLE "dbo"."HU_EMPLOYEE_FILES"
ADD CONSTRAINT "PK_HU_EMPLOYEE_FILES"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_HEALTH'
ALTER TABLE "dbo"."HU_EMPLOYEE_HEALTH"
ADD CONSTRAINT "PK_HU_EMPLOYEE_HEALTH"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_OTHER_INFO'
ALTER TABLE "dbo"."HU_EMPLOYEE_OTHER_INFO"
ADD CONSTRAINT "PK_HU_EMPLOYEE_OTHER_INFO"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_SALARY'
ALTER TABLE "dbo"."HU_EMPLOYEE_SALARY"
ADD CONSTRAINT "PK_HU_EMPLOYEE_SALARY"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE_TRAIN'
ALTER TABLE "dbo"."HU_EMPLOYEE_TRAIN"
ADD CONSTRAINT "PK_HU_EMPLOYEE_TRAIN"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ORG_TITLE'
ALTER TABLE "dbo"."HU_ORG_TITLE"
ADD CONSTRAINT "PK_HU_ORG_TITLE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ORGANIZATION'
ALTER TABLE "dbo"."HU_ORGANIZATION"
ADD CONSTRAINT "PK_HU_ORGANIZATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_TITLE'
ALTER TABLE "dbo"."HU_TITLE"
ADD CONSTRAINT "PK_HU_TITLE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_WORKING'
ALTER TABLE "dbo"."HU_WORKING"
ADD CONSTRAINT "PK_HU_WORKING"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST'
ALTER TABLE "dbo"."OT_OTHER_LIST"
ADD CONSTRAINT "PK_OT_OTHER_LIST"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST_GROUP'
ALTER TABLE "dbo"."OT_OTHER_LIST_GROUP"
ADD CONSTRAINT "PK_OT_OTHER_LIST_GROUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST_TYPE'
ALTER TABLE "dbo"."OT_OTHER_LIST_TYPE"
ADD CONSTRAINT "PK_OT_OTHER_LIST_TYPE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_DISTRICT'
ALTER TABLE "dbo"."HU_DISTRICT"
ADD CONSTRAINT "PK_HU_DISTRICT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_NATION'
ALTER TABLE "dbo"."HU_NATION"
ADD CONSTRAINT "PK_HU_NATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_PROVINCE'
ALTER TABLE "dbo"."HU_PROVINCE"
ADD CONSTRAINT "PK_HU_PROVINCE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ORG_ID", "USERNAME"in table 'SE_CHOSEN_ORG'
ALTER TABLE "dbo"."SE_CHOSEN_ORG"
ADD CONSTRAINT "PK_SE_CHOSEN_ORG"
   PRIMARY KEY ("ORG_ID", "USERNAME" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_CONTRACT'
ALTER TABLE "dbo"."HU_CONTRACT"
ADD CONSTRAINT "PK_HU_CONTRACT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_CONTRACT_TYPE'
ALTER TABLE "dbo"."HU_CONTRACT_TYPE"
ADD CONSTRAINT "PK_HU_CONTRACT_TYPE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_CONTRACT_MAX_V'
ALTER TABLE "dbo"."HU_CONTRACT_MAX_V"
ADD CONSTRAINT "PK_HU_CONTRACT_MAX_V"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_STAFF_RANK'
ALTER TABLE "dbo"."HU_STAFF_RANK"
ADD CONSTRAINT "PK_HU_STAFF_RANK"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_ARISING'
ALTER TABLE "dbo"."INS_ARISING"
ADD CONSTRAINT "PK_INS_ARISING"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_CHANGE'
ALTER TABLE "dbo"."INS_CHANGE"
ADD CONSTRAINT "PK_INS_CHANGE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_COST_FOLLOW_LEVER'
ALTER TABLE "dbo"."INS_COST_FOLLOW_LEVER"
ADD CONSTRAINT "PK_INS_COST_FOLLOW_LEVER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_ENTITLED_TYPE'
ALTER TABLE "dbo"."INS_ENTITLED_TYPE"
ADD CONSTRAINT "PK_INS_ENTITLED_TYPE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_GROUP_REGIMES'
ALTER TABLE "dbo"."INS_GROUP_REGIMES"
ADD CONSTRAINT "PK_INS_GROUP_REGIMES"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_GROUP_SUN_CARE'
ALTER TABLE "dbo"."INS_GROUP_SUN_CARE"
ADD CONSTRAINT "PK_INS_GROUP_SUN_CARE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_SUN_CARE'
ALTER TABLE "dbo"."INS_SUN_CARE"
ADD CONSTRAINT "PK_INS_SUN_CARE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_WHEREHEALTH'
ALTER TABLE "dbo"."INS_WHEREHEALTH"
ADD CONSTRAINT "PK_INS_WHEREHEALTH"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_CV'
ALTER TABLE "dbo"."HU_EMPLOYEE_CV"
ADD CONSTRAINT "PK_HU_EMPLOYEE_CV"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_WORKING_ALLOW'
ALTER TABLE "dbo"."HU_WORKING_ALLOW"
ADD CONSTRAINT "PK_HU_WORKING_ALLOW"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_WORKING_MAX'
ALTER TABLE "dbo"."HU_WORKING_MAX"
ADD CONSTRAINT "PK_HU_WORKING_MAX"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_SPECIFIED_OBJECTS'
ALTER TABLE "dbo"."INS_SPECIFIED_OBJECTS"
ADD CONSTRAINT "PK_INS_SPECIFIED_OBJECTS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_WORKING_ALLOW1'
ALTER TABLE "dbo"."HU_WORKING_ALLOW1"
ADD CONSTRAINT "PK_HU_WORKING_ALLOW1"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_INFOOLD'
ALTER TABLE "dbo"."INS_INFOOLD"
ADD CONSTRAINT "PK_INS_INFOOLD"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_INFORMATION'
ALTER TABLE "dbo"."INS_INFORMATION"
ADD CONSTRAINT "PK_INS_INFORMATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_CHANGE_TYPE'
ALTER TABLE "dbo"."INS_CHANGE_TYPE"
ADD CONSTRAINT "PK_INS_CHANGE_TYPE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_REMIGE_MANAGER'
ALTER TABLE "dbo"."INS_REMIGE_MANAGER"
ADD CONSTRAINT "PK_INS_REMIGE_MANAGER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_REGION'
ALTER TABLE "dbo"."INS_REGION"
ADD CONSTRAINT "PK_INS_REGION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_USER'
ALTER TABLE "dbo"."SE_USER"
ADD CONSTRAINT "PK_SE_USER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_REPORT'
ALTER TABLE "dbo"."SE_REPORT"
ADD CONSTRAINT "PK_SE_REPORT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_REGIMES'
ALTER TABLE "dbo"."INS_REGIMES"
ADD CONSTRAINT "PK_INS_REGIMES"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_ACCIDENT_RISK'
ALTER TABLE "dbo"."INS_ACCIDENT_RISK"
ADD CONSTRAINT "PK_INS_ACCIDENT_RISK"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_JOB_POSITION'
ALTER TABLE "dbo"."HU_JOB_POSITION"
ADD CONSTRAINT "PK_HU_JOB_POSITION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "SE_REPORT_ID", "SE_USER_ID"in table 'SE_USER_REPORT'
ALTER TABLE "dbo"."SE_USER_REPORT"
ADD CONSTRAINT "PK_SE_USER_REPORT"
   PRIMARY KEY ("SE_REPORT_ID", "SE_USER_ID" )
   ENABLE
   VALIDATE;


-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_HEALTH'
ALTER TABLE "dbo"."HU_EMPLOYEE_HEALTH"
ADD CONSTRAINT "FK_FE_HEH"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_EDUCATION'
ALTER TABLE "dbo"."HU_EMPLOYEE_EDUCATION"
ADD CONSTRAINT "FK_HE_HEE"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_FILES'
ALTER TABLE "dbo"."HU_EMPLOYEE_FILES"
ADD CONSTRAINT "FK_HE_HEF"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HE_HEF'
CREATE INDEX "IX_FK_HE_HEF"
ON "dbo"."HU_EMPLOYEE_FILES"
   ("EMPLOYEE_ID");

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_OTHER_INFO'
ALTER TABLE "dbo"."HU_EMPLOYEE_OTHER_INFO"
ADD CONSTRAINT "FK_HE_HEO"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_SALARY'
ALTER TABLE "dbo"."HU_EMPLOYEE_SALARY"
ADD CONSTRAINT "FK_HE_HES"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "TITLE_ID" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HE_HT"
   FOREIGN KEY ("TITLE_ID")
   REFERENCES "dbo"."HU_TITLE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HE_HT'
CREATE INDEX "IX_FK_HE_HT"
ON "dbo"."HU_EMPLOYEE"
   ("TITLE_ID");

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_WORKING'
ALTER TABLE "dbo"."HU_WORKING"
ADD CONSTRAINT "FK_HE_HW"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HE_HW'
CREATE INDEX "IX_FK_HE_HW"
ON "dbo"."HU_WORKING"
   ("EMPLOYEE_ID");

-- Creating foreign key on "ORG_ID" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HU_ORG_HU_EMP"
   FOREIGN KEY ("ORG_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_ORG_HU_EMP'
CREATE INDEX "IX_FK_HU_ORG_HU_EMP"
ON "dbo"."HU_EMPLOYEE"
   ("ORG_ID");

-- Creating foreign key on "DIRECT_MANAGER" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HUEMD_HUEM"
   FOREIGN KEY ("DIRECT_MANAGER")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUEMD_HUEM'
CREATE INDEX "IX_FK_HUEMD_HUEM"
ON "dbo"."HU_EMPLOYEE"
   ("DIRECT_MANAGER");

-- Creating foreign key on "ORG_ID" in table 'HU_ORG_TITLE'
ALTER TABLE "dbo"."HU_ORG_TITLE"
ADD CONSTRAINT "FK_HUOG_HUOT"
   FOREIGN KEY ("ORG_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUOG_HUOT'
CREATE INDEX "IX_FK_HUOG_HUOT"
ON "dbo"."HU_ORG_TITLE"
   ("ORG_ID");

-- Creating foreign key on "TITLE_ID" in table 'HU_ORG_TITLE'
ALTER TABLE "dbo"."HU_ORG_TITLE"
ADD CONSTRAINT "FK_HUTL_HUOT"
   FOREIGN KEY ("TITLE_ID")
   REFERENCES "dbo"."HU_TITLE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUTL_HUOT'
CREATE INDEX "IX_FK_HUTL_HUOT"
ON "dbo"."HU_ORG_TITLE"
   ("TITLE_ID");

-- Creating foreign key on "PARENT_ID" in table 'HU_ORGANIZATION'
ALTER TABLE "dbo"."HU_ORGANIZATION"
ADD CONSTRAINT "FK_HU_ORG_HU_ORG"
   FOREIGN KEY ("PARENT_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_ORG_HU_ORG'
CREATE INDEX "IX_FK_HU_ORG_HU_ORG"
ON "dbo"."HU_ORGANIZATION"
   ("PARENT_ID");

-- Creating foreign key on "ORG_ID" in table 'HU_WORKING'
ALTER TABLE "dbo"."HU_WORKING"
ADD CONSTRAINT "FK_HUOG_HUWK"
   FOREIGN KEY ("ORG_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUOG_HUWK'
CREATE INDEX "IX_FK_HUOG_HUWK"
ON "dbo"."HU_WORKING"
   ("ORG_ID");

-- Creating foreign key on "TITLE_ID" in table 'HU_WORKING'
ALTER TABLE "dbo"."HU_WORKING"
ADD CONSTRAINT "FK_HUTL_HUWK"
   FOREIGN KEY ("TITLE_ID")
   REFERENCES "dbo"."HU_TITLE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUTL_HUWK'
CREATE INDEX "IX_FK_HUTL_HUWK"
ON "dbo"."HU_WORKING"
   ("TITLE_ID");

-- Creating foreign key on "STATUS_ID" in table 'HU_WORKING'
ALTER TABLE "dbo"."HU_WORKING"
ADD CONSTRAINT "FK_OTOTL_HUWK"
   FOREIGN KEY ("STATUS_ID")
   REFERENCES "dbo"."OT_OTHER_LIST"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_OTOTL_HUWK'
CREATE INDEX "IX_FK_OTOTL_HUWK"
ON "dbo"."HU_WORKING"
   ("STATUS_ID");

-- Creating foreign key on "TYPE_ID" in table 'OT_OTHER_LIST'
ALTER TABLE "dbo"."OT_OTHER_LIST"
ADD CONSTRAINT "FK_OOLT_OOL"
   FOREIGN KEY ("TYPE_ID")
   REFERENCES "dbo"."OT_OTHER_LIST_TYPE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_OOLT_OOL'
CREATE INDEX "IX_FK_OOLT_OOL"
ON "dbo"."OT_OTHER_LIST"
   ("TYPE_ID");

-- Creating foreign key on "GROUP_ID" in table 'OT_OTHER_LIST_TYPE'
ALTER TABLE "dbo"."OT_OTHER_LIST_TYPE"
ADD CONSTRAINT "FK_OOLG_OOLT"
   FOREIGN KEY ("GROUP_ID")
   REFERENCES "dbo"."OT_OTHER_LIST_GROUP"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_OOLG_OOLT'
CREATE INDEX "IX_FK_OOLG_OOLT"
ON "dbo"."OT_OTHER_LIST_TYPE"
   ("GROUP_ID");

-- Creating foreign key on "PROVINCE_ID" in table 'HU_DISTRICT'
ALTER TABLE "dbo"."HU_DISTRICT"
ADD CONSTRAINT "FK_HU_PRO_HU_DIS"
   FOREIGN KEY ("PROVINCE_ID")
   REFERENCES "dbo"."HU_PROVINCE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_PRO_HU_DIS'
CREATE INDEX "IX_FK_HU_PRO_HU_DIS"
ON "dbo"."HU_DISTRICT"
   ("PROVINCE_ID");

-- Creating foreign key on "NATION_ID" in table 'HU_PROVINCE'
ALTER TABLE "dbo"."HU_PROVINCE"
ADD CONSTRAINT "FK_HU_NAT_HU_PRO"
   FOREIGN KEY ("NATION_ID")
   REFERENCES "dbo"."HU_NATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_NAT_HU_PRO'
CREATE INDEX "IX_FK_HU_NAT_HU_PRO"
ON "dbo"."HU_PROVINCE"
   ("NATION_ID");

-- Creating foreign key on "SE_REPORT_ID" in table 'SE_USER_REPORT'
ALTER TABLE "dbo"."SE_USER_REPORT"
ADD CONSTRAINT "FK_SE_USER_REPORT_SE_REPORT"
   FOREIGN KEY ("SE_REPORT_ID")
   REFERENCES "dbo"."SE_REPORT"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SE_USER_REPORT_SE_REPORT'
CREATE INDEX "IX_FK_SE_USER_REPORT_SE_REPORT"
ON "dbo"."SE_USER_REPORT"
   ("SE_REPORT_ID");

-- Creating foreign key on "SE_USER_ID" in table 'SE_USER_REPORT'
ALTER TABLE "dbo"."SE_USER_REPORT"
ADD CONSTRAINT "FK_SE_USER_REPORT_SE_USER"
   FOREIGN KEY ("SE_USER_ID")
   REFERENCES "dbo"."SE_USER"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SE_USER_REPORT_SE_USER'
CREATE INDEX "IX_FK_SE_USER_REPORT_SE_USER"
ON "dbo"."SE_USER_REPORT"
   ("SE_USER_ID");

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------
