Public Class AT_DATAINOUTDTO
    Public Property ID As Decimal?
    Public Property EMPLOYEE_ID As Decimal?
    Public Property VN_FULLNAME As String
    Public Property EMPLOYEE_CODE As String
    Public Property WORKINGDAY As Date?
    Public Property FROM_DATE As Date?
    Public Property END_DATE As Date?
    Public Property ORG_ID As Decimal?
    Public Property ORG_NAME As String
    Public Property ORG_DESC As String
    Public Property TITLE_NAME As String
    Public Property STAFF_RANK_ID As Decimal?
    Public Property STAFF_RANK_NAME As String
    Public Property PERIOD_ID As Decimal?
    Public Property IS_TERMINATE As Boolean?
    Public Property STATUS_EXPORT As Decimal?
    Public Property IS_DISSOLVE As Decimal?
    Public Property VALIN1 As Date?
    Public Property VALIN2 As Date?
    Public Property VALIN3 As Date?
    Public Property VALIN4 As Date?
    Public Property VALIN5 As Date?
    Public Property VALIN6 As Date?
    Public Property VALIN7 As Date?
    Public Property VALIN8 As Date?
    Public Property VALIN9 As Date?
    Public Property VALIN10 As Date?
    Public Property VALIN11 As Date?
    Public Property VALIN12 As Date?
    Public Property VALIN13 As Date?
    Public Property VALIN14 As Date?
    Public Property VALIN15 As Date?
    Public Property VALIN16 As Date?
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
End Class
