Public Class AT_LISTPARAM_SYSTEAMDTO
    Public Property ID As Decimal
    Public Property CODE As String
    Public Property NAME As String
    Public Property EFFECT_DATE_FROM As Date?
    Public Property EFFECT_DATE_TO_NB As Date?
    Public Property NOTE As String
    Public Property TO_LEAVE_YEAR As Date?
    Public Property RANK_PAY_OT As Decimal?
    Public Property RANK_PAY_OT_NAME As String
    Public Property HOUR_CAL_OT As Decimal?
    Public Property HOUR_MAX_OT As Decimal?
    Public Property FACTOR_OT As Decimal?
    Public Property CREATE_BY_SHOW As String
    Public Property CREATE_DATE_SHOW As Date?
    Public Property MAX_DAY_OT As Decimal?
    Public Property ACTFLG As String
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
    Public Property YEAR_P As Decimal?
    Public Property YEAR_TN As Decimal?
    Public Property DAY_TN As Decimal?
    Public Property ORG_ID As Decimal?
    Public Property ORG_NAME As String
    Public Property NO_EFFECT_ENT As Boolean?
End Class