Public Class AT_OT_REGISTRATIONDTO
    Public Property ID As Decimal
    Public Property EMPLOYEE_ID As Decimal?
    Public Property EMPLOYEE_CODE As String
    Public Property FULLNAME As String
    Public Property DEPARTMENT_ID As Decimal?
    Public Property DEPARTMENT_NAME As String
    Public Property TITLE_ID As Decimal?
    Public Property TITLE_NAME As String
    Public Property REGIST_DATE As Date?
    Public Property REGIST_DATE_TO As Date?
    Public Property SIGN_ID As Decimal?
    Public Property SIGN_CODE As String
    Public Property OT_TYPE_ID As Decimal?
    Public Property OT_TYPE_NAME As String
    Public Property FROM_AM As Decimal?
    Public Property FROM_AM_MN As Decimal?
    Public Property TO_AM As Decimal?
    Public Property TO_AM_MN As Decimal?
    Public Property FROM_PM As Decimal?
    Public Property FROM_PM_MN As Decimal?
    Public Property TO_PM As Decimal?
    Public Property TO_PM_MN As Decimal?
    Public Property TOTAL_OT As Decimal?
    Public Property OT_100 As Decimal?
    Public Property OT_150 As Decimal?
    Public Property OT_200 As Decimal?
    Public Property OT_210 As Decimal?
    Public Property OT_270 As Decimal?
    Public Property OT_300 As Decimal?
    Public Property OT_370 As Decimal?
    Public Property NOTE As String
    Public Property STATUS As Decimal?
    Public Property STATUS_NAME As String
    Public Property REASON As String
    Public Property IS_DELETED As Decimal?
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
    Public Property MODIFIED_NAME As String
    Public Property P_LANG As String
    Public Property P_USER As String
    Public Property P_MANAGER As String
    Public Property P_MANAGER_ID As Decimal?
    Public Property P_GM As String
    Public Property P_GM_ID As Decimal?
    Public Property REGIST_DATE_FROM As Date?
    Public Property HR_REVIEW As String
    Public Property ID_REGGROUP As Decimal?
End Class