Public Class AT_SHIFTDTO
    Public Property ID As Decimal
    Public Property CODE As String
    Public Property NAME_VN As String
    Public Property NAME_EN As String
    Public Property MANUAL_ID As Decimal?
    Public Property MANUAL_CODE As String
    Public Property MANUAL_NAME As String
    Public Property APPLY_LAW As Decimal?
    Public Property APPLY_LAW_NAME As String
    Public Property PENALIZEA As Decimal?
    Public Property PENALIZEA_NAME As String
    Public Property SATURDAY As Decimal?
    Public Property SATURDAY_CODE As String
    Public Property SATURDAY_NAME As String
    Public Property SUNDAY As Decimal?
    Public Property SUNDAY_CODE As String
    Public Property SUNDAY_NAME As String
    Public Property HOURS_START As Date?
    Public Property HOURS_STOP As Date?
    Public Property BREAKS_FORM As Date?
    Public Property BREAKS_TO As Date?
    Public Property NOTE As String
    Public Property ACTFLG As String
    Public Property IS_NOON As Boolean?
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
    Public Property MINHOUSER As Decimal?
End Class