Public Class AT_SHIFTCYCLEDTO
    Public Property ID As Decimal
    Public Property SHIFT_ID As Decimal?
    Public Property SHIFT_NAME As String
    Public Property STARTDATE As Date?
    Public Property ENDDATE As Date?
    Public Property NOTE As String
    Public Property IS_DELETED As Boolean
    Public Property FML01_ID As Decimal?
    Public Property FML_NAME As String
    Public Property FML02_ID As Decimal?
    Public Property FML03_ID As Decimal?
    Public Property FML04_ID As Decimal?
    Public Property FML05_ID As Decimal?
    Public Property FML06_ID As Decimal?
    Public Property FML07_ID As Decimal?
    Public Property FML08_ID As Decimal?
    Public Property FML09_ID As Decimal?
    Public Property FML10_ID As Decimal?
    Public Property FML11_ID As Decimal?
    Public Property FML12_ID As Decimal?
    Public Property FML13_ID As Decimal?
    Public Property FML14_ID As Decimal?
    Public Property FML15_ID As Decimal?
    Public Property FML16_ID As Decimal?
    Public Property FML17_ID As Decimal?
    Public Property FML18_ID As Decimal?
    Public Property FML19_ID As Decimal?
    Public Property FML20_ID As Decimal?
    Public Property FML21_ID As Decimal?
    Public Property FML22_ID As Decimal?
    Public Property FML23_ID As Decimal?
    Public Property FML24_ID As Decimal?
    Public Property FML25_ID As Decimal?
    Public Property FML26_ID As Decimal?
    Public Property FML27_ID As Decimal?
    Public Property FML28_ID As Decimal?
    Public Property FML29_ID As Decimal?
    Public Property FML30_ID As Decimal?
    Public Property FML31_ID As Decimal?
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
    Public Property YEAR As Decimal?
    Public Property MONTH As Decimal?
    Public Property USERID As Decimal?
    Public Property EMPLOYEE_CODE As String
    Public Property PAGEINDEX As Decimal?
    Public Property PAGESIZE As Decimal?
    Public Property VN_FULLNAME As String
    Public Property ORG_NAME As String
    Public Property WORKINGTYPE_NAME As String
End Class