Public Class AT_TIME_TIMESHEET_DAILYDTO
    Public Property ID As Decimal?
    Public Property EMPLOYEE_ID As Decimal?
    Public Property VN_FULLNAME As String
    Public Property EMPLOYEE_CODE As String
    Public Property WORKINGDAY As Date?
    Public Property FROM_DATE As Date?
    Public Property END_DATE As Date?
    Public Property ORG_ID As Decimal?
    Public Property ORG_NAME As String
    Public Property ORG_DESC As String
    Public Property TITLE_NAME As String
    Public Property SHIFT_NAME As String
    Public Property TITLE_ID As Decimal?
    Public Property PERIOD_ID As Decimal?
    Public Property IS_TERMINATE As Boolean?
    Public Property IS_DISSOLVE As Decimal?
    Public Property PAGE_SIZE As Decimal?
    Public Property PAGE_INDEX As Decimal?
    Public Property STAFF_RANK_NAME As String
    Public Property D1 As String
    Public Property D2 As String
    Public Property D3 As String
    Public Property D4 As String
    Public Property D5 As String
    Public Property D6 As String
    Public Property D7 As String
    Public Property D8 As String
    Public Property D9 As String
    Public Property D10 As String
    Public Property D11 As String
    Public Property D12 As String
    Public Property D13 As String
    Public Property D14 As String
    Public Property D15 As String
    Public Property D16 As String
    Public Property D17 As String
    Public Property D18 As String
    Public Property D19 As String
    Public Property D20 As String
    Public Property D21 As String
    Public Property D22 As String
    Public Property D23 As String
    Public Property D24 As String
    Public Property D25 As String
    Public Property D26 As String
    Public Property D27 As String
    Public Property D28 As String
    Public Property D29 As String
    Public Property D30 As String
    Public Property D31 As String
    Public Property SHIFT_CODE As String
    Public Property HOUR_LEAVE As Date? 
    Public Property LEAVE_CODE As String
    Public Property MANUAL_ID As Decimal?
    Public Property MANUAL_CODE As String
    Public Property LATE As Decimal?
    Public Property LATE_DEDUCTION As Boolean?
    Public Property LATE_OFFICE As Boolean?
    Public Property COMEBACKOUT As Decimal?
    Public Property COMEBACKOUT_DEDUCTION As Boolean?
    Public Property COMEBACKOUT_OFFICE As Boolean?
    Public Property WORKDAY_OT As Decimal?
    Public Property WORKDAY_NIGHT As Decimal?
    Public Property LATE_PERMISSION As Boolean?
    Public Property COMEBACKOUT_PERMISSION As Boolean?
    Public Property TYPE_DAY As String
    Public Property VALIN1 As Date?
    Public Property VALIN2 As Date?
    Public Property VALIN3 As Date?
    Public Property VALIN4 As Date?

    Public Property MORNING_ID As Decimal?
    Public Property SHIFT_ID As Decimal?
    Public Property ARTERNOON_ID As Decimal?

    Public Property MORNING_NAME As String
    Public Property AFTERNOON_NAME As String

    Public Property SHIFTIN As Date?
    Public Property SHIFTOUT As Date?
    Public Property SHIFTBACKOUT As Date?
    Public Property SHIFTBACKIN As Date?

    Public Property ALLOWLATE As Decimal?
    Public Property ALLOWCOMEBACKOUT As Decimal?
    Public Property DEDUCTFROM As Decimal?
    Public Property DEDUCTTO As Decimal?

    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String

    Public Property COLOR As Decimal
End Class
