Public Class AT_WORKSIGNDTO
    Public Property ID As Decimal
    Public Property EMPLOYEE_ID As Decimal?
    Public Property VN_FULLNAME As String
    Public Property EMPLOYEE_CODE As String    
    Public Property WORKINGDAY As DateTime?

    Public Property IS_DISSOLVE As Boolean
    Public Property ORG_ID As Decimal?
    Public Property ORG_NAME As String
    Public Property TITLE_NAME As String
    Public Property PERIOD_ID As Decimal?
    Public Property PAGE_INDEX As Decimal?
    Public Property PAGE_SIZE As Decimal?
    Public Property TOTAL_RECORD As Decimal?
    Public Property SHIFT_ID As Decimal?
    Public Property CODE As String
    Public Property D1 As String
    Public Property D2 As String
    Public Property D3 As String
    Public Property D4 As String
    Public Property D5 As String
    Public Property D6 As String
    Public Property D7 As String
    Public Property D8 As String
    Public Property D9 As String
    Public Property D10 As String
    Public Property D11 As String
    Public Property D12 As String
    Public Property D13 As String
    Public Property D14 As String
    Public Property D15 As String
    Public Property D16 As String
    Public Property D17 As String
    Public Property D18 As String
    Public Property D19 As String
    Public Property D20 As String
    Public Property D21 As String
    Public Property D22 As String
    Public Property D23 As String
    Public Property D24 As String
    Public Property D25 As String
    Public Property D26 As String
    Public Property D27 As String
    Public Property D28 As String
    Public Property D29 As String
    Public Property D30 As String
    Public Property D31 As String
    Public Property WORKINGDAY1 As DateTime?
End Class
