Datetime: 10:14:23 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 10:14:23 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 10:14:24 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 10:14:24 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 10:14:25 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbcertificateexpires_ascx | ToolbarAuthorization
Datetime: 10:14:25 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbcertificateexpires_ascx | CheckAuthorization
Datetime: 10:14:25 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:14:25 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:14:25 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 10:14:25 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 10:14:47 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrlportalcompetencycourse_ascx | ToolbarAuthorization
Datetime: 10:14:47 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrlportalcompetencycourse_ascx | CheckAuthorization
Datetime: 10:14:47 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:14:47 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:14:48 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 10:14:48 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 10:15:00 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_attendance_ctrlportaltimetimesheetdetails_ascx | ToolbarAuthorization
Datetime: 10:15:00 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_attendance_ctrlportaltimetimesheetdetails_ascx | CheckAuthorization
Datetime: 10:15:00 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:15:00 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:15:08 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_attendance_ctrlportaltimetimesheetdetails_ascx | ToolbarAuthorization
Datetime: 10:15:08 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_attendance_ctrlportaltimetimesheetdetails_ascx | CheckAuthorization
Datetime: 10:15:08 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:15:08 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:15:12 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_attendance_ctrlportaltimetimesheetdetails_ascx | ToolbarAuthorization
Datetime: 10:15:12 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_attendance_ctrlportaltimetimesheetdetails_ascx | CheckAuthorization
Datetime: 10:15:12 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:15:12 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:15:15 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_payroll_ctrlpa_portalsalary_ascx | ToolbarAuthorization
Datetime: 10:15:15 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_payroll_ctrlpa_portalsalary_ascx | CheckAuthorization
Datetime: 10:15:15 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:15:15 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:15:29 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_payroll_ctrlpa_portalsalary_ascx | ToolbarAuthorization
Datetime: 10:15:29 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_payroll_ctrlpa_portalsalary_ascx | CheckAuthorization
Datetime: 10:15:29 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:15:29 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:15:48 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_performance_ctrlportalassessmentdirect_ascx | ToolbarAuthorization
Datetime: 10:15:48 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_performance_ctrlportalassessmentdirect_ascx | CheckAuthorization
Datetime: 10:15:48 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:15:48 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:15:58 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlguide_ascx | ToolbarAuthorization
Datetime: 10:15:58 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlguide_ascx | CheckAuthorization
Datetime: 10:16:21 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlguide_ascx | ToolbarAuthorization
Datetime: 10:16:21 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlguide_ascx | CheckAuthorization
Datetime: 10:17:03 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlguide_ascx | ToolbarAuthorization
Datetime: 10:17:03 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlguide_ascx | CheckAuthorization
Datetime: 10:17:21 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlguide_ascx | ToolbarAuthorization
Datetime: 10:17:21 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlguide_ascx | CheckAuthorization
Datetime: 10:17:42 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 10:17:42 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 10:17:43 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 10:17:43 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 10:17:43 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 10:17:43 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 10:17:44 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 10:17:44 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 10:17:48 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 10:17:48 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 10:17:49 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbcertificateexpires_ascx | ToolbarAuthorization
Datetime: 10:17:49 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrldbcertificateexpires_ascx | CheckAuthorization
Datetime: 10:17:49 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:17:49 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:17:49 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrlportalcompetencycourse_ascx | ToolbarAuthorization
Datetime: 10:17:49 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_dashboard_ctrlportalcompetencycourse_ascx | CheckAuthorization
Datetime: 10:17:49 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:17:49 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:19:06 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlguide_ascx | ToolbarAuthorization
Datetime: 10:19:06 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlguide_ascx | CheckAuthorization
Datetime: 10:19:38 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlguide_ascx | ToolbarAuthorization
Datetime: 10:19:38 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlguide_ascx | CheckAuthorization
Datetime: 10:19:49 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlportalcontract_ascx | ToolbarAuthorization
Datetime: 10:19:49 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_profile_ctrlportalcontract_ascx | CheckAuthorization
Datetime: 10:24:20 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_direct_ctrlportaldirectmanagement_ascx | ToolbarAuthorization
Datetime: 10:24:21 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_direct_ctrlportaldirectmanagement_ascx | CheckAuthorization
Datetime: 10:24:21 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_direct_ctrlportaldirectmanagement_ascx | ToolbarAuthorization
Datetime: 10:24:21 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_direct_ctrlportaldirectmanagement_ascx | CheckAuthorization
Datetime: 10:38:41 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_direct_ctrlportaldirectmanagement_ascx | ToolbarAuthorization
Datetime: 10:38:41 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_direct_ctrlportaldirectmanagement_ascx | CheckAuthorization
Datetime: 10:38:50 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_direct_ctrlportaldirectmanagement_ascx | ToolbarAuthorization
Datetime: 10:38:50 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_direct_ctrlportaldirectmanagement_ascx | CheckAuthorization
Datetime: 10:39:07 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_payroll_ctrlpa_portalsalary_ascx | ToolbarAuthorization
Datetime: 10:39:07 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_payroll_ctrlpa_portalsalary_ascx | CheckAuthorization
Datetime: 10:39:07 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:39:07 SA 15 Tháng Mười Một 2017
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
