Datetime: 8:28:37 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 8:28:37 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 8:28:37 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 8:28:37 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 8:28:39 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 8:28:39 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 8:28:39 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 8:28:39 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 8:28:51 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:28:51 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:28:52 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:28:52 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:28:52 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:28:52 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:29:01 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:29:01 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:29:01 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:29:02 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:29:02 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:29:02 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:29:05 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:29:05 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:29:05 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:29:05 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:29:05 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:29:05 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:29:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:29:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:29:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:29:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:29:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:29:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:29:14 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 8:29:14 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 8:29:15 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 8:29:15 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 8:29:16 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 8:29:16 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 8:29:16 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 8:29:16 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 8:29:17 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 8:29:17 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 8:29:19 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 8:29:19 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 8:29:19 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:29:19 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:29:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 8:29:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 8:29:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:29:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:29:58 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 8:29:58 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 8:29:58 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:29:58 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:30:01 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 8:30:01 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 8:30:01 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:30:01 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:30:02 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 8:30:02 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 8:30:02 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:30:02 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:30:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 8:30:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 8:33:43 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:33:43 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:33:45 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 8:33:45 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 8:33:47 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:33:47 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:33:57 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 8:33:57 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 8:33:57 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:33:57 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:33:58 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | OnMainToolbar_Click
Datetime: 8:34:05 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 8:34:05 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 8:34:05 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:34:05 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:34:09 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 8:34:09 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 8:34:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 8:34:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 8:34:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 8:34:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 8:34:11 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 8:34:11 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 8:34:11 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 8:34:11 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 8:34:14 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:34:14 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:34:17 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:34:17 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:34:17 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:34:17 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:34:21 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:34:21 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:34:21 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:34:21 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:34:21 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:34:21 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:34:22 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 8:34:26 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:34:26 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:34:27 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:34:27 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:34:27 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:34:27 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:34:42 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:34:42 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:34:42 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:34:42 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:34:42 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:34:42 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:35:26 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:35:26 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:45:39 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:45:39 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:45:39 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:45:39 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:45:39 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:45:39 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:45:41 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:45:41 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:45:41 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:45:41 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:45:46 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:45:46 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:46:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:46:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:46:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:46:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:46:33 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:46:33 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:46:33 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:46:33 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:46:33 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:46:33 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:46:56 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:46:57 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:46:57 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:46:57 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:46:57 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:46:57 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:52:11 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 8:52:11 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 8:52:12 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 8:52:12 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 8:52:14 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 8:52:14 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 8:52:15 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 8:52:15 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 8:52:16 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 8:52:16 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 8:52:36 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:52:36 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:53:49 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:53:49 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:53:49 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:53:49 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:53:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:53:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:53:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:53:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:53:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:53:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:54:32 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:54:32 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:54:32 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:54:32 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:54:32 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:54:32 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:54:42 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:54:42 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:54:42 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:54:42 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:54:42 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:54:42 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:55:52 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:55:52 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:55:52 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:55:52 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:55:52 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:55:52 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:56:43 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 8:56:43 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 8:56:44 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 8:56:44 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 8:56:44 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 8:56:44 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 8:56:45 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 8:56:45 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 8:56:45 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 8:56:45 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 8:56:48 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 8:56:48 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 8:56:48 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:56:48 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:56:50 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 8:56:50 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 8:56:51 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:56:51 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:56:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 8:56:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 8:56:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:56:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:57:20 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 8:57:20 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 8:57:20 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:57:20 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:57:20 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | OnMainToolbar_Click
Datetime: 8:57:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 8:57:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 8:57:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:57:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:57:28 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 8:57:28 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 8:57:28 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:57:28 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:57:28 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | OnMainToolbar_Click
Datetime: 8:57:29 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 8:57:29 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 8:57:29 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:57:29 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:57:40 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 8:57:40 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 8:57:40 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:57:40 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:57:53 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 8:57:53 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 8:57:53 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:57:53 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:57:53 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | OnMainToolbar_Click
Datetime: 8:57:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 8:57:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 8:57:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:57:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:58:01 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 8:58:01 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 8:58:01 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:58:01 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:58:07 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 8:58:07 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 8:58:08 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:58:08 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:58:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 8:58:11 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 8:58:11 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 8:58:11 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 8:58:12 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 8:58:12 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 8:58:12 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 8:58:12 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 8:58:13 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 8:58:13 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 8:58:13 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 8:58:13 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 8:58:18 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 8:58:18 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 8:58:19 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 8:58:19 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 8:58:19 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 8:58:19 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 8:58:20 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 8:58:20 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 8:58:20 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 8:58:20 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 8:58:27 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:58:27 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:58:27 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:58:27 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:58:27 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:58:27 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:58:30 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:58:30 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:58:30 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:58:30 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:58:30 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:58:30 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:58:30 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 8:58:34 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:58:34 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:58:34 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:58:34 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:58:34 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:58:34 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:58:34 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 8:58:51 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:58:51 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:58:51 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:58:51 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:58:51 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:58:51 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:58:55 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:58:55 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:58:55 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:58:55 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:58:55 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:58:55 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:59:18 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:59:18 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:59:18 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:59:18 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:59:18 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:59:18 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 8:59:44 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 8:59:44 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 8:59:44 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 8:59:44 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 8:59:44 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 8:59:44 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:00:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:00:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:00:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:00:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:00:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:00:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:00:32 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:00:32 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:00:32 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:00:33 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:00:33 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:00:33 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:01:53 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:01:53 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:01:53 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:01:53 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:01:53 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:01:53 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:09:30 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:09:30 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:09:30 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:09:30 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:09:30 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:09:30 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:09:35 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 9:09:35 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 9:09:36 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 9:09:36 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 9:09:37 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 9:09:37 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 9:09:37 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 9:09:37 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 9:09:38 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 9:09:38 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 9:09:47 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:09:47 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:10:01 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:10:01 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:10:05 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 9:10:05 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 9:10:06 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:10:06 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:10:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 9:10:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 9:10:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:10:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:10:23 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 9:10:23 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 9:10:23 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:10:23 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:10:24 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | OnMainToolbar_Click
Datetime: 9:10:24 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:10:24 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:10:24 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:10:24 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:12:28 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:12:28 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:12:28 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:12:28 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:12:45 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:12:45 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:12:45 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:12:45 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:12:52 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:12:52 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:12:52 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:12:52 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:14:12 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 9:14:12 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 9:14:13 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 9:14:13 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 9:14:13 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 9:14:13 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 9:14:14 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 9:14:14 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 9:14:15 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 9:14:15 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 9:14:19 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:14:19 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:14:31 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:14:31 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:15:15 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:15:15 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:25:39 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:25:40 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:25:43 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:25:43 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:25:46 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:25:46 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:25:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:25:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:25:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:25:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:25:54 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | OnMainToolbar_Click
Datetime: 9:25:57 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:25:57 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:25:57 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:25:57 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:26:07 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:26:07 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:26:07 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:26:07 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:26:11 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 9:26:11 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 9:26:12 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 9:26:12 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 9:26:12 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 9:26:12 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 9:26:13 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 9:26:13 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 9:26:13 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 9:26:13 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 9:26:16 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:26:16 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:26:16 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:26:16 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:26:16 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:26:16 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:26:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:26:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:26:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:26:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:26:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:26:25 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:26:40 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:26:40 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:26:40 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:26:40 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:26:40 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:26:40 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:26:40 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 9:26:49 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:26:49 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:26:49 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:26:49 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:26:49 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:26:49 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:26:55 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:26:55 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:26:55 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:26:55 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:26:55 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:26:55 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:26:59 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:26:59 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:26:59 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:26:59 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:26:59 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:26:59 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:27:03 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:27:03 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:27:03 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:27:03 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:27:03 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:27:03 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:27:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:27:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:27:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:27:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:27:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:27:10 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:29:28 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:29:28 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:29:28 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:29:28 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:29:28 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:29:28 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:29:29 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 9:29:33 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:29:33 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:29:33 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:29:33 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:29:33 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:29:33 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:34:15 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:34:16 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:34:16 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:34:16 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:34:16 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:34:16 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:34:16 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 9:34:20 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:34:20 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:34:20 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:34:20 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:34:20 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:34:20 SA 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:02:40 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 2:02:41 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 2:02:41 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 2:02:41 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 2:02:42 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 2:02:42 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 2:02:42 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 2:02:42 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 2:02:43 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 2:02:43 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 2:02:47 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:02:47 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:02:47 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:02:47 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:02:47 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:02:47 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:28:15 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 2:28:15 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 2:28:15 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:28:15 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:28:23 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:28:23 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:28:23 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:28:23 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:28:23 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:28:23 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:51:49 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:51:49 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:51:49 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:51:49 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:51:49 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:51:49 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:54:18 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 2:54:18 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 2:54:18 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:54:18 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:54:22 CH 21 Tháng Năm 2019
Path: Common/Modules/Common/Secure/modules_common_ctrllanguagemanagement_ascx | ViewInit
Datetime: 2:54:23 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrllanguagemanagement_ascx | ToolbarAuthorization
Datetime: 2:54:23 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrllanguagemanagement_ascx | CheckAuthorization
Datetime: 2:54:23 CH 21 Tháng Năm 2019
Path: Common/Modules/Common/Secure/modules_common_ctrllanguagemanagement_ascx | NeedDataSource
Datetime: 2:54:23 CH 21 Tháng Năm 2019
Path: Common/Modules/Common/Secure/modules_common_ctrllanguagemanagement_ascx | UpdateControlState
Datetime: 2:54:23 CH 21 Tháng Năm 2019
Path: Common/Modules/Common/Secure/modules_common_ctrllanguagemanagement_ascx | Refresh
Datetime: 2:54:23 CH 21 Tháng Năm 2019
Path: Common/Modules/Common/Secure/modules_common_ctrllanguagemanagement_ascx | UpdateControlState
Datetime: 2:54:23 CH 21 Tháng Năm 2019
Path: Common/Modules/Common/Secure/modules_common_ctrllanguagemanagement_ascx | ViewLoad
Datetime: 2:54:26 CH 21 Tháng Năm 2019
Path: Common/Modules/Common/Secure/modules_common_ctrllanguagemanagement_ascx | ViewInit
Datetime: 2:54:26 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrllanguagemanagement_ascx | ToolbarAuthorization
Datetime: 2:54:26 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrllanguagemanagement_ascx | CheckAuthorization
Datetime: 2:54:26 CH 21 Tháng Năm 2019
Path: Common/Modules/Common/Secure/modules_common_ctrllanguagemanagement_ascx | Refresh
Datetime: 2:54:26 CH 21 Tháng Năm 2019
Path: Common/Modules/Common/Secure/modules_common_ctrllanguagemanagement_ascx | NeedDataSource
Datetime: 2:54:26 CH 21 Tháng Năm 2019
Path: Common/Modules/Common/Secure/modules_common_ctrllanguagemanagement_ascx | UpdateControlState
Datetime: 2:54:26 CH 21 Tháng Năm 2019
Path: Common/Modules/Common/Secure/modules_common_ctrllanguagemanagement_ascx | ViewLoad
Datetime: 2:54:42 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:54:42 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:54:42 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:54:42 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:54:42 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:54:42 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 3:51:48 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 3:51:48 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 3:51:49 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 3:51:49 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 3:51:50 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 3:51:50 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 3:51:50 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 3:51:50 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 3:51:51 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 3:51:51 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 3:52:11 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 3:52:11 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 3:52:12 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:52:12 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:52:12 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 3:52:12 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 3:52:17 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationmng_ascx | ToolbarAuthorization
Datetime: 3:52:17 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationmng_ascx | CheckAuthorization
Datetime: 3:52:17 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:52:17 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:52:17 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 3:52:17 CH 21 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
