Datetime: 9:10:10 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 9:10:12 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 9:10:12 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 9:10:13 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 9:10:13 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 9:10:13 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 9:10:13 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 9:10:15 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 9:10:15 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 9:10:27 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:10:27 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:10:28 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:10:28 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:12:35 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:12:36 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:12:36 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:12:36 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:13:27 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:13:27 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:13:27 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:13:27 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:27:38 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 9:27:39 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 9:27:39 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 9:27:39 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 9:27:40 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 9:27:40 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 9:27:40 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 9:27:40 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 9:27:41 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 9:27:41 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 9:27:55 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:27:55 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:27:56 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:27:56 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:28:11 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 9:28:11 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 9:28:12 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:28:12 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:29:02 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 9:29:02 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 9:29:02 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:29:02 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:29:05 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 9:29:05 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 9:29:05 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:29:05 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:29:23 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 9:29:23 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 9:29:23 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:29:23 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:29:25 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | OnMainToolbar_Click
Datetime: 9:29:25 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:29:25 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:29:25 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:29:25 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:29:33 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:29:33 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:29:33 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:29:33 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:29:39 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:29:39 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:29:39 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:29:39 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:29:42 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:29:42 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:29:42 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:29:42 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:29:49 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:29:49 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:29:49 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:29:49 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:29:51 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:29:51 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:29:51 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:29:51 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:29:57 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:29:57 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:29:57 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:29:57 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:30:01 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:30:01 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:30:01 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:30:01 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:30:03 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:30:03 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:30:03 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:30:03 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:30:05 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:30:05 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:30:05 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:30:05 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:30:08 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:30:08 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:30:08 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:30:08 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:32:36 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:32:36 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:32:44 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:32:44 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:32:49 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:32:49 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:32:49 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:32:49 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:35:22 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:35:22 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:35:22 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:35:22 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:35:22 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | OnMainToolbar_Click
Datetime: 9:35:26 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:35:26 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:35:26 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:35:26 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:35:39 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:35:39 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:35:39 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:35:39 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:35:39 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:35:39 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:35:49 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:35:50 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:35:50 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:35:50 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:35:50 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:35:50 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:35:50 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 9:35:51 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:35:51 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:35:52 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:35:52 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:35:52 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:35:52 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:36:08 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:36:08 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:37:13 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:37:13 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:37:13 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:37:13 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:37:13 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 9:37:14 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:37:14 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:37:20 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:37:20 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:37:20 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:37:20 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:37:21 SA 20 Tháng Năm 2019
Time Process: 1
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 9:37:26 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:37:26 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:41:59 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 9:41:59 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 9:42:00 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 9:42:00 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 9:42:01 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 9:42:01 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 9:42:02 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 9:42:02 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 9:42:02 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 9:42:02 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 9:42:10 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:42:10 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:42:11 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:42:11 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:42:11 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:42:11 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:42:16 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:42:16 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:42:16 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:42:16 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:42:16 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:42:16 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:42:16 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 9:42:18 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:42:18 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:42:18 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:42:18 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:42:18 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:42:18 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:44:57 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:44:57 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:44:57 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:44:57 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:44:57 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:44:57 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:45:00 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:45:00 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:45:00 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:45:01 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:45:01 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:45:01 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:46:09 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:46:10 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:48:04 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 9:48:04 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 9:48:05 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 9:48:05 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 9:48:06 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 9:48:06 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 9:48:07 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 9:48:07 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 9:48:07 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 9:48:07 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 9:48:14 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:48:14 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:48:21 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:48:21 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:48:21 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:48:21 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:48:28 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:48:28 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:48:28 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:48:28 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:48:28 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:48:28 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:48:28 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 9:48:30 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:48:30 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:48:30 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:48:30 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:48:30 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:48:30 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:48:46 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:48:46 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 9:48:46 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:48:46 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:48:46 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 9:48:46 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 9:48:46 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 9:48:48 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 9:48:49 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 11:00:04 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 11:00:05 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 11:00:06 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 11:00:06 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 11:00:06 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 11:00:06 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 11:00:06 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 11:00:07 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 11:00:07 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 11:00:07 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 11:01:10 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 11:01:10 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 11:01:33 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 11:01:33 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 11:01:33 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 11:01:33 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 11:01:40 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 11:01:40 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 11:19:50 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 11:19:51 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 11:19:51 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 11:19:51 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 11:19:52 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 11:19:52 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 11:19:53 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 11:19:53 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 11:19:53 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 11:19:53 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 11:20:12 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 11:20:12 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 11:20:13 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 11:20:13 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 11:20:13 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 11:20:13 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 11:20:18 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 11:20:18 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 11:20:18 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 11:20:18 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 11:20:18 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 11:20:19 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 11:20:19 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 11:20:20 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 11:20:20 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 11:20:20 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 11:20:21 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 11:20:21 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 11:20:21 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 11:21:10 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 11:21:10 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 11:21:21 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 11:21:21 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 11:21:21 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 11:21:21 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 11:21:21 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 11:21:24 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 11:21:24 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 11:41:49 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 11:41:49 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 11:41:50 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 11:41:50 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 11:41:50 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 11:41:50 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 11:41:51 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 11:41:51 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 11:41:52 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 11:41:52 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 11:42:11 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 11:42:11 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 11:42:33 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 11:42:33 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 11:42:33 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 11:42:33 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 11:42:34 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 11:42:34 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 11:42:34 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 11:42:35 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 11:42:35 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 11:42:35 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 11:42:35 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 11:42:36 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 11:42:36 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 11:42:36 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 11:42:42 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 11:42:42 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 11:52:35 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 11:52:35 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 11:52:36 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 11:52:36 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 11:52:36 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 11:52:36 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 11:52:37 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 11:52:37 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 11:52:37 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 11:52:37 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 11:52:40 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 11:52:40 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 11:57:05 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 11:57:05 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 11:57:06 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 11:57:06 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 11:57:07 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 11:57:07 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 11:57:07 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 11:57:07 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 11:57:08 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 11:57:08 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 11:57:43 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 11:57:43 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 12:33:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 12:33:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 12:33:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 12:33:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 12:34:02 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 12:34:02 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 12:39:46 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 12:39:46 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 12:39:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 12:39:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 12:39:49 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 12:39:49 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 12:39:49 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 12:39:49 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 12:39:50 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 12:39:50 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 12:40:00 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 12:40:00 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 12:43:32 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 12:43:33 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 12:43:34 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 12:43:35 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 12:43:36 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 12:43:36 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 12:43:37 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 12:43:37 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 12:43:37 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 12:43:38 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 12:43:46 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 12:43:46 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 12:54:01 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 12:54:01 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 12:54:02 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 12:54:02 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 12:54:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 12:54:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 12:54:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 12:54:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 12:54:05 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 12:54:05 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 12:55:54 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 12:55:54 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 12:55:55 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 12:55:55 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 12:55:56 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 12:55:56 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 12:55:56 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 12:55:56 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 12:55:57 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 12:55:57 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 12:56:00 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 12:56:00 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 12:59:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 12:59:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 12:59:05 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 12:59:05 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 12:59:07 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 12:59:07 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 12:59:07 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 12:59:07 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 12:59:08 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 12:59:08 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 12:59:29 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 12:59:29 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 1:02:07 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 1:02:07 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 1:02:08 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 1:02:08 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 1:02:10 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 1:02:10 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 1:02:10 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 1:02:10 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 1:02:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 1:02:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 1:02:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 1:02:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 1:08:59 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 1:08:59 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 1:08:59 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 1:08:59 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 1:18:25 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 1:18:25 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 1:18:26 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 1:18:26 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 1:18:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 1:18:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 1:18:28 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 1:18:28 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 1:18:28 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 1:18:28 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 1:18:31 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 1:18:31 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 1:18:55 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 1:18:55 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 1:18:55 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 1:18:55 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 1:18:57 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 1:18:57 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 1:22:08 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 1:22:08 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 1:22:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 1:22:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 1:22:10 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 1:22:10 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 1:22:10 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 1:22:10 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 1:22:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 1:22:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 1:22:34 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 1:22:34 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 1:27:08 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 1:27:08 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 1:27:08 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 1:27:08 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 1:27:12 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 1:27:12 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 1:32:53 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 1:32:53 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 1:32:54 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 1:32:54 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 1:32:56 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 1:32:56 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 1:32:56 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 1:32:56 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 1:32:57 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 1:32:57 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 1:33:01 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 1:33:01 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 1:39:34 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 1:39:35 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 1:39:36 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 1:39:36 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 1:39:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 1:39:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 1:39:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 1:39:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 1:39:45 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 1:39:45 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 1:39:45 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 1:39:45 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 1:39:46 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 1:39:46 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 1:39:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 1:39:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 1:40:01 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 1:40:01 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 1:40:02 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 1:40:02 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 1:40:02 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 1:40:02 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 1:40:05 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 1:40:05 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 1:42:56 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 1:42:56 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 1:42:57 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 1:42:57 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 1:42:58 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 1:42:58 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 1:42:58 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 1:42:59 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 1:42:59 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 1:42:59 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 1:43:02 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 1:43:02 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 1:47:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 1:47:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 1:47:05 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 1:47:05 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 1:47:06 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 1:47:06 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 1:47:07 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 1:47:07 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 1:47:07 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 1:47:07 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 1:48:03 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 1:48:03 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 1:48:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 1:48:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 1:48:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 1:48:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 1:48:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 1:48:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 1:48:17 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 1:48:17 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 1:48:17 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 1:48:17 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 1:48:21 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 1:48:21 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 1:48:43 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 1:48:43 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 1:48:43 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 1:48:43 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 1:48:45 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 1:48:45 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 1:53:23 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 1:53:24 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 1:53:25 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 1:53:25 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 1:53:25 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 1:53:26 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 1:53:26 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 1:53:26 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 1:53:26 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 1:53:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 1:53:30 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 1:53:30 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:01:52 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:01:52 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:01:52 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:01:52 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:01:56 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:01:56 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:21:48 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 2:21:48 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 2:21:49 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 2:21:49 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 2:21:49 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 2:21:50 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 2:21:51 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 2:21:51 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 2:21:51 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 2:21:51 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 2:21:59 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:21:59 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:22:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:22:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:22:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:22:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:22:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:22:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:25:37 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 2:25:37 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 2:25:38 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 2:25:38 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 2:25:38 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 2:25:38 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 2:25:39 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 2:25:39 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 2:25:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 2:25:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 2:25:46 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:25:46 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:26:01 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:26:01 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:26:01 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:26:01 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:26:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:26:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:30:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 2:30:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 2:30:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 2:30:15 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 2:30:15 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 2:30:15 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 2:30:15 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 2:30:15 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 2:30:17 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 2:30:17 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 2:30:19 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:30:19 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:30:35 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:30:35 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:30:35 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:30:35 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:30:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:30:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:30:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:30:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:30:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:30:45 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:30:45 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 2:30:46 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:30:46 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:30:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:30:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:30:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:30:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:31:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:31:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:31:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:31:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:31:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:31:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:31:12 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:31:12 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:31:12 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:31:12 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:31:12 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:31:12 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:31:12 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 2:31:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:31:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:31:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:31:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:31:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:31:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:35:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 2:35:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 2:35:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 2:35:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 2:35:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 2:35:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 2:35:15 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 2:35:15 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 2:35:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 2:35:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 2:36:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:36:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:36:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:36:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:36:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:36:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:36:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:36:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:36:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:36:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:36:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:36:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:36:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 2:36:17 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:36:17 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:36:18 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:36:18 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:36:18 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:36:18 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:37:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:37:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:37:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:37:17 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:37:17 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:37:17 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:37:29 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 2:37:29 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 2:37:29 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:37:29 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:37:35 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 2:37:35 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 2:37:35 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:37:35 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:37:38 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 2:37:38 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 2:37:38 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:37:38 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:37:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 2:37:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 2:37:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:37:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:37:43 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 2:37:43 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 2:37:43 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:37:43 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:38:50 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:38:50 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:38:50 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:38:50 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:38:50 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:38:50 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:38:52 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 2:38:52 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 2:38:53 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:38:53 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:38:54 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 2:38:55 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 2:38:55 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:38:55 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:39:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 2:39:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 2:39:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:39:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:39:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 2:39:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 2:39:10 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 2:39:10 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 2:39:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 2:39:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 2:39:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 2:39:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 2:39:12 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 2:39:12 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 2:39:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 2:39:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 2:39:19 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 2:39:19 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 2:39:19 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:39:19 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 2:39:21 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 2:39:21 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 2:39:21 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 2:39:21 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:22:15 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 3:22:15 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 3:22:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:22:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:22:19 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 3:22:19 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 3:22:20 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:22:20 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:22:23 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 3:22:23 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 3:22:23 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:22:23 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:22:34 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 3:22:34 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 3:22:34 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:22:34 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:22:34 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | OnMainToolbar_Click
Datetime: 3:22:34 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 3:22:34 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 3:22:34 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:22:34 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:22:41 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 3:22:41 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 3:22:41 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:22:41 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:22:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 3:22:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 3:22:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:22:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:22:53 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 3:22:53 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 3:22:53 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 3:22:53 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 3:22:55 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 3:22:55 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 3:22:55 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 3:22:55 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 3:22:56 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 3:22:56 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 3:22:58 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 3:22:58 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 3:22:58 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:22:58 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:22:58 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 3:22:58 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 3:24:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 3:24:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 3:24:12 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 3:24:12 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 3:24:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 3:24:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 3:24:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 3:24:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 3:24:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 3:24:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 3:24:18 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 3:24:18 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 3:29:24 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 3:29:24 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 3:29:25 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 3:29:25 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 3:29:26 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 3:29:26 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 3:29:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 3:29:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 3:29:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 3:29:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 3:29:35 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 3:29:35 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 3:30:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:30:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:30:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 3:30:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 3:30:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 3:30:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 3:30:22 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:30:22 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:30:35 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 3:30:35 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 3:30:35 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:30:35 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:30:39 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 3:30:39 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 3:30:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 3:30:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 3:30:41 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 3:30:41 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 3:30:41 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 3:30:41 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 3:30:42 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 3:30:42 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 3:30:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 3:30:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 3:30:48 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:30:48 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:30:54 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 3:30:54 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 3:32:01 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:32:01 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:32:04 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 3:32:05 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 3:58:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:58:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:58:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 3:58:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 4:02:41 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 4:02:41 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 4:02:42 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 4:02:42 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 4:02:42 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 4:02:42 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 4:02:43 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 4:02:43 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 4:02:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 4:02:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 4:03:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 4:03:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 4:03:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 4:03:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 4:03:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 4:03:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 4:03:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 4:03:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 4:03:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 4:03:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 4:03:56 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 4:03:56 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 4:03:56 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 4:03:56 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 4:28:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 4:28:48 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 4:28:48 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 4:28:48 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 4:28:49 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 4:28:49 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 4:28:49 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 4:28:49 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 4:28:50 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 4:28:50 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 4:29:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 4:29:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 4:35:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 4:35:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 4:35:48 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 4:35:48 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 4:35:48 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 4:35:49 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 4:35:49 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 4:35:50 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 4:35:50 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 4:35:50 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 4:35:55 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 4:35:55 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 4:35:59 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 4:35:59 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 4:36:02 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 4:36:02 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 4:36:02 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 4:36:02 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 4:36:07 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 4:36:07 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 4:36:07 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 4:36:07 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 4:36:24 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 4:36:24 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 4:36:24 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 4:36:24 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 4:39:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 4:39:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 4:39:12 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 4:39:12 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 4:39:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 4:39:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 4:39:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 4:39:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 4:39:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 4:39:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 4:39:20 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 4:39:20 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 4:39:38 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 4:39:38 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 4:39:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 4:39:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 4:39:41 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 4:39:41 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 4:39:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 4:39:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 4:39:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 4:39:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 4:43:46 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 4:43:46 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 4:43:46 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 4:43:46 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 4:44:19 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 4:44:19 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 4:44:19 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 4:44:19 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 4:44:19 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | OnMainToolbar_Click
Datetime: 4:44:20 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 4:44:20 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 5:03:25 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 5:03:25 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 5:03:26 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 5:03:26 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 5:03:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 5:03:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 5:03:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 5:03:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 5:03:28 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 5:03:28 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 5:03:31 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 5:03:31 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 5:17:12 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 5:17:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 5:17:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 5:17:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 5:17:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 5:17:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 5:17:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 5:17:14 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 5:17:15 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 5:17:15 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 5:17:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 5:17:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 5:19:23 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 5:19:23 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 5:19:42 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 5:19:42 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 5:19:42 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 5:19:42 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 5:20:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 5:20:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 5:20:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 5:20:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 5:20:09 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | OnMainToolbar_Click
Datetime: 5:20:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 5:20:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 5:20:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 5:20:11 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 5:20:51 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 5:20:51 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 5:20:55 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 5:20:55 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 5:20:59 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 5:20:59 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 5:20:59 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 5:20:59 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 5:21:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 5:21:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 5:21:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 5:21:13 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 5:21:17 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 5:21:17 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 5:21:17 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 5:21:17 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 5:21:18 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 5:21:18 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 5:21:18 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 5:21:18 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 5:21:19 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 5:21:19 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 5:21:22 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 5:21:22 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 5:21:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 5:21:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 5:21:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 5:21:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 5:21:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 5:21:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 5:21:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 5:21:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 5:21:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 5:21:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 5:30:48 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 5:30:48 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 5:30:49 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 5:30:49 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 5:30:49 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 5:30:49 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 5:30:50 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 5:30:50 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 5:30:51 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 5:30:51 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 5:30:54 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 5:30:54 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 5:31:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 5:31:16 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 5:31:17 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 5:31:17 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 5:31:21 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 5:31:21 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 5:31:21 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 5:31:21 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 5:31:22 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 5:31:22 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 5:31:22 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 5:31:24 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 5:31:24 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 5:31:24 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 5:31:24 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 5:31:24 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 5:31:24 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 5:36:27 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 5:36:28 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 5:36:29 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 5:36:29 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 5:36:29 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 5:36:29 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 5:36:29 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 5:36:30 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 5:36:31 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 5:36:31 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 5:36:36 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 5:36:36 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 5:36:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 5:36:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 5:36:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 5:36:40 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 5:36:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 5:36:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 5:36:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 5:36:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 5:36:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 5:36:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 5:36:44 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 5:36:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 5:36:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 5:36:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 5:36:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 5:36:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 5:36:47 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 5:39:58 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 5:39:59 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 5:40:00 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 5:40:00 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 5:40:01 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 5:40:01 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 5:40:01 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 5:40:01 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 5:40:02 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 5:40:02 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 5:40:05 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 5:40:05 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 5:40:15 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 5:40:15 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 5:40:15 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 5:40:15 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 5:40:18 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 5:40:18 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 5:40:18 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 5:40:18 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 5:40:18 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 5:40:18 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 5:40:18 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 5:40:20 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 5:40:20 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 5:40:20 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 5:40:20 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 5:40:20 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 5:40:20 CH 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
