Datetime: 3:29:25 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 3:29:26 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 3:29:26 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 3:29:28 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 3:29:28 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 3:29:28 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 3:29:28 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 3:29:28 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 3:29:29 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 3:30:06 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 3:30:06 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 3:30:07 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 3:30:07 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 3:30:07 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 3:30:07 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 3:30:08 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 3:30:08 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 3:30:08 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 3:30:08 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 3:30:20 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 3:30:20 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 3:30:21 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:30:21 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:30:21 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 3:30:21 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 3:30:31 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotapprove_ascx | ToolbarAuthorization
Datetime: 3:30:31 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotapprove_ascx | CheckAuthorization
Datetime: 3:30:31 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:30:31 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:30:31 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 3:30:31 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 3:30:36 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotapprove_ascx | ToolbarAuthorization
Datetime: 3:30:37 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotapprove_ascx | CheckAuthorization
Datetime: 3:30:37 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 3:30:37 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 3:30:37 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 3:30:37 CH 22 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
