Datetime: 10:07:12 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 10:07:12 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 10:07:13 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 10:07:13 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 10:07:14 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 10:07:14 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 10:07:49 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 10:07:49 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 10:07:57 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 10:07:57 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 10:10:18 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 10:10:18 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 10:10:20 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 10:10:20 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 10:10:21 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 10:10:21 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 10:10:22 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 10:10:22 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 10:10:22 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 10:10:22 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 10:11:52 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 10:11:52 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 10:14:18 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 10:14:19 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 10:14:19 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:14:19 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:14:21 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | ToolbarAuthorization
Datetime: 10:14:21 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 10:14:22 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 10:14:22 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 10:14:22 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 10:14:22 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 10:14:23 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 10:14:23 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 10:14:23 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 10:14:23 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 10:14:26 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 10:14:26 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 10:14:26 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:14:26 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:14:44 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 10:14:44 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 10:14:44 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:14:44 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:14:48 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 10:14:48 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 10:14:48 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:14:48 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:15:01 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 10:15:01 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 10:15:01 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:15:01 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:15:01 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | OnMainToolbar_Click
Datetime: 10:15:02 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 10:15:02 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 10:15:02 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:15:02 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:15:05 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 10:15:05 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 10:15:05 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:15:05 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:15:12 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | ToolbarAuthorization
Datetime: 10:15:12 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | CheckAuthorization
Datetime: 10:15:12 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:15:12 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:15:12 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationnewedit_ascx | OnMainToolbar_Click
Datetime: 10:15:12 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 10:15:12 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 10:15:12 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:15:12 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:15:22 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 10:15:22 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 10:15:22 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:15:22 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:15:22 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | OnMainToolbar_Click
Datetime: 10:15:24 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 10:15:24 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 10:15:24 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:15:24 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:15:40 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 10:15:40 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 10:15:40 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:15:40 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:15:40 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 10:15:40 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 10:15:52 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 10:15:52 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 10:15:52 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:15:52 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:15:52 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 10:15:52 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 10:15:52 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | OnMainToolbar_Click
Datetime: 10:15:53 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 10:15:53 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 10:15:53 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:15:53 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:15:53 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 10:15:53 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 10:15:59 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 10:15:59 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 10:15:59 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:15:59 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:15:59 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 10:15:59 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 10:16:01 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 10:16:01 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 10:16:01 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:16:01 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:16:01 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 10:16:01 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
Datetime: 10:16:05 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | ToolbarAuthorization
Datetime: 10:16:05 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistrationbylm_ascx | CheckAuthorization
Datetime: 10:16:05 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 10:16:05 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 10:16:05 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | ToolbarAuthorization
Datetime: 10:16:05 SA 28 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlcommon_reject_ascx | CheckAuthorization
