Datetime: 9:10:10 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldashboardportalsixcell_ascx | CheckAuthorization
Datetime: 9:10:12 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | ToolbarAuthorization
Datetime: 9:10:12 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbregapp_ascx | CheckAuthorization
Datetime: 9:10:13 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | ToolbarAuthorization
Datetime: 9:10:13 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbinfoleave_ascx | CheckAuthorization
Datetime: 9:10:13 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | ToolbarAuthorization
Datetime: 9:10:13 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeepaper_ascx | CheckAuthorization
Datetime: 9:10:15 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | ToolbarAuthorization
Datetime: 9:10:15 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_dashboard_ctrldbemployeereg_ascx | CheckAuthorization
Datetime: 9:10:27 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:10:27 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:10:28 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:10:28 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:12:35 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:12:36 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:12:36 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:12:36 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
Datetime: 9:13:27 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | ToolbarAuthorization
Datetime: 9:13:27 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_attendance_ctrlotregistration_ascx | CheckAuthorization
Datetime: 9:13:27 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | ToolbarAuthorization
Datetime: 9:13:27 SA 20 Tháng Năm 2019
Path: Common\Modules\Common\modules_common_ctrlmessagebox_ascx | CheckAuthorization
