'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctrlOffSettingTimeKeepingNewEdit

    '''<summary>
    '''ctrlMessageBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlMessageBox As Global.Common.ctrlMessageBox

    '''<summary>
    '''RadSplitter3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitter3 As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''RadPane1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane1 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''tbarOT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbarOT As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''RadPane2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane2 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''hidID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidDecisionID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidDecisionID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidEmpID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidEmpID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidOrgAbbr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidOrgAbbr As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''valSum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valSum As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''lbCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboTypeBT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTypeBT As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lbFromDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbFromDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rdFromDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdFromDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''lbToDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbToDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rdToDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdToDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''lbNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumber As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''lbREMARK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbREMARK As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtREMARK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtREMARK As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rgEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgEmployee As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''FindEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FindEmployee As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''phFindSign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phFindSign As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock
End Class
