Public Class EmployeeCVDTO
    Public Property EMPLOYEE_ID As Decimal
    Public Property FULL_NAME_VN As String
    Public Property GENDER As Decimal?
    Public Property GENDER_NAME As String
    Public Property IMAGE As String
    Public Property BIRTH_DATE As Date?
    Public Property BIRTH_PLACE As String
    Public Property MARITAL_STATUS As Decimal?
    Public Property MARITAL_STATUS_NAME As String
    Public Property RELIGION As Decimal?
    Public Property RELIGION_NAME As String
    Public Property NATIVE As Decimal?
    Public Property NATIVE_NAME As String
    Public Property NATIONALITY As Decimal?
    Public Property NATIONALITY_NAME As String
    Public Property PER_ADDRESS As String
    Public Property PER_PROVINCE As Decimal?
    Public Property PER_PROVINCE_NAME As String
    Public Property WORKPLACE_ID As Decimal?
    Public Property WORKPLACE_NAME As String
    Public Property INS_REGION_ID As Decimal?
    Public Property INS_REGION_NAME As String
    Public Property PER_WARD As Decimal?
    Public Property PER_WARD_NAME As String
    Public Property PER_DISTRICT As Decimal?
    Public Property PER_DISTRICT_NAME As String
    Public Property HOME_PHONE As String
    Public Property MOBILE_PHONE As String
    Public Property ID_NO As String
    Public Property ID_DATE As Date?
    Public Property ID_PLACE As Decimal?
    Public Property PLACE_NAME As String
    Public Property PASS_NO As String
    Public Property PASS_DATE As Date?
    Public Property PASS_EXPIRE As Date?
    Public Property PASS_PLACE As String
    Public Property VISA As String
    Public Property VISA_DATE As Date?
    Public Property VISA_EXPIRE As Date?
    Public Property VISA_PLACE As String
    Public Property WORK_PERMIT As String
    Public Property WORK_PERMIT_DATE As Date?
    Public Property WORK_PERMIT_EXPIRE As Date?
    Public Property WORK_PERMIT_PLACE As String
    Public Property WORK_EMAIL As String
    Public Property NAV_ADDRESS As String
    Public Property NAV_PROVINCE As Decimal?
    Public Property NAV_PROVINCE_NAME As String
    Public Property NAV_DISTRICT As Decimal?
    Public Property NAV_DISTRICT_NAME As String
    Public Property NAV_WARD As Decimal?
    Public Property NAV_WARD_NAME As String
    Public Property PIT_CODE As String
    Public Property PER_EMAIL As String
    Public Property CONTACT_PER As String
    Public Property CONTACT_PER_PHONE As String
    Public Property CAREER As String


    Public Property NGAY_VAO_DOAN As Date?
    Public Property NOI_VAO_DOAN As String
    Public Property CHUC_VU_DOAN As String
    Public Property DOAN_PHI As Boolean?
    Public Property NGAY_VAO_DANG As Date?
    Public Property NOI_VAO_DANG As String
    Public Property CHUC_VU_DANG As String
    Public Property DANG_PHI As Boolean?
    Public Property BANK_ID As Decimal?
    Public Property BANK_NAME As String
    Public Property BANK_BRANCH_ID As Decimal?
    Public Property BANK_BRANCH_NAME As String
    Public Property BANK_NO As String
    Public Property IS_PERMISSION As Boolean?

    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
    Public Property IS_PAY_BANK As Boolean?

    Public Property MODIFY_TYPE As String '0: not modify, 1: modify image, 2: modify info
    Public Property PROVINCEEMP_ID As Decimal?
    Public Property PROVINCEEMP_NAME As String
    Public Property DISTRICTEMP_ID As Decimal?
    Public Property DISTRICTEMP_NAME As String
    Public Property WARDEMP_ID As Decimal?
    Public Property WARDEMP_NAME As String
    Public Property PROVINCENQ_ID As Decimal?
    Public Property PROVINCENQ_NAME As String
    Public Property OPPTION1 As String
    Public Property OPPTION2 As String
    Public Property OPPTION3 As String
    Public Property OPPTION4 As String
    Public Property OPPTION5 As String
    Public Property OPPTION6 As Date?
    Public Property OPPTION7 As Date?
    Public Property OPPTION8 As Date?
    Public Property OPPTION9 As Date?
    Public Property OPPTION10 As Date?
End Class
