Public Class HealthMngDTO
    Public Property ID As Decimal
    Public Property EMPLOYEE_ID As Decimal
    Public Property EMPLOYEE_CODE As String
    Public Property EMPLOYEE_NAME As String
    Public Property ORG_ID As Decimal
    Public Property ORG_NAME As String
    Public Property TITLE_ID As Decimal
    Public Property TITLE_NAME As String
    Public Property CREATED_DATE As Date
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
    Public Property YEAR_KHAMBENH As Date?
    Public Property DATE_KHAMBENH As Date?
    Public Property CAN_NANG As String
    Public Property HUYET_AP As String
    Public Property NOI_KHOA As String
    Public Property NGOAI_KHOA As String
    Public Property PHU_KHOA As String
    Public Property MAT As String
    Public Property TMH As String
    Public Property RHM As String
    Public Property CONG_THUC_MAU As String
    Public Property DUONG_MAU As String
    Public Property XN_NUOC_TIEU As String
    Public Property X_QUANG As String
    Public Property DIEN_TIM As String
    Public Property SIEU_AM As String
    Public Property XN_PHAN As String
    Public Property SIEU_VI_A As String
    Public Property SIEU_VI_E As String
    Public Property SIEU_VI_B As String
    Public Property KT_VIEN_GAN_B As String
    Public Property CHUC_NANG_GAN As String
    Public Property CHUC_NANG_THAN As String
    Public Property MO_MAU As String
    Public Property KQ1 As String
    Public Property KQ2 As String
    Public Property KQ3 As String
    Public Property KQ4 As String
    Public Property KQ5 As String
    Public Property KQ6 As String
    Public Property KQ7 As String
    Public Property KQ8 As String
    Public Property KQ9 As String
    Public Property KQ10 As String
    Public Property HEALTH_TYPE As String
    Public Property NHOM_BENH As String
    Public Property TEN_BENH As String
    Public Property KET_LUAN As String
    Public Property GHI_CHU As String
    Public Property DO_THINH_LUC_SB As String
    Public Property DO_THINH_LUC_HC As String
    Public Property DO_CN_HO_HAP As String
    Public Property XN_HAMLUONG_TOLUEN As String
    Public Property BENH_NN1 As String
    Public Property BENH_NN2 As String
    Public Property BENH_TN_NN As String
    Public Property NGAY_DIEU_TRI As Date?
    Public Property PP_DIEU_TRI As String
    Public Property KQ_DIEU_TRI As String

End Class
