Public Class HU_PRO_TRAIN_OUT_COMPANYDTO
    Public Property ID As Decimal?
    Public Property EMPLOYEE_ID As Decimal?
    Public Property EMPLOYEE_CODE As String
    Public Property EMPLOYEE_NAME As String
    Public Property FROM_DATE As Date?
    Public Property TO_DATE As Date?
    Public Property FROM_MONTH_YEAR As String
    Public Property TO_MONTH_YEAR As String
    Public Property YEAR_GRA As Decimal?
    Public Property NAME_SHOOLS As String
    Public Property TYPE_TRAIN_ID As Decimal?
    Public Property TYPE_TRAIN_NAME As String
    Public Property SPECIALIZED_TRAIN As String
    Public Property RESULT_TRAIN As String
    Public Property CERTIFICATE As String
    Public Property CERTIFICATE_ID As String
    Public Property EFFECTIVE_DATE_FROM As Date?
    Public Property EFFECTIVE_DATE_TO As Date?
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
    Public Property UPLOAD_FILE As String
    Public Property FILE_NAME As String
    Public Property FORM_TRAIN_ID As Decimal?
    Public Property FORM_TRAIN_NAME As String
    Public Property RECEIVE_DEGREE_DATE As Date?
    Public Property IS_RENEWED As Boolean
End Class
