Public Class HU_PRO_TRAIN_OUT_COMPANYDTOEDIT
    Public Property ID As Decimal?
    Public Property EMPLOYEE_ID As Decimal?
    Public Property EMPLOYEE_CODE As String
    Public Property EMPLOYEE_NAME As String
    Public Property FULL_NAME_VN As String
    Public Property FULL_NAME_EN As String
    Public Property ORG_ID As Decimal?
    Public Property ORG_NAME As String
    Public Property TITLE_ID As Decimal?
    Public Property TITLE_NAME As String
    Public Property FROM_DATE As Date?
    Public Property TO_DATE As Date?
    Public Property FROM_MONTH_YEAR As String
    Public Property TO_MONTH_YEAR As String
    Public Property YEAR_GRA As Decimal?
    Public Property NAME_SHOOLS As String
    Public Property FORM_TRAIN_ID As Decimal?
    Public Property FORM_TRAIN_NAME As String
    Public Property SPECIALIZED_TRAIN As String
    Public Property RESULT_TRAIN As String
    Public Property CERTIFICATE As String
    Public Property CERTIFICATE_ID As Decimal?
    Public Property EFFECTIVE_DATE_FROM As Date?
    Public Property EFFECTIVE_DATE_TO As Date?

    Public Property TYPE_TRAIN_ID As Decimal?
    Public Property RECEIVE_DEGREE_DATE As Date?
    Public Property FK_PKEY As Decimal?
    Public Property STATUS As String
    Public Property STATUS_NAME As String
    Public Property REASON_UNAPROVE As String
    Public Property SEND_DATE As Date?
    Public Property FILE_NAME As String
    Public Property UPLOAD_FILE As String

    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
    Public Property IS_RENEWED As Decimal?
    Public Property RENEWED_NAME As String
    Public Property LEVEL_ID As Decimal?
    Public Property LEVEL_NAME As String
    Public Property SCORE As Decimal?
    Public Property CONTENT_TRAIN As String
    Public Property CODE_CERTIFICATE As String
    Public Property TYPE_TRAIN_NAME As String
    Public Property REMARK As String

    Public Property SCHOOLS_ID As Decimal?
    Public Property SCHOOLS_NAME As String
    Public Property SPECIALIZED_TRAIN_ID As Decimal?
    Public Property SPECIALIZED_TRAIN_NAME As String
    Public Property RESULT_TRAIN_ID As Decimal?
    Public Property RESULT_TRAIN_NAME As String
End Class
