Public Class JobDescriptionDTO
    Public Property ID As Decimal
    Public Property CODE As String
    Public Property NAME As String
    Public Property ORG_ID As Decimal?
    Public Property ORG_NAME As String
    Public Property TITLE_ID As Decimal?
    Public Property TITLE_NAME As String
    Public Property TIME_WORKING As Decimal?
    Public Property JOB_DESCRIPTION As String
    Public Property WORK_CONDITION As String
    Public Property JOB_PARTICULARTIES As String
    Public Property WORK_ENVIRONMENT As String
    Public Property JOB_RESPONSIBILITY As String
    Public Property JOB_POWER As String
    Public Property ATTACH_FILE As String
    Public Property FILENAME As String
    Public Property LEARNING_LEVEL As Decimal?
    Public Property TRAINING_FORM As Decimal?
    Public Property GRADUATE_SCHOOL As Decimal?
    Public Property MAJOR_RANK As Decimal?
    Public Property TRAINING_FORM_2 As Decimal?
    Public Property GRADUATE_SCHOOL_2 As Decimal?
    Public Property MAJOR_RANK_2 As Decimal?
    Public Property COMPUTER_RANK As Decimal?
    Public Property LANGUAGE_1 As Decimal?
    Public Property LANGUAGE_RANK_1 As Decimal?
    Public Property LANGUAGE_2 As Decimal?
    Public Property LANGUAGE_RANK_2 As Decimal?
    Public Property LANGUAGE_3 As Decimal?
    Public Property LANGUAGE_RANK_3 As Decimal?
    Public Property SOFT_SKILL As Decimal?
    Public Property CHARACTER As String
    Public Property NOTE As String
    Public Property SAL_FROM As Decimal?
    Public Property SAL_TO As Decimal?
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
End Class
