Public Class Temp_ConcurrentlyDTO
    Public Property ID As Decimal?
    Public Property EMPLOYEE_ID As Decimal?
    Public Property ORG_CON As Decimal?
    Public Property TITLE_CON As Decimal?
    Public Property EFFECT_DATE_CON As Date?
    Public Property EXPIRE_DATE_CON As Date?
    Public Property ALLOW_MONEY As Decimal?
    Public Property CON_NO As String
    Public Property STATUS As String
    Public Property SIGN_DATE As Date?
    Public Property SIGN_ID As Decimal?
    Public Property REMARK As String
    Public Property CON_NO_STOP As String
    Public Property SIGN_DATE_STOP As Date?
    Public Property EFFECT_DATE_STOP As Date?
    Public Property STATUS_STOP As String
    Public Property SIGN_ID_STOP As Decimal?
    Public Property REMARK_STOP As String
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
    Public Property CONCURENTLY_TYPE As String
    Public Property CONCURENTLY_POSITION As String
    Public Property CONCURENTLY_TYPE_CANCEL As String
    Public Property BASIC1 As String
    Public Property BASIC2 As String
    Public Property BASIC3 As String
    Public Property BASIC4 As String
    Public Property BASIC5 As String
    Public Property BASIC6 As String
    Public Property ORG_ID As Decimal?
    Public Property ORG_NAME As String
    Public Property COM_ORG_NAME As String
    Public Property TITLE_ID As Decimal?
    Public Property TITLE_NAME As String
    Public Property SIGN_ID_2 As Decimal?
    Public Property SIGN_ID_STOP_2 As Decimal?
    Public Property USER_NAME As String
    Public Property IS_DISSOLVE As Decimal?
    Public Property START_DATE As Date?
    Public Property END_DATE As Date?
    Public Property IS_TERMINATE As Boolean?
    Public Property EMPLOYEE_CODE As String
    Public Property IS_ALLOW As Decimal?
    Public Property FILE_BYTE As String
    Public Property FILE_BYTE1 As String
    Public Property IS_CHUYEN As Decimal?
    Public Property FULLNAME_VN As String
    Public Property ORG_CON_NAME As String
    Public Property COM_ORG_CON_NAME As String
    Public Property TITLE_CON_NAME As String
    Public Property ALLOW_MONEY_NUMBER As Decimal?
    Public Property STATUS_CON_NAME As String
    Public Property STATUS_STOP_NAME As String
    Public Property CBSTATUS As String
    Public Property STATUS_NAME As String
    Public Property ORG_ID_DESC As String

    Public Property SIGN_NAME As String
    Public Property SIGN_TITLE_NAME As String
    Public Property SIGN_NAME2 As String
    Public Property SIGN_TITLE_NAME2 As String
    Public Property SIGN_NAME_STOP As String
    Public Property SIGN_TITLE_NAME_STOP As String
    Public Property SIGN_NAME_STOP2 As String
    Public Property SIGN_TITLE_NAME_STOP2 As String

    Public Property ATTACH_FOLDER_BYTE As String
    Public Property ATTACH_FOLDER_BYTE1 As String

    Public Property JOB_ID As Decimal?
    Public Property WORK_POSITION_NAME As String

    Public Property BRANCH_NAME As String
    Public Property DIV_NAME As String
    Public Property PART_NAME As String
    Public Property SHIFT_NAME As String

End Class
