Public Class KPI_EVALUATEDTO
    Public Property ID As Decimal
    Public Property EMPLOYEE_CODE As String
    Public Property FULLNAME As String
    Public Property ORG_NAME As String
    Public Property TITLE_NAME As String
    Public Property SALARY_LEVEL As String
    Public Property SALARY_LEVEL_ID As Decimal?
    Public Property JOIN_DATE As Date?
    Public Property END_DATE As Date?
    Public Property FINANCE_TT As Decimal?
    Public Property FINANCE_TTX As Decimal?
    Public Property CUSTOMER_TT As Decimal?
    Public Property CUSTOMER_TTX As Decimal?
    Public Property PROCESS_TT As Decimal?
    Public Property PROCESS_TTX As Decimal?
    Public Property LEARN_TT As Decimal?
    Public Property LEARN_TTX As Decimal?
    Public Property SUM_TT As Decimal?
    Public Property SUM_TTX As Decimal?
    Public Property SUM_RATE_KPI As Decimal?
    Public Property CLASSFICATION As String
    Public Property CLASSFICATION_ID As Decimal?
    Public Property COMMENTS As String
    Public Property REMARK As String
    Public Property TER_EFFECT_DATE As Date?
    Public Property WORK_STATUS As Decimal?
    Public Property WORK_STATUS_NAME As String
    Public Property IS_TER As Boolean
    Public Property ORG_ID As Decimal
    Public Property KPI_EVALUATE As Decimal?
End Class
