Function: GetOtherList
Datetime: 27/10/2017 10:48:06 AM
Error message: ORA-04063: package body "TVC_KYODO_TEST.PKG_COMMON_LIST" has errors
ORA-06508: PL/SQL: could not find program unit being called: "TVC_KYODO_TEST.PKG_COMMON_LIST"
ORA-06512: at line 1
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 253
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\ProfileDAL\ProfileRepository.vb:line 49
Other Text: iProfile

Function: GetOtherList
Datetime: 27/10/2017 10:50:47 AM
Error message: ORA-04063: package body "TVC_KYODO_TEST.PKG_COMMON_LIST" has errors
ORA-06508: PL/SQL: could not find program unit being called: "TVC_KYODO_TEST.PKG_COMMON_LIST"
ORA-06512: at line 1
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 253
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\ProfileDAL\ProfileRepository.vb:line 49
Other Text: iProfile

