Function: GetOtherList
Datetime: 26/10/2017 3:02:46 PM
Error message: ORA-12545: Connect failed because target host or object does not exist
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 253
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\ProfileDAL\ProfileRepository.vb:line 49
Other Text: iProfile

Function: GetOtherList
Datetime: 26/10/2017 3:06:38 PM
Error message: ORA-12545: Connect failed because target host or object does not exist
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 253
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\ProfileDAL\ProfileRepository.vb:line 49
Other Text: iProfile

Function: GetOtherList
Datetime: 26/10/2017 4:24:54 PM
Error message: ORA-12545: Connect failed because target host or object does not exist
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 253
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\ProfileDAL\ProfileRepository.vb:line 49
Other Text: iProfile

Function: GetOtherList
Datetime: 26/10/2017 4:32:53 PM
Error message: ORA-12545: Connect failed because target host or object does not exist
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 253
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\ProfileDAL\ProfileRepository.vb:line 49
Other Text: iProfile

Function: GetOtherList
Datetime: 26/10/2017 4:35:21 PM
Error message: ORA-12545: Connect failed because target host or object does not exist
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 253
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\ProfileDAL\ProfileRepository.vb:line 49
Other Text: iProfile

Function: GetOtherList
Datetime: 26/10/2017 8:46:42 PM
Error message: ORA-12170: TNS:Connect timeout occurred
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 253
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\ProfileDAL\ProfileRepository.vb:line 49
Other Text: iProfile

Function: GetOtherList
Datetime: 26/10/2017 8:50:50 PM
Error message: ORA-12170: TNS:Connect timeout occurred
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 253
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\ProfileDAL\ProfileRepository.vb:line 49
Other Text: iProfile

Function: GetOtherList
Datetime: 26/10/2017 8:53:45 PM
Error message: ORA-12170: TNS:Connect timeout occurred
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 253
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\ProfileDAL\ProfileRepository.vb:line 49
Other Text: iProfile

