Function: InsertEmployee
Datetime: 19/10/2017 9:02:08 AM
Error message: ORA-06550: line 1, column 7:
PLS-00306: wrong number or types of arguments in call to 'CREATE_NEW_EMPCODE'
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore(String sql, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 162
   at ProfileDAL.ProfileRepository.InsertEmployee(EmployeeDTO objEmp, UserLog log, Decimal& gID, String& _strEmpCode, Byte[] _imageBinary, EmployeeCVDTO objEmpCV, EmployeeEduDTO objEmpEdu, EmployeeHealthDTO objEmpHealth) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\ProfileDAL\ProfileRepository.Employee.vb:line 705
Other Text: iProfile

Function: InsertEmployee
Datetime: 19/10/2017 9:30:52 AM
Error message: ORA-06550: line 1, column 7:
PLS-00306: wrong number or types of arguments in call to 'CREATE_NEW_EMPCODE'
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore(String sql, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 162
   at ProfileDAL.ProfileRepository.InsertEmployee(EmployeeDTO objEmp, UserLog log, Decimal& gID, String& _strEmpCode, Byte[] _imageBinary, EmployeeCVDTO objEmpCV, EmployeeEduDTO objEmpEdu, EmployeeHealthDTO objEmpHealth) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\ProfileDAL\ProfileRepository.Employee.vb:line 705
Other Text: iProfile

