Function: GetEmployeeCVByID
Datetime: 11/12/2017 10:38:19 AM
Error message: ORA-04063: package body "TVC_KYODO_TEST.PKG_PROFILE_REPORT" has errors
ORA-06508: PL/SQL: could not find program unit being called: "TVC_KYODO_TEST.PKG_PROFILE_REPORT"
ORA-06512: at line 1
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 253
   at ProfileDAL.ProfileRepository.GetEmployeeCVByID(String sPkgName, String sEmployee_id) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\ProfileDAL\ProfileRepository.vb:line 1637
Other Text: iProfile

Function: GetEmployeeCVByID
Datetime: 11/12/2017 11:07:35 AM
Error message: ORA-04063: package body "TVC_KYODO_TEST.PKG_PROFILE_REPORT" has errors
ORA-06508: PL/SQL: could not find program unit being called: "TVC_KYODO_TEST.PKG_PROFILE_REPORT"
ORA-06512: at line 1
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\Framework.Data\DataAccess\Query.vb:line 253
   at ProfileDAL.ProfileRepository.GetEmployeeCVByID(String sPkgName, String sEmployee_id) in E:\workspaces\KYODO\05.DEPLOYMENT\SP Core Level2\ProfileDAL\ProfileRepository.vb:line 1637
Other Text: iProfile

