Function: GetOtherList
Datetime: 6/25/2017 4:25:37 PM
Error message: ORA-12170: TNS:Connect timeout occurred
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in C:\Users\thuydinh\Documents\Visual Studio 2010\Projects\Project1\Framework.Data\DataAccess\Query.vb:line 253
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in C:\Users\thuydinh\Documents\Visual Studio 2010\Projects\Project1\ProfileDAL\ProfileRepository.vb:line 27
Other Text: iProfile

Function: GetOtherList
Datetime: 6/25/2017 4:26:00 PM
Error message: ORA-12170: TNS:Connect timeout occurred
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in C:\Users\thuydinh\Documents\Visual Studio 2010\Projects\Project1\Framework.Data\DataAccess\Query.vb:line 253
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in C:\Users\thuydinh\Documents\Visual Studio 2010\Projects\Project1\ProfileDAL\ProfileRepository.vb:line 27
Other Text: iProfile

