'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctrlEmployeeInfo

    '''<summary>
    '''rbiEmployeeImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbiEmployeeImage As Global.Telerik.Web.UI.RadBinaryImage

    '''<summary>
    '''lblEMPLOYEE_CODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEMPLOYEE_CODE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFULLNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFULLNAME As Global.System.Web.UI.WebControls.Label
End Class
