<%@ Control Language="vb" AutoEventWireup="false" CodeBehind="ctrlControlsNewEdit.ascx.vb"
    Inherits="Common.ctrlControlsNewEdit" %>
<%@ Import Namespace="Common" %>
<link href="/Styles/StyleCustom.css" rel="stylesheet" type="text/css" />
<%@ Register Src="../ctrlMessageBox.ascx" TagName="ctrlMessageBox" TagPrefix="Common" %>
<Common:ctrlMessageBox ID="ctrlMessageBox" runat="server" />
<tlk:RadSplitter ID="RadSplitter3" runat="server" Width="100%" Height="100%" Orientation="Horizontal">
    <tlk:RadPane ID="RadPane2" runat="server" Height="100%" Scrolling="Both">
        <tlk:RadToolBar ID="rtbMainToolBar" runat="server" OnClientButtonClicking="clientButtonClicking">
        </tlk:RadToolBar>
        <asp:Panel runat="server" ID="Panel1">
            <table class="table-form" style="width: 99%">
                <tr>
                    <td class="lbCom">
                        <%= Translate("Tên chức năng:")%>
                    </td>
                    <td class="infoCom">
                        <tlk:RadComboBox runat="server" AutoPostBack="true" ID="cboFunctionName" SkinID="LoadDemand">
                        </tlk:RadComboBox>
                    </td>
                </tr>
            </table>
        </asp:Panel>
        <tlk:RadPanelBar runat="server" ID="RadPanelBar1" Width="100%" ExpandMode="MultipleExpandedItems"
            OnClientItemClicking="HeightGridClick">
            <Items>
                <tlk:RadPanelItem Expanded="true" Text="<%$ Translate: Tùy chỉnh Control %>">
                    <ContentTemplate>
                        <tlk:RadGrid PageSize="200" ID="rgListControls" runat="server" AllowMultiRowEdit="true"
                            AllowSorting="false" AllowScroll="true">
                            <ClientSettings EnableRowHoverStyle="true">
                                <Selecting AllowRowSelect="true" />
                            </ClientSettings>
                            <MasterTableView ClientDataKeyNames="Ctl_ID,Label_text" DataKeyNames="Ctl_ID,Label_ID,Label_text,Is_Visible,Is_Validator,ErrorMessage,ErrorTooltip,Validator_ID"
                                EditMode="InPlace" EditFormSettings-EditFormType="AutoGenerated">
                                <Columns>
                                    <tlk:GridClientSelectColumn UniqueName="cbStatus" HeaderStyle-HorizontalAlign="Center"
                                        ItemStyle-HorizontalAlign="Center" HeaderStyle-Width="30px" />
                                    <tlk:GridBoundColumn HeaderText="Control ID" DataField="Ctl_ID" Visible="true" />
                                    <tlk:GridBoundColumn HeaderText="Label ID" DataField="Label_ID" Visible="true" />
                                    <tlk:GridBoundColumn HeaderText="Label" DataField="Label_text" SortExpression="Label_text"
                                        UniqueName="Label_text" Visible="true" />
                                    <tlk:GridCheckBoxColumn DataField="Is_Visible" HeaderText="Ẩn/Hiện" UniqueName="Is_Visible" />
                                    <tlk:GridCheckBoxColumn DataField="Is_Validator" HeaderText="Bắt buộc/Không bắt buộc"
                                        UniqueName="Is_Validator" />
                                    <tlk:GridBoundColumn HeaderText="Thông báo khi lỗi" DataField="ErrorMessage" SortExpression="ErrorMessage"
                                        UniqueName="ErrorMessage" Visible="true" />
                                    <tlk:GridBoundColumn HeaderText="Tooltip Thông báo khi lỗi" DataField="ErrorTooltip"
                                        SortExpression="ErrorTooltip" UniqueName="ErrorTooltip" Visible="true" />
                                    <tlk:GridBoundColumn HeaderText="Validator_ID" DataField="Validator_ID"
                                        SortExpression="Validator_ID" UniqueName="Validator_ID" Visible="true" />
                                    <%--<tlk:GridTemplateColumn HeaderText="Tooltip Thông báo khi lỗi" UniqueName="ErrorTooltip"
                                        SortExpression="ErrorTooltip">
                                        <ItemTemplate>
                                            <%# DataBinder.Eval(Container.DataItem, "ErrorTooltip")%>
                                        </ItemTemplate>
                                        <EditItemTemplate>
                                            <tlk:RadTextBox runat="server" ID="rwErrorTooltip" />
                                        </EditItemTemplate>
                                    </tlk:GridTemplateColumn>--%>
                                </Columns>
                            </MasterTableView>
                            <HeaderStyle HorizontalAlign="Center" Width="150px" />
                            <ClientSettings EnablePostBackOnRowClick="false">
                                <Scrolling FrozenColumnsCount="3" />
                            </ClientSettings>
                        </tlk:RadGrid>
                    </ContentTemplate>
                </tlk:RadPanelItem>
            </Items>
            <Items>
                <tlk:RadPanelItem Expanded="true" Text="<%$ Translate: Tùy chỉnh Grid %>">
                    <ContentTemplate>
                        <tlk:RadGrid PageSize="200" ID="rgListGrid" runat="server" AllowMultiRowEdit="true"
                            AllowSorting="false" AllowScroll="true">
                            <MasterTableView ClientDataKeyNames="ID,Name" DataKeyNames="ID,Name,Is_Visible,Width,OrderBy,DataType"
                                EditMode="InPlace" EditFormSettings-EditFormType="AutoGenerated">
                                <Columns>
                                    <tlk:GridClientSelectColumn UniqueName="cbStatus" HeaderStyle-HorizontalAlign="Center"
                                        ItemStyle-HorizontalAlign="Center" HeaderStyle-Width="30px" />
                                    <tlk:GridBoundColumn DataField="ID" Visible="false" />
                                    <tlk:GridBoundColumn DataField="Name" Visible="true" />
                                    <tlk:GridCheckBoxColumn DataField="Is_Visible" HeaderText="Ẩn/Hiện" UniqueName="Is_Visible" />
                                    <tlk:GridBoundColumn HeaderText="Độ rộng" DataField="Width" SortExpression="Width"
                                        UniqueName="Width" Visible="true" />
                                    <tlk:GridBoundColumn HeaderText="Số thứ tự" DataField="OrderBy" SortExpression="OrderBy"
                                        UniqueName="OrderBy" Visible="true" />
                                    <tlk:GridBoundColumn HeaderText="kiểu dữ liệu" DataField="DataType" SortExpression="DataType"
                                        UniqueName="DataType" Visible="true" />
                                </Columns>
                            </MasterTableView>
                            <HeaderStyle HorizontalAlign="Center" Width="150px" />
                            <ClientSettings EnablePostBackOnRowClick="false">
                                <Scrolling FrozenColumnsCount="3" />
                            </ClientSettings>
                        </tlk:RadGrid>
                    </ContentTemplate>
                </tlk:RadPanelItem>
            </Items>
        </tlk:RadPanelBar>
    </tlk:RadPane>
</tlk:RadSplitter>
<tlk:RadCodeBlock ID="RadCodeBlock1" runat="server">
    <script type="text/javascript">
        function HeightGrid() {
            var itemHeight_01 = $('#table_01').height();
            var itemHeight_02 = $('#table_02').height();
            var availHeight = $(window).height();
            var difference = availHeight - itemHeight_01 - itemHeight_02 - 35 - 20;
            $('#RadPaneData').css('height', difference + 'px');
            //alert(difference);
        }

        function clientButtonClicking(sender, args) {
            var m;
            var bCheck;
            var n;
            //            if (args.get_item().get_commandName() == 'SAVE') {
            //                args.set_cancel(true);
            //            }
            //            if (args.get_item().get_commandName() == 'CANCEL') {
            //                args.set_cancel(true);
            //            }
        }

        function HeightGridClick(sender, args) {
            HeightGrid();
        }

        var enableAjax = true;
        function onRequestStart(sender, eventArgs) {
            eventArgs.set_enableAjax(enableAjax);
            enableAjax = true;
        }
    </script>
</tlk:RadCodeBlock>
