-- --------------------------------------------------
-- Entity Designer DDL Script for Oracle database
-- --------------------------------------------------
-- Date Created: 26/12/2018 5:07:43 PM
-- Generated from EDMX file: D:\MyProject\TMF1\PayrollDAL\PayrollContext.edmx
-- --------------------------------------------------

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

-- ALTER TABLE "PayrollModelStoreContainer"."PA_SALARY_LEVEL" DROP CONSTRAINT "FK_PSG_PSL" CASCADE;

-- ALTER TABLE "PayrollModelStoreContainer"."PA_SALARY_RANK" DROP CONSTRAINT "FK_PSL_PSR" CASCADE;

-- ALTER TABLE "PayrollModelStoreContainer"."HU_EMPLOYEE_HEALTH" DROP CONSTRAINT "FK_FE_HEH" CASCADE;

-- ALTER TABLE "PayrollModelStoreContainer"."HU_EMPLOYEE_CV" DROP CONSTRAINT "FK_HE_HEC" CASCADE;

-- ALTER TABLE "PayrollModelStoreContainer"."HU_EMPLOYEE_EDUCATION" DROP CONSTRAINT "FK_HE_HEE" CASCADE;

-- ALTER TABLE "PayrollModelStoreContainer"."HU_EMPLOYEE_FILES" DROP CONSTRAINT "FK_HE_HEF" CASCADE;

-- ALTER TABLE "PayrollModelStoreContainer"."HU_EMPLOYEE_OTHER_INFO" DROP CONSTRAINT "FK_HE_HEO" CASCADE;

-- ALTER TABLE "PayrollModelStoreContainer"."HU_EMPLOYEE_SALARY" DROP CONSTRAINT "FK_HE_HES" CASCADE;

-- ALTER TABLE "PayrollModelStoreContainer"."HU_WORKING" DROP CONSTRAINT "FK_HE_HW" CASCADE;

-- ALTER TABLE "PayrollModelStoreContainer"."HU_WORKING" DROP CONSTRAINT "FK_HUDM_HUWK" CASCADE;

-- ALTER TABLE "PayrollModelStoreContainer"."HU_EMPLOYEE" DROP CONSTRAINT "FK_HUEMD_HUEM" CASCADE;

-- ALTER TABLE "PayrollModelStoreContainer"."HU_EMPLOYEE" DROP CONSTRAINT "FK_HUEMI_HUEM" CASCADE;

-- ALTER TABLE "PayrollModelStoreContainer"."HU_WORKING" DROP CONSTRAINT "FK_HUIM_HUWK" CASCADE;

-- ALTER TABLE "PayrollModelStoreContainer"."OT_OTHER_LIST_TYPE" DROP CONSTRAINT "FK_OOLG_OOLT" CASCADE;

-- ALTER TABLE "PayrollModelStoreContainer"."HU_ORGANIZATION" DROP CONSTRAINT "FK_HU_ORG_HU_ORG" CASCADE;

-- ALTER TABLE "PayrollModelStoreContainer"."PA_SALARYTYPE_GROUP" DROP CONSTRAINT "FK_SALARYTYPE_FK" CASCADE;

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

-- DROP TABLE "PayrollModelStoreContainer"."PA_SALARY_GROUP";

-- DROP TABLE "PayrollModelStoreContainer"."PA_SALARY_LEVEL";

-- DROP TABLE "PayrollModelStoreContainer"."PA_SALARY_RANK";

-- DROP TABLE "PayrollModelStoreContainer"."HU_EMPLOYEE";

-- DROP TABLE "PayrollModelStoreContainer"."HU_EMPLOYEE_CV";

-- DROP TABLE "PayrollModelStoreContainer"."HU_EMPLOYEE_EDUCATION";

-- DROP TABLE "PayrollModelStoreContainer"."HU_EMPLOYEE_FILES";

-- DROP TABLE "PayrollModelStoreContainer"."HU_EMPLOYEE_HEALTH";

-- DROP TABLE "PayrollModelStoreContainer"."HU_EMPLOYEE_OTHER_INFO";

-- DROP TABLE "PayrollModelStoreContainer"."HU_EMPLOYEE_SALARY";

-- DROP TABLE "PayrollModelStoreContainer"."HU_EMPLOYEE_TRAIN";

-- DROP TABLE "PayrollModelStoreContainer"."HU_WORKING";

-- DROP TABLE "PayrollModelStoreContainer"."OT_OTHER_LIST";

-- DROP TABLE "PayrollModelStoreContainer"."OT_OTHER_LIST_GROUP";

-- DROP TABLE "PayrollModelStoreContainer"."OT_OTHER_LIST_TYPE";

-- DROP TABLE "PayrollModelStoreContainer"."PA_HOLD_SALARY";

-- DROP TABLE "PayrollModelStoreContainer"."HU_ORGANIZATION";

-- DROP TABLE "PayrollModelStoreContainer"."SE_CHOSEN_ORG";

-- DROP TABLE "PayrollModelStoreContainer"."AT_ORG_PERIOD";

-- DROP TABLE "PayrollModelStoreContainer"."SE_CHOSEN_CALCULATE";

-- DROP TABLE "PayrollModelStoreContainer"."PA_OBJECT_SALARY";

-- DROP TABLE "PayrollModelStoreContainer"."PA_FORMULER";

-- DROP TABLE "PayrollModelStoreContainer"."PA_FORMULER_GROUP";

-- DROP TABLE "PayrollModelStoreContainer"."PA_ORG_LUNCH";

-- DROP TABLE "PayrollModelStoreContainer"."PA_PRICE_LUNCH";

-- DROP TABLE "PayrollModelStoreContainer"."PA_PAYMENT_LIST";

-- DROP TABLE "PayrollModelStoreContainer"."PA_INCENTIVE_RANK";

-- DROP TABLE "PayrollModelStoreContainer"."PA_INCENTIVE_RANK_DETAIL";

-- DROP TABLE "PayrollModelStoreContainer"."PA_SALARY_TYPE";

-- DROP TABLE "PayrollModelStoreContainer"."PA_SALARYTYPE_GROUP";

-- DROP TABLE "PayrollModelStoreContainer"."PA_COST_CENTER";

-- DROP TABLE "PayrollModelStoreContainer"."PA_ORGBONUS";

-- DROP TABLE "PayrollModelStoreContainer"."PA_PAYMENTSOURCES";

-- DROP TABLE "PayrollModelStoreContainer"."PA_WORKFACTOR";

-- DROP TABLE "PayrollModelStoreContainer"."PA_WORK_STANDARD";

-- DROP TABLE "PayrollModelStoreContainer"."AT_PERIOD";

-- DROP TABLE "PayrollModelStoreContainer"."PA_LISTSAL";

-- DROP TABLE "PayrollModelStoreContainer"."PA_LISTSALARIES";

-- DROP TABLE "PayrollModelStoreContainer"."PA_TAXATION";

-- DROP TABLE "PayrollModelStoreContainer"."HU_ALLOWANCE_LIST";

-- DROP TABLE "PayrollModelStoreContainer"."HU_ALLOWANCE";

-- DROP TABLE "PayrollModelStoreContainer"."PA_SEND_PAYSLIP";

-- DROP TABLE "PayrollModelStoreContainer"."PA_SEND_PAYSLIP_EMP";

-- DROP TABLE "PayrollModelStoreContainer"."SE_MAIL";

-- DROP TABLE "PayrollModelStoreContainer"."PA_BONUS_IMPORT";

-- DROP TABLE "PayrollModelStoreContainer"."PA_SALARY_FUND_MAPPING";

-- DROP TABLE "PayrollModelStoreContainer"."PA_SEND_BONUSSLIP";

-- DROP TABLE "PayrollModelStoreContainer"."PA_SEND_BONUSSLIP_EMP";

-- DROP TABLE "PayrollModelStoreContainer"."PA_SALARY_FUND";

-- DROP TABLE "PayrollModelStoreContainer"."PA_SALARY_PLANNING";

-- DROP TABLE "PayrollModelStoreContainer"."PA_SENIORITY_DAILY";

-- DROP TABLE "PayrollModelStoreContainer"."PA_SENIORITY_DAILY_TEMP";

-- DROP TABLE "PayrollModelStoreContainer"."PA_SENIORITY_DETAILS";

-- DROP TABLE "PayrollModelStoreContainer"."PA_SENIORITY_DETAILS_TEMP";

-- DROP TABLE "PayrollModelStoreContainer"."PA_SENIORITY_MONTHLY";

-- DROP TABLE "PayrollModelStoreContainer"."PA_SENIORITY_PROCESS";

-- DROP TABLE "PayrollModelStoreContainer"."PA_TITLE_COST";

-- DROP TABLE "PayrollModelStoreContainer"."HU_TITLE";

-- DROP TABLE "PayrollModelStoreContainer"."PA_SALE_COMMISION";

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'PA_SALARY_GROUP'
CREATE TABLE "dbo"."PA_SALARY_GROUP" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(15) NOT NULL,
   "NAME" NVARCHAR2(255) NOT NULL,
   "EFFECT_DATE" DATE NOT NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NOT NULL,
   "CREATED_BY" NVARCHAR2(255) NOT NULL,
   "CREATED_LOG" NVARCHAR2(255) NOT NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_BY" NVARCHAR2(255) NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NOT NULL,
   "ORDERS" NUMBER(38,0) NULL,
   "IS_COEFFICIENT" NUMBER(38,0) NULL,
   "IS_INCENTIVE" NUMBER(38,0) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "IS_DELETED" NUMBER(38,0) NULL
);

-- Creating table 'PA_SALARY_LEVEL'
CREATE TABLE "dbo"."PA_SALARY_LEVEL" (
   "ID" NUMBER(38,0) NOT NULL,
   "SAL_GROUP_ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(15) NOT NULL,
   "NAME" NVARCHAR2(255) NOT NULL,
   "REMARK" NCLOB NULL,
   "CREATED_DATE" DATE NOT NULL,
   "CREATED_BY" NVARCHAR2(255) NOT NULL,
   "CREATED_LOG" NVARCHAR2(255) NOT NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_BY" NVARCHAR2(255) NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NOT NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "ORDERS" NUMBER(38,0) NULL,
   "OTHER_USE" NVARCHAR2(255) NOT NULL
);

-- Creating table 'PA_SALARY_RANK'
CREATE TABLE "dbo"."PA_SALARY_RANK" (
   "ID" NUMBER(38,0) NOT NULL,
   "SAL_LEVEL_ID" NUMBER(38,0) NOT NULL,
   "RANK" NVARCHAR2(255) NULL,
   "SALARY_BASIC" NUMBER(38,0) NULL,
   "REMARK" NCLOB NULL,
   "CREATED_DATE" DATE NOT NULL,
   "CREATED_BY" NVARCHAR2(255) NOT NULL,
   "CREATED_LOG" NVARCHAR2(255) NOT NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_BY" NVARCHAR2(255) NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NOT NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "SAL_GROUP_ID" NUMBER(38,0) NULL,
   "ORDERS" NUMBER(38,0) NULL
);

-- Creating table 'HU_EMPLOYEE'
CREATE TABLE "dbo"."HU_EMPLOYEE" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_CODE" NVARCHAR2(15) NULL,
   "FIRST_NAME_VN" NVARCHAR2(255) NULL,
   "LAST_NAME_VN" NVARCHAR2(255) NULL,
   "FULLNAME_VN" NVARCHAR2(255) NULL,
   "FIRST_NAME_EN" VARCHAR2(255) NULL,
   "LAST_NAME_EN" NVARCHAR2(255) NULL,
   "FULLNAME_EN" NVARCHAR2(255) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "WORK_STATUS" NUMBER(38,0) NULL,
   "CONTRACT_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "JOIN_DATE" DATE NULL,
   "INDIRECT_MANAGER" NUMBER(38,0) NULL,
   "DIRECT_MANAGER" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "LAST_WORKING_ID" NUMBER(38,0) NULL,
   "TER_EFFECT_DATE" DATE NULL,
   "TER_LAST_DATE" DATE NULL,
   "COST_CENTER" NUMBER(38,0) NULL
);

-- Creating table 'HU_EMPLOYEE_CV'
CREATE TABLE "dbo"."HU_EMPLOYEE_CV" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "GENDER" NUMBER(38,0) NULL,
   "IMAGE" NVARCHAR2(255) NULL,
   "BIRTH_DATE" DATE NULL,
   "BIRTH_PLACE" NVARCHAR2(255) NULL,
   "BIRTH_DISTRICT" NUMBER(38,0) NULL,
   "BIRTH_PROVINCE" NUMBER(38,0) NULL,
   "BIRTH_NATION" NUMBER(38,0) NULL,
   "MARITAL_STATUS" NUMBER(38,0) NULL,
   "RELIGION" NUMBER(38,0) NULL,
   "NATIVE" NUMBER(38,0) NULL,
   "NATIONALITY" NUMBER(38,0) NULL,
   "PER_ADDRESS" NVARCHAR2(255) NULL,
   "PER_DISTRICT" NUMBER(38,0) NULL,
   "PER_PROVINCE" NUMBER(38,0) NULL,
   "PER_NATION" NUMBER(38,0) NULL,
   "CUR_ADDRESS" NVARCHAR2(255) NULL,
   "CUR_DISTRICT" NUMBER(38,0) NULL,
   "CUR_PROVINCE" NUMBER(38,0) NULL,
   "CUR_NATION" NUMBER(38,0) NULL,
   "HOME_PHONE" NVARCHAR2(255) NULL,
   "MOBILE_PHONE" NVARCHAR2(255) NULL,
   "ID_NO" NVARCHAR2(15) NULL,
   "ID_DATE" DATE NULL,
   "ID_PLACE" NUMBER(38,0) NULL,
   "PASS_NO" NVARCHAR2(255) NULL,
   "PASS_DATE" DATE NULL,
   "PASS_EXPIRE" DATE NULL,
   "PASS_PLACE" NVARCHAR2(255) NULL,
   "VISA" NVARCHAR2(255) NULL,
   "VISA_DATE" DATE NULL,
   "VISA_EXPIRE" DATE NULL,
   "VISA_PLACE" NVARCHAR2(255) NULL,
   "WORK_PERMIT" NVARCHAR2(255) NULL,
   "WORK_PERMIT_DATE" DATE NULL,
   "WORK_PERMIT_EXPIRE" DATE NULL,
   "WORK_EMAIL" NVARCHAR2(255) NULL,
   "RESIDENCE" NVARCHAR2(255) NULL,
   "RESIDENCE_DATE" DATE NULL,
   "RESIDENCE_EXPIRE" DATE NULL,
   "RESIDENCE_PLACE" NVARCHAR2(255) NULL,
   "NAV_ADDRESS" NVARCHAR2(255) NULL,
   "NAV_DISTRICT" NUMBER(38,0) NULL,
   "NAV_PROVINCE" NUMBER(38,0) NULL,
   "NAV_NATION" NUMBER(38,0) NULL,
   "IS_RESIDENT" NUMBER(5,0) NULL,
   "PIT_CODE" VARCHAR2(255) NULL,
   "PER_EMAIL" NVARCHAR2(255) NULL,
   "CONTACT_PER" NVARCHAR2(255) NULL,
   "CONTACT_PER_PHONE" NVARCHAR2(15) NULL,
   "CONTACT_NATION" NUMBER(38,0) NULL,
   "CONTACT_PROVINCE" NUMBER(38,0) NULL,
   "CONTACT_DISTRICT" NUMBER(38,0) NULL,
   "CONTACT_ADDRESS" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "CONTACT_RELATION" NVARCHAR2(255) NULL
);

-- Creating table 'HU_EMPLOYEE_EDUCATION'
CREATE TABLE "dbo"."HU_EMPLOYEE_EDUCATION" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "ACADEMY" NUMBER(38,0) NULL,
   "MAJOR" NUMBER(38,0) NULL,
   "NLEVEL" NUMBER(38,0) NULL,
   "COMPUTER_CER1" NVARCHAR2(255) NULL,
   "COMPUTER_CER2" NVARCHAR2(255) NULL,
   "COMPUTER_CER3" NVARCHAR2(255) NULL,
   "COMPUTER_LEVEL1" NUMBER(38,0) NULL,
   "COMPUTER_LEVEL2" NUMBER(38,0) NULL,
   "COMPUTER_LEVEL3" NUMBER(38,0) NULL,
   "COMPUTER_MARK1" NVARCHAR2(15) NULL,
   "COMPUTER_MARK2" NVARCHAR2(15) NULL,
   "COMPUTER_MARK3" NVARCHAR2(15) NULL,
   "LANGUAGE1" NUMBER(38,0) NULL,
   "LANGUAGE2" NUMBER(38,0) NULL,
   "LANGUAGE3" NUMBER(38,0) NULL,
   "LANGUAGE_LEVEL1" NUMBER(38,0) NULL,
   "LANGUAGE_LEVEL2" NUMBER(38,0) NULL,
   "LANGUAGE_LEVEL3" NUMBER(38,0) NULL,
   "LANGUAGE_MARK1" NVARCHAR2(15) NULL,
   "LANGUAGE_MARK2" NVARCHAR2(15) NULL,
   "LANGUAGE_MARK3" NVARCHAR2(15) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "GRADUATE_SCHOOL" NVARCHAR2(255) NULL
);

-- Creating table 'HU_EMPLOYEE_FILES'
CREATE TABLE "dbo"."HU_EMPLOYEE_FILES" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "FILE_TYPE" NUMBER(38,0) NULL,
   "FILE_NAME" NVARCHAR2(255) NULL,
   "FILE_SIZE" NUMBER(10,0) NULL,
   "NOTE" NVARCHAR2(255) NULL,
   "UPLOAD_BY" NVARCHAR2(255) NULL,
   "UPLOAD_DATE" DATE NULL
);

-- Creating table 'HU_EMPLOYEE_HEALTH'
CREATE TABLE "dbo"."HU_EMPLOYEE_HEALTH" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "CHIEU_CAO" BINARY_DOUBLE NULL,
   "CAN_NANG" BINARY_DOUBLE NULL,
   "NHOM_MAU" NVARCHAR2(15) NULL,
   "HUYET_AP" NVARCHAR2(15) NULL,
   "MAT_TRAI" NVARCHAR2(15) NULL,
   "MAT_PHAI" NVARCHAR2(15) NULL,
   "LOAI_SUC_KHOE" NUMBER(38,0) NULL,
   "TAI_MUI_HONG" NVARCHAR2(255) NULL,
   "RANG_HAM_MAT" NVARCHAR2(255) NULL,
   "TIM" NVARCHAR2(255) NULL,
   "PHOI_NGUC" NVARCHAR2(255) NULL,
   "VIEM_GAN_B" NVARCHAR2(255) NULL,
   "DA_HOA_LIEU" NVARCHAR2(255) NULL,
   "DU_SUC_KHOE" NVARCHAR2(255) NULL,
   "GHI_CHU_SUC_KHOE" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_EMPLOYEE_OTHER_INFO'
CREATE TABLE "dbo"."HU_EMPLOYEE_OTHER_INFO" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "NGAY_VAO_DOAN" DATE NULL,
   "NOI_VAO_DOAN" NVARCHAR2(255) NULL,
   "NOI_SINH_HOAT_DOAN" NVARCHAR2(255) NULL,
   "DOAN_PHI" NUMBER(5,0) NULL,
   "NGAY_VAO_DANG" DATE NULL,
   "NOI_VAO_DANG" NVARCHAR2(255) NULL,
   "NOI_SINH_HOAT_DANG" NVARCHAR2(255) NULL,
   "DANG_PHI" NUMBER(5,0) NULL,
   "SO_TAI_KHOAN" NVARCHAR2(255) NULL,
   "NGAN_HANG" NUMBER(38,0) NULL,
   "CHI_NHANH" NUMBER(38,0) NULL,
   "NGAY_HIEU_LUC" DATE NULL,
   "NGUOI_THU_HUONG" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_EMPLOYEE_SALARY'
CREATE TABLE "dbo"."HU_EMPLOYEE_SALARY" (
   "EMPLOYEE_ID" NUMBER(38,0) NOT NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "BASIC_SAL" NUMBER(38,0) NULL,
   "SOFT_SAL" NUMBER(38,0) NULL,
   "OTHER_SAL" NUMBER(38,0) NULL,
   "COEFFICIENT" NUMBER(38,0) NULL,
   "CONTRACTUAL_SAL" NUMBER(38,0) NULL,
   "SALARY_ENTERPRISE_ID" NUMBER(38,0) NULL,
   "ALLOWANCE_IDS" NVARCHAR2(255) NULL,
   "ALLOWANCE_SAL" NUMBER(38,0) NULL,
   "ALLOWANCE_TOTAL" NUMBER(38,0) NULL,
   "PERCENT_SALARY" NUMBER(5,0) NULL
);

-- Creating table 'HU_EMPLOYEE_TRAIN'
CREATE TABLE "dbo"."HU_EMPLOYEE_TRAIN" (
   "ID" NUMBER(38,0) NOT NULL,
   "FROM_DATE" DATE NULL,
   "TO_DATE" DATE NULL,
   "SCHOOL_NAME" NCLOB NULL,
   "TRAINING_FORM" NUMBER(38,0) NULL,
   "HIGHEST_LEVEL" NUMBER(5,0) NOT NULL,
   "LEARNING_LEVEL" NUMBER(38,0) NULL,
   "MAJOR" NUMBER(38,0) NULL,
   "GRADUATE_YEAR" NUMBER(38,0) NULL,
   "MARK" NUMBER(38,0) NULL,
   "TRAINING_CONTENT" NCLOB NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_WORKING'
CREATE TABLE "dbo"."HU_WORKING" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TRANSFER_TYPE" NUMBER(38,0) NULL,
   "TRANSFER_REASON" NUMBER(38,0) NULL,
   "INDIRECT_MANAGER" NUMBER(38,0) NULL,
   "DIRECT_MANAGER" NUMBER(38,0) NULL,
   "IS_DECISION" NUMBER(5,0) NULL,
   "DECISION_ID" NUMBER(38,0) NULL,
   "STATUS" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "EFFECT_DATE" DATE NULL,
   "EXPIRE_DATE" DATE NULL,
   "WORKING_TYPE" NUMBER(5,0) NULL,
   "COST_CENTER" NUMBER(38,0) NULL,
   "BASIC_SAL" NUMBER(38,0) NULL,
   "SOFT_SAL" NUMBER(38,0) NULL,
   "OTHER_SAL" NUMBER(38,0) NULL,
   "COEFFICIENT" NUMBER(38,0) NULL,
   "CONTRACTUAL_SAL" NUMBER(38,0) NULL,
   "SALARY_ENTERPRISE_ID" NUMBER(38,0) NULL,
   "ALLOWANCE_IDS" NVARCHAR2(255) NULL,
   "ALLOWANCE_SAL" NUMBER(38,0) NULL,
   "ALLOWANCE_TOTAL" NUMBER(38,0) NULL
);

-- Creating table 'OT_OTHER_LIST'
CREATE TABLE "dbo"."OT_OTHER_LIST" (
   "ID" NUMBER(38,0) NOT NULL,
   "TYPE_ID" NUMBER(38,0) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "ATTRIBUTE1" NVARCHAR2(255) NULL,
   "ATTRIBUTE2" NVARCHAR2(255) NULL,
   "ATTRIBUTE3" NVARCHAR2(255) NULL,
   "ATTRIBUTE4" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "CODE" NVARCHAR2(15) NULL,
   "TYPE_CODE" NVARCHAR2(15) NULL,
   "ORDERBYID" NUMBER(38,0) NULL
);

-- Creating table 'OT_OTHER_LIST_GROUP'
CREATE TABLE "dbo"."OT_OTHER_LIST_GROUP" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'OT_OTHER_LIST_TYPE'
CREATE TABLE "dbo"."OT_OTHER_LIST_TYPE" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(255) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "GROUP_ID" NUMBER(38,0) NULL,
   "IS_SYSTEM" NUMBER(5,0) NULL,
   "TABLE_RELATION" VARCHAR2(2000) NULL
);

-- Creating table 'PA_HOLD_SALARY'
CREATE TABLE "dbo"."PA_HOLD_SALARY" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_ORGANIZATION'
CREATE TABLE "dbo"."HU_ORGANIZATION" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(35) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "PARENT_ID" NUMBER(38,0) NULL,
   "DISSOLVE_DATE" DATE NULL,
   "FOUNDATION_DATE" DATE NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "HIERARCHICAL_PATH" VARCHAR2(1023) NULL,
   "DESCRIPTION_PATH" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ADDRESS" NVARCHAR2(1023) NULL,
   "FAX" NVARCHAR2(1023) NULL,
   "REPRESENTATIVE_ID" NUMBER(38,0) NULL
);

-- Creating table 'SE_CHOSEN_ORG'
CREATE TABLE "dbo"."SE_CHOSEN_ORG" (
   "ORG_ID" NUMBER(38,0) NOT NULL,
   "USERNAME" NVARCHAR2(255) NOT NULL
);

-- Creating table 'AT_ORG_PERIOD'
CREATE TABLE "dbo"."AT_ORG_PERIOD" (
   "ID" NUMBER(38,0) NOT NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "STATUSCOLEX" NUMBER(38,0) NULL,
   "STATUSPAROX" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'SE_CHOSEN_CALCULATE'
CREATE TABLE "dbo"."SE_CHOSEN_CALCULATE" (
   "EMPLOYEEID" NUMBER(38,0) NOT NULL,
   "USERNAME" NVARCHAR2(255) NOT NULL
);

-- Creating table 'PA_OBJECT_SALARY'
CREATE TABLE "dbo"."PA_OBJECT_SALARY" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(20) NULL,
   "NAME_VN" NVARCHAR2(200) NULL,
   "NAME_EN" NVARCHAR2(200) NULL,
   "EFFECTIVE_DATE" DATE NULL,
   "SDESC" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'PA_FORMULER'
CREATE TABLE "dbo"."PA_FORMULER" (
   "ID" NUMBER(38,0) NOT NULL,
   "COL_NAME" NVARCHAR2(200) NULL,
   "INDEX_FML" NUMBER(38,0) NULL,
   "GROUP_FML" NUMBER(38,0) NULL,
   "FORMULER" NVARCHAR2(2000) NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'PA_FORMULER_GROUP'
CREATE TABLE "dbo"."PA_FORMULER_GROUP" (
   "ID" NUMBER(38,0) NOT NULL,
   "TYPE_PAYMENT" NUMBER(38,0) NULL,
   "OBJ_SAL_ID" NUMBER(38,0) NULL,
   "NAME_VN" NVARCHAR2(200) NULL,
   "NAME_EN" NVARCHAR2(200) NULL,
   "START_DATE" DATE NULL,
   "END_DATE" DATE NULL,
   "STATUS" NUMBER(38,0) NULL,
   "SDESC" NVARCHAR2(2000) NULL,
   "IDX" NUMBER(38,0) NULL
);

-- Creating table 'PA_ORG_LUNCH'
CREATE TABLE "dbo"."PA_ORG_LUNCH" (
   "ID" NUMBER(38,0) NOT NULL,
   "LUNCH_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'PA_PRICE_LUNCH'
CREATE TABLE "dbo"."PA_PRICE_LUNCH" (
   "ID" NUMBER(38,0) NOT NULL,
   "PRICE" NUMBER(38,0) NULL,
   "EFFECT_DATE" DATE NULL,
   "EXPIRE_DATE" DATE NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'PA_PAYMENT_LIST'
CREATE TABLE "dbo"."PA_PAYMENT_LIST" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NOT NULL,
   "OBJ_PAYMENT_ID" NUMBER(38,0) NULL,
   "EFFECTIVE_DATE" DATE NOT NULL,
   "VALUE" NUMBER(38,0) NULL,
   "SDESC" NVARCHAR2(1000) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "ORDERS" NUMBER(38,0) NULL
);

-- Creating table 'PA_INCENTIVE_RANK'
CREATE TABLE "dbo"."PA_INCENTIVE_RANK" (
   "ID" NUMBER(38,0) NOT NULL,
   "SAL_GROUP_ID" NUMBER(38,0) NULL,
   "SAL_LEVEL_ID" NUMBER(38,0) NULL,
   "SAL_RANK_ID" NUMBER(38,0) NULL,
   "SAL_INCENTIVE_ID" NUMBER(38,0) NULL,
   "EFFECT_DATE" DATE NOT NULL,
   "REMARK" NVARCHAR2(255) NULL,
   "ORDERS" NUMBER(38,0) NULL,
   "ACTFLG" NCLOB NOT NULL,
   "CREATED_DATE" DATE NOT NULL,
   "CREATED_BY" NCLOB NULL,
   "CREATED_LOG" NCLOB NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NCLOB NULL,
   "MODIFIED_LOG" NCLOB NULL
);

-- Creating table 'PA_INCENTIVE_RANK_DETAIL'
CREATE TABLE "dbo"."PA_INCENTIVE_RANK_DETAIL" (
   "ID" NUMBER(38,0) NOT NULL,
   "INCENTIVE_RANK_ID" NUMBER(38,0) NULL,
   "FROM_TARGET" NUMBER(38,0) NULL,
   "TO_TARGET" NUMBER(38,0) NULL,
   "AMOUNT" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(255) NULL,
   "ORDERS" NUMBER(38,0) NULL,
   "ACTFLG" NCLOB NOT NULL,
   "CREATED_DATE" DATE NOT NULL,
   "CREATED_BY" NCLOB NULL,
   "CREATED_LOG" NCLOB NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NCLOB NULL,
   "MODIFIED_LOG" NCLOB NULL,
   "INCENTIVE_PERCENT" NUMBER(38,0) NULL,
   "INCENTIVE_AMOUNT" NUMBER(38,0) NULL
);

-- Creating table 'PA_SALARY_TYPE'
CREATE TABLE "dbo"."PA_SALARY_TYPE" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(15) NOT NULL,
   "NAME" NVARCHAR2(255) NOT NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NOT NULL,
   "CREATED_BY" NVARCHAR2(255) NOT NULL,
   "CREATED_LOG" NVARCHAR2(255) NOT NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_BY" NVARCHAR2(255) NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NOT NULL,
   "ORDERS" NUMBER(38,0) NULL,
   "IS_INCENTIVE" NUMBER(38,0) NULL,
   "ACTFLG" NVARCHAR2(1) NULL
);

-- Creating table 'PA_SALARYTYPE_GROUP'
CREATE TABLE "dbo"."PA_SALARYTYPE_GROUP" (
   "ID" NUMBER(38,0) NOT NULL,
   "SAL_TYPE_ID" NUMBER(38,0) NOT NULL,
   "SAL_GROUP_ID" NUMBER(38,0) NOT NULL,
   "IS_DIRECT_SALARY" NUMBER(38,0) NOT NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NOT NULL,
   "CREATED_BY" NVARCHAR2(255) NOT NULL,
   "CREATED_LOG" NVARCHAR2(255) NOT NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_BY" NVARCHAR2(255) NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NOT NULL,
   "ORDERS" NUMBER(38,0) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "IS_DELETED" NUMBER(38,0) NULL
);

-- Creating table 'PA_COST_CENTER'
CREATE TABLE "dbo"."PA_COST_CENTER" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(15) NOT NULL,
   "NAME" NVARCHAR2(255) NOT NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NOT NULL,
   "CREATED_BY" NVARCHAR2(255) NOT NULL,
   "CREATED_LOG" NVARCHAR2(255) NOT NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_BY" NVARCHAR2(255) NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NOT NULL,
   "ORDERS" NUMBER(38,0) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "IS_DELETED" NUMBER(38,0) NULL
);

-- Creating table 'PA_ORGBONUS'
CREATE TABLE "dbo"."PA_ORGBONUS" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ORDERS" NUMBER(38,0) NULL,
   "ACTFLG" NVARCHAR2(1) NULL
);

-- Creating table 'PA_PAYMENTSOURCES'
CREATE TABLE "dbo"."PA_PAYMENTSOURCES" (
   "ID" NUMBER(38,0) NOT NULL,
   "YEAR" NUMBER(38,0) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ORDERS" NUMBER(38,0) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "PAY_TYPE" NUMBER(38,0) NULL
);

-- Creating table 'PA_WORKFACTOR'
CREATE TABLE "dbo"."PA_WORKFACTOR" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(20) NOT NULL,
   "XEPLOAI" NVARCHAR2(255) NULL,
   "FACTOR" NUMBER(38,0) NULL,
   "BONUSE" NUMBER(38,0) NULL,
   "EFFECT_DATE" DATE NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL
);

-- Creating table 'PA_WORK_STANDARD'
CREATE TABLE "dbo"."PA_WORK_STANDARD" (
   "ID" NUMBER(38,0) NOT NULL,
   "YEAR" NUMBER(38,0) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "OBJECT_ID" NUMBER(38,0) NULL,
   "PERIOD_STANDARD" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'AT_PERIOD'
CREATE TABLE "dbo"."AT_PERIOD" (
   "YEAR" NUMBER(38,0) NULL,
   "MONTH" NUMBER(38,0) NULL,
   "PERIOD_NAME" NVARCHAR2(255) NULL,
   "START_DATE" DATE NULL,
   "END_DATE" DATE NULL,
   "PERIOD_STANDARD" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ID" NUMBER(38,0) NOT NULL,
   "BONUS_DATE" DATE NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "ACTFLG" NVARCHAR2(1) NULL
);

-- Creating table 'PA_LISTSAL'
CREATE TABLE "dbo"."PA_LISTSAL" (
   "ID" NUMBER(38,0) NOT NULL,
   "COL_NAME" VARCHAR2(20) NULL,
   "NAME_VN" VARCHAR2(200) NULL,
   "NAME_EN" VARCHAR2(200) NULL,
   "DATA_TYPE" NUMBER(38,0) NULL,
   "GROUP_TYPE" NUMBER(38,0) NULL,
   "COL_INDEX" NUMBER(38,0) NULL,
   "STATUS" VARCHAR2(1) NULL,
   "COL_CODE" NVARCHAR2(20) NULL,
   "REMARK" NVARCHAR2(500) NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'PA_LISTSALARIES'
CREATE TABLE "dbo"."PA_LISTSALARIES" (
   "ID" NUMBER(38,0) NOT NULL,
   "TYPE_PAYMENT" NUMBER(38,0) NULL,
   "COL_NAME" VARCHAR2(50) NULL,
   "NAME_VN" VARCHAR2(200) NULL,
   "NAME_EN" VARCHAR2(200) NULL,
   "DATA_TYPE" NUMBER(38,0) NULL,
   "COL_INDEX" NUMBER(38,0) NULL,
   "STATUS" VARCHAR2(1) NULL,
   "IS_VISIBLE" NUMBER(38,0) NULL,
   "IS_INPUT" NUMBER(38,0) NULL,
   "IS_CALCULATE" NUMBER(38,0) NULL,
   "IS_IMPORT" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "INPUT_FORMULER" CLOB NULL,
   "COL_CODE" NVARCHAR2(255) NULL,
   "IS_WORKARISING" NUMBER(5,0) NULL,
   "IS_SUMARISING" NUMBER(5,0) NULL,
   "IS_PAYBACK" NUMBER(5,0) NULL,
   "IS_DELETED" NUMBER(5,0) NULL,
   "IMPORT_TYPE_ID" NUMBER(38,0) NULL,
   "REMARK" NVARCHAR2(500) NULL,
   "EFFECTIVE_DATE" DATE NULL,
   "EXPIRE_DATE" DATE NULL,
   "IS_WORKDAY" NUMBER(5,0) NULL,
   "IS_SUMDAY" NUMBER(5,0) NULL,
   "OBJ_SAL_ID" NUMBER(38,0) NULL,
   "GROUP_TYPE" NUMBER(38,0) NULL
);

-- Creating table 'PA_TAXATION'
CREATE TABLE "dbo"."PA_TAXATION" (
   "ID" NUMBER(38,0) NOT NULL,
   "RESIDENT_ID" NUMBER(38,0) NULL,
   "VALUE_FROM" NUMBER(38,0) NULL,
   "VALUE_TO" NUMBER(38,0) NULL,
   "RATE" NUMBER(38,0) NULL,
   "EXCEPT_FAST" NUMBER(38,0) NULL,
   "FROM_DATE" DATE NULL,
   "TO_DATE" DATE NULL,
   "SDESC" NVARCHAR2(2000) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "ORDERS" NUMBER(38,0) NULL
);

-- Creating table 'HU_ALLOWANCE_LIST'
CREATE TABLE "dbo"."HU_ALLOWANCE_LIST" (
   "ID" NUMBER(38,0) NOT NULL,
   "NAME" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CODE" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "ALLOWANCE_TYPE" NUMBER(38,0) NULL,
   "ORDERS" NUMBER(38,0) NULL,
   "IS_CONTRACT" NUMBER(5,0) NULL,
   "IS_INSURANCE" NUMBER(5,0) NULL,
   "IS_PAY" NUMBER(5,0) NULL
);

-- Creating table 'HU_ALLOWANCE'
CREATE TABLE "dbo"."HU_ALLOWANCE" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NVARCHAR2(255) NULL,
   "ALLOWANCE_TYPE" NUMBER(38,0) NULL,
   "AMOUNT" NUMBER(38,0) NULL,
   "EFFECT_DATE" DATE NULL,
   "EXP_DATE" DATE NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'PA_SEND_PAYSLIP'
CREATE TABLE "dbo"."PA_SEND_PAYSLIP" (
   "ID" NUMBER(38,0) NOT NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "USERNAME" NVARCHAR2(1024) NULL,
   "IS_DISSOLVE" NUMBER(38,0) NULL,
   "ACTION_DATE" DATE NULL,
   "ACTION_TYPE" NUMBER(38,0) NULL,
   "ACTION_STATUS" NUMBER(38,0) NULL,
   "RUN_START" DATE NULL,
   "RUN_END" DATE NULL,
   "RUN_ROW" NUMBER(38,0) NULL
);

-- Creating table 'PA_SEND_PAYSLIP_EMP'
CREATE TABLE "dbo"."PA_SEND_PAYSLIP_EMP" (
   "ID" NUMBER(38,0) NOT NULL,
   "PA_SEND_PAYSLIP_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL
);

-- Creating table 'SE_MAIL'
CREATE TABLE "dbo"."SE_MAIL" (
   "ID" NUMBER(38,0) NOT NULL,
   "SUBJECT" NVARCHAR2(255) NULL,
   "MAIL_FROM" NVARCHAR2(255) NULL,
   "MAIL_TO" NVARCHAR2(1024) NULL,
   "MAIL_CC" NVARCHAR2(1024) NULL,
   "MAIL_BCC" NVARCHAR2(1024) NULL,
   "CONTENT" NCLOB NULL,
   "VIEW_NAME" NVARCHAR2(255) NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "ATTACHMENT" NCLOB NULL
);

-- Creating table 'PA_BONUS_IMPORT'
CREATE TABLE "dbo"."PA_BONUS_IMPORT" (
   "PKEY" NUMBER(38,0) NOT NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "YEAR" NUMBER(5,0) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "SALARY_GROUP" NUMBER(38,0) NULL,
   "PAYMENTSOURCES_ID" NUMBER(38,0) NULL,
   "MONEY" NUMBER(38,0) NULL,
   "SCREATEUSER" NVARCHAR2(50) NULL,
   "DCREATEDATE" DATE NULL,
   "SUPDATEUSER" NVARCHAR2(50) NULL,
   "DUPDATEDATE" DATE NULL
);

-- Creating table 'PA_SALARY_FUND_MAPPING'
CREATE TABLE "dbo"."PA_SALARY_FUND_MAPPING" (
   "ID" NUMBER(38,0) NOT NULL,
   "YEAR" NUMBER(5,0) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "SALARY_GROUP" NUMBER(38,0) NULL,
   "SALARY_NAME" NVARCHAR2(50) NULL,
   "SALARY_FUND" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(50) NULL,
   "CREATED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(50) NULL,
   "MODIFIED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(50) NULL,
   "MODIFIED_LOG" NVARCHAR2(50) NULL
);

-- Creating table 'PA_SEND_BONUSSLIP'
CREATE TABLE "dbo"."PA_SEND_BONUSSLIP" (
   "ID" NUMBER(38,0) NOT NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "USERNAME" NVARCHAR2(1024) NULL,
   "IS_DISSOLVE" NUMBER(38,0) NULL,
   "ACTION_DATE" DATE NULL,
   "ACTION_TYPE" NUMBER(38,0) NULL,
   "ACTION_STATUS" NUMBER(38,0) NULL,
   "RUN_START" DATE NULL,
   "RUN_END" DATE NULL,
   "RUN_ROW" NUMBER(38,0) NULL
);

-- Creating table 'PA_SEND_BONUSSLIP_EMP'
CREATE TABLE "dbo"."PA_SEND_BONUSSLIP_EMP" (
   "ID" NUMBER(38,0) NOT NULL,
   "PA_SEND_BONNUSSLIP_ID" NUMBER(38,0) NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL
);

-- Creating table 'PA_SALARY_FUND'
CREATE TABLE "dbo"."PA_SALARY_FUND" (
   "ID" NUMBER(38,0) NOT NULL,
   "YEAR" NUMBER(38,0) NULL,
   "MONTH" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "SAL_SOFT" NUMBER(38,0) NULL,
   "SAL_OTHER" NUMBER(38,0) NULL,
   "SAL_HARD" NUMBER(38,0) NULL,
   "SAL_ALLOWANCE" NUMBER(38,0) NULL,
   "SAL_TOTAL" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'PA_SALARY_PLANNING'
CREATE TABLE "dbo"."PA_SALARY_PLANNING" (
   "ID" NUMBER(38,0) NOT NULL,
   "YEAR" NUMBER(38,0) NULL,
   "MONTH" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "EMP_NUMBER" NUMBER(38,0) NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'PA_SENIORITY_DAILY'
CREATE TABLE "dbo"."PA_SENIORITY_DAILY" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "STAFF_RANK_ID" NUMBER(38,0) NULL,
   "WORKINGDAY" DATE NULL,
   "SENIORITY" NUMBER(38,2) NULL,
   "SALARY" NUMBER(38,2) NULL,
   "DISCIPLINE_COUNT" NUMBER(38,2) NULL,
   "DISCIPLINE_TYPE_NAME" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'PA_SENIORITY_DAILY_TEMP'
CREATE TABLE "dbo"."PA_SENIORITY_DAILY_TEMP" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "STAFF_RANK_ID" NUMBER(38,0) NULL,
   "WORKINGDAY" DATE NULL,
   "SENIORITY" NUMBER(38,2) NULL,
   "SALARY" NUMBER(38,2) NULL,
   "DISCIPLINE_COUNT" NUMBER(38,2) NULL,
   "DISCIPLINE_TYPE_NAME" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "REQUEST_ID" NUMBER(38,0) NULL,
   "CONTRACT_ID" NUMBER(38,0) NULL
);

-- Creating table 'PA_SENIORITY_DETAILS'
CREATE TABLE "dbo"."PA_SENIORITY_DETAILS" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "STAFF_RANK_ID" NUMBER(38,0) NULL,
   "SENIORITY" NUMBER(38,0) NULL,
   "DAY_COUNT1" NUMBER(38,0) NULL,
   "DAY_COUNT2" NUMBER(38,0) NULL,
   "DAY_COUNT3" NUMBER(38,0) NULL,
   "DAY_COUNT5" NUMBER(38,0) NULL,
   "SALARY" NUMBER(38,0) NULL,
   "PERCENT_SALARY" NUMBER(38,0) NULL,
   "SALARY_TOTAL" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "CONTRACT_ID" NUMBER(38,0) NULL
);

-- Creating table 'PA_SENIORITY_DETAILS_TEMP'
CREATE TABLE "dbo"."PA_SENIORITY_DETAILS_TEMP" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "STAFF_RANK_ID" NUMBER(38,0) NULL,
   "SENIORITY" NUMBER(38,0) NULL,
   "DAY_COUNT1" NUMBER(38,0) NULL,
   "DAY_COUNT2" NUMBER(38,0) NULL,
   "DAY_COUNT3" NUMBER(38,0) NULL,
   "DAY_COUNT5" NUMBER(38,0) NULL,
   "SALARY" NUMBER(38,0) NULL,
   "PERCENT_SALARY" NUMBER(38,0) NULL,
   "SALARY_TOTAL" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "CONTRACT_ID" NUMBER(38,0) NULL
);

-- Creating table 'PA_SENIORITY_MONTHLY'
CREATE TABLE "dbo"."PA_SENIORITY_MONTHLY" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "STAFF_RANK_ID" NUMBER(38,0) NULL,
   "SENIORITY" NUMBER(38,0) NULL,
   "DAY_COUNT1" NUMBER(38,0) NULL,
   "DAY_COUNT2" NUMBER(38,0) NULL,
   "DAY_COUNT3" NUMBER(38,0) NULL,
   "DAY_COUNT5" NUMBER(38,0) NULL,
   "SALARY_TOTAL" NUMBER(38,0) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "CONTRACT_ID" NUMBER(38,0) NULL,
   "PERCENT_SALARY" NUMBER(38,0) NULL
);

-- Creating table 'PA_SENIORITY_PROCESS'
CREATE TABLE "dbo"."PA_SENIORITY_PROCESS" (
   "ID" NUMBER(38,0) NOT NULL,
   "EMPLOYEE_ID" NUMBER(38,0) NULL,
   "ORG_ID" NUMBER(38,0) NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "STAFF_RANK_ID" NUMBER(38,0) NULL,
   "D1" NUMBER(38,0) NULL,
   "D2" NUMBER(38,0) NULL,
   "D3" NUMBER(38,0) NULL,
   "D4" NUMBER(38,0) NULL,
   "D5" NUMBER(38,0) NULL,
   "D6" NUMBER(38,0) NULL,
   "D7" NUMBER(38,0) NULL,
   "D8" NUMBER(38,0) NULL,
   "D9" NUMBER(38,0) NULL,
   "D10" NUMBER(38,0) NULL,
   "D11" NUMBER(38,0) NULL,
   "D12" NUMBER(38,0) NULL,
   "D13" NUMBER(38,0) NULL,
   "D14" NUMBER(38,0) NULL,
   "D15" NUMBER(38,0) NULL,
   "D16" NUMBER(38,0) NULL,
   "D17" NUMBER(38,0) NULL,
   "D18" NUMBER(38,0) NULL,
   "D19" NUMBER(38,0) NULL,
   "D20" NUMBER(38,0) NULL,
   "D21" NUMBER(38,0) NULL,
   "D22" NUMBER(38,0) NULL,
   "D23" NUMBER(38,0) NULL,
   "D24" NUMBER(38,0) NULL,
   "D25" NUMBER(38,0) NULL,
   "D26" NUMBER(38,0) NULL,
   "D27" NUMBER(38,0) NULL,
   "D28" NUMBER(38,0) NULL,
   "D29" NUMBER(38,0) NULL,
   "D30" NUMBER(38,0) NULL,
   "D31" NUMBER(38,0) NULL,
   "SALARY" NUMBER(38,0) NULL,
   "DISCIPLINE_COUNT" NUMBER(38,0) NULL,
   "DISCIPLINE_TYPE_NAME" NVARCHAR2(1023) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "PERIOD_ID" NUMBER(38,0) NULL,
   "PERCENT_SALARY" NUMBER(38,0) NULL,
   "CONTRACT_ID" NUMBER(38,0) NULL,
   "SENIORITY_LAST" NUMBER(38,0) NULL
);

-- Creating table 'PA_TITLE_COST'
CREATE TABLE "dbo"."PA_TITLE_COST" (
   "ID" NUMBER(38,0) NOT NULL,
   "TITLE_ID" NUMBER(38,0) NULL,
   "SAL_BASIC" NUMBER(38,0) NULL,
   "SAL_MOBILE" NUMBER(38,0) NULL,
   "SAL_RICE" NUMBER(38,0) NULL,
   "SAL_INS" NUMBER(38,0) NULL,
   "SAL_SOFT" NUMBER(38,0) NULL,
   "SAL_OTHER" NUMBER(38,0) NULL,
   "SAL_TOTAL" NUMBER(38,0) NULL,
   "EFFECT_DATE" DATE NULL,
   "EXPIRE_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL
);

-- Creating table 'HU_TITLE'
CREATE TABLE "dbo"."HU_TITLE" (
   "ID" NUMBER(38,0) NOT NULL,
   "ACTFLG" NVARCHAR2(1) NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME_EN" NVARCHAR2(255) NULL,
   "NAME_VN" NVARCHAR2(255) NULL,
   "CREATED_DATE" DATE NULL,
   "CREATED_BY" NVARCHAR2(255) NULL,
   "CREATED_LOG" NVARCHAR2(255) NULL,
   "MODIFIED_DATE" DATE NULL,
   "MODIFIED_BY" NVARCHAR2(255) NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(1023) NULL,
   "TITLE_GROUP_ID" NUMBER(38,0) NULL,
   "STATUS" NUMBER(5,0) NULL,
   "LIST_PC_ID" NUMBER(20,0) NULL,
   "DRIVE_INFOR" NUMBER(38,0) NULL,
   "WORK_INVOLVE_ID" NUMBER(38,0) NULL,
   "OVT" NUMBER(38,0) NULL,
   "UPLOAD_FILE" NVARCHAR2(255) NULL,
   "LEVEL_ID" NUMBER(38,0) NULL
);

-- Creating table 'PA_SALE_COMMISION'
CREATE TABLE "dbo"."PA_SALE_COMMISION" (
   "ID" NUMBER(38,0) NOT NULL,
   "CODE" NVARCHAR2(50) NULL,
   "NAME" NVARCHAR2(255) NULL,
   "REMARK" NVARCHAR2(1025) NULL,
   "CREATED_DATE" DATE NOT NULL,
   "CREATED_BY" NVARCHAR2(255) NOT NULL,
   "CREATED_LOG" NVARCHAR2(255) NOT NULL,
   "MODIFIED_DATE" DATE NOT NULL,
   "MODIFIED_BY" NVARCHAR2(255) NOT NULL,
   "MODIFIED_LOG" NVARCHAR2(255) NOT NULL,
   "ORDERS" NUMBER(38,0) NULL,
   "ACTFLG" NVARCHAR2(21) NULL,
   "SALE_RATE" NUMBER(38,0) NULL
);


-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on "ID"in table 'PA_SALARY_GROUP'
ALTER TABLE "dbo"."PA_SALARY_GROUP"
ADD CONSTRAINT "PK_PA_SALARY_GROUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SALARY_LEVEL'
ALTER TABLE "dbo"."PA_SALARY_LEVEL"
ADD CONSTRAINT "PK_PA_SALARY_LEVEL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SALARY_RANK'
ALTER TABLE "dbo"."PA_SALARY_RANK"
ADD CONSTRAINT "PK_PA_SALARY_RANK"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "PK_HU_EMPLOYEE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_CV'
ALTER TABLE "dbo"."HU_EMPLOYEE_CV"
ADD CONSTRAINT "PK_HU_EMPLOYEE_CV"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_EDUCATION'
ALTER TABLE "dbo"."HU_EMPLOYEE_EDUCATION"
ADD CONSTRAINT "PK_HU_EMPLOYEE_EDUCATION"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE_FILES'
ALTER TABLE "dbo"."HU_EMPLOYEE_FILES"
ADD CONSTRAINT "PK_HU_EMPLOYEE_FILES"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_HEALTH'
ALTER TABLE "dbo"."HU_EMPLOYEE_HEALTH"
ADD CONSTRAINT "PK_HU_EMPLOYEE_HEALTH"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_OTHER_INFO'
ALTER TABLE "dbo"."HU_EMPLOYEE_OTHER_INFO"
ADD CONSTRAINT "PK_HU_EMPLOYEE_OTHER_INFO"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_SALARY'
ALTER TABLE "dbo"."HU_EMPLOYEE_SALARY"
ADD CONSTRAINT "PK_HU_EMPLOYEE_SALARY"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE_TRAIN'
ALTER TABLE "dbo"."HU_EMPLOYEE_TRAIN"
ADD CONSTRAINT "PK_HU_EMPLOYEE_TRAIN"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_WORKING'
ALTER TABLE "dbo"."HU_WORKING"
ADD CONSTRAINT "PK_HU_WORKING"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST'
ALTER TABLE "dbo"."OT_OTHER_LIST"
ADD CONSTRAINT "PK_OT_OTHER_LIST"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST_GROUP'
ALTER TABLE "dbo"."OT_OTHER_LIST_GROUP"
ADD CONSTRAINT "PK_OT_OTHER_LIST_GROUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST_TYPE'
ALTER TABLE "dbo"."OT_OTHER_LIST_TYPE"
ADD CONSTRAINT "PK_OT_OTHER_LIST_TYPE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_HOLD_SALARY'
ALTER TABLE "dbo"."PA_HOLD_SALARY"
ADD CONSTRAINT "PK_PA_HOLD_SALARY"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ORGANIZATION'
ALTER TABLE "dbo"."HU_ORGANIZATION"
ADD CONSTRAINT "PK_HU_ORGANIZATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ORG_ID", "USERNAME"in table 'SE_CHOSEN_ORG'
ALTER TABLE "dbo"."SE_CHOSEN_ORG"
ADD CONSTRAINT "PK_SE_CHOSEN_ORG"
   PRIMARY KEY ("ORG_ID", "USERNAME" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_ORG_PERIOD'
ALTER TABLE "dbo"."AT_ORG_PERIOD"
ADD CONSTRAINT "PK_AT_ORG_PERIOD"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEEID", "USERNAME"in table 'SE_CHOSEN_CALCULATE'
ALTER TABLE "dbo"."SE_CHOSEN_CALCULATE"
ADD CONSTRAINT "PK_SE_CHOSEN_CALCULATE"
   PRIMARY KEY ("EMPLOYEEID", "USERNAME" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_OBJECT_SALARY'
ALTER TABLE "dbo"."PA_OBJECT_SALARY"
ADD CONSTRAINT "PK_PA_OBJECT_SALARY"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_FORMULER'
ALTER TABLE "dbo"."PA_FORMULER"
ADD CONSTRAINT "PK_PA_FORMULER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_FORMULER_GROUP'
ALTER TABLE "dbo"."PA_FORMULER_GROUP"
ADD CONSTRAINT "PK_PA_FORMULER_GROUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_ORG_LUNCH'
ALTER TABLE "dbo"."PA_ORG_LUNCH"
ADD CONSTRAINT "PK_PA_ORG_LUNCH"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_PRICE_LUNCH'
ALTER TABLE "dbo"."PA_PRICE_LUNCH"
ADD CONSTRAINT "PK_PA_PRICE_LUNCH"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_PAYMENT_LIST'
ALTER TABLE "dbo"."PA_PAYMENT_LIST"
ADD CONSTRAINT "PK_PA_PAYMENT_LIST"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_INCENTIVE_RANK'
ALTER TABLE "dbo"."PA_INCENTIVE_RANK"
ADD CONSTRAINT "PK_PA_INCENTIVE_RANK"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_INCENTIVE_RANK_DETAIL'
ALTER TABLE "dbo"."PA_INCENTIVE_RANK_DETAIL"
ADD CONSTRAINT "PK_PA_INCENTIVE_RANK_DETAIL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SALARY_TYPE'
ALTER TABLE "dbo"."PA_SALARY_TYPE"
ADD CONSTRAINT "PK_PA_SALARY_TYPE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SALARYTYPE_GROUP'
ALTER TABLE "dbo"."PA_SALARYTYPE_GROUP"
ADD CONSTRAINT "PK_PA_SALARYTYPE_GROUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_COST_CENTER'
ALTER TABLE "dbo"."PA_COST_CENTER"
ADD CONSTRAINT "PK_PA_COST_CENTER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_ORGBONUS'
ALTER TABLE "dbo"."PA_ORGBONUS"
ADD CONSTRAINT "PK_PA_ORGBONUS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_PAYMENTSOURCES'
ALTER TABLE "dbo"."PA_PAYMENTSOURCES"
ADD CONSTRAINT "PK_PA_PAYMENTSOURCES"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_WORKFACTOR'
ALTER TABLE "dbo"."PA_WORKFACTOR"
ADD CONSTRAINT "PK_PA_WORKFACTOR"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_WORK_STANDARD'
ALTER TABLE "dbo"."PA_WORK_STANDARD"
ADD CONSTRAINT "PK_PA_WORK_STANDARD"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_PERIOD'
ALTER TABLE "dbo"."AT_PERIOD"
ADD CONSTRAINT "PK_AT_PERIOD"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_LISTSAL'
ALTER TABLE "dbo"."PA_LISTSAL"
ADD CONSTRAINT "PK_PA_LISTSAL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_LISTSALARIES'
ALTER TABLE "dbo"."PA_LISTSALARIES"
ADD CONSTRAINT "PK_PA_LISTSALARIES"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_TAXATION'
ALTER TABLE "dbo"."PA_TAXATION"
ADD CONSTRAINT "PK_PA_TAXATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ALLOWANCE_LIST'
ALTER TABLE "dbo"."HU_ALLOWANCE_LIST"
ADD CONSTRAINT "PK_HU_ALLOWANCE_LIST"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ALLOWANCE'
ALTER TABLE "dbo"."HU_ALLOWANCE"
ADD CONSTRAINT "PK_HU_ALLOWANCE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SEND_PAYSLIP'
ALTER TABLE "dbo"."PA_SEND_PAYSLIP"
ADD CONSTRAINT "PK_PA_SEND_PAYSLIP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SEND_PAYSLIP_EMP'
ALTER TABLE "dbo"."PA_SEND_PAYSLIP_EMP"
ADD CONSTRAINT "PK_PA_SEND_PAYSLIP_EMP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_MAIL'
ALTER TABLE "dbo"."SE_MAIL"
ADD CONSTRAINT "PK_SE_MAIL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "PKEY"in table 'PA_BONUS_IMPORT'
ALTER TABLE "dbo"."PA_BONUS_IMPORT"
ADD CONSTRAINT "PK_PA_BONUS_IMPORT"
   PRIMARY KEY ("PKEY" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SALARY_FUND_MAPPING'
ALTER TABLE "dbo"."PA_SALARY_FUND_MAPPING"
ADD CONSTRAINT "PK_PA_SALARY_FUND_MAPPING"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SEND_BONUSSLIP'
ALTER TABLE "dbo"."PA_SEND_BONUSSLIP"
ADD CONSTRAINT "PK_PA_SEND_BONUSSLIP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SEND_BONUSSLIP_EMP'
ALTER TABLE "dbo"."PA_SEND_BONUSSLIP_EMP"
ADD CONSTRAINT "PK_PA_SEND_BONUSSLIP_EMP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SALARY_FUND'
ALTER TABLE "dbo"."PA_SALARY_FUND"
ADD CONSTRAINT "PK_PA_SALARY_FUND"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SALARY_PLANNING'
ALTER TABLE "dbo"."PA_SALARY_PLANNING"
ADD CONSTRAINT "PK_PA_SALARY_PLANNING"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SENIORITY_DAILY'
ALTER TABLE "dbo"."PA_SENIORITY_DAILY"
ADD CONSTRAINT "PK_PA_SENIORITY_DAILY"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SENIORITY_DAILY_TEMP'
ALTER TABLE "dbo"."PA_SENIORITY_DAILY_TEMP"
ADD CONSTRAINT "PK_PA_SENIORITY_DAILY_TEMP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SENIORITY_DETAILS'
ALTER TABLE "dbo"."PA_SENIORITY_DETAILS"
ADD CONSTRAINT "PK_PA_SENIORITY_DETAILS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SENIORITY_DETAILS_TEMP'
ALTER TABLE "dbo"."PA_SENIORITY_DETAILS_TEMP"
ADD CONSTRAINT "PK_PA_SENIORITY_DETAILS_TEMP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SENIORITY_MONTHLY'
ALTER TABLE "dbo"."PA_SENIORITY_MONTHLY"
ADD CONSTRAINT "PK_PA_SENIORITY_MONTHLY"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SENIORITY_PROCESS'
ALTER TABLE "dbo"."PA_SENIORITY_PROCESS"
ADD CONSTRAINT "PK_PA_SENIORITY_PROCESS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_TITLE_COST'
ALTER TABLE "dbo"."PA_TITLE_COST"
ADD CONSTRAINT "PK_PA_TITLE_COST"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_TITLE'
ALTER TABLE "dbo"."HU_TITLE"
ADD CONSTRAINT "PK_HU_TITLE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_SALE_COMMISION'
ALTER TABLE "dbo"."PA_SALE_COMMISION"
ADD CONSTRAINT "PK_PA_SALE_COMMISION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on "SAL_GROUP_ID" in table 'PA_SALARY_LEVEL'
ALTER TABLE "dbo"."PA_SALARY_LEVEL"
ADD CONSTRAINT "FK_PSG_PSL"
   FOREIGN KEY ("SAL_GROUP_ID")
   REFERENCES "dbo"."PA_SALARY_GROUP"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_PSG_PSL'
CREATE INDEX "IX_FK_PSG_PSL"
ON "dbo"."PA_SALARY_LEVEL"
   ("SAL_GROUP_ID");

-- Creating foreign key on "SAL_LEVEL_ID" in table 'PA_SALARY_RANK'
ALTER TABLE "dbo"."PA_SALARY_RANK"
ADD CONSTRAINT "FK_PSL_PSR"
   FOREIGN KEY ("SAL_LEVEL_ID")
   REFERENCES "dbo"."PA_SALARY_LEVEL"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_PSL_PSR'
CREATE INDEX "IX_FK_PSL_PSR"
ON "dbo"."PA_SALARY_RANK"
   ("SAL_LEVEL_ID");

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_HEALTH'
ALTER TABLE "dbo"."HU_EMPLOYEE_HEALTH"
ADD CONSTRAINT "FK_FE_HEH"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_CV'
ALTER TABLE "dbo"."HU_EMPLOYEE_CV"
ADD CONSTRAINT "FK_HE_HEC"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_EDUCATION'
ALTER TABLE "dbo"."HU_EMPLOYEE_EDUCATION"
ADD CONSTRAINT "FK_HE_HEE"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_FILES'
ALTER TABLE "dbo"."HU_EMPLOYEE_FILES"
ADD CONSTRAINT "FK_HE_HEF"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HE_HEF'
CREATE INDEX "IX_FK_HE_HEF"
ON "dbo"."HU_EMPLOYEE_FILES"
   ("EMPLOYEE_ID");

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_OTHER_INFO'
ALTER TABLE "dbo"."HU_EMPLOYEE_OTHER_INFO"
ADD CONSTRAINT "FK_HE_HEO"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_SALARY'
ALTER TABLE "dbo"."HU_EMPLOYEE_SALARY"
ADD CONSTRAINT "FK_HE_HES"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_WORKING'
ALTER TABLE "dbo"."HU_WORKING"
ADD CONSTRAINT "FK_HE_HW"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HE_HW'
CREATE INDEX "IX_FK_HE_HW"
ON "dbo"."HU_WORKING"
   ("EMPLOYEE_ID");

-- Creating foreign key on "DIRECT_MANAGER" in table 'HU_WORKING'
ALTER TABLE "dbo"."HU_WORKING"
ADD CONSTRAINT "FK_HUDM_HUWK"
   FOREIGN KEY ("DIRECT_MANAGER")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUDM_HUWK'
CREATE INDEX "IX_FK_HUDM_HUWK"
ON "dbo"."HU_WORKING"
   ("DIRECT_MANAGER");

-- Creating foreign key on "DIRECT_MANAGER" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HUEMD_HUEM"
   FOREIGN KEY ("DIRECT_MANAGER")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUEMD_HUEM'
CREATE INDEX "IX_FK_HUEMD_HUEM"
ON "dbo"."HU_EMPLOYEE"
   ("DIRECT_MANAGER");

-- Creating foreign key on "INDIRECT_MANAGER" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HUEMI_HUEM"
   FOREIGN KEY ("INDIRECT_MANAGER")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUEMI_HUEM'
CREATE INDEX "IX_FK_HUEMI_HUEM"
ON "dbo"."HU_EMPLOYEE"
   ("INDIRECT_MANAGER");

-- Creating foreign key on "INDIRECT_MANAGER" in table 'HU_WORKING'
ALTER TABLE "dbo"."HU_WORKING"
ADD CONSTRAINT "FK_HUIM_HUWK"
   FOREIGN KEY ("INDIRECT_MANAGER")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUIM_HUWK'
CREATE INDEX "IX_FK_HUIM_HUWK"
ON "dbo"."HU_WORKING"
   ("INDIRECT_MANAGER");

-- Creating foreign key on "GROUP_ID" in table 'OT_OTHER_LIST_TYPE'
ALTER TABLE "dbo"."OT_OTHER_LIST_TYPE"
ADD CONSTRAINT "FK_OOLG_OOLT"
   FOREIGN KEY ("GROUP_ID")
   REFERENCES "dbo"."OT_OTHER_LIST_GROUP"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_OOLG_OOLT'
CREATE INDEX "IX_FK_OOLG_OOLT"
ON "dbo"."OT_OTHER_LIST_TYPE"
   ("GROUP_ID");

-- Creating foreign key on "PARENT_ID" in table 'HU_ORGANIZATION'
ALTER TABLE "dbo"."HU_ORGANIZATION"
ADD CONSTRAINT "FK_HU_ORG_HU_ORG"
   FOREIGN KEY ("PARENT_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_ORG_HU_ORG'
CREATE INDEX "IX_FK_HU_ORG_HU_ORG"
ON "dbo"."HU_ORGANIZATION"
   ("PARENT_ID");

-- Creating foreign key on "SAL_TYPE_ID" in table 'PA_SALARYTYPE_GROUP'
ALTER TABLE "dbo"."PA_SALARYTYPE_GROUP"
ADD CONSTRAINT "FK_SALARYTYPE_FK"
   FOREIGN KEY ("SAL_TYPE_ID")
   REFERENCES "dbo"."PA_SALARY_TYPE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SALARYTYPE_FK'
CREATE INDEX "IX_FK_SALARYTYPE_FK"
ON "dbo"."PA_SALARYTYPE_GROUP"
   ("SAL_TYPE_ID");

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------
